### ISSUE TITLE
use '--slave' to start the kernel and make nicer debug output

### ISSUE THREAD

**Issue by JanSchulz** [IRkernel/IRkernel#107]
Currently the kernel startup is quite noisy: it prints both the normal R startup message (suppressible via '--slave') and the initial kernel information which is printed as a multi-line vector. I think it would be nice to output only two-ish lines: one with basics about the interpreter and kernel version and one line with the must-need kernel information. All the rest should be error/warning output.

**Comment by takluyver** [comment]
That's probably reasonable. I added the connection information early on for debugging, and never got round to removing it. I didn't know about `--slave`.

**Comment by takluyver** [comment]
#115 made it quieter.
