### ISSUE TITLE
The registered getOption('pager') function hangs the kernel

### ISSUE THREAD

**Issue by mikecroucher** [IRkernel/IRkernel#112]
If you execute the command

`data()`

in the notebook, you get no output and no subsequent commands work.

I've seen this in Windows and Ubuntu. 
Version 0.3 of IRKernel
R version 3.1.3 in Ubuntu
R version 3.2 in Windows

Could someone confirm please? I might be doing something stupid.

**Comment by JanSchulz** [comment]
In rstudio, this opens a new page, so I guess it tries to do that here, too and of course fails. One could probably write a `repr.packageIQR` function to send this as "text/plain" similar to a normal `print(text)`.

**Comment by flying-sheep** [comment]
a case of magic print function…

`data()` returns a `structure(list(...), class = 'packageIQR')`. If you don’t assign that, `print` is called on it.

but [`utils:::print.packageIQR`](https://github.com/wch/r-source/blob/7802d34ed7afb035c4f4dfdfbc18fe70c22b1208/src/library/utils/R/indices.R#L173-L207) doesn’t seem to do much…

no idea what happens

**Comment by JanSchulz** [comment]
That does a `file.show` which in the end then calls `pager`

-> we should probably overwrite that, similar to readline (https://github.com/IRkernel/IRkernel/issues/85)

**Comment by flying-sheep** [comment]
aah, i see that it does that now.

but we already [do set `options(pager = ...)`](https://github.com/IRkernel/IRkernel/blob/fcc93e765d19f8dbd11b64838b1a104361febf76/R/execution.r#L55-L62)

**Comment by JanSchulz** [comment]
Probably simple make that a function which is called when you do `pager(...)`? The code above does not seem to use the pager option?

**Comment by flying-sheep** [comment]
there is no `pager` outside of `file.show`, as `pager` is [one of is arguments](https://github.com/wch/r-source/blob/53329d972793582209ffb931f1a40c32d000869b/src/library/base/R/files.R#L40) (and set to `getOption('pager')` as default.

**Comment by flying-sheep** [comment]
jup, the thing we register as pager option is broken.

i just tried a notebook with nothing but

```r
getOption('pager')('some_filename', 'title', 'header', FALSE)
```

and it hangs as described. changing bug title
