### ISSUE TITLE
Error in replayPlot(obj): invalid graphics state

### ISSUE THREAD

**Issue by mikecroucher** [IRkernel/IRkernel#113]
Running on windows using the portable Jupyter/R build described at http://www.walkingrandomly.com/?p=5734 

`plot(1:3)`

returns the plot but it also complains

`Error in replayPlot(obj): invalid graphics state`

Googling suggested trying `dev.off()` before plotting again but that didn't help. What did help was 

`options(jupyter.plot_mimetypes = 'image/png')`

Plots continue to work and the error message has gone away.

**Comment by flying-sheep** [comment]
can you try to do it with `options(jupyter.plot_mimetypes = c('image/png', 'image/jpeg'))`?

this will help us to debug if it’s because the plot is replayed more than once or the error is in some device.

if that works, also please try with `options(jupyter.plot_mimetypes = 'image/svg+xml')` and others, and tell us what throws errors

**Comment by JanSchulz** [comment]
We should probably add a function name to the error handler :-)

**Comment by flying-sheep** [comment]
currently we just pass on the error that happended.

we’ll have to specify a function extending the error (which AFAIK can be `simpleError` or string…?) and then calling `handle_error`

**Comment by mikecroucher** [comment]
options(jupyter.plot_mimetypes = c('image/png', 'image/jpeg'))
    plot(1:3)

gives the plot and `Error in replayPlot(obj): invalid graphics state`

    options(jupyter.plot_mimetypes = 'image/svg+xml')
    plot(1:3)

gives the plot and no error message

**Comment by takluyver** [comment]
We seem to be having some trouble with plotting - #117 and #118 are plotting related too.

**Comment by flying-sheep** [comment]
i saw invalid graphics state some times as well. at least the second issue in #118 is fixed.

**Comment by steverowe** [comment]
I am seeing this issue also.  Is there a way to set 
```
options(jupyter.plot_mimetypes = 'image/png') 
```
by default?

**Comment by flying-sheep** [comment]
sure, put the line into your `~/.Rprofile`.

**Comment by sleacher** [comment]
Early in the notebook I had:
```
#IRkernel::set_plot_options(width=4, height=4) 
```
I was getting the error later on. After removing that line and restarting the kernel, I didn't get the error

**Comment by flying-sheep** [comment]
@mikecroucher still have the error?

**Comment by mikecroucher** [comment]
Not seen it in ages

**Comment by flying-sheep** [comment]
good. closed issues are better than open ones :laughing:

**Comment by patrickeganfoley** [comment]
@flying-sheep and @steverowe - your comments helped me get R plots within emacs using [Emacs Ipython Notebooks](https://github.com/tkf/emacs-ipython-notebook).  Thanks!

**Comment by mc-robinson** [comment]
Just ran into this error. If you run into this error and used a line like: 

```options(repr.plot.width=4, repr.plot.height=3)```

earlier in your code. I suggest you set it back to the defaults using 

```options(repr.plot.width=7, repr.plot.height=7)```

I couldn't find a better way to set all the repr options back to defaults, but this worked for now.
