### ISSUE TITLE
Can't initiate IRKernel in Windows 10

### ISSUE THREAD

**Issue by MengyingLi** [IRkernel/IRkernel#120]
Hi I am currently using Windows 10 and followed the instruction about using R to install IRKernel 
![image](https://cloud.githubusercontent.com/assets/6514708/7433312/d5083c4e-efe4-11e4-94f8-3ccfb3069fb2.png)

Everything seems to be fine but there is no R kernel in the drop down menu from Jupyter notebook.  did I miss anything? 
![image](https://cloud.githubusercontent.com/assets/6514708/7433323/fba8ad20-efe4-11e4-9e3a-5f5b29c407f5.png)

**Comment by takluyver** [comment]
That looks like it should have worked. Can you look in `~/.ipython/kernels` and see if there's an `ir` directory there?

**Comment by MengyingLi** [comment]
Hi! Thanks for the prompt reply.  I did see an ir directory there. I installed python using anaconda. Is that because the directory are different?  
![image](https://cloud.githubusercontent.com/assets/6514708/7443750/84f1b260-f117-11e4-91a0-8262439a20b4.png)

**Comment by takluyver** [comment]
That should work with anaconda. Apologies if I'm checking the obvious, but
did you reload the page after you installed IRkernel?

**Comment by MengyingLi** [comment]
Hi, Thank you so much for your help! :) I actually installed python 2.7 first and then add a python 3 to anaconda. Here is the script I initiated python 3 
![image](https://cloud.githubusercontent.com/assets/6514708/7445795/a31d6b12-f176-11e4-81b7-78fc6f03d010.png)

I also checked the ipython folder under the anaconda directory and there is no IR kernel in the kernel folder

![image](https://cloud.githubusercontent.com/assets/6514708/7445801/d45b6a9e-f176-11e4-8ae9-3eb8db8e1cd6.png)

**Comment by takluyver** [comment]
Strange. Can you run this and post the output:

```python
from IPython.kernel.kernelspec import KernelSpecManager
ksm = KernelSpecManager()
ksm.kernel_dirs
```

And also:

```python
ksm.find_kernel_specs()
```

**Comment by MengyingLi** [comment]
Hi Attached is the output from the commands:

![image](https://cloud.githubusercontent.com/assets/6514708/7456420/46a706cc-f239-11e4-9c51-849cadb160af.png)

**Comment by takluyver** [comment]
In the screenshot you posted, where is "This PC > Documents" on the actual filesystem? Is it `C:\Users\menli`, or a different directory? If it's somewhere else, try moving the `.ipython` subdirectory to `C:\Users\menli`.

**Comment by MengyingLi** [comment]
Hi It is actually in C:\Users\menli\Documents. Do I have to move it to the parent folder?
![image](https://cloud.githubusercontent.com/assets/6514708/7457987/891a2e7e-f245-11e4-977f-b21eb66d65da.png)

**Comment by MengyingLi** [comment]
Actually it is already there 
![image](https://cloud.githubusercontent.com/assets/6514708/7458007/bdd960ee-f245-11e4-8941-a45a3a306c72.png)

**Comment by takluyver** [comment]
OK, can you try:

```python
from IPython.kernel.kernelspec import KernelSpecManager, _list_kernels_in, _is_kernel_dir
print(KernelSpecManager.kernel_dirs)
print(_is_kernel_dir('C:\\Users\\menli\\.ipython\\kernels\\ir'))
_list_kernels_in('C:\\Users\\menli\\.ipython\\kernels')
```

**Comment by MengyingLi** [comment]
here is the output. I am wondering whether it is because of the way I initiate jupyter, maybe I should not do "activate py3k" and "ipython notebook" but something like "activate ir" ?

![image](https://cloud.githubusercontent.com/assets/6514708/7458639/ce2879da-f24a-11e4-8635-dd3eeab62dba.png)

**Comment by takluyver** [comment]
No, `activate` refers to conda environments, not IPython kernels.

Maybe you have a whitelist configured for some reason - can you try `KernelSpecManager().whitelist` and see what the output is?

**Comment by MengyingLi** [comment]
The result is "set()"
![image](https://cloud.githubusercontent.com/assets/6514708/7459398/6a22f39c-f250-11e4-82f4-c93499ed1259.png)

**Comment by takluyver** [comment]
OK, I'm confused. This is what `ksm.find_kernel_specs()` does:

```python
d = {}
for kernel_dir in self.kernel_dirs:
    d.update(_list_kernels_in(kernel_dir))

d[NATIVE_KERNEL_NAME] = self._native_kernel_resource_dir
if self.whitelist:
   # filter if there's a whitelist
    d = {name:spec for name,spec in d.items() if name in self.whitelist}
return d
```
We've checked that:

* `C:\\Users\\menli\\.ipython\\kernels` is in `self.kernel_dirs`
* `_list_kernels_in()` on that directory finds 'ir'
* `self.whitelist` is empty, so it shouldn't be filtering.

And yet the result of `ksm.find_kernel_specs()` doesn't include ir. I don't know how that can be. Can you think of anything else to debug?

**Comment by MengyingLi** [comment]
Hi I think the problem might be that I installed python 3 through [minicoda](http://conda.pydata.org/miniconda.html) and I then delete that folder and R kernel pops up in the notebook but still can't be used. Python 3 can be used well and I rerun all the commands and the output is still the same. I rerun all the R codes to reinstall irkernel but nothing changed. Any idea about why I can't locate the file in the error message?
![image](https://cloud.githubusercontent.com/assets/6514708/7461822/b048543c-f261-11e4-81e0-4ba3857783ce.png)

**Comment by takluyver** [comment]
Ah, that sounds like R is not on PATH. Did you install R through Anaconda, or as a separate download? If you installed it separately, you might need to edit the PATH environment variable to add the folder where R is found.

**Comment by MengyingLi** [comment]
Hi, I just add the R folder to the path variable, however the error message was still as shown above after I reloaded the notebook
![image](https://cloud.githubusercontent.com/assets/6514708/7464030/b9ff3f1a-f273-11e4-9236-206886857077.png)
![image](https://cloud.githubusercontent.com/assets/6514708/7464035/d5024a00-f273-11e4-962d-8566af82b8df.png)

**Comment by takluyver** [comment]
I'd guess the directory you need to add is the 'bin' directory under there.

**Comment by MengyingLi** [comment]
Hi, I actually did add 'bin' but the same error message is still there. What might be the best way to install IRkernel in Windows?

**Comment by takluyver** [comment]
I expect you'll need to start a new terminal and use that to start a new notebook server for the change in PATH to take effect.

**Comment by MengyingLi** [comment]
Yeah! it works! Thank you so much for all your help! :)

**Comment by takluyver** [comment]
You're welcome. I would like this to be easier, but I don't know there's anything IRkernel can do to improve it, so I'm closing this.
