### ISSUE TITLE
Installing zmq development headers for RHEL

### ISSUE THREAD

**Issue by breschke** [IRkernel/IRkernel#121]
In an attempt to use IRkernel on a university machine, I discovered it is non-trivial to install zmq development headers (i.e., there is no yum package). As I a result, I cannot compile rzmq. Any advice for non-Ubuntu/Debian flavors of Linux?

**Comment by takluyver** [comment]
There certainly should be a yum package - it looks like it's called [zeromq-devel](https://apps.fedoraproject.org/packages/zeromq-devel) in Fedora.

**Comment by kiyoto** [comment]
@breschke You should try installing `yum install zeromq3-devel`

**Comment by flying-sheep** [comment]
try with the pbdZMQ-based master please
