### ISSUE TITLE
Getting plots to show up on OSX

### ISSUE THREAD

**Issue by asmeurer** [IRkernel/IRkernel#122]
I'm having several problems with plots and I'm trying to figure out if they are bugs with irkernel/irdisplay or issues with my conda packages. I have just been using `plot(1, 2)` to test

# OSX

In OS X, with 0.3 of both irkernel and irdisplay, plots do not show at all. It just says "plot without title". Downgrading to 0.2 I get "Error in display_png(filename=tf): unused argument (filename=tf)", so I am unsure if it ever worked. 

# Linux (solved)

On Linux (64-bit), downgrading irkernel to 0.2, everything works (even with irdisplay 0.3). I get a plot like

![screen shot 2015-05-04 at 2 04 30 pm](https://cloud.githubusercontent.com/assets/71486/7460124/7f082370-f266-11e4-9d00-1b6bc0115b19.png)

but with irkernel 0.3, I get a plot with no labels

![screen shot 2015-05-04 at 2 04 57 pm](https://cloud.githubusercontent.com/assets/71486/7460138/90619ef8-f266-11e4-9f4e-eaa938a261fd.png)

(I am having some issues on my Windows machine so I haven't been able to test things there for now)

Any suggestions on what could be causing these issues? Are they issues with my build or bugs in the code? 

You can reproduce this all by `conda install -c r r-irkernel` (or let me know if it doesn't reproduce for you).

**Comment by flying-sheep** [comment]
issues with firefox’ SVG rendering engine.

**Comment by asmeurer** [comment]
OK, using a newer Firefox on a newer Linux seems to have solved that. But what about OS X? I am using Chrome on OS X.

**Comment by flying-sheep** [comment]
oh, so something like this also occurs on chrome and OSX?

**Comment by flying-sheep** [comment]
the 0.2 problem is that the `display_png` parameter in IRdisplay used to be called `filename`, and the older kernel still calls it like this. IRkernel 0.3 correctly calls something else entirely

**Comment by asmeurer** [comment]
OK, I take that back. The newer Firefox does not work (I was using the old version of irkernel accidentally), but Chrome does seem to work. So at least it's not my problem. 

But yes, on OS X, I am just getting "plot without title".

**Comment by flying-sheep** [comment]
can you do what i asked you to do above? :blush:

**Comment by asmeurer** [comment]
```
In [3]:

capabilities()
Out[3]:
jpeg
FALSE
png
FALSE
tiff
FALSE
tcltk
TRUE
X11
FALSE
aqua
TRUE
http/ftp
TRUE
sockets
TRUE
libxml
TRUE
fifo
TRUE
cledit
FALSE
iconv
TRUE
NLS
TRUE
profmem
FALSE
cairo
FALSE
ICU
TRUE
long.double
TRUE
In [4]:

getOption('jupyter.plot_mimetypes')
Out[4]:
'text/plain' 'image/png' 'image/jpeg' 'application/pdf' 'image/svg+xml'
```

**Comment by flying-sheep** [comment]
> ```
> jpeg    png     cairo
> FALSE   FALSE   FALSE
> ```

uh, your version of R doesn’t support much graphics output…

which is really strange since `aqua   TRUE` means that you have the [`quartz`](https://stat.ethz.ch/R-manual/R-devel/library/grDevices/html/quartz.html) device, which should provide png, jpg, and pdf capabilities.

what devices to you use to write graphics normally if not `png` and `jpeg`?

**Comment by flying-sheep** [comment]
what happends if you do `png('foo.png'); plot(1); dev.off()`?

does a file appear?

**Comment by JanSchulz** [comment]
Tomorrow evening I've access to a mac os x notebook with rstudio installed. Is there any code I can run to make debugging this easier?

**Comment by flying-sheep** [comment]
you could look at IRkernel/repr#8, and answer the questions i ask there.

if `capabilities('png') == FALSE`, will `png('...')` do something? what will the values for the type parameter do?

thanks in advance for your help!

**Comment by asmeurer** [comment]
`png('foo.png'); plot(1); dev.off()` generated a file foo.png that seems to have rendered just fine.

**Comment by flying-sheep** [comment]
thanks! this helps. let’s discuss in IRkernel/repr#8 how to make this work.

**Comment by asmeurer** [comment]
OK, I was able to get my Windows machine fixed. On Windows, I get

![screen shot 2015-05-07 at 3 04 05 pm](https://cloud.githubusercontent.com/assets/71486/7524832/559ffee8-f4ca-11e4-8111-b8c1117f031b.png)

So does this mean that plotting on Windows requires winCairo?

**Comment by flying-sheep** [comment]
i think this will be fixed in IRkernel/repr#8

**Comment by flying-sheep** [comment]
does plotting on OSX work with the newest repr from master?

**Comment by cprybol** [comment]
@flying-sheep, I was having the same issues with plotting on firefox with OSX. Installing the newest repr from master fixed it for me. Looks great now

**Comment by flying-sheep** [comment]
great, thanks for the info :grin:
