### ISSUE TITLE
change set_plot_options for ggplot2

### ISSUE THREAD

**Issue by MengyingLi** [IRkernel/IRkernel#124]
I tried to change the plot width, but after I first set a width using `IRkernel::set_plot_options (width = 200)`, then the graph became too wide and i want to switch back and i tried `IRkernel::set_plot_options (width = 20)` but nothing changed, it was still as large as `width = 200`. and how to specify the width to be the percentage of the cell? i tried both `IRkernel::set_plot_options(width = '100%')` and `IRkernel::set_plot_options(width = 100%)` but neither of them work

Also there is always an error on the top which said `Error in if (args[[1]]$name == "C_title" && !is.null(args[[2]])) {: missing value where TRUE/FALSE needed`

**Comment by flying-sheep** [comment]
plot width is in inches. so 200 is huge. but the CSS for the notebook includes:

```css
div.output_area img, div.output_area svg {
    max-width: 100%;
}
```

so it’s limited to the cell width.

---

about your second problem: this is fixed in the development version of IRkernel/repr. try

```r
devtools::install_github('IRkernel/repr')
```

**Comment by MengyingLi** [comment]
I thought it was in pixels as well. the only warning message is `use repr instead` when I tried to set the width. Also how can I switch back to the normal size? It seems as long as I used `set_plot_options`, it can't be changed at all

**Comment by MengyingLi** [comment]
btw I did not see a clear example about how to use `repr.plot`, could you give an example about how it works? Thanks!

**Comment by flying-sheep** [comment]
normal size is 7. maybe you didn’t try small enough?

and the recommended way is using the [`repr.plot.*` options](https://github.com/IRkernel/repr/blob/master/R/options.r#L51-L61), e.g. via `options(repr.plot.width = 9)`
