### ISSUE TITLE
The format of titles and x axis labels look very weird from ggplot2

### ISSUE THREAD

**Issue by MengyingLi** [IRkernel/IRkernel#125]
I tried to generate a plot using a function, but the x label looks very weird. I tried this in R studio and it works fine. Any idea about how this might happen?
```
allDiffDistPlot = function(i){
p1 = ggplot(all_Consolidated[[i]],aes(x =group ,y = Count ) ) + geom_bar(stat = "identity") +
    xlab("Difference in Days") + ylab ("Number") + theme_economist()+theme(text  =  element_text(size  =  12, face = "bold"),legend.position = "none") + 
    geom_text(data = all_Consolidated[[i]],aes(label = Count),size = 3,vjust = -0.5,position  =  position_dodge(width = 1.05))
               print(p1)
}
```

![image](https://cloud.githubusercontent.com/assets/6514708/7503226/777c98ca-f3f6-11e4-94a3-78fa549bd724.png)

**Comment by flying-sheep** [comment]
firefox’ SVG rendering paired with the way the cairo svg device renders text in SVGs

**Comment by takluyver** [comment]
@flying-sheep do you understand the details of what's going wrong here? It would be nice to make sure that the issue is reported to Firefox or cairo. If this affects a lot of plots (I suspect it does, I've seen SVG issues in very simple plots), I would consider disabling svg for plots in the default options. IPython only sends png by default as well.

**Comment by flying-sheep** [comment]
well, i think an older version of firefox has problems rendering `<use>` objects that refer to `<symbol>` objects.

but i haven’t seen it in a while and it is/was clearly firefox’ fault

**Comment by takluyver** [comment]
I have definitely seen some issues on current Firefox - I don't know what the underlying cause was, though.

**Comment by flying-sheep** [comment]
yeah true, it still breaks for me as well… 

it has to do with the notebook CSS or something. if i copy the HTML code of the enclosing `<div/>` into a new empty HTML document.

* [extracted](http://bl.ocks.org/flying-sheep/3feee91a721e197f8415)
* [native](https://gist.github.com/anonymous/6e0be520ffeb503a82d0) (you have to download this as nbviewer doesn’t work)

**Comment by takluyver** [comment]
that vaguely rings a bell. I think a lot of SVG doesn't expect to be embedded in a page with other styles and things, so it doesn't namespace its classes. We may be able to get round it by putting the SVG in its own iframe. @minrk , am I remembering that right?

**Comment by minrk** [comment]
@takluyver that sounds right. The `isolated` metadata key tells the notebook to put it in an iframe.

**Comment by JanSchulz** [comment]
I think due to the amount of bugreports we will get for this (#126?) it would be better to remove svg from the default plotting formats.

**Comment by takluyver** [comment]
I think that might be best, though perhaps we should experiment with the 'isolated' metadata key too.

**Comment by flying-sheep** [comment]
yeah, definitely. if that’s a one-line fix that allows us to keep SVG as output format, we should do it.

probably comment the choice to do it with an explanation about the render errors.

**Comment by takluyver** [comment]
I've had a go at doing that in #128
