### ISSUE TITLE
best place for syntax highlighting CSS

### ISSUE THREAD

**Issue by flying-sheep** [IRkernel/IRkernel#129]
one can do this:

```r
display.highlight.css <- function(theme = 'default', set.option = TRUE) {
	if (set.option)
		options(repr.function.highlight = TRUE)
	css <- knitr::theme_to_header_html(theme)$highlight
	IRdisplay::display_html(paste0('<style>', css, '</style>'))
}
```

but it requires interplay of IRkernel, IRdisplay, repr, highr, and knitr

i still think it should live sohmewhere as a convenience function, but where?

**Comment by JanSchulz** [comment]
Why do you want to do syntax highlighting in `repr`?

**Comment by flying-sheep** [comment]
for function code (`repr_*.function`) it’s already there and completely optional (if it’s set, `highr` is used to highlight the code)

**Comment by takluyver** [comment]
I wonder if it's easier to do the highlighting on the frontend using `CodeMirror.runMode`. Though I guess that wouldn't work for nbconverted output.

**Comment by JanSchulz** [comment]
I still don't think that these things should go into the repr package:

* it makes repr depend on a highlighting package which must be installed. If repr should be adopted by other packages (e.g. knitr) it would be better to have no dependencies and especially no a dependency for a feature which is seldom used
* adding css for syntax highlighting may interfere with the frontend, which may use a different highlighter and different css rules

So, I would argue that a `repr_text.function` is fine, but nothing else. If a user wants more, the user should implement it. 

[but where would you need such a repr function? showing off a library function? for self defined functions, you can better show the source code and execute it and thereby creating the function.]

**Comment by flying-sheep** [comment]
please read more closely: it doesn’t depend on that package: it uses `requireNamespace` to try and load it, and raise an error if it can’t. and *that* behavior has to be activated via option!

so what exactly is the problem? that the functionality is there?

**Comment by takluyver** [comment]
I don't want to break things up into tiny pieces unnecessarily, but now that we've got a release out, I'm open to the idea of splitting repr into the fundamental API and the implementations of repr methods for common types. I'm not entirely convinced it's necessary yet, but it's worth considering. @JanSchulz , do you have a concrete case where you want to use the repr machinery but not some of the implementations that are currently in repr?
