### ISSUE TITLE
Only return rich formats if necessary

### ISSUE THREAD

**Issue by willwhitney** [IRkernel/IRkernel#140]
Currently IRkernel sends back every response, even if it's really plaintext, as several different MIME types. This makes it impossible for Hydrogen to distinguish whether it should actually be displaying the response as text or as HTML.

**Comment by rgbkrk** [comment]
Generally, from the purview of Jupyter, the frontends are supposed to pick what their richest display protocol is. For Atom and Hydrogen, this should probably be `text/html`. The [notebook ordering may help](https://github.com/jupyter/notebook/blob/b536da10d871f87729d3c9a6269a13bf61779213/notebook/static/notebook/js/outputarea.js#L941-L951). It's the same ordering I'm using in sidecar.

**Comment by willwhitney** [comment]
Sure, that makes perfect sense. But if the kernel sends back latex and HTML
and text and Markdown and [...] for the number `6`, that implies to me that
it really needs to be rendered as an HTML block instead of a tiny bubble.

Basically, at present Hydrogen is treating different response types
differently, and choosing the richest one. But if the kernel is sending
back a "rich" response for trivial data, this breaks down.

**Comment by takluyver** [comment]
I think @flying-sheep chose to do rich reprs even for simple data. In IPython we only have text reprs for numbers, lists, strings etc., and then provide rich reprs for things where it's really important, like tables, graphs, mathematical expressions. We should think about advantages and disadvantages.

**Comment by willwhitney** [comment]
If we want frontends to be able to do different formatting for different kinds of media, the kernel needs to be somehow informing them what that output really is. To me it doesn't seem like there's any advantage to sending back several MIME types which all contain the same content.

In the case of Hydrogen the issue is that I expect an HTML response to be something substantial that shouldn't go in a tiny inline bubble. If always sending back all formats is the way we want to go, I can work around that, but it's much simpler if richer formats are only used for content that's actually rich.

**Comment by takluyver** [comment]
Part of what's tricky in R is that a single number is the same type as a sequence of 100 numbers. I imagine the former should go in an inline bubble, but that would be tricky for the latter.

**Comment by willwhitney** [comment]
Ah, interesting. That's actually fine in my case, though - I'll just wrap
it onto multiple lines.

**Comment by willwhitney** [comment]
But I'd like to be able to treat e.g. a plot or video differently than a
bit of text.

**Comment by takluyver** [comment]
What about something like a data frame - would you prefer an HTML table or ASCII?

**Comment by willwhitney** [comment]
HTML, probably. Anytime there's an advantage to a richer display, I'm all
for it.

**Comment by flying-sheep** [comment]
well, i did it that way for recursive reprs:

a named list of a single integer and multiple strings will something like this:

> **$first**
> &emsp;1
> **$second**
> &emsp;"foo"&emsp;"bar"

can you show me what hydrogen is and what that “bubble” means?

**Comment by flying-sheep** [comment]
hmm, i think the fact that the result is HTML says nothing about its length: “**a**: 1” is shorter than “'some super long string that has\nlinebreaks and stuff!'”

maybe you should decide what kind of popup to display based on if the returned HTML is a block tag or not.

**Comment by willwhitney** [comment]
Strings that are multiline are already a special case.

I think I'm going to move over to a more involved scheme of measuring the element, then laying it out based on that. There may be some weird edge cases in there, but we'll see how it goes.

Since it sounds like this change isn't a clear win, I'll close the issue.
