### ISSUE TITLE
Plot title and label rendering

### ISSUE THREAD

**Issue by MatthewGilbert** [IRkernel/IRkernel#141]
I am having issues with the y axis and the titles of plots getting jumbled. I've included an example of what I'm talking about as well as some system info

The version of the notebook server is 3.0.0-f75fda4 and is running on:
Python 2.7.9 |Anaconda 2.2.0 (64-bit)| (default, Apr 14 2015, 12:54:25) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
R version 3.2.0 (2015-04-16)

    set.seed(42)
    epsilon1 <- rnorm(1000)
    scale <- c(rep(0.5,333), rep(1,334), rep(1.5,333))
    plot(epsilon1, main='Renders fine')
    plot(scale, main='Does not render well')
    plot(epsilon1*scale, main='Does not render well')

![part1](https://cloud.githubusercontent.com/assets/2401026/7788323/e555ef52-0203-11e5-9b50-7cb2323ac53f.png)

![part2](https://cloud.githubusercontent.com/assets/2401026/7788318/b3d57038-0203-11e5-9004-885efa065614.png)

**Comment by takluyver** [comment]
It's working OK here; it might have been fixed by #128. We should probably start thinking about making another release.

**Comment by MatthewGilbert** [comment]
Yes this resolved my issue. Should've looked around a bit more, thanks.

**Comment by takluyver** [comment]
No problem, thanks for confirming that it is fixed.
