### ISSUE TITLE
Add link to irkernel.github.io to description.

### ISSUE THREAD

**Issue by Carreau** [IRkernel/IRkernel#142]
Right now it says `R kernel for IPython` and I don't find any easy/obvious links to website.

And description cannot be editted through PRs :-(

**Comment by flying-sheep** [comment]
The description for [IRkernel/irkernel.github.io](https://github.com/IRkernel/irkernel.github.io) says “Package repository for IRkernel”.

But I agree: It should probably be changed to “Website and package repository for IRkernel” and include a link. (@takluyver has to do it)

**Comment by Carreau** [comment]
> The description for IRkernel/irkernel.github.io says “Package repository for IRkernel”.

Sure but that's the website repository. I was thinking of this repository itself. Most link are to this, and people don't think in looking at other repo of organisation.

**Comment by flying-sheep** [comment]
yes, let’s add it to both (or all) repos.

**Comment by takluyver** [comment]
I've put it as the website link for both repos on Github - is that what you meant?

**Comment by flying-sheep** [comment]
yes! :+1:
