### ISSUE TITLE
0.4 release

### ISSUE THREAD

**Issue by takluyver** [IRkernel/IRkernel#144]
@flying-sheep @JanSchulz , I'd like to get 0.4 out soon, particularly because of the fix for SVG plots. Is there anything you'd particularly like to get in before we cut a release?

**Comment by JanSchulz** [comment]
None that I know of... I should work on drat that the macosx build is fine... But we can workaroudn that with a copy/move...

**Comment by flying-sheep** [comment]
i also don’t need something in. let’s get this done for the bugfixes!

**Comment by takluyver** [comment]
OK, I've pushed a 0.4 tag.

@JanSchulz , can you work your magic with drat again? And @asmeurer, please update the conda package when it suits you.

**Comment by JanSchulz** [comment]
Is it only IRkernel? This is on https://github.com/IRkernel/irkernel.github.io/pull/9.

**Comment by takluyver** [comment]
Thanks. Yes, just IRkernel for now - I did scan through the list of commits since 0.3, and I don't think any of them depend on IRdisplay or repr changes, which is satisfying. We should consider releasing a new version of repr at some point too, but that's lower priority.
