### ISSUE TITLE
Windows binary for version 0.4

### ISSUE THREAD

**Issue by mikecroucher** [IRkernel/IRkernel#146]
Very happy to see the 0.4 release! When will it become the default version for Windows when one does

`install.packages(c('rzmq','repr','IRkernel','IRdisplay'),repos = c('http://irkernel.github.io/', getOption('repos')))`

I just tried an install and still get 0.3

**Comment by takluyver** [comment]
Sorry, I had omitted to merge the PR to add the new packages. They should be there now.

**Comment by mikecroucher** [comment]
It's still reporting 0.3 on windows. On a clean VM, I did

`install.packages(c('rzmq','repr','IRkernel','IRdisplay'),repos = c('http://irkernel.github.io/', getOption('repos')))`

asking for the version number, I get 

`packageVersion('IRKernel')
[1] ‘0.3’
`

**Comment by takluyver** [comment]
@JanSchulz , ideas? Do the `PACKAGES` files need updating? They still refer to 0.3.

**Comment by JanSchulz** [comment]
Yes, my mistake, submitted a new PR with the added (updated) files.
