### ISSUE TITLE
Unnecessary message `IRkernel::main()` when starting kernel

### ISSUE THREAD

**Issue by rsmith31415** [IRkernel/IRkernel#148]
A very trivial report. 

When I start a new R kernel using the following commands:

```
In [1]: from IPython.kernel import MultiKernelManager

In [2]: km = MultiKernelManager()

In [3]: id = km.start_kernel('ir')

In [4]: > IRkernel::main()
```

There is an additional message `IRkernel::main()`, as you can see above. Everything works great, but that bit is a bit annoying particularly when testing kernels using nose. This also occurs with the new version: `from jupyter_client import MultiKernelManager` instead of `from IPython.kernel import MultiKernelManager`

**Comment by flying-sheep** [comment]
the kernel calls `R --quiet -e 'IRkernel::main()' --args '{connection_file}'`

maybe `R --slave -e ...` would be even more quiet?

**Comment by rsmith31415** [comment]
@flying-sheep Sorry for the late response. Yes, it works great now. Thank you.
