### ISSUE TITLE
Annoying message when displaying ggplot2 figures

### ISSUE THREAD

**Issue by xiaoweiz** [IRkernel/IRkernel#151]
OSX Yosemite + python 3.4.3 + ipython 3.1.0
IRKernel installed through binary installation 

The figure can be displayed but is always preceded by a message 
```shell
Error in if (args[[1]]$name == "C_title" && !is.null(args[[2]])) {: missing value where TRUE/FALSE needed
```
The R basic `plot` works without this problem, though. 

Minimal working example:
```R
library(ggplot2)
qplot(Sepal.Length, Petal.Length, data = iris, color = Species)
```

**Comment by flying-sheep** [comment]
[please search](https://github.com/IRkernel/IRkernel/search?q=C_title&type=Issues&utf8=%E2%9C%93)

this is a dplicate of #118 and #124

you can find the solution in both.

**Comment by takluyver** [comment]
I think we need to make a new release of repr to stop this warning from occurring.

**Comment by flying-sheep** [comment]
jup. sorry about introducing the bug :neutral_face:

**Comment by takluyver** [comment]
That's OK. Do you know of anything else we want to get done with repr before we release again?

Ping @JanSchulz too - we're thinking of making a new repr release.

**Comment by flying-sheep** [comment]
we could just do a quick point release. it’s a non-compiled package, so it doesn’t need different systems to be built.

**Comment by JanSchulz** [comment]
@flying-sheep do you mean that one can simple copy the packages to other platforms and run the package generating script?

@takluyver just open a issue in the irkernel.github.io repo with the tag which should be build and ping me.

**Comment by flying-sheep** [comment]
@JanSchulz  idk, we’ll have to search in the metadata, but i doubt, the R bytecode in compiled packages differs on different platforms.
