### ISSUE TITLE
This started happening...

### ISSUE THREAD

**Issue by elbamos** [IRkernel/IRkernel#156]
Could have been the new R version, could have been... well, lots of things I suppose.  Any suggestions on tracking-down the error?

```
~$ ipython console --kernel ir
IPython Console 3.1.0
> IRkernel::main()

In [1]: 
```

after waiting a minute let's see if i can get a

```
In [1]: simpleerror()
```

nope, just does nothing. ctrl-c?

```
^CError in poll.socket(list(sockets$hb, sockets$shell, sockets$control),  :
  Interrupted system call
Calls: <Anonymous> -> <Anonymous> -> poll.socket -> .Call
Execution halted
nopekernel died, restart ([y]/n)? n
```

**Comment by takluyver** [comment]
I think that mostly looks like what I'd expect, except that there's no output from `simpleError()`. Do you see output from e.g. `1+1`?

**Comment by elbamos** [comment]
At the time, I wasn't getting output from 2+2 or anything at all else. I did eventually resolve this by uninstalling and reinstalling the whole ipython stack, zeromq, and the irkernel packages.

**Comment by takluyver** [comment]
OK. I'm not sure what caused that, but closing this since you're no longer having the problem.

**Comment by elbamos** [comment]
Yes -- I'm pretty confident that it was an issue in the ipython installation, not in IRkernel.  Thanks again for your work!

**Comment by takluyver** [comment]
You're welcome :-)
