### ISSUE TITLE
Different R versions with kernelspec

### ISSUE THREAD

**Issue by alvinwt** [IRkernel/IRkernel#157]
Would it be possible to run different R versions with different kernel specs. I have multiple R environments on a server and I would like to run them using different IRkernels. Otherwise, would it be possible to do that in a running IRKernel?

**Comment by takluyver** [comment]
Yes, you can do it with different kernel specs. The kernel spec will probably be installed in `~/.ipython/kernels/ir/`. Copy that folder and edit the contents of `kernel.json` to point to the other R.

**Comment by JanSchulz** [comment]
IMO the only thing we need to add to make this possible is to add an optional parameter for the name of the kernel spec. Our current implementation of the install spec command already includes the full path to the r version, so no problem there. We currently pass `'--name', 'ir'` ([code](https://github.com/IRkernel/IRkernel/blob/master/R/installspec.r#L33)) to the kernelspec command, so simple adding a optional argument to `installspec <- function(user = TRUE, name="ir") {` and using that there will be enough...

**Comment by JanSchulz** [comment]
Ah, and replace the name with something unique, so that you can see the difference in the notebook...

**Comment by takluyver** [comment]
@JanSchulz Adding an optional parameter sounds good to me. Want to do a PR? :-)

**Comment by JanSchulz** [comment]
done: #252...
