### ISSUE TITLE
Install R kernel Windows Python 3 failed

### ISSUE THREAD

**Issue by aremirata** [IRkernel/IRkernel#159]
Please assist. I am getting the error as seen on the attached file. I installed R on my windows and ran all the codes mentioned yet I got the error as seen on the attached. When I ran ipython (jupyter) on my virtual env, I got the errors seen on the attached file when opening a new R kernel notebook

![untitled](https://cloud.githubusercontent.com/assets/9316964/8313829/c6e19d56-1a17-11e5-94f6-1a73ddf3ade9.png)

Circle back - geoffrey.murillo24@gmail.com

**Comment by takluyver** [comment]
If you open a command prompt and type `R`, does it start R? If not, you need to edit your PATH environment variable so it can find R.

**Comment by gmur24** [comment]
@takluyver How to change the Path envi var?

**Comment by takluyver** [comment]
http://www.computerhope.com/issues/ch000549.htm

**Comment by gmur24** [comment]
Thank you @takluyver ! It's already working.

**Comment by takluyver** [comment]
Great
