### ISSUE TITLE
Revolution R: kernel restarting

### ISSUE THREAD

**Issue by aflyax** [IRkernel/IRkernel#162]
After I installed Revolution R, following the instructions on their website, the IR kernel keeps restarting. Is there something I need to do additionally to point IR kernel/Jupyter to the new installation of R?

**Comment by flying-sheep** [comment]
well, the kernelspec just calls `R`, whatever that is.

either you create a copy of the directory in `~/.ipython/kernels/ir` and edit the `'R'` in the <samp>kernel.json</samp> to point to your binary, or you start it with `PATH` set to wherever your `R` binary is.

**Comment by aflyax** [comment]
I just re-installed the IR kernel, and it works now.
