### ISSUE TITLE
Don't see R in the dropdown menu

### ISSUE THREAD

**Issue by stefkernel** [IRkernel/IRkernel#163]
Hi,

I'm in:
- Windows 7
- R 3.1.3 ( and I edited the system path, so it can be run at the command prompt by typing "R")
- Anaconda with Python 3.4.

I followed the "Installing via supplied binary packages" explanations so basically in an R console I executed  `install.packages(c('rzmq','repr','IRkernel','IRdisplay'),
                 repos = c('http://irkernel.github.io/', getOption('repos')))
IRkernel::installspec()`

I didn't use the "Installing from source" (I assume I don't need it because I did the other way).

The problem is when I launch IPython (Py 3.4) Notebook I don't find R in the dropdown menu when I want to change the kernel
Here is what is display when I launch IPython (Py 3.4) Notebook :

![rkernel](https://cloud.githubusercontent.com/assets/13149591/8475462/0b834d8a-20b0-11e5-8abf-d7f6ff3b01bd.png)

Can you help me to figure out what's wrong ?

**Comment by rgbkrk** [comment]
If you're on Anaconda, you can actually run:

```
conda config --add channels r
conda install --yes r-irkernel
```

but it uses a separate R installation. /cc @asmeurer

**Comment by ruffyleaf** [comment]
I'm  on Win10 and I am unable to get the R kernel on notebook.

It works in console though. Tried the above also doesn't work.

**Comment by takluyver** [comment]
What does `jupyter kernelspec list` show you?

**Comment by ruffyleaf** [comment]
Available kernels:
  python2    C:\Anaconda\lib\site-packages\ipykernel\resources
  ir         C:\Anaconda\share\jupyter\kernels\ir

It works fine when I use the console. But similar problem with Stefkernel is that it doesn't appear in the dropdown when I create a new notebook.

(it works perfectly fine on my Mac with El Capitan)

**Comment by ruffyleaf** [comment]
Hi guys,

This was answered with Issue#120.

We need to add R to the local or global PATH.

If you installed it here:
C:\Program Files\R\R-3.2.2 << add to Path

**Comment by takluyver** [comment]
I don't think PATH affects what kernels are show in the dropdown. It should show the same choices that you saw from `jupyter kernelspec list`.

**Comment by ruffyleaf** [comment]
After putting R into the Path, it now shows up in the dropdown list.

Worked for Issue #120

**Comment by takluyver** [comment]
I'm glad it's working for you now, but I still think it was probably something else that fixed it. R not being on PATH causes the "system cannot find the file specified" error shown in [this comment](https://github.com/IRkernel/IRkernel/issues/120#issuecomment-98842356).

**Comment by ruffyleaf** [comment]
yes you are right. It shouldn't be the cause. C:\Anaconda was in the Path, and that R would have been used. 

I removed the other path to R, and the dropdown is showing good. I wonder what could have caused. 

Anyway, I will be setting up another machine soon and will trace the steps carefully.

**Comment by flying-sheep** [comment]
seems fixed/invalid, right?

**Comment by scottming** [comment]
I have the same problem, I use anaconda

```
(my-r-env) ➜  ~ jupyter kernelspec list
Available kernels:
  python2    /usr/local/share/jupyter/kernels/python2
```
How do I fix it?

**Comment by flying-sheep** [comment]
where did `IRkernel::installspec()` install it to?

**Comment by scottming** [comment]
I can see that in the dropdown now, but I have a new trouble, My IRkernel can't start on Jupyter.

<img width="975" alt="2016-07-24 14 22 12" src="https://cloud.githubusercontent.com/assets/12830256/17082266/a8ea9b16-51a9-11e6-97ae-f2b4f6e42af9.png">

the error on my iterm2:
```
[I 14:18:53.309 NotebookApp] Kernel started: 64c7c08a-c80b-4815-aeb8-5c66185fc624
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/scott/R/x86_64-pc-linux-gnu-library/3.3/stringi/libs/stringi.so':
  /home/scott/.anaconda3/lib/R/bin/exec/../../lib/../.././libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/scott/R/x86_64-pc-linux-gnu-library/3.3/stringi/libs/stringi.so)
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
[I 14:18:56.311 NotebookApp] KernelRestarter: restarting kernel (1/5)
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/scott/R/x86_64-pc-linux-gnu-library/3.3/stringi/libs/stringi.so':
  /home/scott/.anaconda3/lib/R/bin/exec/../../lib/../.././libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/scott/R/x86_64-pc-linux-gnu-library/3.3/stringi/libs/stringi.so)
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```

I have two R, one is for Jupyter, and another is for Rstudio server.
```R
> IRkernel::installspec()
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/home/scott/R/x86_64-pc-linux-gnu-library/3.3/stringi/libs/stringi.so':
  /home/scott/.anaconda3/lib/R/bin/exec/../../lib/../.././libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/scott/R/x86_64-pc-linux-gnu-library/3.3/stringi/libs/stringi.so)
```

Please help me, thanks a lot!

**Comment by flying-sheep** [comment]
your compiled packages don’t fit your R version.

remove your whole R package library and reinstall everything. (you could also reinstall just the compiled ones, but identifying them is probably more hassle)

**Comment by scottming** [comment]
I have done these:
```shell
conda remove r r-essentials
conda remove gcc libgcc
rm -rf .anaconda3/lib/R/
conda install -c r r-essentials
```
and run
```
jupyter notebook
```

but It can't work,the same error.

**Comment by takluyver** [comment]
Based on [this thread](https://groups.google.com/a/continuum.io/forum/#!topic/conda/nqPfPGYP--g), try removing gcc and libgcc without removing R.

**Comment by scottming** [comment]
I have tried
```
conda remove gcc libgcc
```
Not see the R in the dropdown, so  I  installed IRkernel again

```
conda install r-irkernel
```

When I run `jupyter notebook` return the same error

```shell
WARNING:root:kernel baa588a3-8169-4483-88f9-3bee9053962a restarted
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/home/scott/R/x86_64-pc-linux-gnu-library/3.3/stringi/libs/stringi.so':
  /home/scott/.anaconda3/lib/R/bin/exec/../../lib/../.././libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/scott/R/x86_64-pc-linux-gnu-library/3.3/stringi/libs/stringi.so)
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```
So I thought that  is this error coming from stringi package? Then I installed that from conda,
Jupyter  didn't work well, then I opened my Rstudio server, and run this
```
remove.packages('stringi')
```
Jupyter notebook R works.
But I will use stringi package  on Rstudio server, I can't always remove that. Is there another way to fix this **dead error**?

**Comment by flying-sheep** [comment]
no, if your R installation is broken, then there’s nothing we can do.

if it’s broken on a server, you’ll need to tell the server admin to fix it.

**Comment by takluyver** [comment]
From what I can glean, this is some incompatibility introduced by conda, but I don't really understand it properly.

**Comment by flying-sheep** [comment]
i’ve tried out anaconda and found it to be more trouble than it’s worth.

**Comment by scottming** [comment]
I've contacted Anaconda, he said [there is no fix for needing RStudio's stringi with conda's R at present](https://groups.google.com/a/continuum.io/d/msg/conda/nqPfPGYP--g/CkiiDkyyBQAJ). I know what to do, I'll remove that.
Thank you for your help!

**Comment by sumendar** [comment]
similar problem i am facing here , could you please advice about the path, where we should add, and how? @ruffyleaf @takluyver

**Comment by ruffyleaf** [comment]
@sumendar did you install Anaconda and on Windows OS?

**Comment by sumendar** [comment]
yes @ruffyleaf , i installed Anaconda on windows and i installed r-essentials by creating new environment using the command `conda create -n my-r-env -c r r-essentials` , It works well on console/bash without any errors/warnings, but i am unable to get that "my-r-env " into the drop down list of my jupyter,  when i use `jupyter notebook`  its taking into default R , that's also showing kernel error.

**Comment by nicolairiis** [comment]
@sumendar ,

I have the same problem. When installing R-essentials as a new envoirment, I would like to link the kernel such that when i launch jupyter notebook I can see the R kernel in the drop down list.

I laucn the jupyter notebook from the "root" envoirment, since it is run on a server. I have tried `jupyter kernelspec install PATHTORKERNEL`. The R kernel then shows up in the drop down menu, but the kernel keeps crashing.

How does one properly link an envoirment as a "kernel" to run?

**Comment by takluyver** [comment]
See the [installation instructions](https://irkernel.github.io/installation/), in particular `IRkernel::installspec()`.

**Comment by nicolairiis** [comment]
@takluyver This requires an existing r installation.

The above command `conda create -n my-r-env -c r r-essentials` installs R in a new environment in anaconda.

The question is, how does one run the r kernel (now installed in that environment) on the root environment?

**Comment by takluyver** [comment]
`IRkernel::installspec()` is what tells Jupyter about the existence of the R kernel. Doing that inside the environment where you installed it should let Jupyter outside that environment use it.

**Comment by mantzaris** [comment]
> If you're on Anaconda, you can actually run:
> 
> ```
> conda config --add channels r
> conda install --yes r-irkernel
> ```
> 
> but it uses a separate R installation. /cc @asmeurer

This worked for me, even being on Ubuntu

**Comment by UpasanaDutta98** [comment]
> conda config --add channels r
> conda install --yes r-irkernel

This worked for me on Mac.

**Comment by soerendip** [comment]
I would like to install in a different environment than base. But in that case R does not appear in jupyter.

**Comment by flying-sheep** [comment]
Have you read the docs for `installspec`? You can specify `user`, `sys_prefix`, or even `prefix` to install the kernelspec to wherever you want.

**Comment by soerendip** [comment]
I can install the Python kernel without problems, but for the R kernel I have to run R and install the IR kernel inside the R console. 
Installing it via `conda install r-base` is not sufficient if R is not installed in the base environment. I will have a look at the `installspecs`, if I find them.

**Comment by flying-sheep** [comment]
It’s a function of the `IRkernel` package. You need to run it if you want to use the IRkernel. Might be that the conda package comes with a pre-built `kernel.json` it installs into the right location.

**Comment by b06601024** [comment]
> > conda config --add channels r
> > conda install --yes r-irkernel
> 
> This worked for me on Mac.

**Comment by sorenwacker** [comment]
Did you install R in a separate environment though?
@b06601024
