### ISSUE TITLE
need a separate heartbeat thread?

### ISSUE THREAD

**Issue by stevengj** [IRkernel/IRkernel#164]
I noticed that you seem to be implementing your heartbeat response in the same event loop that processes other events.   This is a problem, because if you have a long-running computation it will take too long to respond to a heartbeat request and Jupyter will think that the kernel has died.

We had the same problem initially in Julia (JuliaLang/IJulia.jl#8) and solved it by spawning a real OS thread to respond to the heartbeats.  I don't know if you can do this natively in R, but if not it just involves writing a one-line C function that calls `zmq_device` and then blocks forever, which you then pass to `pthread_create` or the Windows equivalent.

**Comment by takluyver** [comment]
We're moving away from using heartbeats, and instead keeping an eye on the kernel process to see if it has died. We already do this when the kernel is started locally, and we plan to add a 'kernel nanny' to do it on remote machines as well. I'm hoping that that change will take place before the shoddy heartbeat implementation in IRkernel becomes a practical problem.

**Comment by flying-sheep** [comment]
@takluyver did that happen already?

**Comment by takluyver** [comment]
It didn't, sadly. Hopefully I'll have time to look into it at some point.
