### ISSUE TITLE
Cannot install rzmq on mac os X

### ISSUE THREAD

**Issue by jeffwong** [IRkernel/IRkernel#165]
It should be noted that one has to brew install zmq first before installing the r package rzmq.  Otherwise you will receive this error

Warning message:
In doTryCatch(return(expr), name, parentenv, handler) :
  unable to load shared object '/Library/Frameworks/R.framework/Resources/modules//R_X11.so':
  dlopen(/Library/Frameworks/R.framework/Resources/modules//R_X11.so, 6): Library not loaded: /opt/X11/lib/libSM.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Resources/modules//R_X11.so
  Reason: image not found

**Comment by takluyver** [comment]
That error message doesn't look like it's related to zmq at all.

**Comment by micrain** [comment]
I got a similar error related to the rzmq package which got resolved after doing brew install zmq and reinstalling rzmq.

**Comment by xiaoweiz** [comment]
I had a similar issue and it occurred on two different Mac machines. The script 
``` R
install.packages(c('rzmq','repr','IRkernel','IRdisplay'), repos = c('http://irkernel.github.io/', getOption('repos')))
```
runs fine. But 
```R
IRkernel::installspec()
```
yields 
``` R
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/rzmq/libs/rzmq.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.2/Resources/library/rzmq/libs/rzmq.so, 6): Library not loaded: /usr/local/lib/libzmq.4.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.2/Resources/library/rzmq/libs/rzmq.so
  Reason: image not found
```

**Comment by flying-sheep** [comment]
try

```shell
brew unlink zeromq
brew update
brew install zeromq
```

you need homebrew for that

**Comment by xiaoweiz** [comment]
I thought I'd use the binary installation to avoid homebrew in the first place...

**Comment by flying-sheep** [comment]
hmm, where does `/usr/local/lib/libzmq.3.dylib` (or 4) come from if not homebrew?

sorry, I don’t use OS X

**Comment by nicolewhite** [comment]
I'm having the same issue. I've tried everything that was talked about in https://github.com/IRkernel/IRkernel/issues/50 but I can't get past this:

```r
IRkernel::installspec()
```

Yields:

```
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/rzmq/libs/rzmq.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.2/Resources/library/rzmq/libs/rzmq.so, 6): Library not loaded: /usr/local/lib/libzmq.4.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.2/Resources/library/rzmq/libs/rzmq.so
  Reason: image not found
```

**Comment by xiaoweiz** [comment]
@flying-sheep
There isn't `/usr/local/lib/libzmq.3.dylib` (or whatever number) on my machine before homebrew. My guess is that the OSX machine used to produce the binary packages does have such a file when it compiles the source (as `rzmq.so` attempts to reference it).

**Comment by flying-sheep** [comment]
well i guess then there isn’t a way around homebrew right?

**Comment by xiaoweiz** [comment]
I know little about compilation but if the binary package for Windows works, the issue for OS X should in principle be solved.

**Comment by flying-sheep** [comment]
idk. only guessing but:

might be that the windows rzmq.dll statically links (~contains) the main ZMQ functionality while the OSX rzmq.dylib dynamically links it, which would mean that only the latter requires zmq.dylib.4 while the former requires nothing.

as said: only guessing.

**Comment by higgser** [comment]
I tried many different solution to fix the problem with the missing zmq library on my OS X. The easiest and only solution that work for me was to install version 4 of zeromq with homebrew. With the latest version 5 the ipython notebook did not connect with the kernel, even after fixing the linking issue with the install_name_tool. So my solution was;

brew uninstall zeromq
brew install zeromq405

Afterwards I reinstall the R packages of the IRkernel and it finally worked.

**Comment by flying-sheep** [comment]
try with the pbdZMQ-based master please
