### ISSUE TITLE
Suppressing verbose output

### ISSUE THREAD

**Issue by alvinwt** [IRkernel/IRkernel#166]
Is there a way to suppress the verbose output when executing functions in the cell? There is a cat() function that I cannot remove that throws out long and unnecessary output.

**Comment by takluyver** [comment]
You mean a `cat()` function in some library you're using? I don't think we can distinguish that from things that you do want to print. Maybe the library needs a flag to not print the verbose output?

**Comment by alvinwt** [comment]
I submitted an issue to that library but I would expect more packages to have similar problems with verbose output at the commandline, less suited to the notebook. An idea would be something similar to knitr's echo=FALSE argument which hides ugly code.

**Comment by flying-sheep** [comment]
everything that ends up on stderr and stdout will be displayed, just like when using a command line.

you can use [`capture.output`](https://stat.ethz.ch/R-manual/R-devel/library/utils/html/capture.output.html) or [`sink('/dev/null')`](https://stat.ethz.ch/R-manual/R-devel/library/base/html/sink.html)

**Comment by fomightez** [comment]
This work-around using IRdisplay's `clear_output` allows to hide output after-the-fact. **So it won't suppress making the output initially, yet results in removing it at the end.** (Uses `IRdispaly`, sort of like in ['is there a way to hide the code (e.g. when publishing)'](https://github.com/IRkernel/IRkernel/issues/201#issuecomment-362434411), but for hiding the output from R code execution.)

Run the following somewhere towards the top of your `.ipynb` file.

```R
library(IRdisplay)
```

Then for cells where you'd like to remove the output ultimately, you can add the clear step at the end, like so:

```R
print(2 + 2)
print(8 + 8)
print(16 + 16)
for (x in 1:705) {
    Sys.sleep(0.02)
    print(x)
}
print("imagine other stuff would go here....")
clear_output(wait = FALSE) # THIS WILL CLEAR OUT ALL OUTPUT AFTER RUNNING THE CODE ABOVE
```

That cell won't show any output **ultimately**. While it is running, it will initially show the output from the first three print statements.

It will also allow you to just remove the output from early portions of the cell if you add additional code after the `clear_output`.

Has the advantage that it will work for code that is multiple lines in a cell without need to add `invisible()` to each and every line.

Based on [here](https://github.com/IRkernel/IRkernel/issues/432) and [here](https://cran.r-project.org/web/packages/IRdisplay/IRdisplay.pdf) that involve IRdisplay's `clear_output` function that was added in 2021
