### ISSUE TITLE
IRKernel Fails to Launch Because IRKernel Installed in Personal Library

### ISSUE THREAD

**Issue by jonrobinson2** [IRkernel/IRkernel#167]
I am running R on my local windows computer and trying to access the R kernel in the notebook. Despite the UI recognizing an R kernel exists when I start up I get this error:

```python
Error in loadNamespace(name) : there is no package called 'IRkernel'
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
[I 18:11:54.750 NotebookApp] KernelRestarter: restarting kernel (1/5)
> IRkernel::main()
Error in loadNamespace(name) : there is no package called 'IRkernel'
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
[I 18:11:57.766 NotebookApp] KernelRestarter: restarting kernel (2/5)
> IRkernel::main()
Error in loadNamespace(name) : there is no package called 'IRkernel'
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
[I 18:12:00.776 NotebookApp] KernelRestarter: restarting kernel (3/5)
> IRkernel::main()
Error in loadNamespace(name) : there is no package called 'IRkernel'
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
[W 18:12:01.806 NotebookApp] Timeout waiting for kernel_info reply from 112b7c8b
-b49b-491e-b813-1f6c3b053d10
[I 18:12:03.799 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 112b7c8b-b49b-491e-b813-1f6c3b053d10 restarted
> IRkernel::main()
Error in loadNamespace(name) : there is no package called 'IRkernel'
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```

I most certainly have the IRKernel package installed but when I install the package it does so to my personal library because it can't write to the admin library. I think the reason that the IRkernal isn't found in the traceback is because Jupyter doesn't know where to look for it. Does this make sense? Am I doing something wrong here?

```r
> installed.packages()[c("IRkernel"),]
                                                                                                     Package 
                                                                                                  "IRkernel" 
                                                                                                     LibPath 
                                                             "C:/Users/Jonathan/Documents/R/win-library/3.2" 
                                                                                                     Version 
                                                                                                       "0.4" 
                                                                                                    Priority 
                                                                                                          NA 
                                                                                                     Depends 
                                                                                            "\nR (>= 3.0.1)" 
                                                                                                     Imports 
"\nrepr,\nmethods,\nevaluate (>= 0.5.4),\nIRdisplay,\nrzmq (>= 0.7.0),\njsonlite (>= 0.9.6),\nuuid,\ndigest" 
                                                                                                   LinkingTo 
                                                                                                          NA 
                                                                                                    Suggests 
                                                                                                          NA 
                                                                                                    Enhances 
                                                                                                          NA 
                                                                                                     License 
                                                                                        "MIT + file LICENSE" 
                                                                                             License_is_FOSS 
                                                                                                          NA 
                                                                                       License_restricts_use 
                                                                                                          NA 
                                                                                                     OS_type 
                                                                                                          NA 
                                                                                                      MD5sum 
                                                                                                          NA 
                                                                                            NeedsCompilation 
                                                                                                          NA 
                                                                                                       Built 
                                                                                                     "3.2.0" 
```

**Comment by takluyver** [comment]
If you're running R as the same user, I don't see why it wouldn't be finding your per-user packages. It certainly finds them for me on Linux.

**Comment by jonrobinson2** [comment]
Hm. So only thing I can think of that is different is that I installed the IRkernel package in my RStudio instance of R which installs to my personal package repository, which is not in the library folder that other packages like the parallel package is:

```r
C:/Users/Jonathan/Documents/R/win-library/3.2
```

**Comment by flying-sheep** [comment]
for me, both command line R and RStudio use and install to the same user library. likely you should find out why this doesn’t happen for you.

**Comment by takluyver** [comment]
I think all user libraries should be under `C:\Users`, so presumably the program files one is a systemwide location.

How do you install packages (like parallel) into the other location?

**Comment by jonrobinson2** [comment]
Those are preinstalled libraries that come with an R installation and are
installed in the Program Files folder on Windows.

**Comment by takluyver** [comment]
Ah, gotcha. I don't think personal libraries in general are a problem - that seems to be the normal way that R installs packages.

@flying-sheep do you know how to check where it's looking for packages? We want the equivalent of Python's `sys.path`.

**Comment by jonrobinson2** [comment]
In R there is the .libpath(). Just from RStudio it doesn't let me install
to the Program Files library where the preinstalled packages go.

**Comment by takluyver** [comment]
OK, and if you start R at the command line and run `.libPaths()`, does it show your personal package library?

**Comment by jonrobinson2** [comment]
Nope it doesn't.

```r
> .libPaths()
[1] "C:/Program Files/RRO/R-3.2.0/library"
```

**Comment by jonrobinson2** [comment]
Maybe this is more of a Windows RStudio issue where I need to figure out how to let RStudio install packages to that folder.

**Comment by jonrobinson2** [comment]
Hm, so this is all solved if I run RStudio as an admin. I guess issue closed?

**Comment by takluyver** [comment]
It sounds to me like the problem is the other way round - R should be looking in your personal library, even when it's not started from RStudio. What happens if you do an `install.packages()` in R in the command prompt?

**Comment by jonrobinson2** [comment]
It installs so the Program Files system library. Seems if I install
IRkernel from there it will run. Am deleting all my packages and
reinstalling them now as packages installed as an Admin.

**Comment by jonrobinson2** [comment]
Hm. So I entered RStudio running it as an admin here using the instructions for installation from the README and got this, which still installed it as a user library and means that the Kernel can't find the packages required to start an R Kernel on my personal Jupyter Server on this clumsy local Windows machine:

```r
> install.packages(c('rzmq','repr','IRkernel','IRdisplay'),
+                  repos = c('http://irkernel.github.io/', lib='C:/Program Files/RRO/R-3.2.0/library', getOption('repos')))
Installing packages into ‘C:/Users/Jonathan/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
Warning in install.packages :
  unable to access index for repository C:/Program Files/RRO/R-3.2.0/library/src/contrib
Warning in install.packages :
  unable to access index for repository C:/Program Files/RRO/R-3.2.0/library/bin/windows/contrib/3.2
trying URL 'http://irkernel.github.io/bin/windows/contrib/3.2/rzmq_0.7.7.zip'
Content type 'application/zip' length 680354 bytes (664 KB)
downloaded 664 KB

trying URL 'http://irkernel.github.io/bin/windows/contrib/3.2/repr_0.2.zip'
Content type 'application/zip' length 17800 bytes (17 KB)
downloaded 17 KB

trying URL 'http://irkernel.github.io/bin/windows/contrib/3.2/IRkernel_0.4.zip'
Content type 'application/zip' length 66004 bytes (64 KB)
downloaded 64 KB

trying URL 'http://irkernel.github.io/bin/windows/contrib/3.2/IRdisplay_0.3.zip'
Content type 'application/zip' length 23946 bytes (23 KB)
downloaded 23 KB

package ‘rzmq’ successfully unpacked and MD5 sums checked
package ‘repr’ successfully unpacked and MD5 sums checked
package ‘IRkernel’ successfully unpacked and MD5 sums checked
package ‘IRdisplay’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Jonathan\AppData\Local\Temp\Rtmp0OjAw6\downloaded_packages

```

**Comment by jonrobinson2** [comment]
Ugh, nevermind. I'm having a bad day. Put the lib argument before the repos argument and it installed fine into the system library. Voila everything works!

**Comment by takluyver** [comment]
OK - I still think it should see your per-user library directory, but I'm glad you got it working, in any case.

**Comment by phrmoy** [comment]
Had a similar issue. My solution was to add

.libPaths(pathArrayVariable)

to the file "Rprofile.site" such that the executable R.exe had access to the packages installed through RStudio.

I hope this helps.

**Comment by empenguinxh** [comment]
My solution is just cut all the packages from user defined lib directory to R's default lib directory
When installing packages using Rstudio, you can choose which directory to use.

Besides, the correct grammar to install packages with lib specified should be
  
   install.packages(c('rzmq','repr','IRkernel','IRdisplay'),lib='C:/Program Files/R/R-3.2.2/library', repos = c('http://irkernel.github.io/', getOption('repos')))

**Comment by jmagosta** [comment]
I've seen this as a Windows issue - where R (not necessarily RStudio) defaults to C:\Users\.. rather than C:\Program Files\... as @jonrobinson2 commented on Jul 9, 2015.  The workaround is to place all package installs into the system lib path: C:\Program Files\..  The resolution should be for Jupyter to look in both places for what it needs.

**Comment by astonian** [comment]
I noticed this problem after installing Windows R. I started sparkR from <spark installation/bin/sparkR>
Installed IRKernel & after this, it worked from notebook.

**Comment by daelinder** [comment]
I was having the same issue that OP encountered. I followed the directions to install IRKernel in RStudio, and I found that my code was installing to my personal library directory. 

My .libpaths() returned 2 paths:
* "C:/Users/david.linder/Documents/R/win-library/3.3"
* "C:/Program Files/R/R-3.3.1/library"    

I noticed that if I explicitly defined the lib path in my install.packages() command to the system library, those packages were copied over and installed correctly in the Program-Files directory. Afterwards, when I tried to use the R kernel in Jupyter Notebook, it worked flawlessly. 

````r
> ## I'm using ggplot2 for the purpose of this example, but this solution applies to any package
> .libPaths()
[1] "C:/Users/david.linder/Documents/R/win-library/3.3" "C:/Program Files/R/R-3.3.1/library"               

> install.packages('ggplot2')
Installing package into ‘C:/Users/david.linder/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/ggplot2_2.1.0.zip'
Content type 'application/zip' length 2002604 bytes (1.9 MB)
downloaded 1.9 MB

package ‘ggplot2’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
C:\Users\david.linder\AppData\Local\Temp\RtmpeiZl07\downloaded_packages

> install.packages('ggplot2', lib = .libPaths()[2], dependencies = TRUE)
````

**Comment by flying-sheep** [comment]
well, the [kernelspec](https://github.com/IRkernel/IRkernel/blob/master/inst/kernelspec/kernel.json) simply runs `R --slave -e "IRkernel::main()" --args "{connection_file}"`.

if you can run `R` from a terminal and then load `library(IRkernel)`, the above command should also work

**Comment by ChristineVH** [comment]
I'm having the same issue as OP but with the added hurdle that I can't get admin rights to the computer so I can't write to the Program Files location. I had a lot of trouble getting the kernel installed without admin privileges but it seems like I finally got it - but now installed somewhere jupyter can't see it. Is there any way to work around this?

**Comment by takluyver** [comment]
Can you try the solution in [this comment](https://github.com/IRkernel/IRkernel/issues/167#issuecomment-134535146), but using a `.RProfile` file in your home directory (on Windows, that should be `C:\Users\Username`).

This page has relevant info: http://www.statmethods.net/interface/customizing.html

**Comment by jpeacock29** [comment]
So there's a clear and correct solution as the last comment, in `~/.Rprofile` (note the lowercase `p`),

    # specify my personal library where IRkernel is installed
    r_libs_user = '~/.R/x86_64-pc-linux-gnu-library/3.2'
    # add that folder to the list of paths, telling R to find packages stored there
    .libPaths(r_libs_user)

This will be loaded when R is launched by Jupyter and allow R to find the IRkernel package.

**Comment by jjkavalam** [comment]
@jpeacock29 Thank you. This just works. You saved me a lot of time.

**Comment by seattlemarinersprospect** [comment]
I want to say that these solutions didn't work, and I also had my libraries installing in local directories. I fixed it by specifying the library path as above, but the github link for IRKernel wouldn't install. This was corrected by running

`with_libpaths(new = 'C:/Program Files/R/R-3.4.1/library', devtools::install_github('IRkernel/IRkernel'))`
