### ISSUE TITLE
export as PDF fails from R kernel in jupyter

### ISSUE THREAD

**Issue by paciorek** [IRkernel/IRkernel#169]
This should be easy to reproduce -- I was simply on try.jupyter.org and selected the R kernel.

I entered
a = 3
print(a)
in the first cell.

Then file->download as-> pdf gave this error

500 : Internal Server Error
The error was:
nbconvert failed: command could not be found: pdflatex

Same thing happens locally on a Jupyter instance with R kernel running on Ubuntu 14.10.

I'll note the same error occurs with Jupyter running a Python kernel, but doing the same on my Ubuntu 14.10 machine is fine.

**Comment by takluyver** [comment]
> command could not be found: pdflatex

Converting to PDF needs Latex. I don't think we install it on try.jupyter.org.

**Comment by rgbkrk** [comment]
Nothing wrong with installing LaTeX on try jupyter, post an issue on https://github.com/jupyter/docker-demo-images

**Comment by paciorek** [comment]
Yes, it turns out that saving to PDF from Jupyter + R in does work outside
of try.jupyter.org, contrary to my initial post.  So presumably a
try.jupyter.org issue.

**Comment by keevee09** [comment]
I have had the same issue today. I'm on OSX Yosemite with MacTex 2015 installed, python3.4.3 and attempting to save as pdf(latex) fails with a 500: Internal Server Error. Here is  part of the output from the bash console running the ipython notebook instance:
    LaTeX Warning: No \author given.
   
    ! Missing $ inserted.
    <inserted text>
                    $
    l.237     \textbf{quartz_off_screen:}
                                          3
    ?
    ! Emergency stop.
    <inserted text>
                    $
    l.237     \textbf{quartz_off_screen:}
                                          3
    !  ==> Fatal error occurred, no output PDF file produced!
    Transcript written on notebook.log.
   
[W 00:43:09.865 NotebookApp] 500 GET /nbconvert/pdf/Code/DataAnalysis/Quandl/Assessing%20Linear%20Models%20in%20R.ipynb?download=true (::1): nbconvert failed: PDF creating failed
[E 00:43:09.872 NotebookApp] {

And here is a link to the full output from attempting to save a notebook as pdf:
http://pastebin.com/WmQcwu4q

**Comment by keevee09** [comment]
PS: I can confirm that a python kernel notebook converts fine to pdf via latex.
