### ISSUE TITLE
`IRkernel::installspec()` fails if only Python 3 notebook is installed

### ISSUE THREAD

**Issue by QuLogic** [IRkernel/IRkernel#171]
I only have the Python 3 IPython installed. Much like Python recommendations, `ipython` points to `ipython2`, and `ipython3` is by itself. `installspec` uses `ipython`, so it fails when the Python 2 version is not installed (and I'd want it installed for Python 3 anyway.)

**Comment by takluyver** [comment]
If you install from our packages, you should get an `ipython` script for either Python version (in addition to `ipython2` or `ipython3`).

Whichever Python is used to install it, the kernelspec will be installed to a directory that both versions will look at, so it doesn't matter which one it's installed with.

Once Jupyter is out (we're just dealing with the last couple of packages, so it should be in the next couple of weeks), we can update this to use the `jupyter` command, which won't have different spellings for different Pythons.

**Comment by QuLogic** [comment]
> If you install from our packages, you should get an `ipython` script for either Python version (in addition to `ipython2` or `ipython3`).

Doesn't appear to be true for Fedora system packages. Maybe not Ubuntu either (not sure if they do some alternatives stuff.)

> Whichever Python is used to install it, the kernelspec will be installed to a directory that both versions will look at, so it doesn't matter which one it's installed with.

Ah, good to know. I just faked it with a quick `ipython` wrapper.

**Comment by flying-sheep** [comment]
should work now. we try several binaries now until we found one that works.

**Comment by moormaan** [comment]
Hi everyone,
I'm trying to install RKernel for IPython3, and am experiencing the following issue when I run `IRkernel::installspec()`:

> [TerminalIPythonApp] CRITICAL | Bad config encountered during initialization:
> [TerminalIPythonApp] CRITICAL | Unrecognized flag: '--replace'

I have Anaconda with Python 3 installed, and am running Linux Mint 17.1. I'm sorry if this is not the right place to post this question, but it was the only place I saw a problem with running `IRkernel::installspec()` being discussed, and thought it might be relevant.

**Comment by flying-sheep** [comment]
what does `ipython kernelspec install -h` tell you? is `--replace` among the options?

what ipython version do you have?

**Comment by moormaan** [comment]
I've figured out my problem. I've been running `sudo R` in order to install *devtools*. Once I ran just `R` and ran `IRkernel::installspec()`, it was done in less then a second without output, and I got the R notebook type. For completeness, here are the outputs for the commands you asked me to run:

$ **ipython kernelspec install -h**
> Install a kernel specification directory.
> 
> Options
> -------
> 
> Arguments that take values are actually convenience aliases to full
> Configurables, whose aliases are listed on the help line. For more information
> on full configurables, see '--help-all'.
> 
> --user
>     Install to the per-user kernel registry
> --debug
>     set log level to logging.DEBUG (maximize logging output)
> --replace
>     Replace any existing kernel spec with this name.
> --name=<Unicode> (InstallKernelSpec.kernel_name)
>     Default: ''
>     Install the kernel spec with this name
> --log-level=<Enum> (Application.log_level)
>     Default: 30
>     Choices: (0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL')
>     Set the log level by value or name.
> --ipython-dir=<Unicode> (BaseIPythonApplication.ipython_dir)
>     Default: ''
>     The name of the IPython directory. This directory is used for logging
>     configuration (through profiles), history storage, etc. The default is
>     usually $HOME/.ipython. This option can also be specified through the
>     environment variable IPYTHONDIR.

> To see all available configurables, use `--help-all`

$ **ipython --version**
> 3.2.0

**Comment by flying-sheep** [comment]
glad that it works. ipython, started with admin privileges seems to choke on that `--replace` flag (which clearly exists, as you can see in the help output)

**Comment by moormaan** [comment]
Thanks for your replies, and for the kernel - it works like a charm! I'm accessing R via HTTP from my tablet while going through an online course, and it's extremely helpful!

**Comment by takluyver** [comment]
I'd guess that when you sudo, it's finding a copy of IPython you have installed from apt, which will be older.

**Comment by flying-sheep** [comment]
glad to hear that @moormaan :smile:

i started to contribute here because i missed autocompletion and intended to use the kernel
