### ISSUE TITLE
no output in console/notebook with IRkernel

### ISSUE THREAD

**Issue by dvera** [IRkernel/IRkernel#182]
It appears IRkernel installed successfully.

When I run a cell with the R kernel in notebook, nothing is returned.

When I run a command in the console with ir kernel, it hangs at the cursor in a new line.

This does not happen with the python kernel.

How may I troubleshoot this?

**Comment by takluyver** [comment]
This sounds like the long-running issue #8. What OS are you on, and what version of zmq do you have?

**Comment by dvera** [comment]
Thanks.

I'm using zmq 4.0.7
I'm not using 4.1.3 because I'm having trouble compiling it on my system.

```
[user@host ~]$ uname -a
Linux host 2.6.32-431.11.2.el6.x86_64 #1 SMP Mon Mar 3 13:32:45 EST 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by takluyver** [comment]
Is it possible that the installed version of zmq has changed since you installed rzmq and/or pyzmq? If either is finding a different version from the one it's compiled with, that may cause problems.

**Comment by dvera** [comment]
I don't believe so. I switched to zmq version 3 and now everything appears to be working fine.
