### ISSUE TITLE
switch R version in IRKernel

### ISSUE THREAD

**Issue by MengyingLi** [IRkernel/IRkernel#183]
I recently installed R 3.2.1 and installed several new packages and I have both R 3.1.2 and R 3.2.1 on my machine. But it seems that IRKernel can't detect which R version to use and I want to load the packages I installed on R 3.2.1, but it can't work. Is there anyway to specify the package folder path of IRKernel?
![image](https://cloud.githubusercontent.com/assets/6514708/9452502/6c4381b6-4a69-11e5-95f3-63ff593a46c0.png)

![image](https://cloud.githubusercontent.com/assets/6514708/9452524/8eacb614-4a69-11e5-97a9-afad72e6baa5.png)

**Comment by takluyver** [comment]
You'll need to find the [kernel spec](http://jupyter-client.readthedocs.org/en/latest/kernels.html#kernel-specs) installed by IRkernel - on Windows, look in `%PROGRAMDATA%\jupyter\kernels\ir`.

Make a copy of that directory with a new name (e.g. `ir_32`). In it, you'll need to edit the `kernel.json` file. Make the first entry in `argv` in there be the full path to the `R.exe` you want it to run. Change the display name to something you can distinguish.

The error with installing packages is a separate thing - you need to specify the mirror using the `repos` argument to [install.packages()](http://stat.ethz.ch/R-manual/R-devel/library/utils/html/install.packages.html).

**Comment by MengyingLi** [comment]
thanks! It works! :) but is there any plan to make the upgrade of R version in IR kernel more easily?

**Comment by takluyver** [comment]
Upgrading R should be relatively easy. It's having two versions side by side, and wanting to be able to use both, that's tricky.

**Comment by ahiralesc** [comment]
In ubuntu ir is in .local/share/jupyter/kernels/ir in such directory you will find kernel.json which contains:
{
  "argv": ["/opt/anaconda2/lib/R/bin/R", "--slave", "-e", "IRkernel::main()", "--args", "{connection_file}"],
  "display_name": "R",
  "language": "R"
}

You can update conda's version of R with conda update r-essentials instead of changing the path to another R distribution in your system.
