### ISSUE TITLE
Not all output is send to the client?

### ISSUE THREAD

**Issue by jankatins** [IRkernel/IRkernel#184]
From http://opiateforthemass.es/articles/why-i-dont-like-jupyter-fka-ipython-notebook/

> This is maybe R specific, but I made an experience that the output is incomplete. Especially if you work with ggplot. Some warning messages don’t appear in the notebook, but in the terminal, you started the notebook from. This is annoying, because actually that means that you should check your terminal and your output after every command you run to make sure not to miss warnings and error messages.

@Quiri: could you post a small example where this happens?

**Comment by Quiri** [comment]
library(ggplot2)
data <- data.frame(x = letters[1:5], y = runif(5))
ggplot(data, aes(x, y)) + geom_bar()

**Comment by takluyver** [comment]
I believe that [this code](https://github.com/IRkernel/IRkernel/blob/c0f407adfc2baf631eed074ddeabd044beef071d/R/execution.r#L156-L162) should instruct evaluate to capture and redirect all the kinds of output it knows about. So I can only assume ggplot is writing warning messages in some odd way that doesn't capture. And if evaluate doesn't capture it, there's probably no easy way to capture it inside R.

We've talked before about making Jupyter wrap the kernel processes to capture anything from stdout/stderr at the OS level, but we haven't decided to do that yet.

**Comment by JanSchulz** [comment]
I've tried to include that in a RMarkdown file and the output also went to the (R-)console. The second chunk shows an error. So it seems that ggplot does something special here :-(

```R
---
title: "Untitled"
author: "Jan Schulz"
date: "19. September 2015"
output: html_document
---

text

``{r error = TRUE, message = TRUE, warnings = TRUE}
library(ggplot2)
data <- data.frame(x = letters[1:5], y = runif(5))
ggplot(data, aes(x, y)) + geom_bar()
``


``{r error = TRUE, message = TRUE, warnings = TRUE}
a <- 1 + a
``
```

I'm not sure how that can be, but the code which does it is here: https://github.com/hadley/ggplot2/blob/1244716efd8bf5555705c05a8613cca7a0f84995/R/stat-bin.r (last version which has this error message) -> https://github.com/hadley/ggplot2/blob/1244716efd8bf5555705c05a8613cca7a0f84995/R/utilities.r#L237

**Comment by JanSchulz** [comment]
Not sure if this has anything to do with it, but the evaluate code has some branches for warnings which I don't understand: https://github.com/hadley/evaluate/blob/master/R/eval.r#L122

**Comment by flying-sheep** [comment]
what do you not understand about it?

**Comment by JanSchulz** [comment]
For me it look like warnings and so on should be catched, but as far as I can see this isn't the case. Is there a stepping debugger for R?

**Comment by flying-sheep** [comment]
yeah, you can set it using `browser()`. i also don’t get why it isn’t working :smile: 

but if you want convenience, use the RStudio debugger

**Comment by JanSchulz** [comment]
Just for the reference: This looks like a problem in evaluate:

```
library(evaluate)

code <- "library(ggplot2)
data <- data.frame(x = letters[1:5], y = runif(5))
ggplot(data, aes(x, y)) + geom_bar()
"


l = list()
txt <- function(o, type) {
  t <- paste(o, collapse = '\n')
  t <- paste("OUT: ", t)
  l[length(l)+1] <<- paste("T: ",Sys.time()," type: ", type, "  -> ", t)
}
oh <- new_output_handler(source = identity, 
                         text = function(o) txt(o, "text"), 
                         graphics = identity,
                         message = function(o) txt(o, "message"), 
                         warning = function(o) txt(o, "warn"), 
                         error = function(o) txt(o, "error"), 
                         value = identity)



x <- evaluate(code, output_handler = oh)
l
```

I've opened a bug there: https://github.com/hadley/evaluate/issues/60

**Comment by janschulz** [comment]
The original bug seems to be gone in the latest ggplot:

```R
library(ggplot2)
data <- data.frame(x = letters[1:5], y = runif(5))
ggplot(data, aes(x, y)) + geom_bar()
```

results in nothing in the console and this in the notebook:
```
Error: stat_count() must not be used with a y aesthetic.
Traceback:

1. prepare_mimebundle(obj, .self$handle_display_error)
2. repr_text(obj)
3. repr_text.default(obj)
4. paste(capture.output(print(obj)), collapse = "\n")
5. capture.output(print(obj))
6. evalVis(expr)
7. withVisible(eval(expr, pf))
8. eval(expr, pf)
9. eval(expr, envir, enclos)
10. print(obj)
11. print.ggplot(obj)
12. ggplot_build(x)
13. by_layer(function(l, d) l$compute_statistic(d, panel))
14. f(l = layers[[i]], d = data[[i]])
15. l$compute_statistic(d, panel)
16. f(..., self = self)
17. self$stat$setup_params(data, self$stat_params)
18. f(...)
19. stop("stat_count() must not be used with a y aesthetic.", call. = FALSE)
```

[For the stacktrace, I opened https://github.com/IRkernel/repr/issues/45]

So as this is the only occurrence I know of, I thinks this should now get a "unreproducable" tag :-(
