### ISSUE TITLE
Jupyter 4.0.4 doesn't open notebooks with python Kernels on Mac

### ISSUE THREAD

**Issue by Sjnjerak** [IRkernel/IRkernel#188]
I just updated to Jupyter 4.0.4 through the Anaconda distribution. I can open the notebook app fine, but when I try to open one of my existing notebooks in my browser the No information is seen, and the circle in the corner indicate that the kernel is busy (see image). 
![notebook_will_not_open](https://cloud.githubusercontent.com/assets/8447235/9878784/60764e04-5bbc-11e5-9a8c-d881c3ba0993.png)

I don't get any error message in the terminal window, in fact the terminal window gives no indication that I have tried to open something. 

I'm running Mac OS version 10.10.5.

Going back to an earlier version of Jupyter fixes the problem, but I would like to update at some point and thought you should be aware of the issue.

Thank you.

**Comment by takluyver** [comment]
This is the issue tracker for the R kernel - I think you wanted the [jupyter/notebook](https://github.com/jupyter/notebook) issue tracker.

Before you file an issue there, though, hit Ctrl-F5 a few times to try to clear the cache. Sometimes there are caching issues with JS when you update.
