### ISSUE TITLE
upgrading from older versions of IRkernel on OS X

### ISSUE THREAD

**Issue by smartinsightsfromdata** [IRkernel/IRkernel#189]
After a while I came back to yupiter and IRkernel.  In the mean time I've updated R to R3.2.2

Not surprisingly the R kernel crashed.

Tried to re-install the packages, but nothing worked.  

I got:
```
>IRkernel::installspec()
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Users/e/Library/R/3.2/library/rzmq/libs/rzmq.so':
  dlopen(/Users/e/Library/R/3.2/library/rzmq/libs/rzmq.so, 6): Library not loaded: /usr/local/lib/libzmq.4.dylib
  Referenced from: /Users/e/Library/R/3.2/library/rzmq/libs/rzmq.so
  Reason: image not found
```
The solution was to install the packages **from source**, i.e. using 
```
> install.packages(c('rzmq','repr','IRkernel','IRdisplay'), type="source",
                  repos = c('http://irkernel.github.io/', getOption('repos')))
```

This fixed it: I got the expected response from `IRkernel::installspec()` and yupiter worked as a charm.

I suggest to update the README?  
(my apologies but I've no time for a pr...)

**Comment by takluyver** [comment]
I don't think the difference is about upgrading versus installing, but rather the zmq version that rzmq is built with. That same error was discussed in the comments of #165. I don't know what there is we can do to improve matters.

**Comment by minimaxir** [comment]
+1 for this solution. Hit it while having to reinstall IRkernel.
