### ISSUE TITLE
Issue with repr

### ISSUE THREAD

**Issue by wabee** [IRkernel/IRkernel#191]
When trying to set up IRkernel I get this error:

```
* installing *source* package 'repr' ...
** R
Warning: unable to re-encode 'options.r' lines 28, 31
Warning: unable to re-encode 'repr_matrix_df.r' lines 15, 16, 17
```

R.3.2.2 and Windows 7

**Comment by takluyver** [comment]
It looks like the problem is the non-ascii characters added in IRkernel/repr@a04be61363e8b8255a0bc1420c7707679f80791e. @flying-sheep , any idea what we need to do to make R on Windows happy about those?

**Comment by flying-sheep** [comment]
hmm [seemingly windows is broken](https://tomizonor.wordpress.com/2013/04/17/file-utf8-windows/) despite us [we declare the encoding](https://github.com/IRkernel/repr/blob/master/DESCRIPTION#L13). we could of course replace stuff with escape sequences (`\uabcd`)

**Comment by takluyver** [comment]
Shall we try with the escape sequences?

**Comment by flying-sheep** [comment]
sure, why not.

* [⋮](http://graphemica.com/⋮) `\u22EE`
* [⋯](http://graphemica.com/⋯) `\u22EF`
* [⋰](http://graphemica.com/⋰) `\u22F0`
* [⋱](http://graphemica.com/⋱) `\u22F1`

**Comment by wabee** [comment]
Is this committed?

**Comment by flying-sheep** [comment]
it is

**Comment by wabee** [comment]
Tried to reinstall but got the same error message.
IRkernel::installspec() runs without errors but have no idea how the errors will affect functionality

**Comment by flying-sheep** [comment]
1. it’s not released. you need to do `devtools::install_github('IRkernel/repr')` to install the git version.
2. `IRkernel::installspec()` just has to be run when we changed the `kernelspec.json` in the `IRkernel/IRkernel` project. since this bug is about `IRkernel/repr`, not `IRkernel/IRkernel`, you don’t have to run it.

**Comment by wabee** [comment]
open #191

**Comment by flying-sheep** [comment]
:smile: np!
