### ISSUE TITLE
jupyter notebook plotting not working

### ISSUE THREAD

**Issue by episodeyang** [IRkernel/IRkernel#192]
Thanks for this great kernel!

I'm trying to follow the Welcome to R tutorial on try.jupyter.org, but it looks like it is broken. The kernel keeps restarting when the plotting function is ran. (you can find the tutorial here in the root: https://try.jupyter.org)

I just started R (a friend of mine is trying to use my project [here](www.escherpad.com/signup), which is a real-time collaborative jupyter client I built for my lab, and I told him to start with try.jupyter.org first), so I'm not sure whether this problem on try.jupyter.org is a problem with the kernel or with the code?

Thanks in advance!

Ge

**Comment by flying-sheep** [comment]
the versions seem to be OK:

```
In [1]:  packageVersion('IRdisplay')
         packageVersion('IRkernel')
         packageVersion('repr')
Out[1]:  [1] '0.3'
Out[1]:  [1] '0.4'
Out[1]:  [1] '0.3'
```

the newest would be 0.3, 0.4, 0.4, and there are no critical things in the missing repr update.

**Comment by takluyver** [comment]
@rgbkrk has anything changed recently on try.jupyter that might affect the R plotting? Do you have any way to see logs from user sessions that might explain a kernel crash?

**Comment by episodeyang** [comment]
thanks everyone for helping!

**Comment by rgbkrk** [comment]
We switched to Jupyter notebook 4.0 and are using tini as the init process. I can't imagine all nodes are having trouble on try Jupyter though... Let me do some digging.

**Comment by rgbkrk** [comment]
The nodes on Jupyter notebook 4.0 with tini are A-OK. It was an old node that was acting up. This seems fine to me right now.

**Comment by flying-sheep** [comment]
OK, works well now!

**Comment by episodeyang** [comment]
Thanks guys! It works super well now!

just incidentally: I was looking at the raw data and found this super cool!! 

Is it common to have multiple types of the same data presented like this?

![multiple copies of the same plot](https://www.dropbox.com/s/a2po6zff0ntm4i1/Screenshot%202015-09-30%2011.22.10.png?raw=1)

**Comment by takluyver** [comment]
It's normal to have multiple copies of the same plot in different formats, yes. Although I thought we had dropped PDF and JPEG by default now. Maybe we haven't release that yet, or maybe tmpnb needs a package updating.

**Comment by flying-sheep** [comment]
according to the package versions above, it doesn’t really.

again no idea what’s going on…

**Comment by episodeyang** [comment]
It's fine! In Escherpad I was handling this incorrectly. Now I just need to make a new output view that allows the user to choose a different output type in the UI.

**Comment by takluyver** [comment]
> Now I just need to make a new output view that allows the user to choose a different output type in the UI.

You may not actually need that. The idea is that all the formats in the 'mimebundle' are equivalent renderings of the same thing, and the frontend chooses the one that it's best able to display. So the live notebook, which is HTML based, might prefer HTML > markdown > SVG > PNG > plaintext (this is an example, I haven't checked the real priority order), while converting to Latex might prefer Latex > PDF > png ...

Our own UI doesn't expose the choice to the user, because what they see should be equivalent in any format that the interface can display (besides the plain text fallback). There are ways to configure the priority for nbconvert, but that's a fairly advanced setting.

**Comment by flying-sheep** [comment]
worth mentioning that of course you don’t need to handle all. a LaTeX renderer doesn’t have to use some HTML→LaTeX converter to be somehow able to render HTML, you can just ignore it.

**Comment by episodeyang** [comment]
haha yeah, so here is my current list of priorities: 

```javascript 
var mime_type_priorities = [
            'image/svg+xml',
            'image/svg',
            'image/png',
            'image/jpeg',
            'image/pdf',
            'text/html',
            'application/pdf',
            'text/html',
            'text/markdown',
            'text/plain',
            'text/latex'];
```

What do you think?

**Comment by flying-sheep** [comment]
well, can you render all that? if not, better remove the ones you can’t render.

**Comment by episodeyang** [comment]
Yeah, I can render all of these.

**Comment by rgbkrk** [comment]
`text/html` is in there twice

**Comment by episodeyang** [comment]
@rgbkrk Thanks Kelly! Haha you just spotted my mistake:) Need more sleep :cold_sweat:

**Comment by episodeyang** [comment]
Also I'm not sure if there is non-xml svg and how it would look like. The svg+xml needed to be treated differently because of of global glyph deinition. but I don't recall what image/svg (non +xml) look like.

**Comment by takluyver** [comment]
I think `image/svg+xml` is the correct mimetype for SVG, and anything claiming `image/svg` is just mistaken. IRkernel should never give an `image/svg` option. You can see the mimetypes we might output here:

https://github.com/IRkernel/repr/blob/master/R/generics.r#L119

**Comment by episodeyang** [comment]
I see! Thanks!

**Comment by hvsarma** [comment]
Add the following. `options(jupyter.plot_mimetypes = 'image/svg+xml')`. 
This rendered my ggplots beautifully.
