### ISSUE TITLE
RMySQL Library

### ISSUE THREAD

**Issue by barnettjacob** [IRkernel/IRkernel#197]
Hey, thanks for all the awesome work!

I'm unable to install the RMySQL package using the normal method i.e.: `install.packages('RMySQL', repos='http://cran.us.r-project.org')`.

I get a `Warning message:
In install.packages("RMySQL", repos = "http://cran.us.r-project.org"): installation of package ‘RMySQL’ had non-zero exit status` error message.

This has worked for other packages e.g. Lubridate.

Any ideas?
Jacob

**Comment by takluyver** [comment]
Does it work if you do the same thing in a regular R terminal?

**Comment by barnettjacob** [comment]
Yes but I do get a prompt `Do you want to install from sources the package which needs compilation?
y/n:`

**Comment by takluyver** [comment]
Ah, right. Code that tries to prompt the user won't work until we implement the stdin part of the protocol. And if it's prompting in a subprocess, as implied by the error message, it won't work at all.

I guess you can get round this by adding `type="source"` when you call `install.packages`.

**Comment by barnettjacob** [comment]
Good suggestion although in this case I'm still getting the error - specifying the source also gives me the error in the R console. 

Obviously this isn't your problem although RMySQL is a pretty widely used package so I guess this will impact other people :-)

`------------------------- ANTICONF ERROR ---------------------------
Configuration failed because mysql-connector-c was not found. Try installing:
 * deb: libmysqlclient-dev | libmariadbclient-dev (Debian, Ubuntu)
 * rpm: mariadb-devel | mysql-devel (Fedora, CentOS, RHEL)
 * csw: mysql56_dev (Solaris)
 * brew: mysql-connector-c (OSX)
If mysql-connector-c is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a mysql-connector-c.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘RMySQL’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/RMySQL’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/RMySQL’`

**Comment by barnettjacob** [comment]
Ignore above `brew install mysql-connector-c` fixed it. Thanks a million.

**Comment by takluyver** [comment]
Ah, I guess you're on a platform where it would normally install from a binary package, but one of the dependencies must only have a source package.

**Comment by takluyver** [comment]
Glad it's working. I've opened #199 about the stdin protocol, so I'll close this.
