### ISSUE TITLE
Plot labels rendering when downloading as html

### ISSUE THREAD

**Issue by piero2c** [IRkernel/IRkernel#198]
After a plot the second plot has render errors.
I found similar issues here but they were all resolved a long time ago, I wonder if it's a browser error?

I'm using Chrome 45.0.2454.101 on Linux Mint

"The version of the notebook server is 4.0.4 and is running on:
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]

Current Kernel Information:
R version 3.2.2 (2015-08-14)"

![p1](https://cloud.githubusercontent.com/assets/13797878/10309598/e5de0d22-6c13-11e5-83f6-e7e71959c98e.png)
![p2](https://cloud.githubusercontent.com/assets/13797878/10309599/e5edaf84-6c13-11e5-9c83-ef85878d8b17.png)

The pdf is fine

**Comment by takluyver** [comment]
How did you install IRkernel, and what version did you get? That does look very much like errors that we already fixed.

**Comment by piero2c** [comment]
I used the following

install.packages(c('rzmq','repr','IRkernel','IRdisplay'),
                 repos = c('http://irkernel.github.io/', getOption('repos')))
IRkernel::installspec()

**Comment by takluyver** [comment]
Do you see the same on https://try.jupyter.org/ ?

I'm on an older computer at the moment, and rzmq won't compile, so I can't easily test it locally.

**Comment by piero2c** [comment]
https://try.jupyter.org/ works fine = /

I don't know if this is related but, I had this problem earlier when I tried to install rzmq:
https://github.com/JustinTulloss/zeromq.node/issues/281

This solution solved the issue
http://askubuntu.com/questions/365074/cannot-install-zeromq-package-from-chris-lea-zeromq-in-12-04/388770#388770

Besides that, IRkernel was installed normally

**Comment by takluyver** [comment]
I missed that this is when downloading as HTML. I've just looked at the code, and I don't think nbconvert respects the `isolated` flag we used to solve this issue. I've opened jupyter/nbconvert#129 to address that.

**Comment by piero2c** [comment]
Thank you takluyer!
If anyone is having the same issue, downloading the notebook as Rmd and then converting to html trough Rstudio packages worked for me.

**Comment by flying-sheep** [comment]
jup, the SVG isolation support of nbconvert is at fault. although i can’t really thing of a way to do it there.

we have a possibility to avoid this error by parsing the SVG as XML, finding all `<use/>` nodes, collecting their `href`s, finding all symbols `id`-referenced by them, and altering the ids by prefixing them with some randomly generated GUID.
