### ISSUE TITLE
is there a way to hide the code (e.g. when publishing)?

### ISSUE THREAD

**Issue by smartinsightsfromdata** [IRkernel/IRkernel#201]
Using rmarkdown withRStudio it is possible to prefix a cell with 
```
````{r echo=FALSE} 
```
This is really useful when you don't want to bore your audience with many lines of code, but just to focus on the important chunks.
Is it possible with jupyter / IRkernel?

Pls note that the issue discussed [here](https://github.com/IRkernel/IRkernel/issues/166) was different: it was about suppressing output from R.

My question is how to suppress visibility of chunks of code when publishing to pdf / html / markdown.

**Comment by takluyver** [comment]
You probably want to tag cells somehow in metadata, and then use a custom Nbconvert template to exclude them from the output. Nbconvert is the piece that turns notebook files into other formats like pdf or html. We wrote some examples of doing this for a tutorial here:
https://github.com/jupyter/ngcm-tutorial/tree/master/Day-2/nbconvert_templates

There's more info on customising nbconvert templates here:
http://nbconvert.readthedocs.org/en/latest/customizing.html

**Comment by smartinsightsfromdata** [comment]
@takluyver I pasted in the cell metadata the following:
````
{
  "collapsed": false,
  "trusted": true,
  "nbconvert": {
    "hide_code": true
  }
}
````
But still I can see the cell, e.g. during print preview.  

Am I missing something?

**Comment by flying-sheep** [comment]
that’s what i do in one of mine. i use the slideshow toolbar to set this metadata:

```json
"slideshow": {
    "slide_type": "skip"
}
```
and use this in my template:

```latex
((*- extends 'article.tplx' -*))

[...]

((*- block any_cell -*))
((*- if cell.metadata.get('name') != 'introduction' and  cell['metadata'].get('slideshow', {}).get('slide_type', '') != 'skip' -*))
((( super() )))
((*- endif -*))
((*- endblock any_cell -*))
```

**Comment by JoseRZapata** [comment]
I used this code in a jupyter cell and it works for me
[https://stackoverflow.com/questions/35015947/hiding-code-in-jupiter-in-r](https://stackoverflow.com/questions/35015947/hiding-code-in-jupiter-in-r)  

```r
library(IRdisplay)
display_html(
'<script>  
code_show=true; 
function code_toggle() {
  if (code_show){
    $(\'div.input\').hide();
  } else {
    $(\'div.input\').show();
  }
  code_show = !code_show
}  
$( document ).ready(code_toggle);
</script>
  <form action="javascript:code_toggle()">
    <input type="submit" value="Click here to toggle on/off the raw code.">
 </form>'
)
```
