### ISSUE TITLE
Error printing data frame

### ISSUE THREAD

**Issue by mndrake** [IRkernel/IRkernel#202]
I am getting a warning when printing a data frame that has more rows than are displayed when one of the columns is a factor column.

Here is an example notebook that does not render correctly for me.

In a prior version of IRkernel (0.3) it did render correctly, but the current version from github does not.

https://gist.github.com/mndrake/71ce9b15543cfa2fea46

**Comment by flying-sheep** [comment]
it’s a [repr](https://github.com/IRkernel/repr) bug. would you mind re-filing it there and closing it here?

**Comment by mndrake** [comment]
Posted in [repr](https://github.com/IRkernel/repr/issues/16), can close here. @flying-sheep thanks for pointing me in the right direction.
