### ISSUE TITLE
R kernel always dead: Jupyter and conda for R

### ISSUE THREAD

**Issue by RaymondChia** [IRkernel/IRkernel#204]
I installed R-Essentials by following the steps in https://www.continuum.io/blog/developer/jupyter-and-conda-r. But when I run "Jupyter notebook" and start a R kernel, the kernel is always dead, and terminal feeds back: 
*I 09:25:00.040 NotebookApp] KernelRestarter: restarting kernel (4/5)
/home/ray/anaconda3/lib/R/bin/exec/R: symbol lookup error: /home/ray/anaconda3/lib/R/bin/exec/../../lib/../../libreadline.so.6: undefined symbol: PC*

Does anyone know how to handle it? Thanks.

**Comment by flying-sheep** [comment]
this describes the error: https://github.com/ContinuumIO/anaconda-issues/issues/152#issuecomment-92093986

you can do

```r
cp -p /lib/x86_64-linux-gnu/libreadline.so.6 ~/anaconda/lib/libreadline.so.6
```

apparently

**Comment by RaymondChia** [comment]
It works now. Thank you very much.

**Comment by SepehrAkhavan** [comment]
I also have the same problem. For me, terminal returns:
unable to load shared object '/Users/sepehrakhavan/anaconda/lib/R/library/rzmq/libs/rzmq.so':
  dlopen(/Users/sepehrakhavan/anaconda/lib/R/library/rzmq/libs/rzmq.so, 6): Library not loaded: @rpath/./libzmq.4.dylib
  Referenced from: /Users/sepehrakhavan/anaconda/lib/R/library/rzmq/libs/rzmq.so
  Reason: image not found

Really appreciate your help,
-Sepehr

**Comment by flying-sheep** [comment]
@SepehrAkhavan different issue:

https://github.com/IRkernel/IRkernel/wiki/Dev-info

> RZMQ/ZMQ version mismatch. You likely updated the system ZMQ lib and now RZMQ points to a nonexistent .so/.dylib file. Reinstall (and force recompilation of) RZMQ.

**Comment by elliecasey** [comment]
I hahve a similar problem - the kernel dies after I try to run anything. The terminal returns this 

[I 10:59:30.323 NotebookApp] Kernel started: 2cd641f4-8469-4023-a3ec-6be557436f48
[1] "Got unhandled msg_type:" "comm_open"
[I 10:59:36.140 NotebookApp] Kernel restarted: 2cd641f4-8469-4023-a3ec-6be557436f48
Error in unlockBinding("base_display", displayenv) :
  no binding for "base_display"
Calls: <Anonymous> ... <Anonymous> -> handle_shell -> <Anonymous> -> unlockBinding
Execution halted

Thanks for your help,

Ellie

**Comment by flying-sheep** [comment]
please update both IRdisplay and IRkernel to the newest git versions as described on the website.

**Comment by elliecasey** [comment]
Thanks @flying-sheep , i tried this but getting this error 
Downloading GitHub repo IRkernel/IRdisplay@master
from URL https://api.github.com/repos/IRkernel/IRdisplay/zipball/master
Installing IRdisplay
Error in if (download_method_secure()) { :
  missing value where TRUE/FALSE needed

**Comment by flying-sheep** [comment]
that’s a bug in devtools. do you have the newest version?

**Comment by h8d5lo1** [comment]
Hello @flying-sheep, I'm having a similar problem to elliecasey. I'm working from OSX 10.11.5 and have done a lot of troubleshooting. When I load up an R notebook the kernel appears alive, but on running a command it dies and I get the following error in the terminal:


```
Error in unlockBinding("base_display", displayenv) : 
  no binding for "base_display"
Calls: <Anonymous> ... <Anonymous> -> handle_shell -> <Anonymous> -> unlockBinding
Execution halted
```

I've updated to the latest versions of IRkernel and IRdisplay, and get the following message when trying now:

```
> library(devtools)
> install_github('IRkernel/IRdisplay')
Skipping install of 'IRdisplay' from a github remote, the SHA1 (6f275754) has not changed since last install.
  Use `force = TRUE` to force installation
> install_github('IRkernel/IRkernel')
Skipping install of 'IRkernel' from a github remote, the SHA1 (f71b035f) has not changed since last install.
  Use `force = TRUE` to force installation
```

Any help you can offer would be much appreciated!

**Comment by brendo1001** [comment]
I had this issue. The problem appeared to be with the IRkernel version. The following script got me sorted.

install.packages(c('repr', 'IRdisplay', 'pbdZMQ', 'devtools'))
devtools::install_github('IRkernel/IRkernel')
IRkernel::installspec()  # to register the kernel in the current R installation

**Comment by flying-sheep** [comment]
`unlockBinding("base_display", displayenv)` isn’t part of any code we have anymore. you somehow still have an old version…

**Comment by h8d5lo1** [comment]
Thanks a lot. I've tried that many times before but after reinstalling R and using @ck37's advice about setting up a temporary directory so my sed programme is found in the search (another issue I had), and then installing repr, IRdisplay, pbdZMQ, devtools and IRkernel, i have finally got it working!

**Comment by flying-sheep** [comment]
great! :smile:

**Comment by puneetjindal** [comment]
I have tried the above mentioned steps on my windows machine but it is not working

**Comment by janschulz** [comment]
@puneetjindal What is you exact error message?

**Comment by puneetjindal** [comment]
@janschulz : It says " Kernel deleted before session" when it open the ipython notebook with R kernel

**Comment by janschulz** [comment]
Can you get the log in the notebook window?

**Comment by takluyver** [comment]
Do you have an up to date version of Jupyter? Depending on how you installed it, try:

```
conda update jupyter
```

or:

```
pip install --upgrade jupyter
```

**Comment by jolespin** [comment]
```
this describes the error: ContinuumIO/anaconda-issues#152 (comment)

you can do

cp -p /lib/x86_64-linux-gnu/libreadline.so.6 ~/anaconda/lib/libreadline.so.6
apparently
```
How can this work for OSX?

**Comment by flying-sheep** [comment]
that’s one of the reasons why i dumped anaconda. it’s not worth the pain

**Comment by jolespin** [comment]
the weird thing is that it was working fine before . I wonder how to fix it my kernel is updated

**Comment by flying-sheep** [comment]
anaconda issue. their libs interfere with the system libs and everything is a huge mess.

please ask there, as none of us have OS X and can help you here :disappointed:

**Comment by jolespin** [comment]
aw man, thanks for getting back to me.  i'll probably just use RStudio :( I was really stoked on using R in Jupyter

**Comment by flying-sheep** [comment]
aww, stupid anaconda. i’d really like to help you.

as said, it’s just the libs shipped with it conflicting with system libs. you could use the IRkernel without anaconda, or by having them fix it, so let’s hope they can help you

**Comment by jolespin** [comment]
How can you use IRKernel w/o anaconda?

**Comment by flying-sheep** [comment]
just use a normal R installation and install the kernel with the [official instructions](https://irkernel.github.io/installation/)

**Comment by Shicheng-Guo** [comment]
Solved: for centOS

`cp /lib64/libreadline.so.6 ~/anaconda3/lib/libreadline.so.6
`

**Comment by dthboyd** [comment]
I have a similar problem - the kernel dies after I try to run anything. The terminal returns this
File "//anaconda/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
    ImportError: No module named 'jupyter_spark'
[I 05:39:40.366 NotebookApp] Serving notebooks from local directory: /Users/davidboyd
[I 05:39:40.367 NotebookApp] 0 active kernels 
[I 05:39:40.367 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 05:39:40.367 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 05:39:45.545 NotebookApp] 404 GET /clusters?_=1492767583537 (::1) 50.56ms referer=http://localhost:8888/tree
[I 05:39:58.059 NotebookApp] Creating new notebook in 
[E 05:40:01.465 NotebookApp] Failed to run command:
    ['/Users/davidboyd/anaconda/lib/R/bin/R', '--slave', '-e', 'IRkernel::main()', '--args', '/Users/davidboyd/Library/Jupyter/runtime/kernel-82ff82ea-32c2-495b-981e-9ab243a71e7a.json']
        PATH='//anaconda/bin:/Users/davidboyd/anaconda/bin:/Users/davidboyd/anaconda/bin:/anaconda/anaconda/bin:/Users/davidboyd/anaconda/bin:/Users/davidboyd/anaconda/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/X11/bin://anaconda/bin'
        with kwargs:
    {'cwd': '/Users/davidboyd', 'stderr': None, 'start_new_session': True, 'stdin': -1, 'stdout': None}
    
[E 05:40:01.486 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "//anaconda/lib/python3.5/site-packages/notebook/base/handlers.py", line 457, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "//anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "//anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "//anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File "//anaconda/lib/python3.5/site-packages/notebook/services/sessions/handlers.py", line 62, in post
        kernel_id=kernel_id))
      File "//anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "//anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "//anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File "//anaconda/lib/python3.5/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
        kernel_name)
      File "//anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "//anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "//anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File "//anaconda/lib/python3.5/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "//anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "//anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "//anaconda/lib/python3.5/site-packages/tornado/gen.py", line 285, in wrapper
        yielded = next(result)
      File "//anaconda/lib/python3.5/site-packages/notebook/services/kernels/kernelmanager.py", line 87, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "//anaconda/lib/python3.5/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "//anaconda/lib/python3.5/site-packages/jupyter_client/manager.py", line 243, in start_kernel
        **kw)
      File "//anaconda/lib/python3.5/site-packages/jupyter_client/manager.py", line 189, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "//anaconda/lib/python3.5/site-packages/jupyter_client/launcher.py", line 123, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "//anaconda/lib/python3.5/subprocess.py", line 947, in __init__
        restore_signals, start_new_session)
      File "//anaconda/lib/python3.5/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/davidboyd/anaconda/lib/R/bin/R'
[E 05:40:03.023 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Accept-Language": "en-US,en;q=0.5",
      "Content-Length": "73",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:48.0) Gecko/20100101 Firefox/48.0",
      "Content-Type": "application/json",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Accept-Encoding": "gzip, deflate",
      "X-Requested-With": "XMLHttpRequest",
      "Referer": "http://localhost:8888/notebooks/Untitled79.ipynb?kernel_name=ir"
    }
[E 05:40:03.023 NotebookApp] 500 POST /api/sessions (::1) 2642.47ms referer=http://localhost:8888/notebooks/Untitled79.ipynb?kernel_name=ir
[W 05:40:03.240 NotebookApp] 404 GET /spark/api/v1/applications (::1) 3.94ms referer=http://localhost:8888/notebooks/Untitled79.ipynb?kernel_name=ir
[W 05:40:10.335 NotebookApp] 404 GET /spark/api/v1/applications (::1) 8.53ms referer=http://localhost:8888/notebooks/Untitled79.ipynb?kernel_name=ir
[W 05:40:20.334 NotebookApp] 404 GET /spark/api/v1/applications (::1) 2.75ms referer=http://localhost:8888/notebooks/Untitled79.ipynb?kernel_name=ir
[W 05:40:30.350 NotebookApp] 404 GET /spark/api/v1/applications (::1) 12.38ms referer=http://localhost:8888/notebooks/Untitled79.ipynb?kernel_name=ir
[W 05:40:40.346 NotebookApp] 404 GET /spark/api/v1/applications (::1) 5.73ms referer=http://localhost:8888/notebooks/Untitled79.ipynb?kernel_name=ir
[W 05:40:50.337 NotebookApp] 404 GET /spark/api/v1/applications (::1) 13.12ms referer=http://localhost:8888/notebooks/Untitled79.ipynb?kernel_name=ir
[W 05:41:00.327 NotebookApp] 404 GET /spark/api/v1/applications (::1) 2.56ms referer=http://localhost:8888/notebooks/Untitled79.ipynb?kernel_name=ir
[W 05:41:10.342 NotebookApp] 404 GET /spark/api/v1/applications (::1) 11.08ms referer=http://localhost:8888/notebooks/Untitled79.ipynb?kernel_name=ir
[W 05:41:20.350 NotebookApp] 404 GET /spark/api/v1/applications (::1) 7.59ms referer=http://localhost:8888/notebooks/Untitled79.ipynb?kernel_name=ir
[

**Comment by JoshB29** [comment]
I found this error is resulting from having the $R_HOME variable set. in by .bashrc, just deleting that variable remove this error.
