### ISSUE TITLE
conda irkernel fails to launch, conda now shipping with libzmq.so.5

### ISSUE THREAD

**Issue by parente** [IRkernel/IRkernel#205]
Not sure if this is a conda or irkernel issue (or where to file the conda issue). Conda now seems to be installing `/opt/conda/lib/libzmq.so.5` instead of `libzmq.so.4` upon an install like:

```
conda install  'r-base=3.2*' 'r-irkernel=0.4*' 
```

(Sidenote: There doesn't appear to be a 0.5 release in conda yet.)

This causes IRKernel to fail when launched via jupyter notebook:

```
[I 16:58:40.696 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel a52710b4-f7c3-43c7-b859-c4130b138608 restarted
> IRkernel::main()
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/opt/conda/lib/R/library/rzmq/libs/rzmq.so':
  libzmq.so.4: cannot open shared object file: No such file or directory
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```

If this should be opened somewhere else, please let me know.

**Comment by takluyver** [comment]
I would guess that whoever is handling the conda packages needs to rebuild the rzmq package with the new version of libzmq. @ilanschnell @groutr, who is responsible for that now?

**Comment by parente** [comment]
@asmeurer helped us with a conda irkernel build problem previous. Maybe he maintains rzmq too?

**Comment by JanSchulz** [comment]
@parente https://twitter.com/asmeurer/status/651164877554188288 :-(

**Comment by parente** [comment]
Ah, doh!

**Comment by chtlp** [comment]
Hey I just encountered this problem, is there a fix I can try quickly now? Thanks!

**Comment by parente** [comment]
@chtlp Here's the workaround I have in jupyter/docker-stacks at the moment:

https://github.com/jupyter/docker-stacks/blob/master/all-spark-notebook/Dockerfile#L92

**Comment by chtlp** [comment]
@parente Thanks! It worked beautifully. There are several versions of zeromq matching `anaconda/pkgs/zeromq-4.0.*` in my environment so I I just picked the highest version among them.

**Comment by cfljam** [comment]
I have been able to rebuild  a working conda install of jupyter + r-kernel by specifying the zeromq version

```
conda create -y -n my-py3r-env -c r r-essentials  python=3.4 zeromq=4.0*
```

**Comment by matt-negrin** [comment]
Hi @parente, 

Thank you for posting your workaround in the jupyter/docker-stacks. I'm having a bit of trouble implementing it, though. When I look in the following directory:

~/anaconda/pkgs/zeromq-4.0.*/lib/

All I see are these files:

libzmq.5.dylib	libzmq.a	libzmq.dylib	libzmq.la	pkgconfig

How can I get a version of libzmq.so.4.* ?

Thank you!

**Comment by cfljam** [comment]
I was able to fix my r-irkernel libzmq issues with

```
conda install zeromq=4.0.5
```

**Comment by quartox** [comment]
I was able to fix my libzmq issue by installing the R packages for the IRkernel from the R command line:

`install.packages(c('rzmq','repr','IRkernel','IRdisplay'),
                 repos = c('http://irkernel.github.io/', getOption('repos')),
                 type = 'source')`

`IRkernel::installspec()`

**Comment by matt-negrin** [comment]
@cfljam - Thanks for the quick reply. I uninstalled and reinstalled Anaconda (2.4.0), ran R essentials (conda install -c r r-essentials), and then ran your conda command (conda install zeromq=4.0.5).

Unfortunately, I'm still stuck. Below is the error I receive when I try to launch an R kernel.

Any ideas as to what I'm missing? 

Thank you for your help!

IRkernel::main()
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/Users/matthew.negrin/anaconda/lib/R/library/rzmq/libs/rzmq.so':
  dlopen(/Users/matthew.negrin/anaconda/lib/R/library/rzmq/libs/rzmq.so, 6): Library not loaded: @rpath/./libzmq.4.dylib
  Referenced from: /Users/matthew.negrin/anaconda/lib/R/library/rzmq/libs/rzmq.so
  Reason: image not found

**Comment by jmberros** [comment]
I confirm that the quickfix by @cfljam worked for me too, on an Ubuntu 15.10 fresh install. I ran this:

`conda create -y -n rkernel-fix -c r r-essentials  python=3.4 zeromq=4.0*`

It's important to include the `python=3.4` bit, since it will stille break with anaconda's default python3.5. Just downgrading to `zeromq=4.0.5` didn't do it for me without the python version change in the new env.

Thanks a lot @cfljam, this was driving me insane. I didn't think conda was actually delivering a broken R-notebook and I assumed it was on my side. As of December, this is still unattended.

**Comment by frickp** [comment]
I also had this issue running the R kernel on Jupyter. I'm using OS X and got basically the same error messages as @matt-negrin.

Like @matt-negrin, I couldn't get the @cfljam solution solution to work. I can confirm that the @parente solution on October 24 worked. What I did was create a symlink from where `/anaconda/lib/R/library/rzmq/libs/rzmq.so` is looking to an older, working version of `libzmq.4.dylib`. If you are new to this like me, what this is doing is creating a symlink in place of a non-existent file and pointing that link to a working copy of the file.

Here is the script that worked for me:

`ln -s  ~/anaconda/pkgs/zeromq-4.0.5-1/lib/libzmq.4.dylib ~/anaconda/lib/libzmq.4.dylib`

I wasted way too much time finding this fix. Hope it helps someone else.

**Comment by parente** [comment]
My docker-stacks hack no longer works as of today: whatever lib was installing zeromq 4.0.5 no longer does so. Doing a `conda install zeromq=4.0.5` gets necessary libraries installed again but then zeromq 4.1.x gets removed during the downgrade. This causes jupyter notebook to fail to launch looking for libzmq.so.5.

**Comment by takluyver** [comment]
I guess you'll need to set up a separate conda env to install IRkernel in for now.

@asmeurer has [previously said](https://github.com/IRkernel/IRkernel/issues/177#issuecomment-145632414) that @groutr and @ilanschnell are the people to bug for conda packaging issues now, but I'm starting to get the impression that the conda IRkernel package, and possibly all conda R packages, are not being maintained.

**Comment by parente** [comment]
Ahead of my finding yet another hack around the problem, the upstream issue was reported fixed a few days ago and I confirmed it fixed over in Docker stacks. (Sorry for not posting back here.)

This can be closed now.

**Comment by takluyver** [comment]
Thanks @parente. Could we get a link to the upstream issue that got fixed?

**Comment by parente** [comment]
Yep. Here's the upstream issue ContinuumIO/anaconda-issues#506
