### ISSUE TITLE
R Kernel is always dead - R 3.1.2 and Mac OS 10.7

### ISSUE THREAD

**Issue by SepehrAkhavan** [IRkernel/IRkernel#207]
Like another the question/issue reported earlier, I also have the same problem with a dead R Kernel (the other question was closed so I'm asking in a new thread). 
Terminal returns:

```
unable to load shared object '/Users/sepehrakhavan/anaconda/lib/R/library/rzmq/libs/rzmq.so':
dlopen(/Users/sepehrakhavan/anaconda/lib/R/library/rzmq/libs/rzmq.so, 6): Library not loaded: @rpath/./libzmq.4.dylib
Referenced from: /Users/sepehrakhavan/anaconda/lib/R/library/rzmq/libs/rzmq.so
Reason: image not found
```

I have ANOCONDA and R Essentials already downloaded. Would it be a problem with my R/Mac OS version? 
Really appreciate your help,
-Sepehr

**Comment by michaelmarkwang** [comment]
Same problem. I tried almost all the suggestions in other thread with the same probelm but there doesn't seem to have a solution yet.

**Comment by flying-sheep** [comment]
https://github.com/IRkernel/IRkernel/wiki/Dev-info
