### ISSUE TITLE
How to install older release?

### ISSUE THREAD

**Issue by apoku** [IRkernel/IRkernel#209]
The latest release does not seem to work (Jupyter does not detect the R kernel). I have another installation that was using the 0.4 release and I would like to try to install that older version. How can I do this from the command line?

**Comment by apoku** [comment]
http://stackoverflow.com/a/17082609 used elements of this technique:

Got the rzmq and repr dependencies via your installation instructions

    install.packages(c('rzmq','repr'), repos = c('http://irkernel.github.io/', getOption('repos')))

I followed the steps here to manually download the release tar.gz files for IRKernel (0.4) and IRdisplay (0.3) which I know last worked.

I installed them both from the windows command line

    R CMD INSTALL IRdisplay-0.3.tar.gz
    R CMD INSTALL IRkernel-0.4.tar.gz

Followed that up with your installation instructions

    IRkernel::installspec()

And the older release is working!

**Comment by takluyver** [comment]
I'm glad it's working for you, though I'd have liked to try to work out what was wrong with the installation of the latest version...
