### ISSUE TITLE
Exception in thread Thread-1 when testing IRkernel

### ISSUE THREAD

**Issue by rsmith31415** [IRkernel/IRkernel#210]
I have been testing kernels (using nose) for a while and after some recent update, I noticed that I'm receiving the following error: `Exception in thread Thread-1 (most likely raised during interpreter shutdown):`. This happens infrequently but after enough trials (maybe, 10 or 20), it will throw that exception. The interesting thing is that this only occurs in python 2.7.10. I don't think it happened under python 2.7.9 but maybe I never noticed.

The following is similar to the code I have been using so far. However, I have made a few attempts to fix this issue without much success (e.g. shutting down kernels individually with `kn.shutdown_kernel()`).

```
from jupyter_client.kernelspec import KernelSpecManager
from tornado.testing import AsyncHTTPTestCase
from ..app import Application

import json

class TestR(AsyncHTTPTestCase):

    def get_app(self):
        self.application = Application()
        return self.application

    def setUp(self):
        super(TestR, self).setUp()
        self.list_of_kernels = []
        id = self.application.km.create_kernel('ir')
        self.list_of_kernels.append(id)

    def tearDown(self):
        for i in self.list_of_kernels:
            kernel = self.application.km.manager.get_kernel(i)
            kernel.shutdown_kernel(now=True)

        super(TestR, self).setUp()

    def test_get_method_with_kernel(self):
        response = self.fetch('/kernel', method='GET')
        response = json.loads(response.body.decode('utf8'))
        self.assertEqual(len(response['kernel_ids']), 1)
```

and the full traceback is:

```
(env-py2)➜  nosetests test_r.py
.
----------------------------------------------------------------------
Ran 1 test in 1.191s

OK
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/home/user/anaconda/envs/env-py2/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/home/user/anaconda/envs/env-py2/lib/python2.7/site-packages/jupyter_client/channels.py", line 135, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'sleep'
```

`create_kernel` is just a method that basically uses the multikernel manager to get kernels ready and the GET request returns the kernel id of the recently created kernel.

I tried to use ipykernel but I think it is harder to get the same exception and after some modifications, I haven't been able to reproduce it again.

Is there something obviously wrong that is causing that error?

**UPDATE**:

This is the self-contained code:

```
from tornado.testing import AsyncHTTPTestCase
from jupyter_client import MultiKernelManager
import json
import tornado.web

class IRHandler(tornado.web.RequestHandler):
    def get(self):
        data = {}
        data['kernel_ids'] = self.application.kernels

        self.write(data)

class Application(tornado.web.Application):
    
    def __init__(self):

        self.kernels = []
        self.manager = MultiKernelManager()

        handlers = [
            (r'/index', IRHandler),
        ]

        settings = {
            'debug': True,
        }

        tornado.web.Application.__init__(self, handlers, **settings)

    def create_kernel(self, kernel_name):
        kernel_id = self.manager.start_kernel(kernel_name=kernel_name)
        kernel = self.manager.get_kernel(kernel_id)
        client = kernel.client()
        client.start_channels()
        client.wait_for_ready()

        self.kernels.append(kernel_id)

        return kernel_id

def main():
    app = Application()
    app.listen(8000)

if __name__ == '__main__':
    main()


class TestR(AsyncHTTPTestCase):

    def get_app(self):
        self.application = Application()

        return self.application

    def setUp(self):
        super(TestR, self).setUp()
        self.application.create_kernel('ir')

    def tearDown(self):
        for i in self.application.kernels:
            kernel = self.application.manager.get_kernel(i)
            kernel.shutdown_kernel(now=True)

        super(TestR, self).setUp()

    def test_get_method(self):
        response = self.fetch('/index', method='GET')
        response = json.loads(response.body.decode('utf8'))
        self.assertEqual(len(response['kernel_ids']), 1)
```

As I said, it takes a few iterations before getting the exception. Tested in Ubuntu 15.10, jupyter_client 4.1.1, nose 1.3.7, python 2.7.10, tornado 4.2.1.

Thanks

**Comment by takluyver** [comment]
I don't think this is an issue in IRkernel, though it's possible that something about IRkernel makes it more likely to occur. Error messages like that usually mean that a thread has not been explicitly stopped before the process terminates.

In your case, I think you need to call `kernel.stop_channels()` in your `tearDown` method. shutdown_kernel sends a message telling the kernel process (IRkernel) to shut itself down, stop_channels shuts down the Python machinery that communicates with it.

**Comment by rsmith31415** [comment]
Thank you. You're absolutely right, but I think `kernel.stop_channels()` should be `client.stop_channels()`. That definitely seems to fix it. 

Is there some reason why this doesn't occur in Python 3? Or maybe it happens but it is an extremely rare occurrence.

**Comment by takluyver** [comment]
There were some changes to garbage collection in Python 3.4 that might have affected it. In general, it's a good idea to stop threads explicitly before the process finishes, even if it doesn't appear to cause a problem, because it might do something odd 0.1% of the time.

Yes, you're right, `stop_channels()` is a client method. :-)

**Comment by rsmith31415** [comment]
Interesting. Yes, I wasn't very comfortable with this exception even if it seemed to work in Python 3.5. Thank you for your help.
