### ISSUE TITLE
zeromq not listed among the dependencies in the docs

### ISSUE THREAD

**Issue by giacecco** [IRkernel/IRkernel#216]
Hi All, perhaps it was just me who did not know, but the instructions at http://irkernel.github.io/installation/ don't say that zeromq is required before installing, and probably other dependencies, too (e.g. R itself). On Mac that is easily fixed with ```brew install zeromq``` for the ones who use Homebrew. Is it useful to add something about it?

**Comment by flying-sheep** [comment]
yes it is. in the requirements section of both this readme and the homepage.

however it’s hard to say what packages are needed for installing and which ones for installing from source. (source is possible for all platforms, binary for Windows and OS X)

* Windows:

	* binary windows IRkernel packages
	* no zmq (?)

* OS X:

	* binary OS X IRkernel packages (except if there are problems, then `rzmq` from source)
	* `brew install zmq` (when installing from source or also when installing from binary packages?)

		umm, you said `brew install zeromq`? are you sure it’s not `zmq`?

* Linux:

	* source IRkernel packages
	* devel zmq packages for all platforms where they are separated, else combined binary/devel packages: `libzmq3-dev` (ubuntu/debian) or `czmq-devel` (fedora) or `zeromq` (arch)

**Comment by giacecco** [comment]
Mmmh I can't find the "zero" string either in the readme https://github.com/IRkernel/IRkernel/blob/master/README.md nor in the Requirements section of the website at http://irkernel.github.io/requirements/ nor on the installation page http://irkernel.github.io/installation/ . I must be doing something wrong.

You're very right when you say that, in general, it is hard to list the full list of required packages, so probably it's not useful to list zeromq in particular, if we can't list all others, too.

I've just checked and ```zeromq``` and ```zmq``` are aliases in Homebrew.

**Comment by flying-sheep** [comment]
no, you’re right: zeromq is the only system dependency, so we have to do that.

i’m only thinking about how and where.

into http://irkernel.github.io/requirements or http://irkernel.github.io/installation (under the binary/source tab)

what do you think?

**Comment by giacecco** [comment]
I would drop the requirements page and integrate its contents in the installation page, so that if - like me - people bump into a problem at their first attempt they just go back and read the installation page carefully top to bottom.

I guess that people using something like Jupyter are likely skilled enough to investigate the installation terms for their own environment, rather than needing you giving instructions for each operating system, that may be difficult to keep up to date on the long term. From that point of view, listing Zeromq as a requirement is sufficient.

**Comment by flying-sheep** [comment]
> I guess that people using something like Jupyter are likely skilled enough to investigate the installation terms for their own environment

sadly that can’t be assumed, since some people install jupyter to complete university assignments. and those students might just start out with their studies…

**Comment by giacecco** [comment]
Point taken

**Comment by flying-sheep** [comment]
i moved this to the right repo: IRkernel/irkernel.github.io#21
