### ISSUE TITLE
Don’t execute lines after a failing one

### ISSUE THREAD

**Issue by flying-sheep** [IRkernel/IRkernel#218]
When executing a cell, we evaluate all lines, even if an earlier one breaks. this is potentially horrible:

```r
get.my.path <- function() {
    stop('unimplemented!')
}

dir <- '~'
dir <- file.path(dir, get.my.path())
unlink(dir, recursive=TRUE)
```

executed in a cell, this would delete your home dir (probably, i obviously didn’t test it)

**Comment by takluyver** [comment]
For a more trivial example for testing:

```
foo   # Error because foo is not found
print('hi')
```

Interestingly, if you surround the code with braces, it appears to do the correct thing:

```
{
foo
print('hi')
}
```

Maybe we just need to add braces around it before executing?

**Comment by flying-sheep** [comment]
heh, yeah, my example was more for showing how serious the problem is.

but let’s just use `evaluate(..., stop_on_error = 2)` instead of hacking in braces :laughing:

**Comment by takluyver** [comment]
OK, I think that makes sense. We currently explicitly pass `0L`, even though that's the default. I hope there wasn't some reason we were doing that...

**Comment by flying-sheep** [comment]
that’s why we have tests… oh wait we haven’t :stuck_out_tongue_winking_eye:

well, in any case, passing 1 or 2 is the right theing to do and whatever it’s soppused to work around, we should do differently

**Comment by takluyver** [comment]
It's absolutely the right thing to do, I just hope there's a good way to properly solve whatever it was working around.

Thanks for the reminder to get back to my tests PR ;-)
