### ISSUE TITLE
make `traceback()` work

### ISSUE THREAD

**Issue by flying-sheep** [IRkernel/IRkernel#219]
calling `traceback()` does nothing

**Comment by takluyver** [comment]
I guess that's because we catch the error to display it, and traceback() only deals with uncaught errors.

**Comment by flying-sheep** [comment]
jup, we need to stop doing that or display the traceback.

best would be to only catch the traceback if we’re displaying it

**Comment by takluyver** [comment]
I don't think we can stop catching errors, because an uncaught error would result in the kernel dying. So we need to catch them and somehow either store the traceback into `.Traceback` ourselves, or override `traceback()` to display results stored somewhere else.

**Comment by flying-sheep** [comment]
ah, makes sense.

then let’s use [`evaluate::try_capture_stack`](https://github.com/hadley/evaluate/blob/3b83a80e94628523cd5271e2250026097e52e7d3/R/traceback.r#L29) (or its way to do things), because else we don’t get tracebacks.

**Comment by takluyver** [comment]
That sounds like a good idea :-)

**Comment by flying-sheep** [comment]
superseeded by #222
