### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by methodds** [IRkernel/IRkernel#221]
I tried to install IR kernel on Linux Mint, latest anaconda version, R3.2, by following the source installation notes from:

http://irkernel.github.io/installation/

At the last part i receive an error:
```
Error in IRkernel::installspec() : 
  Jupyter or IPython 3.0 has to be installed but could neither run “jupyter” nor “ipython”, “ipython2” or “ipython3”.
             (Note that “ipython2” is just IPython for Python 2, but still may be IPython 3.0)
```

Starting the jupyter notebook by typing ``jupyter notebook`` in a terminal works flawlessly.

**Comment by takluyver** [comment]
Are you trying to run that in a GUI like R studio? You may need to start R from a terminal to do it, so that it picks up the correct `$PATH`.

**Comment by methodds** [comment]
As noted in the instruction I entered all commands within a terminal R session, but it did not work.

**Comment by takluyver** [comment]
What does `jupyter --version` give you?

**Comment by methodds** [comment]
``jupyter --version 4.0.6``

**Comment by takluyver** [comment]
OK, let's see what's going on in the R code. Can you try:

```
system2('jupyter', '--version', TRUE, FALSE)
```

and:

```
compareVersion('4.0.6', '3.0.0')
```

**Comment by methodds** [comment]
```
> system2('jupyter', '--version', TRUE,FALSE)
[1] "4.0.6"

> compareVersion('4.0.6', '3.0.0')
[1] 1

```
thanks for your help! :)

**Comment by takluyver** [comment]
I'm mystified, because that's exactly what the code is doing:
https://github.com/IRkernel/IRkernel/blob/13ed0d702fa227d88fdd9f9f2d2f16578b1edaa9/R/kernel.r#L320

I'm not sure what the difference is between you doing it manually and the installspec function doing it.

**Comment by methodds** [comment]
well the error message is python related, so maybe the problem has something to do with zmq (what ever this is) ?

**Comment by methodds** [comment]
Here is the complete traceback:

```
> IRkernel::installspec()
Traceback (most recent call last):
  File "/home/cs/anaconda3/bin/jupyter-kernelspec", line 2, in <module>
    from jupyter_client.kernelspecapp import KernelSpecApp
  File "/home/cs/anaconda3/lib/python3.5/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/home/cs/anaconda3/lib/python3.5/site-packages/jupyter_client/connect.py", line 21, in <module>
    import zmq
  File "/home/cs/anaconda3/lib/python3.5/site-packages/zmq/__init__.py", line 70, in <module>
    from zmq import devices
  File "/home/cs/anaconda3/lib/python3.5/site-packages/zmq/devices/__init__.py", line 7, in <module>
    from zmq.devices import basedevice, proxydevice, monitoredqueue, monitoredqueuedevice
  File "zmq/backend/cython/context.pxd", line 26, in init zmq.devices.monitoredqueue (zmq/devices/monitoredqueue.c:4455)
  File "/home/cs/anaconda3/lib/python3.5/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: /home/cs/anaconda3/lib/python3.5/site-packages/zmq/backend/cython/message.cpython-35m-x86_64-linux-gnu.so: undefined symbol: zmq_msg_gets
```

**Comment by takluyver** [comment]
Ah, I missed that update in your previous message. Yes, that looks like an error with pyzmq.

@minrk, did we work out if there was a problem with the way pyzmq is compiled in anaconda?

**Comment by methodds** [comment]
Its starting to get interesting: I removed pyzmq and installed the latest version, then IRKernel install worked. When trying to load an R kernel in the jupyter notebook, the kernel dies instantly and the error ``Segmentation fault`` appears in the terminal.

**Comment by takluyver** [comment]
Hmmm, that's not good. May be a problem with how rzmq is compiled :-S

**Comment by garretchristensen** [comment]
I get the same error as @methodds original error. Ubuntu 14.04, Anaconda 3, jupyter version 4.0.6, R 3.2.3 . I installed from source as per Linux instructions at http://irkernel.github.io/installation/
and get the error after running IRkernel::installspec():

    Jupyter or IPython 3.0 has to be installed but could neither run “jupyter” nor “ipython”,     “ipython2”      or     “ipython3”.
             (Note that “ipython2” is just IPython for Python 2, but still may be IPython 3.0)

**Comment by garretchristensen** [comment]
OK, nevermind, I guess. After

    conda update ipython 
    conda update pyzmq

everything appears to be working.
