### ISSUE TITLE
Subsequent plotting functions are displayed in new figures

### ISSUE THREAD

**Issue by mirjalil** [IRkernel/IRkernel#23]
So, normally in R, when you use plot() function, a new figure is constructed, and following lines() or points() or legend() functions will add something to that figure! However, in RKernel for ipython it is different as each new function will continue to a new figure. An example is provided here:

http://nbviewer.ipython.org/github/mirjalil/DataScience/blob/master/R.Programs/RKernel_plot_bug.ipynb

**Comment by piklprado** [comment]
Got the same with
```
with(.GlobalEnv, {
...
}
     )
```
But still is a nuisance for teaching demos.

**Comment by flying-sheep** [comment]
AFAIK even this suffices:

```r
{
	plot(1)
	legend('right', 'foo')
}
```

but i’m not sure, since i tried a few things in my local copy :)

**Comment by JanSchulz** [comment]
Not sure if this helps, but knitr also uses `evaluate` and so should have the same issues:

Here is how knotr saves plots:
https://github.com/yihui/knitr/blob/master/R/plot.R#L58

There is also a `merge_low_plot` function.

**Comment by takluyver** [comment]
merge_low_plot, and in particular [is_low_change](https://github.com/yihui/knitr/blob/master/R/plot.R#L184) look like what we want.

**Comment by flying-sheep** [comment]
great work!

**Comment by jmadzo** [comment]
awesome! that was only one annoying thing when i used IRkernel, I'm so happy it's gone.
