### ISSUE TITLE
flush out stream regulary

### ISSUE THREAD

**Issue by JanSchulz** [IRkernel/IRkernel#230]
If I run a print in a loop, the printed text will not display until the cell is finished or a `message(...)` is run.

```
for (i in 1:5){
    print("text")
    Sys.sleep(1)
    }
```
-> will print out all text in one got after the 5 secs

```
for (i in 1:5){
    print("text")
    message("")
    Sys.sleep(1)
    }
```
-> Will print out each text immediately.

These will also print immediately:

```
for (i in 1:5){
    print("text")
    }
Sys.sleep(3)
```
and 

```
print("text")
Sys.sleep(3)
```

I've no idea why the output is flushed in some cases and not in the "sleep in the loop" case, but as using message in the loop will print it, I suspect that there is a way to e.g. look for a `\n` in the stream and if it's there, send the stream? Or also export a helper functions which flushes the stream?

**Comment by flying-sheep** [comment]
dupe of #3, right?

**Comment by JanSchulz** [comment]
yes...
