### ISSUE TITLE
Stop execution of queued cells on error

### ISSUE THREAD

**Issue by JanSchulz** [IRkernel/IRkernel#232]
Currently the notebook with an R kernel keeps executing cells even if a cell got an error. In python the currently queued cells are not anymore executed.

eg the following notebook with three cells:

```r
print("whatever")
# --- next cell ---
stop("Stop execution here")
# --- next cell ---
print("Should not run")
```

and then execute the whole notebook via "Cell -> Run All. -> It should only execute the first two cells but not the third. Currently it executes all three.

IMO the current behaviour is very problematic as it can damage data: e.g. when doing a longrunnign computation in cell 2 and saving it to disk in cell 3. Now cell 3 is executed and overwrites the previous data with nothing / wrong things.

**Comment by JanSchulz** [comment]
So what should be happening here? This is currently relaly making me mad, as I use exceptions/stop in my "Kernel>restart & run all" workflow :-(

**Comment by takluyver** [comment]
Meh, it looks like the execution messages all get sent at once, and the kernel is responsible for cancelling them on an exception. That's a bit annoying, but there we go. The Python code that does that is here: https://github.com/ipython/ipykernel/blob/1d97cb2a04149387a0d2dbea1b3d0af691d8df6c/ipykernel/kernelbase.py#L623

We'll need to write an R equivalent.

**Comment by JanSchulz** [comment]
@takluyver This should definitely by one of your kernel test cases :-)

**Comment by JanSchulz** [comment]
PR in https://github.com/IRkernel/IRkernel/pull/264... I will use that tomorrow in some R analysis, lets see if it works...
