### ISSUE TITLE
reimplement with different zmq lib?

### ISSUE THREAD

**Issue by JanSchulz** [IRkernel/IRkernel#233]
According to https://github.com/armstrtw/rzmq/pull/16#issuecomment-165628017, there is now a new zmq lib available on R on Linux, mac and windows and it's on CRAN: [pbdZMQ](https://cran.r-project.org/web/packages/pbdZMQ/index.html). If we implement the zmq stuff on this lib, we can upload irkernel and the rest to cran and get the windows and mac binary packages auto-build and we don't need to maintain our own repo anymore.

**Comment by flying-sheep** [comment]
ok, this is fucking awesome and will save us lots of trouble

**Comment by flying-sheep** [comment]
bit of a problem: snoweye/pbdZMQ#23

**Comment by jmagosta** [comment]
I get an version error on Unbuntu 14.04 "trusty" when doing 
install.package('rzmq'),
 static_assert(ZMQ_VERSION_MAJOR >= 3,"The minimum required version of libzmq is 3.0.0.");
 despite having apt-getted libzmq3.  
Current R version on Ubuntu is 3.0.2 - is that part of the problem?

**Comment by flying-sheep** [comment]
as it looks now, we’ll pull #238 anyway, so maybe you could try with that one?

```r
library(devtools)
install_github('snoweye/pbdZMQ')
install_github('IRkernel/IRkernel', ref = 'pbd-zmq')
```
