### ISSUE TITLE
How do I set a CRAN mirrror to install an R package in Jupyter?

### ISSUE THREAD

**Issue by rthompermd** [IRkernel/IRkernel#234]
I have tried to find an answer here and on the web but I can't find one.  Can someone steer me in the right direction.  I am trying to install the "readr" package into a Jupyter notebook running an R kernel, but get the following error message:   "Error in contrib.url(repos, "source"): trying to use CRAN without setting a mirror".  Any tips on how to set the CRAN mirror (hopefully permanently) would be appreciated.

**Comment by flying-sheep** [comment]
The default is `install.packages(repos = getOption('repos'))`, which evaluates to `c(CRAN = '@CRAN@')`

`@CRAN@` means “show a selector”, but IRkernel doesn’t identify as “interactive” yet, so interactive functions like popping up a repo selector doesn’t work.

therefore, you either have to call `install.packages(..., repos = c('https://...', ...))` every time, or `options(repos = c('https://...', ...))` once in your notebook (before the `install.packages`) call.

you can get something automatically by doing e.g.:

```r
country.code <- 'de'  # use yours
url.pattern <- 'https://'  # use http if you want
repo.data.frame <- subset(getCRANmirrors(), CountryCode == country.code & grepl(url.pattern, URL))
options(repos = repo.data.frame$URL)
```

**Comment by JanSchulz** [comment]
Should we put that into a FAQ on the website?

**Comment by flying-sheep** [comment]
yes, please do it or file an issue in the website’s repo so we don’t forget about it

**Comment by JanSchulz** [comment]
Oh, and another question: should we add a way to run commands on kernel startup like it is possible with the python kernel? Or is rprofile the way to go?

**Comment by flying-sheep** [comment]
yeah, i think rprofile seems like a good place. only problem is there’s no good way to detect if we’re running in a kernel AFAIK.

**Comment by rthompermd** [comment]
Thank you for your prompt response and help.
