### ISSUE TITLE
R kernel keeps dying due to segfault

### ISSUE THREAD

**Issue by stared** [IRkernel/IRkernel#237]
I installed IRkernel according to the instructions for OS X and without getting errors. However, when I try to run R kernel in Jupyter Notebook, the kernel dies and I get the following error message in the terminal:

```
[I 21:05:13.536 NotebookApp] KernelRestarter: restarting kernel (3/5)

 *** caught segfault ***
address 0x6048, cause 'memory not mapped'

Traceback:
 1: .Call("initContext", PACKAGE = "rzmq")
 2: init.context()
 3: .Object$initialize(...)
 4: initialize(value, ...)
 5: initialize(value, ...)
 6: methods::new(def, ...)
 7: Kernel$new(connection_file = connection_file)
 8: IRkernel::main()
aborting ...
```

What is the problem & how can I fix it?

In any case, my versions:

* OS X 10.11.2 (El Capitan)
* R 3.2.3
* IPython 4.0.1

See also: https://github.com/conda/conda-recipes/issues/312 (though, in my case it is a homebrew-installed python, not Anaconda)

**Comment by takluyver** [comment]
Looks like a failure in rzmq. I haven't seen that one before, though, and I don't know what to do about it. I feel like these issues crop up more on Macs than elsewhere.

**Comment by stared** [comment]
OK, I made it working (perhaps with some minor errors, though: `"Got unhandled msg_type:" "comm_open"`, but still it works).

Steps:

```brew update zmq```

Not sure if it was necessary, but it changed the error message when starting R kernel.

Then, guided by https://github.com/IRkernel/IRkernel/issues/50, I uninstalled `rzmq` and then installed it again from https://github.com/armstrtw/rzmq, that is before installing other packages from IRkernel I did:

```
library('devtools')
install_github('armstrtw/rzmq')
```

In any case, I see that many people are reporting problems with `rzmq`.

**Comment by takluyver** [comment]
Glad it's working now.

**Comment by stared** [comment]
@takluyver As the standard installation instruction does not work for some systems (e.g. mine) isn't it worth to update IRkernel (e.g. setting different version of rzmq) or at least adding a relevant troubleshooting remark?

**Comment by takluyver** [comment]
I'm not really sure what it would say. "Try updating stuff, or uninstalling and reinstalling things, until it starts working"? "rzmq is frequently problematic"? There's so many different problems people have run into, and this isn't one I recall seeing before, so I don't think it's worth noting specifically unless there are other people seeing the same thing.

**Comment by stared** [comment]
@takluyver What I see in other projects is a section *troubleshooting* listing known problems with their solutions. If everything works fine, there is no need to go there. If does not - it's worth to list ones that were solved at least once.

Saying "rzmq is frequently problematic" does not solve a thing. (OK, it may focus one's efforts on particular library - but often one already gets error messages related to it; I would have saved time if I had encountered such troubleshooting list.)

(As a side note, I find this IRkernel difficult to install; with my previous system (OS X 10.8 Mountain Lion) I spend a day trying to install it, with no success (problems with rzmq, but different ones). However, with Anaconda it works without effort; just for some other reasons I wanted to keep my Homebrew installation.)

**Comment by flying-sheep** [comment]
once we pull #238, the rzmq stuff is hopefully a problem of the past.

**Comment by sawsimeon** [comment]
Hi, I also get the same error when I try to load the rJava R package.  I install rJava using Studio to R library in anaconda. I can load rJava in Rstudio successfully. But when I load in jupiter notebook. The Error occur.


```
 *** caught segfault ***
address 0x18, cause 'memory not mapped'

Traceback:
 1: .Call(RgetNullReference)
 2: assign(".jzeroRef", .Call(RgetNullReference), .env)
 3: .jfirst(libname, pkgname)
 4: fun(libname, pkgname)
 5: doTryCatch(return(expr), name, parentenv, handler)
 6: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 7: tryCatchList(expr, classes, parentenv, handlers)
 8: tryCatch(fun(libname, pkgname), error = identity)
 9: runHook(".onLoad", env, package.lib, package)
10: loadNamespace(package, c(which.lib.loc, lib.loc))
11: doTryCatch(return(expr), name, parentenv, handler)
12: tryCatchOne(expr, names, parentenv, handlers[[1L]])
13: tryCatchList(expr, classes, parentenv, handlers)
14: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        msg <- conditionMessage(e)        sm <- strsplit(msg, "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && identical(getOption("show.error.messages"),         TRUE)) {        cat(msg, file = stderr())        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
15: try({    ns <- loadNamespace(package, c(which.lib.loc, lib.loc))    env <- attachNamespace(ns, pos = pos, deps)})
16: library(rJava)
17: eval(expr, envir, enclos)
18: eval(expr, envir, enclos)
19: withVisible(eval(expr, envir, enclos))
20: withCallingHandlers(withVisible(eval(expr, envir, enclos)), warning = wHandler,     error = eHandler, message = mHandler)
21: doTryCatch(return(expr), name, parentenv, handler)
22: tryCatchOne(expr, names, parentenv, handlers[[1L]])
23: tryCatchList(expr, classes, parentenv, handlers)
24: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        msg <- conditionMessage(e)        sm <- strsplit(msg, "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && identical(getOption("show.error.messages"),         TRUE)) {        cat(msg, file = stderr())        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
25: try(f, silent = TRUE)
26: handle(ev <- withCallingHandlers(withVisible(eval(expr, envir,     enclos)), warning = wHandler, error = eHandler, message = mHandler))
27: evaluate_call(expr, parsed$src[[i]], envir = envir, enclos = enclos,     debug = debug, last = i == length(out), use_try = stop_on_error !=         2L, keep_warning = keep_warning, keep_message = keep_message,     output_handler = output_handler)
28: evaluate(request$content$code, envir = .GlobalEnv, output_handler = oh,     stop_on_error = 0L)
29: doTryCatch(return(expr), name, parentenv, handler)
30: tryCatchOne(expr, names, parentenv, handlers[[1L]])
31: tryCatchList(expr, names[-nh], parentenv, handlers[-nh])
32: doTryCatch(return(expr), name, parentenv, handler)
33: tryCatchOne(tryCatchList(expr, names[-nh], parentenv, handlers[-nh]),     names[nh], parentenv, handlers[[nh]])
34: tryCatchList(expr, classes, parentenv, handlers)
35: tryCatch(evaluate(request$content$code, envir = .GlobalEnv, output_handler = oh,     stop_on_error = 0L), interrupt = function(cond) interrupted <<- TRUE,     error = handle_error)
36: executor$execute(msg)
37: handle_shell()
38: kernel$run()
39: IRkernel::main()
aborting ...

```
