### ISSUE TITLE
Relativity

### ISSUE THREAD

**Issue by stonebig** [IRkernel/IRkernel#239]
hi,

Is there another option than to have absolute path in kernel.json ?

````
["D:/WinPython/basedir34/buildQt5/winpython-3.4.4.amd64/tools/R/bin/x64/R", "--slave", "-e", "IRkernel::main()", "--args", "{connection_file}"], "
````
a path relative to "~", or other default like %JUPYTER_DATA_DIR%, known by the irkernel would be nice.

**Comment by flying-sheep** [comment]
we had one using `%PATH%`, but people said it had only upsides to change it to absolute paths.

why do you need that?

**Comment by stonebig** [comment]
Ok: I don't mind if your default case is an absolute fixed string, I just need a solution for this special case.

When, on my windows PC, I move my Winpython from one place to another, this kernel.json is the only thing that doesn't follow:
````
{
  "argv": ["D:/WinPython/basedir34/buildQt5/winpython-3.4.4.amd64/tools/R/bin/x64/R", "--slave", "-e", "IRkernel::main()", "--args", "{connection_file}"],
  "display_name": "R",
  "language": "R"
}
````
has to manually be transformed in 
````
{
  "argv": ["D:/result_tests/winpython-3.4.4.0r.amd64/tools/R/bin/x64/R", "--slave", "-e", "IRkernel::main()", "--args", "{connection_file}"],
  "display_name": "R",
  "language": "R"
}

````

If a system variable could be used to define that path, I would not have to manually update that part, and R kernel would magically work after the move.

Please note that %R magic support the move already. 

 
(beware of windows "\" that has to be transformed in "\\")

example:
````
{
  "argv": ["%winpydir%/../tools/R/bin/x64/R", "--slave", "-e", "IRkernel::main()", "--args", "{connection_file}"],
  "display_name": "R",
  "language": "R"
}

````
having
````
echo %winpydir%
D:\result_tests\winpython-3.4.4.0r.amd64\python-3.4.4.amd64
````

earlier complaint (https://github.com/ipython/ipython/issues/7739#issuecomment-74164364)

**Comment by takluyver** [comment]
You can put `{prefix}` in the path, it will be expanded to Python's `sys.prefix`, which should be inside your winpython directory.

**Comment by stonebig** [comment]
It works ! thanks a lot @takluyver !

````
{
  "argv": ["{prefix}/../tools/R/bin/x64/R", "--slave", "-e", "IRkernel::main()", "--args", "{connection_file}"],
  "display_name": "R",
  "language": "R"
}
````
