### ISSUE TITLE
Set some option so code can detect when it's running in IRkernel

### ISSUE THREAD

**Issue by takluyver** [IRkernel/IRkernel#24]
From a discussion with @ramnathv.

Note that being in IRkernel does not necessarily imply that the code is running in the notebook - there are multiple frontends speaking the same protocol, and they may even be connected to the kernel at the same time. But we can reliably indicate that we're in the kernel.

**Comment by flying-sheep** [comment]
@JanSchulz said:

> My proposal:
> 
> in the kernel.r$run add an option:
> 
> ```r
> option(irkernel.in_kernel = TRUE)
> ```
> 
> Packages can then check for this and adjust behaviour (e.g. produce different markdown output)
> 
> ```r
> getOption("irkernel.in_kernel", FALSE)
> ```
> 
> Any objections? Different names?

and we should set it to `FALSE` in the options file so users can discover it.

**Comment by flying-sheep** [comment]
1. `jupyter.in_kernel` to match `jupyter.plot_mimetypes`
2. [set it to `FALSE` here](https://github.com/IRkernel/IRkernel/blob/ba45b39767be483a3da2bea0eb77e8fac2243aa1/R/options.r#L19)

**Comment by flying-sheep** [comment]
1. `jupyter.in_kernel` to match `jupyter.plot_mimetypes`
2. [set it to `FALSE` here](https://github.com/IRkernel/IRkernel/blob/ba45b39767be483a3da2bea0eb77e8fac2243aa1/R/options.r#L19)

**Comment by JanSchulz** [comment]
IMO this isn't worth to set to false: who will import the r kernel in a regular session? And users of this will anyway have to handle the case that it isn't set because in the majority of the cases (=RStdio users...) it won't.

**Comment by flying-sheep** [comment]
it’ll be more visible that way.
