### ISSUE TITLE
installation failing on ubuntu trusty with libzmq version error despite libzm3-dev being installed 

### ISSUE THREAD

**Issue by hjwp** [IRkernel/IRkernel#241]
I'm seeing this error when trying to follow the installation instructions:

```
 static_assert(ZMQ_VERSION_MAJOR >= 3,"The minimum required version of libzmq is 3.0.0.");
```

This is despite having updated the R packages first, and having installed libzmq3-dev.

Is there any need to specify the LIBRARY_PATH or something?  I'm trying to do the build as a non-root user...

**Comment by takluyver** [comment]
Double check that `libzmq1` and `libzmq-dev` are not installed, as they have an older version. But I think that `libzmq3-dev` should conflict with `libzmq-dev`, so it shouldn't be possible to have both installed at once. I don't know what else could be causing that.

**Comment by hjwp** [comment]
Thanks Thomas, have double-checked, neither of those are installed.  And, you're right, they do conflict, trying to install libzmq1 tells me it would need to remove libzmq3-dev.

Any other ideas?  Is there another way to manually check the libzmq version?  Or another way to build the binaries needed?

**Comment by hjwp** [comment]
Happy New Year btw! :)

**Comment by takluyver** [comment]
Happy New Year!

Could there be another copy of libzmq sitting around somewhere, not installed by apt? I don't know what search path it uses.

If you use (or could use) Anaconda, you can install rzmq (which is what's having the problem) with a binary package from [this channel](https://conda.anaconda.org/r):

```
conda install -c r r-rzmq
```

**Comment by hjwp** [comment]
There is a libzmq.so in */usr/local/lib/python2.7/dist-packages/zmq/libzmq.so* -- not sure if it might be finding that one somehow...

**Comment by takluyver** [comment]
Hmmm, it's possible, but I don't think it would find that when compiling an R package.

We're working on transititioning to another zmq package called pbdzmq (see #238). I hope that will ease some of these installation difficulties, but I don't know if it will affect this.

**Comment by flying-sheep** [comment]
try with the pbdZMQ-based master please
