### ISSUE TITLE
Pretty print data.table object like pandas data frame?

### ISSUE THREAD

**Issue by jeffwong-nflx** [IRkernel/IRkernel#248]
Is there a way to pretty print a data.table like the Pandas data frame? I usually just get a blob of text as if it were a regular print from R

**Comment by takluyver** [comment]
If you just do `df` at the end of a cell, you should get it as an HTML table.

**Comment by janschulz** [comment]
Closing as this is the same behaviour as in python:

```
print(df) # -> Text output
df # -> html output
```

**Comment by takluyver** [comment]
And to do rich display without putting it at the end of a cell:

```r
IRdisplay::display(df)
```

Python equivalent:

```python
IPython.display.display(df)
```

**Comment by flying-sheep** [comment]
you mean “at the top level of a cell”.

as it is now:

```r
df  # displays

for (df in dfs) {
	df  # doesn’t display
}
```

**Comment by janschulz** [comment]
The "last in a cell" (py) vs "the output of any expression in the cell" (R) is probably worth another FAQ item...

E.g. 
```R
{
df
NULL
}
```

Will also not output a thing...

**Comment by janschulz** [comment]
Issue: https://github.com/IRkernel/irkernel.github.io/issues/27

**Comment by MichaelChirico** [comment]
See also: https://github.com/Rdatatable/data.table/issues/1523

There's not currently any plan to support HTML printing (`xtable` is probably better suited for that), but perhaps if enough support is expressed...
