### ISSUE TITLE
`devtools` installation error?

### ISSUE THREAD

**Issue by jeff1207** [IRkernel/IRkernel#249]
Question about the correct way to install R packages with the IRkernel/Jupyter. (I am also trying to correctly use `conda` as well). The error is when I try to install `devtools`; but I'm showing how I got there from the beginning: 

First, I just created a new conda environment and installed the IRkernel via: `conda create -y -n anaconda_r -c r r-irkernel r-recommended r-essentials anaconda rpy2 jupyter notebook`

Then, I activated the environment, started an R notebook, and I installed some packages that weren't installed initially as `install.packages("astsa", repos='http://cran.us.r-project.org')`. Worked!

Finally, I tried the same, with `devtools`; `install.packages("devtools", repos='http://cran.us.r-project.org')` and it fails with the following errors: 

```
also installing the dependencies ‘curl’, ‘httr’, ‘memoise’, ‘whisker’, ‘rstudioapi’, ‘git2r’, ‘withr’

Warning message:
In install.packages("devtools", repos = "http://cran.us.r-project.org"): installation of package ‘curl’ had non-zero exit statusWarning message:
In install.packages("devtools", repos = "http://cran.us.r-project.org"): installation of package ‘git2r’ had non-zero exit statusWarning message:
In install.packages("devtools", repos = "http://cran.us.r-project.org"): installation of package ‘httr’ had non-zero exit statusWarning message:
In install.packages("devtools", repos = "http://cran.us.r-project.org"): installation of package ‘devtools’ had non-zero exit status
```

I did the same thing in RStudio (and it worked), so what's the right way to install this kind of thing?

**Comment by JanSchulz** [comment]
wild guess; rstudio sets some environment variables which are needed to compile native packages?

**Comment by JanSchulz** [comment]
which OS are you on?

**Comment by flying-sheep** [comment]
i’ll close this as it’s not our bug, but we’ll keep helping you in here.

**Comment by jbwhit** [comment]
I helped Jeff w/ this earlier this week. @JanSchulz, the OS is Mac OS X (10.11 I think).

@flying-sheep whose bug/where is a more appropriate place to ask this question?

**Comment by flying-sheep** [comment]
hard to say since the actual error that happened during `install.packages` wasn’t mentioned.

but probably anaconda or R.

**Comment by JanSchulz** [comment]
Ok, can you try the same in a regular R console (aka in a terminal activate the new environment and run `r`)? That's what we use as well, so if that also doesn't work, then rstudio must do something to make it work.

Can you also try to install curl directly instead of devtools? curl does some native compiling AFAIK and I suspect that this is the problem... Please use `install.packages(..., verbose=TRUE, keep_outputs=TRUE)`.

**Comment by kamaulindhardt** [comment]
Has this issue been resolved? I get the same error when I try to install "devtools" on my Jupiter Lab workspace. This is the message I get:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/83076278/125324976-b93b1080-e340-11eb-9c96-da886f07d01e.png">

**Comment by flying-sheep** [comment]
There was never an issue. Something in your environment is broken in a way that makes installing it impossible.

IRkernel isn’t involved here, except in that it (involuntarily) hides the error message due to #416
