### ISSUE TITLE
Handle comm_open messages

### ISSUE THREAD

**Issue by janschulz** [IRkernel/IRkernel#253]
Every startup of an R kernel in my notebook results in this:

```
> IRkernel::main()
[1] "Got unhandled msg_type:" "comm_open"
```

**Comment by takluyver** [comment]
I guess something in the widget machinery is sending that. I don't think it's worth handling the messages unless we support widgets, and I'm not particularly eager to get into that. Maybe we should just not bother printing that on `comm_*` messages, as that's something we know we don't handle.

**Comment by flying-sheep** [comment]
we could “handle” them by giving more information about message content and messaging in a way that indicates that it’s no problem (so that people don’t think it’s a relevant message for their bug)

**Comment by lbustelo** [comment]
@flying-sheep @takluyver  Any advice in how we could start implementing Comm on top of this kernel? I want to enable https://github.com/jupyter-incubator/declarativewidgets on top of IRkernel. The project already supports Python and Scala. Would be great to have R support as well.

**Comment by rgbkrk** [comment]
Whoa that would be sweet @lbustelo!

**Comment by flying-sheep** [comment]
aww sweet! didn’t know about that project yet and always felt the current widgets were too python specific.

well, shell channel messages are handled [here](https://github.com/IRkernel/IRkernel/blob/dcc778744bb29c6ee0d20cbbc3361aaa5b51ba11/R/kernel.r#L116): you add a entry to the switch and a matching function. you’ll have to add entries for `comm_open`, `comm_msg` and `comm_close` afaik.

then there is also the control channel (separate channel for priority stuff) handled [here](https://github.com/IRkernel/IRkernel/blob/dcc778744bb29c6ee0d20cbbc3361aaa5b51ba11/R/kernel.r#L229). i have no idea if comm messages can be important enough to be sent on this channel, and the docs only mention `shutdown_request` being sent here, so you’ll have to ask someone about this.

**Comment by takluyver** [comment]
I'm pretty sure comm messages should never go over the control channel.

**Comment by lbustelo** [comment]
@flying-sheep Thanks for the feedback. We'll report back our findings.

**Comment by lbustelo** [comment]
Ha! we will also need to implement some simple magic support... there is no way to do %%HTML in this kernel. Unrelated to this issue... but stuff we are finding out.

**Comment by takluyver** [comment]
`IRdisplay::display_html("<h1>boo</h1>")` should work. Magics are just a convenient syntax, everything they do is possible with regular functions.

**Comment by lbustelo** [comment]
@takluyver You are right... but are you against to adding `%%HTML`. That way we don't have to wrap complex HTML in a string. I'll open a separate issue for this discussion.

**Comment by lbustelo** [comment]
Opened #260

**Comment by lbustelo** [comment]
Just sharing some status here. We have our first stab at Comm on this kernel done. We are waiting for IBM legal to give use the go-ahead to contribute to this repo. I'm hoping that gets resolved this week given that it did not take that much code.
