### ISSUE TITLE
Ghost NAs generated by ellipses in R dataframe display?

### ISSUE THREAD

**Issue by zazizoma** [IRkernel/IRkernel#254]
R dataframe displays ellipses, and claims they are invalid factor levels to be replaced with NAs, which appear to be ghosts . . .

[Dataframe issue.pdf](https://github.com/IRkernel/IRkernel/files/110452/Dataframe.issue.pdf)

![screen shot 2016-01-29 at 2 32 41 pm](https://cloud.githubusercontent.com/assets/10425738/12688801/d427cf82-c695-11e5-8baf-92df485266d4.png)

IRkernel v0.5
IRdisplay v0.3
repr v0.4

**Comment by flying-sheep** [comment]
fixed in repr master. we should do a new release.

**Comment by janschulz** [comment]
Closing, as fixed in repr
