### ISSUE TITLE
installation problem in OS X 10.11.3 - Capitan

### ISSUE THREAD

**Issue by thianj23** [IRkernel/IRkernel#256]
Hi, I'm tryin to install de IRkernel from the R console in mi mac, but when I run the lines:

```r
install.packages(c('rzmq','repr','IRkernel','IRdisplay'),
                 repos = c('http://irkernel.github.io/', getOption('repos')))
```

 I get the following error:

```
--- Please select a CRAN mirror for use in this session ---
--- Please select a CRAN mirror for use in this session ---

  There are binary versions available but the source versions are
  later:
         binary source needs_compilation
repr        0.2    0.4             FALSE
IRkernel    0.4    0.5             FALSE

--- Please select a CRAN mirror for use in this session ---
trying URL 'http://irkernel.github.io/bin/macosx/mavericks/contrib/3.2/rzmq_0.7.7.tgz'
Content type 'application/octet-stream' length 81898 bytes (79 KB)
downloaded 79 KB

trying URL 'http://irkernel.github.io/bin/macosx/mavericks/contrib/3.2/IRdisplay_0.3.tgz'
Content type 'application/octet-stream' length 21391 bytes (20 KB)
downloaded 20 KB


The downloaded binary packages are in
	/var/folders/lp/y3_df87d7612qydx97_mnp7r0000gn/T//RtmpyaYfFr/downloaded_packages
installing the source packages ‘repr’, ‘IRkernel’

trying URL 'http://irkernel.github.io/src/contrib/repr_0.4.tar.gz'
Content type 'application/octet-stream' length 11355 bytes (11 KB)
downloaded 11 KB

trying URL 'http://irkernel.github.io/src/contrib/IRkernel_0.5.tar.gz'
Content type 'application/octet-stream' length 17951 bytes (17 KB)
downloaded 17 KB

* installing *source* package ‘repr’ ...
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (repr)
* installing *source* package ‘IRkernel’ ...
** R
** inst
** preparing package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/rzmq/libs/rzmq.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.2/Resources/library/rzmq/libs/rzmq.so, 6): Library not loaded: /usr/local/lib/libzmq.4.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.2/Resources/library/rzmq/libs/rzmq.so
  Reason: image not found
ERROR: lazy loading failed for package ‘IRkernel’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/IRkernel’

The downloaded source packages are in
	‘/private/var/folders/lp/y3_df87d7612qydx97_mnp7r0000gn/T/RtmpyaYfFr/downloaded_packages’
Warning message:
In install.packages(c("rzmq", "repr", "IRkernel", "IRdisplay"),  :
  installation of package ‘IRkernel’ had non-zero exit status
```

Can anyone help me out with this?

**Comment by takluyver** [comment]
Try [this comment](https://github.com/IRkernel/IRkernel/issues/165#issuecomment-169964231).

We've replaced the zmq library, so hopefully this will get easier with the new release.

**Comment by flying-sheep** [comment]
@takluyver we should do a release these days.

**Comment by takluyver** [comment]
We should, and we were talking about releasing repr as well, right?

Is there anything else we want to do before making a release?

Ping @JanSchulz for packaging wizardry ;-)

**Comment by flying-sheep** [comment]
well, i fear this interrupt bullshit ain’t gonna fix itself anytime soon and is as far as i’m concerned a relatively minor issue (i’ve never accidentally hit the stop button while nothing was running)

**Comment by JanSchulz** [comment]
Just make a new issue about a release and I will do the packages...

We really should get an extra repo to do the builds...

**Comment by takluyver** [comment]
@JanSchulz not quite sure what you mean, but do you want me to create a new repo and make you a collaborator on it so you can set something up? If so, what do you want it to be called?

**Comment by JanSchulz** [comment]
@takluyver Not yet... I'm currently tryiing to get the conda packaging builds working (aka conda-smithy -> https://github.com/conda-forge/conda-smithy/pull/51) and I think such a setup should also work for R packages, but that means

* Find a way to install R tools on appveyor (should work...)
* decide whether to use condas R (no latest R version on windows :-/) or R directly
* setup the build environment on three CI services (source+linux, windows, Macosx)
* build the package(s) by committing something like a conda packages recipe (see https://github.com/JanSchulz/conda-build-wheel for somethign similar for building wheels from conda recipies)
* Upload the package to a branch in a separate repo (irkernel.github.io) and submit that as PR
* install a travis task there, which regenerates the repository meta files and get that commited in the repo (and this should not trigger a travis run...)

None of this is actual implemented, but it looks doable, but I don't have the time right now so building by hand looks easier...

**Comment by flying-sheep** [comment]
there is an OSX CI?

**Comment by takluyver** [comment]
IIRC, Travis can be cajoled into doing OSX builds if you pretend you're an objective C project. I guess that would require a separate repo.

**Comment by takluyver** [comment]
But actually, @JanSchulz, now that we no longer require rzmq, and pbdZMQ takes care of their own binary builds, can't we just publish source packages? There's no need to compile any of our packages, so we shouldn't need to set up all that machinery to build on different platforms.

It might still be nice to have at least Windows tests, since that's such a different environment from Posix, but it doesn't need to be done for release.

**Comment by flying-sheep** [comment]
true. or we could just go CRAN

**Comment by thianj23** [comment]
Thanks @takluyver  It works

**Comment by flying-sheep** [comment]
great! :smile:
