### ISSUE TITLE
Release 0.7

### ISSUE THREAD

**Issue by flying-sheep** [IRkernel/IRkernel#257]
I’ll write the release info ☺

**Comment by takluyver** [comment]
Terrific, thanks!

**Comment by flying-sheep** [comment]
[done](https://github.com/IRkernel/IRkernel/releases/tag/0.6)

**Comment by JanSchulz** [comment]
Continuing from https://github.com/IRkernel/IRkernel/issues/256: Should we simple upload to CRAN?

I would very much prefer that...

That would also need uploads of repr and the display package...

**Comment by takluyver** [comment]
From what I've heard, uploading to CRAN is not very simple - that's why I was happy to have a self hosted repository set up that we could use. But if you want to try submitting it to CRAN, I'd be happy to see it up there.

repr would be the package to start with. @flying-sheep, is there anything else to do before tagging a new version of repr? HTML escaping (IRkernel/repr#21)?

**Comment by JanSchulz** [comment]
Checklist: https://cran.r-project.org/submit.html

I think the main problem could be this:

For source:
> Maintainers will be asked to update packages which show any warnings or significant notes, especially at around the time of a new x.y.0 release. Packages which are not updated are liable to be archived.
> - A package must not tamper with the code already loaded into R: any attempt to change code in the standard and recommended packages which ship with R is prohibited. Altering the namespace of another package should only be done with the agreement of the maintainer of that package.
> - Packages should not modify the global environment (user’s workspace).

And for the binaries:
> it passes R CMD check without error for all the available sub-architectures, [...]

**Comment by flying-sheep** [comment]
HTML and latex escaping would be nice, yeah.

and getting something submitted to CRAN isn’t that hard. i have a package there.

there *are* many nitpicky details we have to follow though. sentence structure in description and stuff like that

**Comment by JanSchulz** [comment]
@flying-sheep @takluyver So who should do the cran upload? I'm very much for it, because that would mean we don't have to maintain the repo on irkernel.github.org anymore. IMO it's better one of you does it because while I am able to build the windows binaries, I don't have much clue on the rest of the packaging side...

BTW: irkernel will be included in debian: https://lists.debian.org/debian-devel/2016/02/msg00276.html :-)

**Comment by takluyver** [comment]
OK, when we've got the next release of repr ready, I'll have a go at submitting it to CRAN (unless you'd rather, @flying-sheep ?)

I wish I could get excited about it being included in Debian, but to be honest I think it just means users get stuck on an outdated version for years. The IPython package is still at 2.4.1 even in Debian unstable, the channel that gets updates first. But then, [intent-to-package bugs](https://www.debian.org/devel/wnpp/being_packaged_byage) are not a reliable indicator of anything actually getting done.

**Comment by JanSchulz** [comment]
Ok, I think we should simple submit what we have to CRAN now. There is currently no 0.6 release on the irkernel repo and IMO it would be better to start now and get the resubmissions out of the way :-)

I just checkked repr and this looks IMO good:

```
* checking dependencies in R code ... NOTE
Unexported object imported by a ':::' call: 'utils:::.getHelpFile'
  See the note in ?`:::` about the use of this operator.
```

was the only message I got during `R CMD check %%G*.tar.gz`...

**Comment by flying-sheep** [comment]
OK, seems like we’ve got some stuff to fix first.

**Comment by chronitis** [comment]
For reference, I filed the ITPs for irkernel + dependencies. This was the logical continuation of the Ubuntu PPA I set up with a few Jupyter kernels. 

Packages for 0.6.1 are built and ready, but no one has reviewed and sponsored them so nothing has happened since then. I suspect in practice they are blocked until the jupyter packaging is finished. If CRAN uploads are likely to happen with 0.7.0 it would also make sense to wait for that, since that would imply the package names changing (`r-irkernel-irdisplay` -> `r-cran-irdisplay`).

As far as packages being up to date, that I suppose depends on my continued interest. I suspect more likely users would be on Ubuntu than pure Debian, in which case updates can be handled by PPA, but getting the packages and their dependencies in Debian at least means the PPA doesn't have to carry the slower-updating parts. I think there is some value in being able to do `apt install jupyter irkernel ihaskell ijulia...` and get a ready-to-go system, but your milage may of course vary.

**Comment by flying-sheep** [comment]
currently everything here’s a bit confusing as we had a slew of changes and bug reports and additions. we should priorize what needs to get into 0.7 and work on that, then release 0.7 in the internal repos and simultaneously go for CRAN.

everyone in?

**Comment by janschulz** [comment]
IMO we should start right now with repr and irdisplay to get them into cran... IMO with either a new release of repr or the old one. Just to give it more time to remove issues which might pop up during the submission process

**Comment by takluyver** [comment]
@chronitis personally, I wouldn't bother trying to get the Jupyter ecosystem into distro-supplied Debian packages. I think it's simply being developed far too fast for Debian's structures to keep up, and people who try to install from Debian get ancient versions that the developers have long since moved on from. Nor is Debian good at backporting security fixes - the version of IPython even in Debian unstable is vulnerable to a security issue announced last summer (and it's in Debian's tracker).

This is up to you, of course, but I would strongly recommend to stick with packaging systems we can control directly, like pip, conda (using Anaconda.org) or PPAs.

**Comment by flying-sheep** [comment]
well i guess things will quiet down at some point but that point isn’t too close.

**Comment by janschulz** [comment]
Running `R CMD check` in the r-devel version leads to this:

```
c:\data\external\R
λ build_rpackage.bat --Rdevel --check irkernel
# Building packages: irkernel
# Checking: yes
# Building for R-devel
c:\Program Files\R\R-devel
 - Building package irkernel
* checking for file 'irkernel/DESCRIPTION' ... OK
* preparing 'IRkernel':
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
Removed empty directory 'IRkernel/example-notebooks'
* building 'IRkernel_0.6.tar.gz'

# CHECKING the package
* using log directory 'c:/data/external/R/IRkernel.Rcheck'
* using R Under development (unstable) (2016-04-25 r70548)
* using platform: x86_64-w64-mingw32 (64-bit)
* using session charset: ISO8859-1
* checking for file 'IRkernel/DESCRIPTION' ... OK
* this is package 'IRkernel' version '0.6'
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... NOTE
Found the following hidden files and directories:
  .travis.yml
These were most likely included in error. See section 'Package
structure' in the 'Writing R Extensions' manual.
* checking for portable file names ... OK
* checking whether package 'IRkernel' can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... NOTE
Malformed Description field: should contain one or more complete sentences.
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... NOTE
Found the following possibly unsafe calls:
File 'IRkernel/R/execution.r':
  unlockBinding("base_display", displayenv)

find_jupyter: no visible global function definition for
  'compareVersion'
namedlist: no visible global function definition for 'setNames'
Undefined global functions or variables:
  compareVersion setNames
Consider adding
  importFrom("stats", "setNames")
  importFrom("utils", "compareVersion")
to your NAMESPACE file.
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... WARNING
Missing link or links in documentation object 'comm_manager.Rd':
  'CommManager'

See section 'Cross-references' in the 'Writing R Extensions' manual.

* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... WARNING
Functions or methods with usage in documentation object 'IRkernel' but not in code:
  getOption

* checking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'IRkernel'
  'jupyter.*'
Objects in \usage without \alias in documentation object 'IRkernel':
  'getOption'

Bad \usage lines found in documentation object 'IRkernel':
  options(jupyter.* = ...)
  jupyter_option_defaults$jupyter.*

Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter 'Writing R documentation files' in the 'Writing R
Extensions' manual.
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking examples ... NONE
* checking PDF version of manual ... OK
* DONE

Status: 3 WARNINGs, 3 NOTEs
See
  'c:/data/external/R/IRkernel.Rcheck/00check.log'
for details.


* installing to library 'C:/portabel/R/R/win-library/3.4'
* installing *source* package 'IRkernel' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* MD5 sums
packaged installation of 'IRkernel' as IRkernel_0.6.zip
* DONE (IRkernel)
```

**Comment by flying-sheep** [comment]
well, we don’t have to fix notes, but since we have `getOption('jupyter.in_kernel')` we can use that.

we could change [`comm_manager_env`](https://github.com/IRkernel/IRkernel/blob/master/R/kernel.r#L364) to `kernel_env` and put a kernel instance inside of it as well, then change `base_display` to:


```r
base_display <- function(data, metadata = NULL) {
	if (!isTRUE(getOption('jupyter.in_kernel')) {
		warning("IR_display can only be used from the IPython R kernel and R magic.")
	} else {
		IRkernel::executor()$display_data(data, metadata)
	}
}
```

**Comment by janschulz** [comment]
Can we use the option system instead? I'm still dreaming of a wider use of repr and hard coding a dependency on irkernel in that way prevents that.

**Comment by takluyver** [comment]
That base_display doesn't really leave an easy way for the R magic to use the display functionality (admittedly it hasn't yet, but I still hope that it will). Can we put arbitary objects in options? If so, we can co-opt that as a shared namespace. I think that's what you're suggesting, @janschulz ?

**Comment by flying-sheep** [comment]
`base_display` isn’t in repr, it’s in IRdisplay.

**Comment by janschulz** [comment]
IMO 

```R
base_display <- function(data, metadata = NULL) {
    if (is.function(getOption('jupyter.base_display_func')) {
        getOption('jupyter.base_display_func')(data, metadata)
    } else {
        warning('IR_display can only be used from the IPython R kernel and R magic.')
    }
}
```

**Comment by janschulz** [comment]
Ok, the above is now in https://github.com/IRkernel/IRdisplay/pull/23

**Comment by janschulz** [comment]
So, in IRkernel, we only have the problem with modifying the global environment, aka #301
