### ISSUE TITLE
Installing RKernel on macOS El Capitan

### ISSUE THREAD

**Issue by Velcin** [IRkernel/IRkernel#259]
Despite all my efforts, I wasn't able to install the R kernel for my IPython/Jupyter notebook on Canopy.

I've closely followed the clear instructions given in: http://www.michaelpacer.com/maths/r-kernel-for-ipython-notebook (or, alternatively, http://irkernel.github.io/installation/)

All goes well (with the message "DONE (IRkernel)") until the last step that install the kernel on jupyter:

```R
IRkernel::installspec()
```

Here is the weird message I get:

> File "/Users/julien/Library/Enthought/Canopy_64bit/User/bin/jupyter-kernelspec", line 8
> from jupyter_client.kernelspecapp import KernelSpecApp.launch_instance
>                                                       ^
> SyntaxError: invalid syntax

My configuration is the following:

- Macbook with El Capitan
- R version 3.2.2
- IPython 4.0.1
- Jupyter 4.0.6

Thank you for your help.

Julien

**Comment by flying-sheep** [comment]
please run

```r
for (binary in c('jupyter', 'ipython', 'ipython3', 'ipython2')) {
    version <- tryCatch(system2(binary, '--version', TRUE, FALSE), error = function(e) '0.0.0')
    if (compareVersion(version, '3.0.0') >= 0) { break }
}
cat(sprintf('%s: %s'), binary, version)
```

and paste the output here

**Comment by Velcin** [comment]
There it is:

> for (binary in c('jupyter', 'ipython', 'ipython3', 'ipython2')) {
+     version <- tryCatch(system2(binary, '--version', TRUE, FALSE), error = function(e) '0.0.0')
+     if (compareVersion(version, '3.0.0') >= 0) { break }
+ }
> cat(sprintf('%s: %s\n', binary, version))
jupyter: 4.0.6

**Comment by flying-sheep** [comment]
hmm, ok, that’s irrelevant, but i just saw that there indeed is a syntax error:

```python
from jupyter_client.kernelspecapp import KernelSpecApp.launch_instance
```

this isn’t valid python.

form the path i infer that you use enthought’s canopy distribution. please file a bug there that their `jupyter-kernelspec` is borked.

**Comment by Velcin** [comment]
You're perfectly right, thank you. I've just edited the file and my notebook can handle R :-).

I'll post a message on the canopy's website.

Julien

**Comment by JCorson** [comment]
For the record, the syntax error reported in this issue, is **not** found in Canopy's default `jupyter-kernelspec`.

**Comment by Velcin** [comment]
Thank you for your message. That's quite strange. I guess this is due to 
some mishandling from my side. Sorry for the inconvenience.
Julien
