### ISSUE TITLE
Error messages show "vertically", with one character per line.

### ISSUE THREAD

**Issue by denilsonsa** [IRkernel/IRkernel#261]
How to reproduce:

```sh
pyvenv-3.4 venv
source venv/bin/activate
pip install jupyter

sudo apt-get install r-base

# Option 1:
sudo add-apt-repository ppa:chronitis/jupyter
sudo apt-get update
sudo apt-get install irkernel

# Option 2:
# Just follow the instructions from: "Development Version"
# https://irkernel.github.io/installation/#devel-panel

# Then:
jupyter notebook
```

Then I tried an extremely simple (but incorrect) line of code:

![Error message in Jupyter](https://cloud.githubusercontent.com/assets/121676/13188400/6cf668ec-d738-11e5-9711-deaa24016670.png)

![Inspecint the error message in the Chrome Developer Tools](https://cloud.githubusercontent.com/assets/121676/13188383/5a23df88-d738-11e5-8af2-fae4554b5379.png)

After some minutes, a proper error message is shown, when Jupyter tries to save the notebook:

![Error/warning when trying to save the notebook](https://cloud.githubusercontent.com/assets/121676/13188520/19d6bed6-d739-11e5-8fee-5a95243d7919.png)

Valid lines seem to have the correct output:

![Output of "print", renders correctly](https://cloud.githubusercontent.com/assets/121676/13188706/359288a2-d73a-11e5-95e7-a542dd5eb7cb.png)

Versions:

* Ubuntu 15.10 (wily)
* The version of the notebook server is 4.1.0
* Python 3.4.3+ (default, Oct 14 2015, 16:03:50) [GCC 5.2.1 20151010]
* Current Kernel Information: R version 3.2.2 (2015-08-14)
* IRkernel version: 0.6
    * Tested with Ubuntu package 0.6.1-1~ppa15.10~1 from https://launchpad.net/~chronitis/+archive/ubuntu/jupyter
    * Also tested by installing directly from github (using `install_github('IRkernel/IRkernel')` and `IRkernel::installspec()`), but without uninstalling the system-wide `.deb` package.

P.S.: I have experience with Python, but I have never used R before.

**Comment by takluyver** [comment]
I think we're returning a string for traceback when it should be an array. This is complicated by the fact that R has no distinction between a one-element vector and a single object.

**Comment by takluyver** [comment]
The code in question is here:
https://github.com/IRkernel/IRkernel/blob/dcc778744bb29c6ee0d20cbbc3361aaa5b51ba11/R/execution.r#L161

**Comment by flying-sheep** [comment]
meh, forgot a `as.list` probably.

**Comment by JanSchulz** [comment]
I also get this error on a save when I execute a simple `irkernel` cell:

```
Notebook Validation failed: "Error in eval(expr, envir, enclos): object 'irkernel' not found\nTraceback:\n" is not of type 'array':
"Error in eval(expr, envir, enclos): object 'irkernel' not found\nTraceback:\n"
```

**Comment by JanSchulz** [comment]
https://github.com/IRkernel/IRkernel/pull/263 Fixes both problems for me...

@flying-sheep Is that intentional that all blank lines have spaces in them in that file? My editor removes them on save and I don't really want to use `git add -p` for all my commits... :-)
