### ISSUE TITLE
Running vignette("nse") does not work

### ISSUE THREAD

**Issue by janschulz** [IRkernel/IRkernel#267]
It opens a browser tab with `http://127.0.0.1:31903/library/dplyr/doc/nse.html`, but the tab doesn't load anything... :-(

**Comment by flying-sheep** [comment]
uh, how is that related to IRkernel?

doesn’t `vignette` spin up its own webserver regardless of from where you call it?

**Comment by JanSchulz** [comment]
Basically because it works in rstudio (shows up in rstudio in the area where the plots also show up) :-)

**Comment by flying-sheep** [comment]
because RStudio intercepts many things (just like is)

what does vanilla R do for you though?

**Comment by JanSchulz** [comment]
Also works...

**Comment by flying-sheep** [comment]
so it spins up the server in both cases but only the plain R one works somehow?

wat

**Comment by JanSchulz** [comment]
Vanilla R opens a browser which displays the thing. Here is tcpview of these two processes: the upper one is the one from a R console and the lower one from the R kernel in a notebook (which does not show a page).

![2016-02-28_214433](https://cloud.githubusercontent.com/assets/890156/13381771/8e5f10d2-de64-11e5-8720-c2dfc8e8e032.png)

**Comment by JanSchulz** [comment]
Is this working on linux/mac?

**Comment by JanSchulz** [comment]
Another interesting artefact is that if I restart the kernel (aka kill the old kernel), the vignette of the page which was opened by the **old** kernel is then displayed instantly. Even interrupting does work, so I have a nice workaround how to display a vignette: run the cell, wait for the new tab to open (which happens instantly but sits there and  "waits" for the content) and then `kernel -> interrupt`. Fun :-)

**Comment by JanSchulz** [comment]
What is actually running the server?  I tried `vignette` to display the code but that seems to return a class  but does not spin up a server?

**Comment by flying-sheep** [comment]
well, that would be `utils:::print.vignette`, of course!

since `repr` falls back to calling `print` when it has no special handling implemented, that explains why *something* happens. but not why it’s so weird.

we probably have to implement a better `repr_html.vignette`.

**Comment by takluyver** [comment]
It sounds like the server it spins up is getting blocked by the kernel somehow - like when the kernel is inside the poll system call, that stops the server from responding.

I agree that the best way to solve it is probably to do something else to display vignettes.

**Comment by JanSchulz** [comment]
If the kernel interferes with http servers, then we should test plotting libs which also spin up a server (if there are such libs)

**Comment by takluyver** [comment]
Good point. I think [rbokeh](https://github.com/bokeh/rbokeh) might.

**Comment by JanSchulz** [comment]
And I found a new workaround:

```
vignette("nse")
Sys.sleep(2)
```

This shows the page immediately, so it seems that the polling is the problem...

Maybe add a timeout to the polling and if no message was found during the interval sleep a tiny fraction of a second? Or put the execution into a different thread?

**Comment by takluyver** [comment]
I don't want to start messing with threads. And there's no obvious reason why zmq polling would block a server that's running in a subprocess. If we do see it with some plotting libraries, polling for a short time might be reasonable, but if it's just vignettes, I think @flying-sheep's idea of doing something smarter with them in repr is preferable.

**Comment by flying-sheep** [comment]
yes. and generally interactive HTML stuff. we have a bug for it already, but i think we wanted cooler notebook features first.

i’d love to see [profvis](https://github.com/rstudio/profvis) working :smile:

**Comment by JanSchulz** [comment]
Has someone tried to run parallel code which runs in the background (does such r libs actually exist?) in the notebook? Not that this is also broken by the poll...

**Comment by janschulz** [comment]
So, the easiest short term workaround seems to add a function to the globalenv which shadows `vignette` and doing a very short sleep.

```
vignette <- function(...){
    print(utils::vignette(...))
    # 0.1 is too little, so add some margin... 
    Sys.sleep(0.4)
}
```
