### ISSUE TITLE
After doing IRkernel::installspec() in R 3.1.3, I am not seeing R in the Notebook list in Jupyter

### ISSUE THREAD

**Issue by Balajideivam** [IRkernel/IRkernel#268]
May I know how to fix this issue? 
After doing IRkernel::installspec() in R 3.1.3, I am not seeing R in the Notebook list in Jupyterhub. 

How to add the same?

**Comment by flying-sheep** [comment]
well, on my systems, `ls ~/.jupyter/kernels` lists `ir`. and on yours?

maybe jupyterhub needs a global install (`installspec(user = FALSE)`)

**Comment by takluyver** [comment]
Try `jupyter kernelspec list` to see what kernels it finds.

This might be to do with going through Jupyterhub. Maybe try installing systemwide with `IRkernel::installspec(user=FALSE)`
