### ISSUE TITLE
Help  for installation of package ‘IRkernel’ had non-zero exit status

### ISSUE THREAD

**Issue by chaser3** [IRkernel/IRkernel#270]
I have already seen previous issues but they are not working for me. I use a mac book pro OS X El Capitan and want to use R with iPython. Please Help!!! 

```
 There are binary versions available but the source versions are later:
         binary source needs_compilation
repr        0.2    0.4             FALSE
IRkernel    0.4    0.5             FALSE

trying URL 'http://irkernel.github.io/bin/macosx/mavericks/contrib/3.2/rzmq_0.7.7.tgz'
Content type 'application/octet-stream' length 81898 bytes (79 KB)
==================================================
downloaded 79 KB

trying URL 'http://irkernel.github.io/bin/macosx/mavericks/contrib/3.2/IRdisplay_0.3.tgz'
Content type 'application/octet-stream' length 21391 bytes (20 KB)
==================================================
downloaded 20 KB


The downloaded binary packages are in
	/var/folders/v8/5h9n_g9921gg4y8sz4hq9pgw0000gn/T//Rtmp2p5b09/downloaded_packages
installing the source packages ‘repr’, ‘IRkernel’

trying URL 'http://irkernel.github.io/src/contrib/repr_0.4.tar.gz'
Content type 'application/octet-stream' length 11355 bytes (11 KB)
==================================================
downloaded 11 KB

trying URL 'http://irkernel.github.io/src/contrib/IRkernel_0.5.tar.gz'
Content type 'application/octet-stream' length 17951 bytes (17 KB)
==================================================
downloaded 17 KB

* installing *source* package ‘repr’ ...
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (repr)
* installing *source* package ‘IRkernel’ ...
** R
** inst
** preparing package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/rzmq/libs/rzmq.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.2/Resources/library/rzmq/libs/rzmq.so, 6): Library not loaded: /usr/local/lib/libzmq.4.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.2/Resources/library/rzmq/libs/rzmq.so
  Reason: image not found
ERROR: lazy loading failed for package ‘IRkernel’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/IRkernel’

The downloaded source packages are in
	‘/private/var/folders/v8/5h9n_g9921gg4y8sz4hq9pgw0000gn/T/Rtmp2p5b09/downloaded_packages’
Warning message:
In install.packages(c("rzmq", "repr", "IRkernel", "IRdisplay"),  :
  installation of package ‘IRkernel’ had non-zero exit status
```

**Comment by flying-sheep** [comment]
try using the in-development version:

```R
install.packages('devtools')
devtools::install_github('IRkernel/IRkernel')
```

**Comment by chaser3** [comment]
install.packages('devtools') did fine 
but the next command returned error

Downloading GitHub repo IRkernel/IRkernel@master
from URL https://api.github.com/repos/IRkernel/IRkernel/zipball/master
Installing IRkernel
Skipping 2 unavailable packages: IRdisplay, repr
Installing 1 package: pbdZMQ
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  '/private/var/folders/v8/5h9n_g9921gg4y8sz4hq9pgw0000gn/T/RtmptCfydL/devtools5331fb10086/IRkernel-IRkernel-a59fdc0'  \
  --library='/Library/Frameworks/R.framework/Versions/3.2/Resources/library' --install-tests 

* installing *source* package ‘IRkernel’ ...
** R
** inst
** preparing package for lazy loading
Error : .onLoad failed in loadNamespace() for 'pbdZMQ', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/pbdZMQ/libs/pbdZMQ.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.2/Resources/library/pbdZMQ/libs/pbdZMQ.so, 6): Library not loaded: /Builds/CRAN-QA-Simon/packages/mavericks-x86_64/Rlib/3.2/pbdZMQ/libs/libzmq.4.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.2/Resources/library/pbdZMQ/libs/pbdZMQ.so
  Reason: image not found
ERROR: lazy loading failed for package ‘IRkernel’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/IRkernel’
Error: Command failed (1)

**Comment by flying-sheep** [comment]
so what’s happening is that both `rzmq` and `pbdZMQ` fail to install for you.

you can try filing an issue [here](https://github.com/snoweye/pbdZMQ/issues)

**Comment by chaser3** [comment]
no i've checked the bin where libraries are installed for R there rmzq and pbdZMQ are present but iKernel is not getting installed. I've tried everything but everytime its getting the same error
Reason: image not found
program exited with non-zero exit

**Comment by flying-sheep** [comment]
look in the output you pasted. the 5th line is:

`Installing 1 package: pbdZMQ`

which means that it starts installing pbdZMQ as a dependency of IRkernel.

the failure happens during installation of pbdZMQ.

**Comment by flying-sheep** [comment]
ah, i see, you’re right in that it does happen while trying to install IRkernel. still weird: why does almost nothing happen after `Installing 1 package: pbdZMQ` and before `installing *source* package ‘IRkernel’`?

it’s still an error occurring inside of pbdZMQ, though:

```
Error : .onLoad failed in loadNamespace() for 'pbdZMQ'
```

try in an R console (R from bash or Rstudio, but not R.app!) to do `library(pbdZMQ)`

**Comment by chaser3** [comment]
library(pbdZMQ)
Error : .onLoad failed in loadNamespace() for 'pbdZMQ', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/pbdZMQ/libs/pbdZMQ.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.2/Resources/library/pbdZMQ/libs/pbdZMQ.so, 6): Library not loaded: /Builds/CRAN-QA-Simon/packages/mavericks-x86_64/Rlib/3.2/pbdZMQ/libs/libzmq.4.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.2/Resources/library/pbdZMQ/libs/pbdZMQ.so
  Reason: image not found
Error: package or namespace load failed for ‘pbdZMQ’

**Comment by flying-sheep** [comment]
see: pbdZMQ doesn’t work. did you file a bug there?
