### ISSUE TITLE
enable selection of variable names with full stops on one click

### ISSUE THREAD

**Issue by DSLituiev** [IRkernel/IRkernel#271]
It might be deep wired in browser internals, but it would be extremely useful if one could select R variable names which include "." like `as.matrix`  on one click.

**Comment by takluyver** [comment]
We have no control over that. CodeMirror - the text editor used in the notebook - *might*, but I suspect it's something browsers determine.

**Comment by flying-sheep** [comment]
this’ll do the job.

```js
CodeMirror.registerHelper("wordChars", "r", /[\w.]/);
```

feel free to file a book in [notebook](https://github.com/jupyter/notebook) to do this.

**Comment by JanSchulz** [comment]
... or with [CodeMirror](https://github.com/codemirror/CodeMirror)

BTW: for pythong there is a similar bug: try a double click on `u"text"`

**Comment by DSLituiev** [comment]
So where should one type / paste that command?
Can you please open an issue, @Phillip A., as you probably better can
explain what can be done? Thank you!

**Comment by flying-sheep** [comment]
@DSLituiev you can do it :wink:

**Comment by DSLituiev** [comment]
@flying-sheep : can you please expound on where does the code you provided should go?

**Comment by flying-sheep** [comment]
i did it: codemirror/CodeMirror#3856

**Comment by DSLituiev** [comment]
Thank you!
