### ISSUE TITLE
Unable to install IRkernel due to segfault

### ISSUE THREAD

**Issue by EvoNerd** [IRkernel/IRkernel#274]
When I try to install following either the instructions for the binary or the source code I get a segfault (message below).
I'm running OS X 10.11.3 and R version 3.2.3
Any help with this issue would be great!

* installing *source* package ‘IRkernel’ ...
** R
** inst
** preparing package for lazy loading

 *** caught segfault ***
address 0x18, cause 'memory not mapped'

Traceback:
 1: dyn.load(file, DLLpath = DLLpath, ...)
 2: library.dynam(lib, package, package.lib)
 3: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
 4: namespaceImport(ns, loadNamespace(i, c(lib.loc, .libPaths()),     versionCheck = vI[[i]]), from = package)
 5: loadNamespace(package, lib.loc, keep.source, partial = TRUE)
 6: withCallingHandlers(expr, packageStartupMessage = function(c) invokeRestart("muffleMessage"))
 7: suppressPackageStartupMessages(loadNamespace(package, lib.loc,     keep.source, partial = TRUE))
 8: code2LazyLoadDB(package, lib.loc = lib.loc, keep.source = keep.source,     compress = compress)
 9: makeLazyLoading(pkg_name, lib, keep.source = keep.source)
10: doTryCatch(return(expr), name, parentenv, handler)
11: tryCatchOne(expr, names, parentenv, handlers[[1L]])
12: tryCatchList(expr, classes, parentenv, handlers)
13: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        msg <- conditionMessage(e)        sm <- strsplit(msg, "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && identical(getOption("show.error.messages"),         TRUE)) {        cat(msg, file = stderr())        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
14: try({    suppressPackageStartupMessages(.getRequiredPackages(quietly = TRUE))    makeLazyLoading(pkg_name, lib, keep.source = keep.source)})
15: do_install_source(pkg_name, instdir, pkg, desc)
16: do_install(pkg)
17: tools:::.install_packages()
aborting ...
/Library/Frameworks/R.framework/Resources/bin/INSTALL: line 34:  3487 Done                    echo 'tools:::.install_packages()'
      3488 Segmentation fault: 11  | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" $myArgs --slave --args ${args}

**Comment by takluyver** [comment]
Can you try installing the development version? We've switched the ZMQ library we use, which might fix this.

```
devtools::install_github("IRkernel/IRkernel")

**Comment by EvoNerd** [comment]
I still get a segfault when I try the code you sent.
Dunno if it's useful, but here's the message:

*** caught segfault ***
address 0x18, cause 'memory not mapped'

Traceback:
 1: dyn.load(file, DLLpath = DLLpath, ...)
 2: library.dynam(lib, package, package.lib)
 3: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
 4: asNamespace(ns)
 5: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
 6: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
 7: asNamespace(ns)
 8: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
 9: loadNamespace(name)
10: doTryCatch(return(expr), name, parentenv, handler)
11: tryCatchOne(expr, names, parentenv, handlers[[1L]])
12: tryCatchList(expr, classes, parentenv, handlers)
13: tryCatch(loadNamespace(name), error = function(e) stop(e))
14: getNamespace(ns)
15: asNamespace(ns)
16: getExportedValue(pkg, name)
17: devtools::install_github

**Comment by takluyver** [comment]
In both cases it's crashing trying to load a compiled library, I think. It seems most likely that that's zeromq. If you start R and type `library(rzmq)` or `library(pbdZMQ)`, does it segfault? What about starting Python and doing `import zmq`.

**Comment by EvoNerd** [comment]
`library(rzmq)` in R and `import zmq` in python work just fine. But `library(pbdZMQ)` gives me an error message:
> Error : .onLoad failed in loadNamespace() for 'pbdZMQ', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Users/Pongo/Rlibs/pbdZMQ/libs/pbdZMQ.so':
  dlopen(/Users/Pongo/Rlibs/pbdZMQ/libs/pbdZMQ.so, 6): Library not loaded: /Builds/CRAN-QA-Simon/packages/mavericks-x86_64/Rlib/3.2/pbdZMQ/libs/libzmq.4.dylib
  Referenced from: /Users/Pongo/Rlibs/pbdZMQ/libs/pbdZMQ.so
  Reason: image not found
Error: package or namespace load failed for ‘pbdZMQ’

**Comment by takluyver** [comment]
Hmmm. I'm not sure if that's the same issue or not, but it looks like a problem with the binary package of pbdZMQ - it looks like it's picked up an absolute path from the machine it was built on. @snoweye, is that plausible?

**Comment by EvoNerd** [comment]
I've solved the problem. It was an issue with my lib paths. I solved the issue by NOT having a custom lib path in my .Rprofile 
...and just FYI to others, I realized the problem when some other libraries (e.g. Matrix, plyr) were segfaulting when I tried loading them in R (note that NOT all libraries were segfaulting).

This solution worked for me because I have superuser privileges on my computer but may be a problem for people trying to install locally...

**Comment by flying-sheep** [comment]
great!

**Comment by ambj** [comment]
@EvoNerd can you elaborate on where you deleted the custom lib?? I seem to have the exact same problem as you, but I'm not sure where to remove the custom lib path, and where my .Rprofile is.

**Comment by avislova** [comment]
@EvoNerd @ambj I also have the same issue - don't know how to remove custom lib path from .Rprofile

thanks!

**Comment by depy** [comment]
Having the same problem. I don't have ~/.Rprofile at all. I'm using anaconda + R.

**Comment by depy** [comment]
If you are using Anaconda, this solved it for me:
`conda install zeromq`

**Comment by ambj** [comment]
I did not have the ~/.Rprofile either. But it worked for me to update my R version and using conda as suggested by @depy. Thank you very much for the help!

**Comment by MoHeydarian** [comment]
I was having the same error as EvoNerd. Your solution was a quick fix @depy, thanks!

**Comment by Victorfy** [comment]
@depy amazing!! but what does it mean?

**Comment by Prashan7h** [comment]
@depy the solution works, thank you.
