### ISSUE TITLE
Add a way to identify if run in the kernel

### ISSUE THREAD

**Issue by JanSchulz** [IRkernel/IRkernel#275]
My proposal:

in the kernel.r$run add an option:

```r
option(irkernel.in_kernel = TRUE
```

Packages can then check for this and adjust behaviour (e.g. produce different markdown output)

```r
getOption("irkernel.in_kernel", FALSE)
```

Any objections? Different names?

**Comment by takluyver** [comment]
Sounds fine to me.

**Comment by flying-sheep** [comment]
#24
