### ISSUE TITLE
Download as R Markdown (.Rmd)

### ISSUE THREAD

**Issue by mikebentley15** [IRkernel/IRkernel#279]
Note: this is a suggested enhancement.

Since the Jupyter notebook is simply Markdown mixed with R code, it shouldn't be too much to ask if we could download it as an R Markdown file.  That way you could download it and use it in RStudio.  I know you can download the .r file, but this would be much more appropriate, don't you think?

**Comment by flying-sheep** [comment]
i don’t think you can define your own formats that appear in the list, or can you?

we could ship a template that can be used with nbconvert, and instructions to use it…

**Comment by mikebentley15** [comment]
Hi Phillip,

I have no idea.  I downloaded the source code and tried to see where to do
it, but couldn't find it within an hour that I spent.

I tried googling, but I don't think the documentation for creating a kernel
is very complete.  I think to really see if it can be done and how, one
would need to download the Jupyter source code and see how it works.  I
might spend a little time this next week to see if I can find out in about
one or two hours.

But don't you think it would be an awesome feature!?  It would truly give a
good bridge between RStudio and Jupiter with the IRKernel.  You could
develop it in Jupyter, then give it to someone else as an R markdown file.

By the way, great job with the IRKernel!  I recently discovered it and am
very impressed at how well it is integrated and how well it works.

Thanks,
Mike

**Comment by flying-sheep** [comment]
i’m not a fan of Rmarkdown and think notebooks are better.

i also think that the download dialog only provides what nbconvert can do:

> ['custom', 'html', 'latex', 'markdown', 'notebook', 'pdf', 'python', 'rst', 'script', 'slides']

“custom” of course excluded as it requires a template that you can’t specify in the web interface.

but as said: we can provide one!

**Comment by takluyver** [comment]
It's possible to provide custom exporters for nbconvert, but I don't think
there's currently a way to expose them in the notebook menu. It's a
reasonable thing to add to the notebook, though - I think Haskell has a use
case for it too.

**Comment by mikebentley15** [comment]
If it's doable, that would be cool.  If not, I understand.

I agree, I like notebooks better, but what if you need to give it to
someone that doesn't use jupyter, but likes RStudio  instead, which by the
way is an impressive IDE?

- Mike
It's possible to provide custom exporters for nbconvert, but I don't think
there's currently a way to expose them in the notebook menu. It's a
reasonable thing to add to the notebook, though - I think Haskell has a use
case for it too.

—
Reply to this email directly or view it on GitHub
<https://github.com/IRkernel/IRkernel/issues/279#issuecomment-195487775>.

**Comment by chronitis** [comment]
I wrote a standalone tool to do this: [ipyrmd](https://github.com/chronitis/ipyrmd)

I'm afraid it never got integrated with the notebook or nbformat directly, but it should do a reasonable job of `Rmd <-> ipynb` conversion. I admittedly haven't touched it for a while, but that is mostly because I used it to convert the `Rmd` documents I had and haven't really needed to go back.

**Comment by mikebentley15** [comment]
This is a pretty cool tool!  I'd say it works pretty well.

- Mike

**Comment by flying-sheep** [comment]
IRkernel/irkernel.github.io#24

**Comment by grst** [comment]
I want to present an alternative approach for this issue: 

Recently, I added Rmarkdown support to [ipymd](https://github.com/grst/ipymd). With this plugin, Rmarkdown can be directly opened and edited in jupyter, as if it was a notebook. All source code is stored in `.Rmd` and all results in `.nb.html`, as it is done by rstudio. 

This avoids futile file conversions and imho combines the best of two worlds.

**Comment by flying-sheep** [comment]
sounds rad!

**Comment by mikebentley15** [comment]
Very cool!
