### ISSUE TITLE
Use monospace font in console printing

### ISSUE THREAD

**Issue by renkun-ken** [IRkernel/IRkernel#281]
I'm using IRkernel in Jupyter notebook. I notice that the output of the following code is displayed in monospace font:

``` r
x <- rnorm(1000)
y <- 2 * x + 0.2 * rnorm(1000)
model <- lm(y ~ x)
model
```

But the output of an ordinary expression does not:

``` r
1:10
c(a=1,b=2)
list(a=1,b=2)
sapply(mtcars, class)
```

I suggest using monospace font in the console output of R expressions for consistency. If so the output will look like

![jupyter_ir_monospace_output1](https://cloud.githubusercontent.com/assets/4662568/13802845/b845e13c-eb7a-11e5-93bc-4a456432eaa0.png)

**Comment by flying-sheep** [comment]
monospace means: “repr doesn’t have a pretty format for this and therefore plain console output is shown”

**Comment by JanSchulz** [comment]
The question is whether we have chosen a good default by using rich display for primitive things like lists and vectors. Another default could be to only output html for `data.frame` and `matrix` and only turn on the other stuff via an option (`jupyter.display.rich_primitives`).

At least I would leave it at that, the current list output is IMO to long and wasts too much screen space:

![2016-03-16_103550](https://cloud.githubusercontent.com/assets/890156/13807720/e083cb68-eb62-11e5-8111-906977f158e2.png)

[It's also really bad how the output jumps around :-( -> should all start at the front -> https://github.com/IRkernel/repr/issues/22)

vs 

![2016-03-16_103750](https://cloud.githubusercontent.com/assets/890156/13807765/26e95aaa-eb63-11e5-8430-774537848161.png)

**Comment by JanSchulz** [comment]
@renkun-ken in some time, you can probably do a `pander(summary(...))` and get a rich output...

**Comment by flying-sheep** [comment]
your real issue is IRkernel/repr#22, but you still propose not doing rich output?

why not just fix rich output in IRkernel/repr#22?

**Comment by JanSchulz** [comment]
> your real issue is IRkernel/repr#22, but you still propose not doing rich output?

Yes, mainly because I don't see a benefit of having richt display for such primitives: they take more space and are not c&p friendly (tabs, etc). (It's even better with the python approach to output eval-able representations, but we had this already... :-))

For tables and other higher level stuff in most cases there is a clear benefit of rich output. Especially for things like regression tables where you want to compare stuff between rows and columns.

**Comment by flying-sheep** [comment]
i don’t agree that they necessarily take up more space. as said: let’s change the named vector repr, and your issue is gone.

**Comment by flying-sheep** [comment]
there’s more reprs now, this should be rare
