### ISSUE TITLE
Trimmed display of named numeric vector

### ISSUE THREAD

**Issue by renkun-ken** [IRkernel/IRkernel#282]
Run the following script in Jupyter R Notebook:

```
quantile(rnorm(100))
```

But the names of the output numeric vector are somehow trimmed like:

![jupyter_ir_trimmed_named_vector](https://cloud.githubusercontent.com/assets/4662568/13802734/b3fb5540-eb79-11e5-8191-65eba85aa214.png)

**Comment by renkun-ken** [comment]
If the output is displayed in monospace font, such trimming disappears:

![jupyter_ir_monospace_output](https://cloud.githubusercontent.com/assets/4662568/13802780/1213a01a-eb7a-11e5-9b09-92e2cdda0cbf.png)

Related to #281.

**Comment by flying-sheep** [comment]
has to be an issue with your browser’s rendering.

when you check the CSS you see there’s much space left and nothing funky going on that could reasonably result in that trimming

![not cut](https://cloud.githubusercontent.com/assets/291575/13805935/921ff8e8-eb58-11e5-9bde-d02ecb935598.png)

**Comment by takluyver** [comment]
@renkun-ken what browser are you using? I couldn't replicate that in Firefox or Chromium.

@flying-sheep let's not be too quick to dismiss reports like this. Clearly the display is sub-optimal in at least one browser, and even if that's the browser's fault, we may want to see if there's something we can do to improve it. Dealing with different rendering engines is the cost of using HTML ;-).

**Comment by renkun-ken** [comment]
@takluyver I'm using Firefox 46.0b1 64bit under Win10.

**Comment by takluyver** [comment]
OK, it's possible that it's a rendering error that will get fixed before that version of Firefox is released. Do you have a stable version of Firefox you can test with as well?

**Comment by renkun-ken** [comment]
I use Firefox 45 and the rendering is exactly the same. I use the element inspector and disable "overflow: hidden" for `.dl-horizontal` class, and the cropping no longer exists.

**Comment by flying-sheep** [comment]
as said: as far as i can see it’s impossible that this rendering error is the CSS’s fault.

the text is right-aligned and its container has `overflow: hidden`. this should have no effect as there is no negative margin or relative positioning or so involved. it just looks like firefox doesn’t correctly place the text inside of the box.

**Comment by takluyver** [comment]
Odd. It's working for me in Firefox 45 on Linux. :confused:

**Comment by flying-sheep** [comment]
probably a combination of the font, firefox version and/or font rendering library (@renkun-ken: on which OS are you?)

**Comment by takluyver** [comment]
Windows 10 (so say my amazing psychic reading powers ;-)

**Comment by flying-sheep** [comment]
after stalking his github profile as well, i assume @renkun-ken uses a custom font rendering engine on windows.

well, i’d start there if i used that and had a font rendering problem :laughing:

**Comment by renkun-ken** [comment]
@flying-sheep Yes, I'm using MacType (a wrapper of FreeType) to render fonts with better quality on Windows. I guest it is exactly where the problem comes out. Everything else work quite well.

**Comment by takluyver** [comment]
I didn't even know such a thing was possible! But yeah, if you're using a non-standard font renderer, we are definitely calling Someone Else's Problem on text rendering issues. :smile:
