### ISSUE TITLE
Less than symbol (<) causes string truncation

### ISSUE THREAD

**Issue by dhimmel** [IRkernel/IRkernel#286]
Strings that include `<` do not display properly. If any characters follow the `<`, those characters as well as the `<` will not diplay. See [this notebook](https://gist.github.com/dhimmel/03112405fec91e5e7eaf "Gist of a notebook with the bug") for an example.

**Comment by takluyver** [comment]
See IRkernel/repr#38. We need to do HTML escaping.

**Comment by dhimmel** [comment]
@takluyver, ah makes sense. The notebook is displaying text as raw HTML.

Should I close this issue or what till IRkernel/repr#38 is resolved?

**Comment by takluyver** [comment]
I think we can close it as a duplicate of that one.

**Comment by dhimmel** [comment]
Got it. Will use the suggested workaround for now:

```r
htmltools::htmlEscape('my string with < nowprints')
```
