### ISSUE TITLE
Latest version not used under Windows

### ISSUE THREAD

**Issue by Nikolai-Hlubek** [IRkernel/IRkernel#288]
When using: 

```r
install.packages(c('rzmq','repr','IRkernel','IRdisplay'), repos = c('http://irkernel.github.io/', getOption('repos')))
```

with the latest R under Windows 7 64bit, I do not get IRKernel 0.6.1 but 0.5.

**Comment by takluyver** [comment]
It looks like 0.6 and 0.6.1 were tagged but never packaged. @flying-sheep @janschulz ?

**Comment by flying-sheep** [comment]
because things are moving all the time right now. maybe releasing now is better than when all that stuff is in.

**Comment by Nikolai-Hlubek** [comment]
It would be cool if you could compile the packages, because the fix to the UTF-8 bug is really important to me and I had some problems installing from source today.

**Comment by flying-sheep** [comment]
sure, we’ll do that!

until then: does the installation from github work?

```r
install.packages('devtools')
# Need RCurl for install_github
install.packages('RCurl')
library(devtools)
# Install the packages
install_github('IRkernel/repr')
install_github('IRkernel/IRdisplay')
install_github('IRkernel/IRkernel')
```

**Comment by Nikolai-Hlubek** [comment]
No unfortunately it doesn't. Corporate firewall for the win. ;-)

I tried it like this: 
```
# Install required packages for Jupyter R-Kernel
install.packages(c('rzmq', 'repr', 'IRkernel', 'IRdisplay'),repos = c('http://irkernel.github.io/', getOption('repos')))

# Update R-Kernel to latest version
install.packages("https://github.com/IRkernel/IRkernel/archive/0.6.1.tar.gz", repo=NULL, type="source")

# Link R-Kernel to Jupyter (all users)
IRkernel::installspec(user = FALSE)
```

but now I get errors 
`"Got unhandled msg_type: "comm_open"
`
and when I run something:
`there is no package called 'Rcpp'`

**Comment by flying-sheep** [comment]
weird. if you’re sure 0.6.1 has the fixes you want, there’s no way that installing it via tarball shouldn’t do the trick

**Comment by Nikolai-Hlubek** [comment]
Fresh day, fresh mind. ;-)

The error message I mentioned above stays, but the install commands from above worked. UTF-8 also works. I needed to set the encoding of every document to UTF-8 and I had missed one yesterday. 

Thank you for the help guys. 
This ticket can be closed once the packages are compiled.

**Comment by janschulz** [comment]
I updated the install instructions in #327 so install_github is again used... We are currntly uploading the packages to CRAN, so after that it's a regular `install.packages("IRkernel")`
