### ISSUE TITLE
installspec: unused arguments (name = "ir32", displayname = "R 3.2")

### ISSUE THREAD

**Issue by DSLituiev** [IRkernel/IRkernel#290]
I am trying to follow the installation instructions. 

Running  `IRkernel::installspec()` works. Subsequent running `IRkernel::installspec(name = 'ir32', displayname = 'R 3.2')` yields an error:

```
IRkernel::installspec(name = 'ir32', displayname = 'R 3.2')
Error in IRkernel::installspec(name = "ir32", displayname = "R 3.2") :
  unused arguments (name = "ir32", displayname = "R 3.2")
```

System: MacOSX10.10.5, Python3.5

**Comment by takluyver** [comment]
I think we need to do a new release before you can use those. The main instructions [on the website](http://irkernel.github.io/installation/) don't refer to them.
