### ISSUE TITLE
repr version error

### ISSUE THREAD

**Issue by poplav** [IRkernel/IRkernel#294]
In [jupyter-incubator/declarativewidgets](https://github.com/jupyter-incubator/declarativewidgets) we are installing the IRkernel on each build [here](https://github.com/jupyter-incubator/declarativewidgets/blob/master/etc/r/install.r).  
We are getting an errror when running `devtools::install_git("https://github.com/IRkernel/IRkernel.git")`

Specifically:

```r
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘repr’ 0.3 is already loaded, but >= 0.4.99 is required
```

I suspect this error was introduced by the recent commit [require newer repr] (https://github.com/IRkernel/IRkernel/commit/752ced6df9d093f0c5439f618346ab40813d0e18).

Any advice/resolution to this issue would be greatly appreciated.

**Comment by janschulz** [comment]
You probably need to do install everything from github, in the right order:

```
devtools::install_github(IRkernel/repr")
devtools::install_github(IRkernel/IRdisplay")
devtools::install_github(IRkernel/IRkernel")
```

**Comment by poplav** [comment]
@janschulz Thanks, for the insight.
We resolved the issue under https://github.com/jupyter-incubator/declarativewidgets/pull/303.
We can close the issue.

**Comment by flying-sheep** [comment]
sorry for the inconvenience, but we needed to do that in order to ensure that IRkernel doesn’t try to access a not-yet-existing API in an old repr version.

but i guess your build will work reliably now!
