### ISSUE TITLE
spatial data plots in jupyter not displaying

### ISSUE THREAD

**Issue by snowlizard13** [IRkernel/IRkernel#297]
I am just learning to use Jupyter and I'm having trouble producing any spatial data plots running the same code that works in RStudio, and I am receiving no error messages. I can get 'regular' scatter plots to display as expected using `plot`, but no spatial plots using either `plot `or `spplot` (sp package) in Jupyter. Do these generate a different file format that needs special attention for Jupyter to display?

In RStudio I can get these:
`plot(mapdata) `
![image](https://cloud.githubusercontent.com/assets/17767431/14571028/5bc95f1e-0304-11e6-9a00-a1f6a38be2a8.png)

`spplot(mapdata, c("cluster"), colorkey=list(space="bottom"))`
![image](https://cloud.githubusercontent.com/assets/17767431/14571079/a0aed442-0304-11e6-89ba-ec6d61ee3f48.png)

But I have no results running the same code on the same data using Juptyer. Is there a difference in rendering these images that needs special consideration in Jupyter?

**Comment by janschulz** [comment]
Can you add a reproduceable example?

A first guess would be that the map plots do not work with svg, which is unfortunately the default. 

Try this to use only png plotting:

```
options(jupyter.plot_mimetypes = c("text/plain", "image/png" )) # no more svg...
```

**Comment by snowlizard13** [comment]
Yep, that worked. Thank you!

**Comment by takluyver** [comment]
I said I was neutral in the plot formats debate, but if there are some kind of plots that fail with svg, I think that pushes me towards saying turn it off by default. @flying-sheep ?

**Comment by flying-sheep** [comment]
i think we should investigate why it doesn’t display first/instead
