### ISSUE TITLE
In install.packages(c("rzmq", "repr", "IRkernel", "IRdisplay"),  :   installation of package ‘IRkernel’ had non-zero exit status

### ISSUE THREAD

**Issue by nmolkeri** [IRkernel/IRkernel#298]
When I run the below code 
```
install.packages(c('rzmq','repr','IRkernel','IRdisplay'),
+ repos = c('http://irkernel.github.io/', getOption('repos')))
```

I am getting this error

```
  There are binary versions available but the source versions are
  later:
         binary source needs_compilation
repr        0.2    0.4             FALSE
IRkernel    0.4    0.5             FALSE

trying URL 'http://irkernel.github.io/bin/macosx/mavericks/contrib/3.2/rzmq_0.7.7.tgz'
Content type 'application/octet-stream' length 81898 bytes (79 KB)
==================================================
downloaded 79 KB

trying URL 'http://irkernel.github.io/bin/macosx/mavericks/contrib/3.2/IRdisplay_0.3.tgz'
Content type 'application/octet-stream' length 21391 bytes (20 KB)
==================================================
downloaded 20 KB


The downloaded binary packages are in
	/var/folders/2l/sm3y5dp96mj0shqdl4q8b0180000gn/T//RtmpSeELgF/downloaded_packages
installing the source packages ‘repr’, ‘IRkernel’

trying URL 'http://irkernel.github.io/src/contrib/repr_0.4.tar.gz'
Content type 'application/octet-stream' length 11355 bytes (11 KB)
==================================================
downloaded 11 KB

trying URL 'http://irkernel.github.io/src/contrib/IRkernel_0.5.tar.gz'
Content type 'application/octet-stream' length 17951 bytes (17 KB)
==================================================
downloaded 17 KB

* installing *source* package ‘repr’ ...
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (repr)
* installing *source* package ‘IRkernel’ ...
** R
** inst
** preparing package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/rzmq/libs/rzmq.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.2/Resources/library/rzmq/libs/rzmq.so, 6): Library not loaded: /usr/local/lib/libzmq.4.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.2/Resources/library/rzmq/libs/rzmq.so
  Reason: image not found
ERROR: lazy loading failed for package ‘IRkernel’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/IRkernel’

The downloaded source packages are in
	‘/private/var/folders/2l/sm3y5dp96mj0shqdl4q8b0180000gn/T/RtmpSeELgF/downloaded_packages’
Warning message:
In install.packages(c("rzmq", "repr", "IRkernel", "IRdisplay"),  :
  installation of package ‘IRkernel’ had non-zero exit status
```

Can anyone help me with this.

**Comment by janschulz** [comment]
Please install from github:

```
library("devtools")
install_github("IRkernel/repr")
install_github("IRkernel/IRdisplay")
install_github("IRkernel/IRkernel") # should install a zmq lib from cran
```

**Comment by ikinsella** [comment]
Hi, I am unfortunately running into the same issue when following your instructions. Specifically, the first three commands work just fine for me, but `install_github("IRkernel/IRkernel")` fails just like when I originally tried to use `install.packages()`. 
```
 > install_github("IRkernel/IRdisplay")
Downloading GitHub repo IRkernel/IRdisplay@master
from URL https://api.github.com/repos/IRkernel/IRdisplay/zipball/master
Installing IRdisplay
Skipping 1 unavailable package: repr
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/1s/89q_bggn28jcp85js8d8yc300000gn/T/RtmpBBQ78P/devtools3a2025e9ad46/IRkernel-IRdisplay-2a66d08'  \
  --library='/Library/Frameworks/R.framework/Versions/3.2/Resources/library' --install-tests 

* installing *source* package ‘IRdisplay’ ...
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (IRdisplay)
> install_github("IRkernel/IRkernel")
Downloading GitHub repo IRkernel/IRkernel@master
from URL https://api.github.com/repos/IRkernel/IRkernel/zipball/master
Installing IRkernel
Skipping 2 unavailable packages: IRdisplay, repr
Installing 1 package: pbdZMQ
trying URL 'http://cloud.r-project.org/bin/macosx/mavericks/contrib/3.2/pbdZMQ_0.2-2.tgz'
Content type 'application/x-gzip' length 559609 bytes (546 KB)
==================================================
downloaded 546 KB


The downloaded binary packages are in
	/var/folders/1s/89q_bggn28jcp85js8d8yc300000gn/T//RtmpBBQ78P/downloaded_packages
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/1s/89q_bggn28jcp85js8d8yc300000gn/T/RtmpBBQ78P/devtools3a205d2e9192/IRkernel-IRkernel-26dc7bc'  \
  --library='/Library/Frameworks/R.framework/Versions/3.2/Resources/library' --install-tests 

* installing *source* package ‘IRkernel’ ...
** R
** inst
** preparing package for lazy loading
Error : .onLoad failed in loadNamespace() for 'pbdZMQ', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/pbdZMQ/libs/pbdZMQ.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.2/Resources/library/pbdZMQ/libs/pbdZMQ.so, 6): Library not loaded: /Builds/CRAN-QA-Simon/packages/mavericks-x86_64/Rlib/3.2/pbdZMQ/libs/libzmq.4.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.2/Resources/library/pbdZMQ/libs/pbdZMQ.so
  Reason: image not found
ERROR: lazy loading failed for package ‘IRkernel’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/IRkernel’
Error: Command failed (1)
```

**Comment by ikinsella** [comment]
Good news everyone! I found an old [issue](https://github.com/armstrtw/rzmq/issues/18) in another project which discussed the problem and presented a fix. It seems that on MacOSX, the rzmq library is looking for `libzmq.4.dylib` which homebrew has renamed to `libzmq.5.dylib`. It's important to note, however, that the quick fix at the top of the page allowed me to install the kernel, but DID NOT allow the kernel to run. Therefore, I highly recommend first trying to install the older zeromq first:
```brew uninstall zeromq; brew install zeromq405```

**Comment by avislova** [comment]
@janschulz I am also running into an issue with the fourth command:

    install_github("IRkernel/IRkernel")

I am getting the following error:

    > install_github("IRkernel/IRkernel")
    Downloading GitHub repo IRkernel/IRkernel@master
    from URL https://api.github.com/repos/IRkernel/IRkernel/zipball/master
    Installing IRkernel
    trying URL 'https://cran.rstudio.com/src/contrib/jsonlite_1.0.tar.gz'
    Content type 'application/x-gzip' length 1057732 bytes (1.0 MB)
    ==================================================
    downloaded 1.0 MB

    sh: /usr/bin/gnutar: No such file or directory
    sh: /usr/bin/gnutar: No such file or directory
    Error in system(cmd, intern = TRUE) : error in running command
    In addition: Warning message:
    In utils::untar(src, exdir = target, compressed = "gzip") :
      ‘/usr/bin/gnutar -xf     '/var/folders/s_/qhhsy6p97z57lhhrdqz_zn6r0000gn/T//RtmpvMLY9L/jsonlite_1.0.tar.gz' -C     '/var/folders/s_/qhhsy6p97z57lhhrdqz_zn6r0000gn/T//RtmpvMLY9L/devtools490a71400229'’ returned error code 127

**Comment by flying-sheep** [comment]
please read the error closely: it’s a problem with installing jsonlite, one of our dependencies.

i’m closing this since it’s completely unrelated to this project, but we will continue to help you here!

**Comment by avislova** [comment]
Hello!

Thanks a lot! I would greatly appreciate if you could walk me through some
troubleshooting because I am totally stuck wrestling with this issue and
have made zero progress on my actually work in like 2 weeks. Frustrating.

FYI I actually had IRKernel working fine at one point (I was using it as
kind of a computational 'lab notebook'), and I'm not sure what I did to
break it.  At this point, I have done many different things to try to fix
it, I think I may have made it worse, haha.

*Uninstalling relevant software in attempt to 'start fresh':*

Anyways, I am trying to uninstall and reinstall anaconda and R (again). My
first problem is that, for some reason, I am having a hard time getting rid
of R entirely (see:
http://stackoverflow.com/questions/38390548/how-to-uninstall-r-completely-from-os-x).
I think this may have something to do with the eventual problem. The weird
thing is that I can't find R anywhere on my computer, but I can still run
it from command line.

*Reinstalling Anaconda*

So, after uninstalling anaconda and R (well, trying), I reinstalled
anaconda from here: https://www.continuum.io/downloads (for OS X Python
version 3.5) in my applications directory. At this point I am able to
launch jupiter notebook fine from the command line, and am able to edit and
save a python notebook.

*Different ways to install IRkernel:*

Now, I am not sure of the "best" way to install the IRkernel. There is
this:

*method 1:*

install.packages(c('repr', 'pbdZMQ', 'devtools'))
devtools::install_github(c('IRkernel/IRdisplay', 'IRkernel/IRkernel'))
IRkernel::installspec()


(from: https://irkernel.github.io/installation/)

*method 2:*

But there is also "R essentials" setup:
https://www.continuum.io/blog/developer/jupyter-and-conda-r

*method 3:*

And also this:
conda install -c r r-irkernel

*method 4:*

Also, I think I could install R first, and then install the IRkernal from
inside R, right?

...

*Attempts to install IRkernel:*

Ok, so I began by trying 'method 3.' The installation seems to have worked
fine, no errors came up (which is kind of strange, because I thought I had
just uninstalled R so how can I install and R package??). Anyways, now R is
appearing as an option under notebooks when I launch jupyter. But now I am
back to the original problem - R kernel crashed when I try to start it, and
I get the original error about .onLoad failed and pdbZMQ. I don't think
there is anything about jsonlite in this error.

So I open R from command line and view a list of user-installed packages
like this:


> ip <- as.data.frame(installed.packages()[,c(1,3:4)])

> rownames(ip) <- NULL

> ip <- ip[is.na(ip$Priority),1:2,drop=FALSE]

> print(ip, row.names=FALSE)

   Package Version

 base64enc   0.1-3

    digest   0.6.9

  evaluate     0.9

 IRdisplay     0.3

  IRkernel     0.6

  jsonlite  0.9.22

  magrittr     1.5

    pbdZMQ   0.2-3

        R6   2.1.2

      repr     0.7

   stringi   1.1.1

   stringr   1.0.0

      uuid   0.1-2



IRdisplay, IRkernal and jsonlite are all there.... ok - what is the next
thing I can do to try to figure out this problem?


Uninstall and reinstall jsonlite?


Thanks again!


-Alice

**Comment by takluyver** [comment]
To clarify a bit, there are two main ways to install IRkernel: using CRAN+Github (as in the instructions on http://irkernel.github.io/), or as a conda package called `r-irkernel`.

There is also a conda package of R itself, and if you install `r-irkernel` with conda, it will install and use conda's version of R. So if you already have another R installation which you want to use IRkernel with, you should follow the CRAN+Github install method to install IRkernel into that R.

The error you originally posted, and this issue as a whole, is about installing something with the CRAN+Github method, but now you seem to have tried the Anaconda route.  What problem are you encountering with that?

**Comment by avislova** [comment]
Great, that cleared things up for me and I got it working now.

Thanks a lot!

**Comment by DanielMo123** [comment]
Hello, I am having the same error as avislova had. 


I first tried to install the r-irkernel conda package but the kernel kept crashing.

KernelRestarter: restarting kernel (2/5)
Error: .onLoad failed in loadNamespace() for 'pbdZMQ', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/anaconda/lib/R/library/pbdZMQ/libs/pbdZMQ.so':
  dlopen(/anaconda/lib/R/library/pbdZMQ/libs/pbdZMQ.so, 6): Library not loaded: @rpath/libzmq.5.dylib
  Referenced from: /anaconda/lib/R/library/pbdZMQ/libs/pbdZMQ.so
  Reason: image not found
Execution halted

I then download these:

library("devtools")
install_github("IRkernel/repr")
install_github("IRkernel/IRdisplay")
install_github("IRkernel/IRkernel")

One the fourth command I got this error. I'm not to sure where to go from here. Thanks for the help.


sh: /usr/bin/gnutar: No such file or directory
sh: /usr/bin/gnutar: No such file or directory
Error in system(cmd, intern = TRUE) : error in running command
In addition: Warning message:
In utils::untar(src, exdir = target, compressed = "gzip") :
  ‘/usr/bin/gnutar -xf '/var/folders/x9/qnfj575508d7p7bp5ht75l8c0000gn/T//RtmpqmgudH/digest_0.6.10.tar.gz' -C '/var/folders/x9/qnfj575508d7p7bp5ht75l8c0000gn/T//RtmpqmgudH/devtools23343928b'’ returned error code 127

**Comment by flying-sheep** [comment]
well, apparently your R installation is broken, as `utils::untar` doesn’t work.

you can try to set the `TAR` environment variable to something that works or install `gnutar`

**Comment by DanielMo123** [comment]
Thanks for the help. I ended up installing gnutar. I ended up with another error: ERROR: compilation failed for package ‘pbdZMQ’. I ended up using conda install zeromq which finally let IRkernel install

**Comment by flying-sheep** [comment]
great!

**Comment by aseemmahajan** [comment]
Hi everyone, sorry for opening this up again, but I'm similarly having difficulty installing pbdzmq via CRAN. I end up getting the following error when R is testing whether the package can be loaded

`Error: package or namespace load failed for ‘pbdZMQ’:
 .onLoad failed in loadNamespace() for 'pbdZMQ', details:
  call: if (org != fn.libzmq.4.dylib) {
  error: missing value where TRUE/FALSE needed
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/local/lib/R/3.4/site-library/pbdZMQ’
Warning message:
In install.packages("/Users/[username]/Downloads/pbdZMQ_0.2-6.tar.gz",  :
  installation of package ‘/Users/[username]/Downloads/pbdZMQ_0.2-6.tar.gz’ had non-zero exit status`

I get the same error from CRAN and when trying to install the ".tar.gz" file manually. (For reference, I have zeromq 4.2.2 installed along with the latest version of R.) Any suggestions without reverting to conda? Thanks.

**Comment by aseemmahajan** [comment]
``Error: package or namespace load failed for ‘pbdZMQ’: .onLoad failed in loadNamespace() for 'pbdZMQ', details: call: if (org != fn.libzmq.4.dylib) { error: missing value where TRUE/FALSE needed Error: loading failed Execution halted ERROR: loading failed
removing ‘/usr/local/lib/R/3.4/site-library/pbdZMQ’ Warning message: In install.packages("/Users/[username]/Downloads/pbdZMQ_0.2-6.tar.gz", : installation of package ‘/Users/[username]/Downloads/pbdZMQ_0.2-6.tar.gz’ had non-zero exit status`
`

**Comment by flying-sheep** [comment]
plase use

````markdown
```r
<code>
```
````

**Comment by aseemmahajan** [comment]
Sorry about that!
```r
Error: package or namespace load failed for ‘pbdZMQ’:
 .onLoad failed in loadNamespace() for 'pbdZMQ', 
details: call: if (org != fn.libzmq.4.dylib) { error: missing value where TRUE/FALSE needed 
Error: loading failed Execution halted ERROR: loading failed
removing ‘/usr/local/lib/R/3.4/site-library/pbdZMQ’ 
Warning message: 
In install.packages("/Users/[username]/Downloads/pbdZMQ_0.2-6.tar.gz", :
 installation of package ‘/Users/[username]/Downloads/pbdZMQ_0.2-6.tar.gz’ had non-zero exit status
```
In any case, I finally got this to work by removing the most recent version of ZeroMQ, which gave `fn.libzmq.5.dylib` and instead linked to ZeroMQ@4.0 which gave `fn.libzmq.5.dylib`

**Comment by flying-sheep** [comment]
oh, cool! if you think it’s something that should be fixed upstream still, please open an issue at https://github.com/snoweye/pbdZMQ/issues
