### ISSUE TITLE
Add completion for function arguments

### ISSUE THREAD

**Issue by balta2ar** [IRkernel/IRkernel#299]
In Python notebooks I use completion for function arguments all the time. Could you please add the same here?

**Comment by flying-sheep** [comment]
what keyboard shortcut is that?

and if you know: what [message type](http://jupyter-client.readthedocs.org/en/latest/messaging.html) is it?

**Comment by balta2ar** [comment]
The shortcut is `Shift-Tab`. Sorry, I don't know its message type. But the window looks as follows:
![argument completion](http://scrin.org/i/16/04/tmpfnovzd6e5us.png)

**Comment by flying-sheep** [comment]
should be `inspect_request`

**Comment by balta2ar** [comment]
I also occasionally see in the console this:
```
[1] "Got unhandled msg_type:" "comm_open"
```

**Comment by poplav** [comment]
@balta2ar , Comm support was recently added #253.  It's likely not on the tag/version your using.

**Comment by balta2ar** [comment]
Indeed, I've just noticed in the log: `[1] "Got unhandled msg_type:" "inspect_request"`

**Comment by flying-sheep** [comment]
`inspect_request` is now handled, but still doesn’t do signatures

**Comment by kmishra9** [comment]
Following — this would make Jupyter Notebooks truly competitive w/ R Notebooks in RStudio as the lack of quick documentation support is what is holding me back from using them all the time.

**Comment by flying-sheep** [comment]
What do you propose? Currently, IRkernel finds the word under the cursor and inspects that one.

Would you say that it should instead find the innermost function call if possible? like:

```r
foo(one, two(two.one, two.two), three)
 ↑    ↑                 ↑
 |    |                 Shift-Tab here: inspects two, not two.two
 |    Shift-Tab here: inspects foo
 Shift-Tab here: also inspects foo

**Comment by kmishra9** [comment]
Ah, so if Shift-Tab finally works for documentation support (I think the implementation proposed in the diagram sounds very reasonable too) I’ll have to give it a try. I’ll report back here if I can think of any suggestions/pain points to iterate on.
