### ISSUE TITLE
Using install.packages during setup results in a warning

### ISSUE THREAD

**Issue by ejolly** [IRkernel/IRkernel#300]
```
Warning message:
In doTryCatch(return(expr), name, parentenv, handler) :
  unable to load shared object '/Library/Frameworks/R.framework/Resources/modules//R_X11.so':
  dlopen(/Library/Frameworks/R.framework/Resources/modules//R_X11.so, 6): Library not loaded: /opt/X11/lib/libSM.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Resources/modules//R_X11.so
  Reason: image not found
```
Some functionality works fine, but plotting with ggplot doesn't always work properly and the warning pops up during use of the R kernel in the notebook. 

I have xcode with developer tools already installed.
System: Macbook pro retina 2015, OSX 10.11.4 El Capitan

**Comment by janschulz** [comment]
How did you install the package? 

We don't touch any X11 stuff, so this looks more like an error which happens when a different lib was installed (or used) and has some compilation error?

**Comment by ejolly** [comment]
I just follow the directions from the [website](https://irkernel.github.io/installation/).  Here's exactly what I executed:  
1. `xcode-select --install` (which returned already installed since I had done this through the App Store at an earlier time)
2. `brew install zmq` (along with updates, which worked successfully)
3. Open R in the same terminal and ran `install.packages(c('rzmq','repr','IRkernel','IRdisplay'),
                 repos = c('http://irkernel.github.io/', getOption('repos')))` (I also tried the installing from source option, but I get the same problem
4. `IRkernel::installspec()` (I also tried the system-wide option but get the same problem)

**Comment by flying-sheep** [comment]
hmm. maybe you have to install X11? i remember having read once that it doesn’t exist by default.

does ggplot work reliably outside of the IRkernel?

**Comment by ejolly** [comment]
Yup it was an X11 issue! X11 is no longer included/supported by Apple in recent versions of OSX.

[XQuartz](http://www.xquartz.org/) in now the alternative.

**Comment by picarus** [comment]
I think the warning comes from the dialog in which you select a CRAN repo to install the packages from. In my case, I got a text output with the list of CRAN repos.

**Comment by acnash** [comment]
For what it is worth, I've just had this exact error when trying to install Bioconductor in R on an absolutely fresh MacBook Pro (first thing I've done out of the box), R version 3.5.2 and OS X 10.14.
