### ISSUE TITLE
Add a way to contibute our own functions to the execution environment

### ISSUE THREAD

**Issue by janschulz** [IRkernel/IRkernel#301]
It would be nice if the environments for the kernel and the environment for the execution are separated (from my perspective that looks to be the case) and if there is a simple "entry point" how to add functions and objects into the execution environment:

E.g. if one could do this:

```r
# in "shadows.r"
.add_to_execution_env("vignette", function(...) {...})
.add_to_execution_env("browser", function(...) {...})
.add_to_execution_env("view", function(...)
	stop("View is not (yet) supported in jupyter"))
```

This is currently over my head, maybe @flying-sheep could give me some pointers what would be needed here?

**Comment by takluyver** [comment]
We initially created an environment for user code to execute in, but it turns out that a lot of R stuff assumes that user code is running the global environment, so eventually we had to use the global environment for running user code.

**Comment by flying-sheep** [comment]
my favourite idea is (if possible) to have a namespace that always resides between package namespaces and `.GlobalEnv`, and fill it with proxy functions that just call the `base` functions we want to shadow. while the kernel is running, we replace them.

**Comment by janschulz** [comment]
I think the "env between packages and globalenv" is what RStudio does (AGPL...): 

https://github.com/rstudio/rstudio/blob/374557bdaf4423c016f41b6a43ffb2e9854fc862/src/cpp/r/R/Tools.R#L16

Exampleusage: : https://github.com/rstudio/rstudio/blob/374557bdaf4423c016f41b6a43ffb2e9854fc862/src/cpp/r/R/Options.R#L17
