### ISSUE TITLE
set cran mirror for the session

### ISSUE THREAD

**Issue by janschulz** [IRkernel/IRkernel#306]
Currently `install.packages` raises an error when called without explicitly setting a cran mirror. I would like to propose that we set one for the user, namely `https://cloud.r-project.org/`, which seems to redirect based on your current geo location: https://cran.r-project.org/mirrors.html

Setting should only happen if the users hasn't set a mirror in the profile file...

**Comment by janschulz** [comment]
Here is our FAQ entry which would become obsolete: http://irkernel.github.io/faq/

**Comment by flying-sheep** [comment]
how should we go about this?

check if `identical(getOption('repos'), c(CRAN = '@CRAN@'))` and set it then [here](https://github.com/IRkernel/IRkernel/blob/cb7fd617fda7959f0855623a2529d36bd7c93d45/R/execution.r#L308-L326)?

**Comment by janschulz** [comment]
This is what RStudio does:

https://github.com/rstudio/rstudio/blob/f337647969e2c02394d4dac06212aa8501777025/src/cpp/r/R/Tools.R#L484-L520
```R
.rs.addFunction( "setCRANRepos", function(reposUrl)
{
  local({
      r <- getOption("repos");
      # attribute indicating the repos was set from rstudio prefs
      attr(r, "RStudio") <- TRUE
      r["CRAN"] <- reposUrl;
      options(repos=r)
    })
})

.rs.addFunction( "setCRANReposAtStartup", function(reposUrl)
{
   # check whether the user has already set a CRAN repository
   # in their .Rprofile
   repos = getOption("repos")
   cranMirrorConfigured <- !is.null(repos) && repos != "@CRAN@"

   if (!cranMirrorConfigured)
      .rs.setCRANRepos(reposUrl)
})


.rs.addFunction( "isCRANReposFromSettings", function()
{
   !is.null(attr(getOption("repos"), "RStudio"))
})


.rs.addFunction( "setCRANReposFromSettings", function(reposUrl)
{
   # only set the repository if the repository was set by us
   # in the first place (it wouldn't be if the user defined a
   # repository in .Rprofile or called setRepositories directly)
   if (.rs.isCRANReposFromSettings())
      .rs.setCRANRepos(reposUrl)
})
```

Lets just do something similar in a new `init_session()`?

**Comment by janschulz** [comment]
PR incoming...

**Comment by flying-sheep** [comment]
> `!is.null(repos) && repos != "@CRAN@"`

isn’t this wrong if `length(repos) > 1`? i’d use `identical`…

**Comment by janschulz** [comment]
will switch...
