### ISSUE TITLE
libbz2-1.dll missing, can't start Jupyter notebook with R kernel

### ISSUE THREAD

**Issue by Diego-MX** [IRkernel/IRkernel#309]
Hey there kerneleers,
I'm not able to start a notebook with R engine.  I'm running Jupyter from an Anaconda install in Windows.  The error is an _Rterm.exe System Error_ windows and reads the following:  

    The program can't start because libbz2-1.dll is missing from your
    computer. Try reinstalling the program to fix the problem. 

I looked into reinstalling _libbz2-1.dll_, although I must say it looked risky.  So I thought to check in here first.  
Thank you for your help,  let me know if I can provide specific information from my install.  
Regards.

**Comment by takluyver** [comment]
I don't think we've ever seen that one before. How did you install R? Can you use R outside Jupyter?

**Comment by Diego-MX** [comment]
Thanks.  
That's a good question.  I have a local installation and an Anaconda one as well, and I was trying to localize everything at Anaconda's. 
I did notice that R runs fine (and its _R.home()_ is Anaconda's), but RStudio doesn't (also recently linked to Anaconda's install).

**Comment by Diego-MX** [comment]
Guys, I think this issue had to do with R rather than the kernel.  
I reinstalled R with `conda install -c r r` and it got fixed.  
Thank you for your help.

**Comment by takluyver** [comment]
You're welcome :-)

**Comment by tentrillion** [comment]
I am experiencing this problem after completely wiping an anaconda R distribution and reinstalling both anaconda and r-essentials.  This is on a computer that has never seen another R installation other than the anaconda one.

**Comment by yakovkeselman** [comment]
I searched for the library inside Anaconda, and found it in the first directory below. I added both to the PATH Windows variable, and it worked.

C:\Anaconda3\Library\mingw-w64\bin;C:\Anaconda3\Library\mingw-w64\lib;

**Comment by GusHebblewhite** [comment]
Hi all

I just got this error after installing r into a new conda environment (`conda create -n r-env -c r r-essentials` followed by `IRkernel::installspec()` to make the kernel accessible to my root environment).

Installing r (`conda install r`) into my root environment seemed to fix it.

I'm not familiar enough with how things should work to know if this is expected behavior, but I thought this comment might help anyone who is facing the same problem.

**Comment by nkutbw** [comment]
- run `jupyter kernelspec list` in the shell to find which kernel is to be fixed
- run `jupyter kernelspec remove your_kernelname` to delete it
- run `conda activate your_env`  and open the R console
- run `IRkernel::installspec(name = 'ir336', displayname = 'R 3.3.6')` with your custom name to reinstall a R kernel into the jupyter

**Comment by khanzanbaz123** [comment]
> 

thanks a ton
