### ISSUE TITLE
a missing detail in installation procedure ?

### ISSUE THREAD

**Issue by stonebig** [IRkernel/IRkernel#31]
Hi,

Looking more closely the error messages when installing on windows, I notice this one

```
> install_github('armstrtw/rzmq', pull=8, ref=NULL)
Erreur : Please install jsonlite package
```

it seems to suggest an added step in installation

```
install_github("jsonlite")
(or ?)
install_github("jeroenooms/jsonlite")
```

(apparently, it's IRKernel, that wants it )

```
importFrom(jsonlite,fromJSON)
```

so ...

```
install_github("jeroenooms/jsonlite")
```

.... and crash 

```
`      -----------------------------------
* installing *source* package 'jsonlite' ...
Warning: running command 'sh ./configure.win' had status 127
ERROR: configuration failed for package 'jsonlite'
* removing 'C:/Users/famille/AppData/Local/Temp/Rtmp0kndNo/Rinstd2c505d1de/jsonl
ite'
      -----------------------------------
ERROR: package installation failed
Erreur : Command failed (1)
```

Just in case, I posted the question on jsonlite project
https://github.com/jeroenooms/jsonlite/issues/28

**Comment by stonebig** [comment]
Happy new yeaR 2015 !
Did someone came to the rescue to provide R Windows Binary packages for IRkernel ?

**Comment by takluyver** [comment]
Doesn't look like it: http://cran.r-project.org/web/packages/rzmq/index.html

**Comment by armstrtw** [comment]
CRAN needs static windows libs for zmq to do this (compiled w/ the mingw stack they use for R-windows).
