### ISSUE TITLE
Kernel status messages should be sent before & after each shell request

### ISSUE THREAD

**Issue by takluyver** [IRkernel/IRkernel#311]
We currently only send them on execution. I think the spec wasn't clear when we first wrote the code, but this was decided in message spec version 5:
http://jupyter-client.readthedocs.io/en/latest/messaging.html#kernel-status

This would be a relatively easy task if someone is looking to start contributing.

From jupyter/jupyter-js-services#139

**Comment by janschulz** [comment]
@parente, @takluyver Isn't this closed with the merge of #312?

**Comment by takluyver** [comment]
Yep, thanks.

**Comment by rwhorman** [comment]
@takluyver @janschulz  any outlook on a new release incorporating this fix?  we are using jupyter-js-services against R kernels and this makes it rather troublesome to use.

**Comment by janschulz** [comment]
IMO we could send IRdisplay to CRAN and then IRKernel.

**Comment by dockter-84** [comment]
Yes,  I'm interested in incorporating the fix, too.

**Comment by rwhorman** [comment]
@janschulz seems good. so how does this progress to closing on a new release? need to vote somewhere and slip bitcoins to somebody?  ;-)

**Comment by rwhorman** [comment]
@flying-sheep any comment on getting a release?

**Comment by flying-sheep** [comment]
i seem to be a bit inactive in te last weeks, right? :neutral_face: 

well, @janschulz has created milestones for both the kernel and IRdisplay. i’ll see if i get IRdisplay submitted to CRAN this weekend

**Comment by rwhorman** [comment]
@flying-sheep  how did things work out on the weekend? Are we rolling?

**Comment by flying-sheep** [comment]
sorry, no

btw.: i’d like to get IRkernel/IRdisplay#19 fixed first.

**Comment by rwhorman** [comment]
@flying-sheep @janschulz  so now we're waiting on this one? IRkernel/IRdisplay#20

**Comment by flying-sheep** [comment]
i think we’re basically waiting on IRkernel/IRdisplay#33 and IRkernel/IRkernel#368.

it’s important to get this nailed down before we publish (make the packages’ responsibility clear)
