### ISSUE TITLE
Output tables with factors correctly

### ISSUE THREAD

**Issue by valentas-kurauskas** [IRkernel/IRkernel#316]
Unless I add stringsAsFactors = TRUE, the output of

``data.frame(x=c("aa", "bb"), y=c(1,2))``

shows 1 and 2 for x, instead of "aa" and "bb".

**Comment by janschulz** [comment]
This is https://github.com/IRkernel/repr/issues/47

**Comment by janschulz** [comment]
And it's addressed in repr: `devtools::install_github("irkernel/repr")`

**Comment by valentas-kurauskas** [comment]
Thanks a lot @janschulz.

**Comment by valentas-kurauskas** [comment]
`devtools::install_github("irkernel/repr")` fixes the factor issue, but seems to introduce a new one: integers in displayed tables are converted to floats (before the update previously they were not).

`data.frame(a=c(1,2), b=rep(sqrt(2),2))`

    | a | b 
---|---|---
1 | 1.000000 | 1.414214
2 | 2.000000 | 1.414214

**Comment by flying-sheep** [comment]
could you file an issue in the repr repository for that?

i bet this has to do with the “upcasting” row extraction thing. hmm. the thing i though i did before those factor issues arised was extracting 1, 2 or 4 matrix/dataframe chunks (depending on how much limiting has to be done) and converting that to a character matrix.

why don’t we do that anymore? it should cleanly handle everything without any single-row-extractions.

**Comment by janschulz** [comment]
And we need tests for all types...
