### ISSUE TITLE
Printing issue on OS X

### ISSUE THREAD

**Issue by ColCarroll** [IRkernel/IRkernel#317]
On a new notebook, it looks like categorical variables aren't being formatted correctly:

<img width="541" alt="screen shot 2016-05-09 at 9 52 11 am" src="https://cloud.githubusercontent.com/assets/2295568/15115200/d78b395e-15cb-11e6-9355-aef6999150af.png">

`print(head(iris))` works as expected (though looks like this is not html output).    I also see expected output if I use a notebook on tmpnb.org.

I am using R 3.2.5,  jupyter 4.1.0, and followed README install instructions this morning (so IRKernel 0.5, IRdisplay 0.3, repr 0.6).

**Comment by ColCarroll** [comment]
If it helps to narrow things down, comparing `sessionInfo()` on tmpnb.org and my local install, I have newer versions of:

- `tools` (3.2.5 vs 3.2.2)
- `jsonlite` (0.9.19 vs 0.9.17)
- `digest` (0.6.9 vs 0.6.8)
- `repr` (0.6 vs 0.3)
-  `evaluate` (0.9 vs 0.8)

**Comment by ColCarroll** [comment]
Looks like #316  is related

**Comment by janschulz** [comment]
This is https://github.com/IRkernel/repr/issues/47

**Comment by flying-sheep** [comment]
Fixed in @bd5e9b6a8499afe8155e55b3a6453b302f36f7d3

cc @janschulz @karldw
