### ISSUE TITLE
Use plain text display in the terminal

### ISSUE THREAD

**Issue by mikecroucher** [IRkernel/IRkernel#319]
In R terminal: 

    > c(1,2,3)
    [1] 1 2 3

In the notebook, the leading [1] is removed. Is there an option to make it appear exactly as it does in the R terminal?

**Comment by janschulz** [comment]
This is out "rich display": you can remove that with `options(jupyter.rich_display=FALSE), but that also removes rich (=html) display for dataframes.

**Comment by janschulz** [comment]
I just added this: https://github.com/IRkernel/repr/issues/52

**Comment by janschulz** [comment]
I'm closing this here, please subscribe in https://github.com/IRkernel/repr/issues/52

**Comment by flying-sheep** [comment]
actually idk why in the terminal it shouldn’t fall back to the text display

**Comment by janschulz** [comment]
Unfortunately, there is no way to know in the kernel what the frontend is :-(

**Comment by takluyver** [comment]
That shouldn't matter in this case, though. The plain text representation should be sent, and the terminal should use that. Is it not? The original issue was about displaying in the notebook.

**Comment by janschulz** [comment]
The original issue is IMO not talking about jupyter in a kernel, but plain R in a terminal:

> In the **notebook**, the leading `[1]` is removed. Is there an option to make it appear exactly as it does in the **R terminal**?

I've never tried the terminal with an R kernel, but if the terminal cannot display html, it should just display plain text (which apart from plots is sent). The only shortcoming could b plots, which would need some terminal support as we don't open a viewer in the kernel (not sure how (or if) python does it)

**Comment by takluyver** [comment]
The terminal frontend can be configured to run an image viewer program to display image output, but I don't think it's set up to by default.

**Comment by janschulz** [comment]
```
λ jupyter console --kernel ir32
Jupyter Console 4.1.1


In [1]: print("hallo")
[1] "hallo"

In [2]: plot(1:3)

```

-> the console displays plain text but as plots don't send some text, nothing for plots :-(

**Comment by janschulz** [comment]
On the other hand, this happens: for the qtconsole:

```
λ jupyter qtconsole --kernel ir32
Error in tryCatch(evaluate(request$content$code, envir = .GlobalEnv, output_handler = oh,  :
  object 'handle_error' not found
Calls: <Anonymous> ... <Anonymous> -> handle_shell -> <Anonymous> -> tryCatch
Execution halted
[JupyterQtConsoleApp] KernelRestarter: restarting kernel (1/5)
[JupyterQtConsoleApp] WARNING | kernel restarted
Error in tryCatch(evaluate(request$content$code, envir = .GlobalEnv, output_handler = oh,  :
  object 'handle_error' not found
Calls: <Anonymous> ... <Anonymous> -> handle_shell -> <Anonymous> -> tryCatch
Execution halted
[JupyterQtConsoleApp] WARNING | kernel died: 3.000171661376953
[JupyterQtConsoleApp] KernelRestarter: restarting kernel (2/5)
[JupyterQtConsoleApp] WARNING | kernel restarted
Error in tryCatch(evaluate(request$content$code, envir = .GlobalEnv, output_handler = oh,  :
  object 'handle_error' not found
Calls: <Anonymous> ... <Anonymous> -> handle_shell -> <Anonymous> -> tryCatch
Execution halted
[JupyterQtConsoleApp] WARNING | kernel died: 3.010172128677368
[JupyterQtConsoleApp] KernelRestarter: restarting kernel (3/5)
[JupyterQtConsoleApp] WARNING | kernel restarted
Error in tryCatch(evaluate(request$content$code, envir = .GlobalEnv, output_handler = oh,  :
  object 'handle_error' not found
Calls: <Anonymous> ... <Anonymous> -> handle_shell -> <Anonymous> -> tryCatch
Execution halted
```

**Comment by janschulz** [comment]
Ok, #318 fixes the above, but now I get a popup from qtconsole this when I quit ( `q()`) the kernel:

```
---------------------------
Error starting QtConsole
---------------------------
Traceback (most recent call last):
  File "C:\portabel\miniconda\lib\site-packages\qtconsole\base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "C:\portabel\miniconda\lib\site-packages\qtconsole\jupyter_widget.py", line 184, in _handle_execute_reply
    super(JupyterWidget, self)._handle_execute_reply(msg)
  File "C:\portabel\miniconda\lib\site-packages\qtconsole\frontend_widget.py", line 484, in _handle_execute_reply
    self._process_execute_ok(msg)
  File "C:\portabel\miniconda\lib\site-packages\qtconsole\frontend_widget.py", line 805, in _process_execute_ok
    if not self._process_execute_payload(item):
  File "C:\portabel\miniconda\lib\site-packages\qtconsole\jupyter_widget.py", line 319, in _process_execute_payload
    handler(item)
  File "C:\portabel\miniconda\lib\site-packages\qtconsole\jupyter_widget.py", line 492, in _handle_payload_exit
    self._keep_kernel_on_exit = item['keepkernel']
KeyError: 'keepkernel'

---------------------------
OK   
---------------------------
```

Do we forget to send this?

**Comment by janschulz** [comment]
Seems so: http://jupyter-client.readthedocs.io/en/latest/messaging.html#payloads-deprecated

**Comment by janschulz** [comment]
see https://github.com/IRkernel/IRkernel/pull/314 -> third commit for the fix...

**Comment by flying-sheep** [comment]
> In the **notebook**, the leading `[1]` is removed. Is there an option to make it appear exactly as it does in the **R terminal**?

oh damn so i totally misread OP and confused everyone.

**Comment by janschulz** [comment]
So, closing again :-)
