### ISSUE TITLE
rzmq_issue

### ISSUE THREAD

**Issue by bigpas** [IRkernel/IRkernel#32]
Hi,

I am on MacOs 10.9, I'm not  able to install "rzmq", 
I got this error message

```
* installing to library ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library’
* installing *source* package ‘rzmq’ ...
** package ‘rzmq’ successfully unpacked and MD5 sums checked
** libs
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c interface.cpp -o interface.o
interface.cpp:22:10: fatal error: 'zmq.hpp' file not found
#include <zmq.hpp>
         ^
1 error generated.
make: *** [interface.o] Error 1
ERROR: compilation failed for package ‘rzmq’
* removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/rzmq’
```

thanks

**Comment by OrganicIrradiation** [comment]
I am having the same issue with Mac OS X 10.10.2.

Starting with a fresh install of Homebrew, I installed python, python3, r, and zmq:

    brew install python python3 r zeromq

I am trying to install [IRkernel](https://github.com/takluyver/IRkernel), which requires that rzmq be installed.  However, I get a fatal error with "'zmq.h' file not found" when I run the following:

    install.packages("devtools")
    install.packages('RCurl')
    library(devtools)
    install_github('armstrtw/rzmq')

I tried relinking zmq with ```brew link zeromq' and I tried the solution suggested by rgbkrk; however, neither fixed my problem.  Any suggestions?

**Comment by rgbkrk** [comment]
Have you also done `brew install czmq zmq`?

**Comment by OrganicIrradiation** [comment]
@rgbkrk Yep, also have czmq installed via brew, but still get the same error:
```
* installing *source* package ‘rzmq’ ...
** package ‘rzmq’ successfully unpacked and MD5 sums checked
** libs
clang++ -std=c++11 -I/usr/local/Cellar/r/3.1.2_1/R.framework/Resources/include -DNDEBUG -I../inst/cppzmq -I/usr/local/opt/gettext/include -I/usr/local/opt/readline/include -fPIC -D__ACCELERATE__ -c interface.cpp -o interface.o
interface.cpp:22:10: fatal error: 'zmq.h' file not found
#include <zmq.h>
^
```

I've also tried copying zmq.h to ```/usr/local/include/``` manually and with:
```
brew tap bertjwregeer/compat
brew install cppzmq
```

Neither has fixed the problem.

**Comment by OrganicIrradiation** [comment]
Turns out that /usr/local/include was not in the clang++ search path.  This can be confirmed by running ```clang++ -E -x c++ - -v < /dev/null``` and looking at the printed search paths.  Thanks to @ccwang002 for pointing this out in https://github.com/takluyver/IRkernel/issues/50. To fix this, I ran ```xcode-select --install``` to install the command line tools.

Just to summarize, here were the steps necessary to get IRkernel setup on this machine:
```
# Install Xcode Command Line Tools if not already installed
$ xcode-select --install

# Install python, r, and zmq via homebrew
$ brew install python python3 r zeromq

# Install iPython/Jupyter
$ pip install ipython[all]

# Install IRkernel
$ r
> install.packages("devtools")
> install.packages('rzmq')
# Need RCurl for install_github
> install.packages('RCurl')
> library(devtools)
> install_github("takluyver/IRdisplay")
> install_github("takluyver/IRkernel")
# Only if you have IPython 3 or above installed:
> IRkernel::installspec()
```
