### ISSUE TITLE
IRkernel 0.5 in on irkernel.github.io

### ISSUE THREAD

**Issue by alexvorobiev** [IRkernel/IRkernel#320]
I tried updating IRkernel following the official instructions on http://irkernel.github.io/installation/ and got v.0.5 (I am on Linux). Is there a reason why the latest release 0.6.1 is not in the repository?

**Comment by janschulz** [comment]
We are currently trying to get the packages on CRAN. Installing using `devtools::install_github("irkernel/IRkernel")` (and `"irkernel/repr"` and `"irkernel/IRdisplay"`) works great now we don't have any native dependencies anymore which ar enot n CRAN.

**Comment by janschulz** [comment]
I've submitted PRs to change back all install instruction to use either the version on CRAN (repr is already there) or the old `devtools::install_github("irkernel/IRkernel") (or "irkernel/repr" or "irkernel/IRdisplay"). Basically: the old install instructions are dead and we should probably remove the repo altogether...

**Comment by janschulz** [comment]
I opened https://github.com/IRkernel/irkernel.github.io/issues/30 fo the removal. The instructions should be updated in #327
