### ISSUE TITLE
Travis: add checks for different versions of repr and irdisplay

### ISSUE THREAD

**Issue by janschulz** [IRkernel/IRkernel#321]
I think we should both check for the released versions of repr and (soon...) IRdisplay in addition to the github versions.

E.g. we have to prevent wrong upload sequences like currently uploading IRkernel without IRdisplay.

**Comment by flying-sheep** [comment]
jup. how do you create separate targets with conditional code in travis?

**Comment by janschulz** [comment]
See: https://github.com/IRkernel/IRkernel/pull/314/files#diff-354f30a63fb0907d4ad57269548329e3R10
And then used here: https://github.com/IRkernel/IRkernel/pull/314/files#diff-28f1434f1467ce86d05e864f47813853R10
