### ISSUE TITLE
License...

### ISSUE THREAD

**Issue by janschulz** [IRkernel/IRkernel#322]
Currently the irkernel package declares that it is 

```
License: MIT + file LICENSE
```

I don't think that can be true as we use R packages which are GPL, so actually we distribute our code under the GPL brand...

I'm also currently looking into https://github.com/IRkernel/IRkernel/issues/301 and I want to use https://github.com/rstudio/rstudio/blob/master/src/cpp/r/R/Tools.R, but that is under AGPL (which according to the [FAQ](http://www.gnu.org/licenses/license-list.en.html#AGPLv3.0) can be combined into a complete work).

So where does that leave us? IMO: as we are "giving" our code under MIT, so everybody can do with individual code files which we have written, what they want -> so a more restrictive license like the AGPL doesn't matter for us (=maintainer/contributors) because we essentially gving our code away without asking for anything in return.

 On the other hand a different person who wants to take the code private is not allowed because someone who has copyright over the GPL parts can ask for the source code of the whole because the whole stuff is also covered under GPL? 

So for introduced code like the RStudio ones, we have to declare AGPL and add that to the individual code files and into the description?

**Comment by flying-sheep** [comment]
it is true insofar that everyone who contributed did so under MIT terms.

it might be invalid due to what you said though. if this is the case, we need to get consent from all contributors to relicense to GPL.

**Comment by janschulz** [comment]
I'm not sure: AFAIK you can use MIT code in GPL/AGPL code where it is essentially GPL covered code, so I think relicensing it under a *GPL license is already covered by MIT?

**Comment by takluyver** [comment]
AIUI, it's fine for the code in this package to be MIT licensed, and when it's distributed as a 'combined work' with GPL licensed code, the whole of that combination is distributed under the GPL. This is OK because the MIT license is GPL compatible.

I don't think anyone's very sure what the GPL means with code in dynamic languages, though, because it's written in terms of static compilation in a language like C.

**Comment by janschulz** [comment]
Alos fun:

```R
R CMD check --as-cran
* checking CRAN incoming feasibility ... NOTE
Maintainer: 'Thomas Kluyver <thomas@kluyver.me.uk>'
New submission

License components with restrictions and base license permitting such:
  MIT + file LICENSE
File 'LICENSE':
  Copyright (c) 2014, Thomas Kluyver

  Permission is hereby granted, free of charge, to any person obtaining
  a copy of this software and associated documentation files (the
  "Software"), to deal in the Software without restriction, including
  without limitation the rights to use, copy, modify, merge, publish,
  distribute, sublicense, and/or sell copies of the Software, and to
  permit persons to whom the Software is furnished to do so, subject to
  the following conditions:
  [...]
```

**Comment by takluyver** [comment]
I think that file is just the MIT license, so probably the metadata can just say 'MIT'. I probably copied some example I found.

**Comment by janschulz** [comment]
ok, removed...

**Comment by janschulz** [comment]
Ok, it gets you coming and going:

```
* checking DESCRIPTION meta-information ... NOTE
License components which are templates and need '+ file LICENSE':
  MIT
```

**Comment by takluyver** [comment]
Bahaha!

**Comment by janschulz** [comment]
Also fun:

```
Found the following (possibly) invalid URLs:
  URL: http://localhost:8888/
    From: README.md
    Status: Error
    Message: libcurl error code 7
    	Failed to connect to localhost port 8888: Connection refused
```

**Comment by takluyver** [comment]
I take it we can't trick CRAN into running a notebook server when it checks it? ;-)

**Comment by janschulz** [comment]
If this becomes a problem, I will just remove it...

**Comment by flying-sheep** [comment]
it’s very important information. if it becomes a problem, they should fix this.

it’s not the only project that did or will ever spawn a server.

**Comment by janschulz** [comment]
Fortunately, we don'T spawn a server, we can just tell "In the Notebook UI" :-)

Anyway: I implemented the whole "add our own environment" more or less without the code from RStudio (-> https://github.com/IRkernel/IRkernel/pull/324), so at least we don't have to add AGPL to the licences...

**Comment by flying-sheep** [comment]
> Also (not) fun:
> 
> ```
> [...]
> License components with restrictions and base license permitting such:
>   MIT + file LICENSE
> File 'LICENSE':
> [...]
> ```

[that’s](https://github.com/IRkernel/IRdisplay/blob/master/LICENSE) what they mean with it. it’s pretty unclear, but 1. you need to just fill in the template variables and 2. the NOTE will always appear as info for the CRAN maintainers
