### ISSUE TITLE
No rzmq binary for R 3.3.* or 3.4.*

### ISSUE THREAD

**Issue by richierocks** [IRkernel/IRkernel#326]
When following the installation instructions, [here](https://irkernel.github.io/installation/) under the current R release, 3.3.0 or R-devel (which has version 3.4.0), no `rzmq` binary is found.

```{r}
install.packages('rzmq', repos = 'http://irkernel.github.io')
## Warning in install.packages :
##   cannot open URL 'http://irkernel.github.io/bin/windows/contrib/3.3/PACKAGES.gz': HTTP status was '404 Not Found'
```

Installing from source fails for me, but installing the binary under R-3.2.5 works.

Related: https://github.com/IRkernel/IRkernel/issues/298

**Comment by janschulz** [comment]
Please don't use that anymore, just use the devtools version as in #327 until we have everything on CRAN... Sorry for the inconvenience...
