### ISSUE TITLE
Documentation for help

### ISSUE THREAD

**Issue by methodds** [IRkernel/IRkernel#332]
Hi,

is there any documentation file for using the help ``?/??`` functionality? For me it does not work properly. As an example, trying to view help files for ggplot2 results in :+1: 

```
?ggplot2

No documentation for ‘ggplot2’ in specified packages and libraries: you could try ‘??ggplot2’
```

and ``??ggplot2``
does not produce any output.

**Comment by flying-sheep** [comment]
the input is just sent to R, so this really can’t be our bug.

i guess your problem is that `ggplot2` is the package name and `ggplot` the function name.

try one of these:

```r
package?ggplot2  # help(package = 'ggplot2')
?ggplot          # help(ggplot)
```

you can learn about `?` and `??` via

```r
help(help)
help('?')
help('??')
```
