### ISSUE TITLE
The graph produced by ggplot got mismatched in label when transformed the notebook to html

### ISSUE THREAD

**Issue by MengyingLi** [IRkernel/IRkernel#334]
I don't know whether this issue has been addressed before but every time when i transformed the Jupyter notebook to HTML, the plot's labels got weird behavior as below 
![2222](https://cloud.githubusercontent.com/assets/6514708/15271050/2d8978d4-19eb-11e6-927b-407517a6e897.PNG)

**Comment by takluyver** [comment]
It's probably the issue with SVG in the HTML output - see #331 and jupyter/nbconvert#129

**Comment by MengyingLi** [comment]
Thanks! I was able to walk around the issue by using the `options`
