### ISSUE TITLE
running both grid and base-graphics system kills the kernel

### ISSUE THREAD

**Issue by randy3k** [IRkernel/IRkernel#342]
It is fine when running the same chunk of code in command line, however, running both grid and base-graphics devices kills the kernel. Interestingly, If the two commands are separated into different cells, it works again.

```r
library(ggplot2)
qplot(1:10)
plot(1:10)
```

The console says
```r
*** caught segfault ***
address 0x4, cause 'memory not mapped'

Traceback:
 1: grDevices::replayPlot(obj)
 2: repr_recordedplot_generic(obj, ".svg", FALSE, dev.cb)
 3: repr_svg.recordedplot(plotobj, attr(plotobj, ".irkernel_width"),     attr(plotobj, ".irkernel_height"))
 4: mime2repr[[mime]](plotobj, attr(plotobj, ".irkernel_width"),     attr(plotobj, ".irkernel_height"))
 5: doTryCatch(return(expr), name, parentenv, handler)
 6: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 7: tryCatchList(expr, classes, parentenv, handlers)
 8: tryCatch({    formats[[mime]] <- mime2repr[[mime]](plotobj, attr(plotobj,         ".irkernel_width"), attr(plotobj, ".irkernel_height"))}, error = handle_error)
 9: send_plot(last_recorded_plot)
10: executor$execute(msg)
11: handle_shell()
12: kernel$run()
13: IRkernel::main()
```

Mac OSX 10.11, R 3.3, master of IRKernel and IRDisplay, jupyter 4.1.0

**Comment by janschulz** [comment]
revert https://github.com/IRkernel/IRkernel/commit/24e68335eae19e098d0b55f02554f13550c7571b ? 

@randy3k Can you try `options(device = "pdf")` or `options(device = "png")` and report if the problem still happens?

**Comment by randy3k** [comment]
Oops, I forgot to mention that I have reverted 24e6833.

Both pdf and png devices produce the same segfault error.

**Comment by randy3k** [comment]
More interestingly, it works if I reverse of order
```
plot(1:10)
qplot(1:10)
```

But this doesn't work again
```
plot(1:10)
qplot(1:10)
plot(1:10)
```

**Comment by janschulz** [comment]
Is that also happening in RStudio or the default R console?

**Comment by janschulz** [comment]
Just tested it on windows: no problem n neither rstudio nor the notebook :-(

**Comment by randy3k** [comment]
More discovery,
RStudio works fine *if I run the commands one by one*. (Command line R works find anyway)

If the whole chunk is selected and executed in RStudio,
```
library(ggplot2)
qplot(1:10)
plot(1:10)
```
It shows the `plot` command result , If I click the previous plot button, it only shows an empty plot. 
Anyway, it does produce a segfault.

**Comment by randy3k** [comment]
This seems to be fixed in the latest version.

**Comment by flying-sheep** [comment]
good stuff, since i guess nobody had any idea how to even debug this
