### ISSUE TITLE
DESCRIPTION has `Version: 0.6`

### ISSUE THREAD

**Issue by mingwandroid** [IRkernel/IRkernel#344]
.. but `0.6.1` has been released. Is this deliberate?

**Comment by flying-sheep** [comment]
not at all, damn. hmm, either we create an orphan commit that only updates the version number and move the tag to point to it or we do a 0.7 release with all the changes since then.

**Comment by mingwandroid** [comment]
I think making it version `0.7` sounds safest as then there's no ambiguity.

**Comment by flying-sheep** [comment]
yes, right. we probably have quite some new stuff anyway :wink:

**Comment by poplav** [comment]
subscribing for updates

**Comment by poplav** [comment]
@flying-sheep any updates on when a `0.7` release will be out?

**Comment by flying-sheep** [comment]
generally, we’d like to fix all of [those issues](https://github.com/IRkernel/IRkernel/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.7) but the interactive stuff is elusive.

i guess we should just push those back , fix #231, call it 0.7, and put it on CRAN.

opinions, @janschulz, @takluyver?

**Comment by flying-sheep** [comment]
ping @janschulz @takluyver

**Comment by janschulz** [comment]
I'm off for the next few weeks, sorry...

**Comment by takluyver** [comment]
Sorry, I've been travelling. I think most of those issues can be bumped to a later release if it means we can get an improved version out. I'd prioritise the two there marked 'bug': #231 and #280. It sounds like there is an easy partial fix to #280 (make functions raise a clear error rather than trying something they can't do properly).

**Comment by flying-sheep** [comment]
Jan already did that in #333

**Comment by takluyver** [comment]
Scotland, Germany, and the Channel Islands so far!

OK, with the dummy functions in place, then it's just #231 that it would be nice to fix before a release.

**Comment by flying-sheep** [comment]
i hope you haven’t been in munich, else we missed a chance to meet :smile:

#231 is also hard and not our bug: https://github.com/hadley/evaluate/issues/71

**Comment by takluyver** [comment]
I did pass through Munich, on my way to Erlangen for Euroscipy. I shall remember for next time I'm going that way!

**Comment by flying-sheep** [comment]
great! the only things i know about Erlangen are from [this weird (german) song](https://www.youtube.com/watch?v=G_k20C8hOEs). and the fact that Erlang is *not* named after it (it means **Er**icson **lang**uage)

**Comment by flying-sheep** [comment]
whoops: i meant

> #231 is also hard and **not** fixable from within IRkernel: hadley/evaluate#71

**Comment by takluyver** [comment]
Apparently the cool cellars of Erlangen made it very rich selling cool beer in the summer, up until refrigeration was invented. Now you know another thing about it ;-)

**Comment by flying-sheep** [comment]
“becoming rich selling beer” seems like a good idea for time travellers

**Comment by flying-sheep** [comment]
fixed: [0.7](https://github.com/IRkernel/IRkernel/releases/tag/0.7)
