### ISSUE TITLE
Console Kernel Dies Without a Message

### ISSUE THREAD

**Issue by dpavlic** [IRkernel/IRkernel#347]
I'm having the oddest issue. I start the console kernel and want to read a tab delimited file. I do `jupyter console --kernel=ir` and then:

```
a <- read.csv('/path/to/file/file.txt', sep='\t', stringsAsFactors=FALSE)
```

After a second I get the message `kernel died, restart ([y]/n)? `. It will always fail at this point. Not the only example. `library(dplyr)` or `library(plyr)` works just fine. On the other hand, `library(xlsx)` will cause almost immediate failure.

This is on a CentOS 6 machine, R 3.2.3. 

There is no error message of any kind that comes up. 

The most baffling thing is, the R notebook will *work just fine in all these cases*. What could be the issue?

EDIT: Note that this is clearly a very strange corner case, since everything works as expected on my home Ubuntu 16.04 machine. I can't load the same csv from home, but the other ones work fine. Doing `library(xlsx)` causes similarly no problems. Any suggestions on how I could go about debugging this? The silent failure is particularly perplexing.

**Comment by flying-sheep** [comment]
first: are you using the development versions of IRdisplay and IRkernel?

you can start a notebook and connect to its kernel, then you’ll see the notebook server’s output:

```bash
jupyter notebook
```

open/create a notebook and copy the id at the end of a line like `[I 08:12:56.177 NotebookApp] Kernel started: ac7c4ae1-652a-486b-b93a-6dc4d6961d25`

```bash
jupyter console --kernel ir --existing ac7c4ae1-652a-486b-b93a-6dc4d6961d25
```

**Comment by dpavlic** [comment]
I definitely didn't specify a tag when installing, so I'd have pulled the latest master (everything installed on this machine yesterday).

So, connecting to the existing kernel gives me the same problem; here is what is interesting. When the kernel 'dies' in the console, there is _no_ log of this happening in the jupyter notebook log. Secondly, the kernel clearly hasn't died: I can continue to use the kernel in the notebook perfectly fine and without issue. Only after I select y or n at `kernel died, restart ([y]/n)?` in the console will the kernel restart or die in the notebook.

**Comment by takluyver** [comment]
I suspect it may be to do with heartbeats, because the notebook doesn't use them. If something stops the kernel responding to the heartbeat, clients that check that may decide that it's dead.

I am still trying to remove the need for a kernel heartbeat entirely. Unfortunately, [the proposal](https://github.com/jupyter/enhancement-proposals/pull/14) got bogged down in competing use cases and kind of stalled.

**Comment by flying-sheep** [comment]
so we have a vampire kernel? no heartbeat but ![kraken-its-alive](https://cloud.githubusercontent.com/assets/291575/15713161/8acdb6e4-2815-11e6-8ae8-b3df74dfc81e.jpg)

**Comment by dpavlic** [comment]
The story gets weirder.

I have set up a remote kernel via [remote_ikernel](https://bitbucket.org/tdaff/remote_ikernel). I therefore run the remote kernel from my local jupyter console. **NO ERROR**. Jupyter console versions are identical, although jupyter itself is 4.0.6 on the remote, and 4.1.0 locally. I will try to update the remote jupyter, but needless to say this is very odd.

**Comment by dpavlic** [comment]
Closing because the issue is lies with jupyter 4.0.6. Updating jupyter to 4.1.0 fixes the problem and all is well in the world.
