### ISSUE TITLE
warning message for raster rendering

### ISSUE THREAD

**Issue by MengyingLi** [IRkernel/IRkernel#353]
I tried the exact the same thing in Rstudio and it did not give me an error but in IRkernel it gave me a warning as `Warning message:
In grid.Call.graphics(L_raster, x$raster, x$x, x$y, x$width, x$height, : raster rendering is not implemented for this device`

The code is as below:
```
pp <- function (n,r=4) {
 x <- seq(-r*pi, r*pi, len=n)
 df <- expand.grid(x=x, y=x)
 df$r <- sqrt(df$x^2 + df$y^2)
 df$z <- cos(df$r^2)*exp(-df$r/6)
 df
}
p <- ggplot(pp(20), aes(x=x,y=y))

p + geom_tile(aes(fill = z))
```

**Comment by janschulz** [comment]
I can reproduce that error message in RStudio with
```R
> pictex("NUL")
> pp <- function (n,r=4) {
+     x <- seq(-r*pi, r*pi, len=n)
+     df <- expand.grid(x=x, y=x)
+     df$r <- sqrt(df$x^2 + df$y^2)
+     df$z <- cos(df$r^2)*exp(-df$r/6)
+     df
+ }
> p <- ggplot(pp(20), aes(x=x,y=y))
> 
> p + geom_tile(aes(fill = z))
Warning message:
In grid.Call.graphics(L_raster, x$raster, x$x, x$y, x$width, x$height,  :
  raster rendering is not implemented for this device
> 
```

-> This looks like a not up to date version of master (master has changed the default device again)

-> Can you reinstall from master and report back if that removes the error? If not, please add information about your system (OS, ...) and whether you are running master (and what commit) or a released version.

**Comment by MengyingLi** [comment]
thanks! after i reinstalled it from the master the error is gone. My rstudio did not produce the error message though...
![irtile](https://cloud.githubusercontent.com/assets/6514708/16020676/f960879c-3163-11e6-8225-648536396e54.PNG)
