### ISSUE TITLE
Can I specify the path of the kernel when installing using "IRkernel::installspec()"

### ISSUE THREAD

**Issue by luborliu** [IRkernel/IRkernel#355]
Hi,

I am still trying to figure out my issue in https://github.com/IRkernel/IRkernel/issues/313#issuecomment-224751199

The potential working way would be to download and install R packages from CRAN instead of using conda. But now I met a new issue which should be solvable. In the dockerfile, when it comes to installation of the IRkernel, the kernel will be installed in the path of "root" which is not accessible by other users. 

```
Step 13 : RUN Rscript -e "IRkernel::installspec()"
 ---> Running in 0b6f1f3c26a5
[InstallKernelSpec] Installed kernelspec ir in /root/.local/share/jupyter/kernels/ir
```

So is there a way to add some parameters in installspec() to let the kernel be installed in `"/usr/local/share/jupyter/kernels/ir"`?

**Comment by takluyver** [comment]
```r
IRkernel::installspec(user = FALSE)
```

This is [in the install page](http://irkernel.github.io/installation/) ;-)

**Comment by luborliu** [comment]
Oh right. Sorry for this issue.. I will close it.
