### ISSUE TITLE
Show all the columns of table

### ISSUE THREAD

**Issue by Jiang-Li** [IRkernel/IRkernel#356]
When I use head() to review a table with many columns, only some of the columns can be displayed. I know how to show all the columns in Python on Jupyter. How can I do the same thing for R? Thanks.

**Comment by janschulz** [comment]
Have a look at these two options:

```R
option(repr.matrix.max.rows = 100)
option(repr.matrix.max.cols = 30)
```

**Comment by Jiang-Li** [comment]
Can I use ipython -- to set it? If so how can I do? Thanks.

**Comment by janschulz** [comment]
That is R Code, just execute it before the rest of the code. Or add it to your R profile.

**Comment by Jiang-Li** [comment]
OK the options() works. Thx!

**Comment by Quetzalcohuatl** [comment]
A small tidbit: The commands should be
`options(repr.matrix.max.rows = 100)`
`options(repr.matrix.max.cols = 30)`

**Comment by qbao96xb** [comment]
I would rather suggest that you should use ```collect``` after ```head```
