### ISSUE TITLE
Error installing on Debian testing

### ISSUE THREAD

**Issue by pachevalier** [IRkernel/IRkernel#357]
I've tried to install IRKernel in Debian testing. I've got the following error : 

> install.packages("rzmq")
Installation du package dans ‘/home/debian/R/x86_64-pc-linux-gnu-library/3.3’
(car ‘lib’ n'est pas spécifié)
essai de l'URL 'https://cran.univ-paris1.fr/src/contrib/rzmq_0.7.7.tar.gz'
Content type 'application/x-gzip' length 16246 bytes (15 KB)
==================================================
downloaded 15 KB

sh: 0: getcwd() failed: No such file or directory

**Comment by janschulz** [comment]
Where did you get these instructions from? `rzmq` isn't been used in irkernel for ages :-)

You can find updated instructions in the README: https://github.com/IRkernel/IRkernel#installation

**Comment by pachevalier** [comment]
Thanks. It works and its great !
