### ISSUE TITLE
Error printing data frame with ordered factor

### ISSUE THREAD

**Issue by seisdrum** [IRkernel/IRkernel#360]
Printing a data frame with a column containing an ordered factor results in an error:
```r
df <- data.frame(a=factor(1:10, ordered=T))
head(df)
```
```
Error in vapply(df, class, FUN.VALUE = character(1L)): values must be length 1,
 but FUN(X[[1]]) result is length 2
Traceback:

1. tryCatch({
 .     for (mime in getOption("jupyter.display_mimetypes")) {
 .         r <- mime2repr[[mime]](obj)
 .         if (!is.null(r)) 
 .             data[[mime]] <- r
 .     }
 . }, error = handle_error)

  a
1 1
2 2
3 3
4 4
5 5
6 6
```

**Comment by janschulz** [comment]
Which versions are you on?

In my setup (basically repr and irkernel from master, windows), this doesn't happen. Can you test with repr from master?

**Comment by seisdrum** [comment]
Cool, thank you! Installing the current master of repr seems to have done the trick. Sorry about that. I tried installing the current IRkernel master but was unaware of the repr package.
