### ISSUE TITLE
error when install on windows

### ISSUE THREAD

**Issue by econwang** [IRkernel/IRkernel#361]
Thanks for providing this package, I follow the installation instruction, but when run
devtools::install_github('IRkernel/IRkernel')
get error:
```
*** installing help indices
Error in gsub("&", "&amp;", x, fixed = TRUE) :
  '<a5> <33>) about IRkernel.'
* removing 'C:/Program Files/R/R-3.2.2/library/IRkernel'
: Command failed (1)
```

**Comment by flying-sheep** [comment]
my mistake, it’s [this line](https://github.com/IRkernel/IRkernel/commit/c2570c2ee046244298fe5adf0b659247d5f3d0d8#diff-24b6c97449375f7c7f06960b305916caR1)

we’ll have to change it to use `\eqn{\ge 3}`

**Comment by flying-sheep** [comment]
fixed in 2b656708a51ad675209a10ca089cf2cddf8ccc7f

**Comment by econwang** [comment]
still does not work

**Comment by flying-sheep** [comment]
details?

**Comment by econwang** [comment]
the same:
```
*** installing help indices
Error in gsub("&", "&amp;", x, fixed = TRUE) :
  '<a5> <33>) about IRkernel.'
* removing 'C:/Program Files/R/R-3.2.2/library/IRkernel'
: Command failed (1)
```

**Comment by flying-sheep** [comment]
sorry, i forgot to also update the `.Rd` files. please try again, it’ll work.

**Comment by econwang** [comment]
thanks, now it works
