### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by flying-sheep** [IRkernel/IRkernel#362]
a recent change to jupyter_kernel_tests (i think) broke everything.

also when running the tests locally, somehow pbdZMQ’s `.onLoad` doesn’t get executed for me. therefore:

1. [`.zmqopt_init()`](https://github.com/snoweye/pbdZMQ/blob/3de2ae73053869c6c84c77cf8169ed62c9f0d6ba/R/windows/zzz.r#L16) isn’t run
2. so `.pbd_env$ZMQ.PO` is NULL
3. therefore [this `rep()` invocation](https://github.com/IRkernel/IRkernel/blob/e4ba868a714f6bdffc7d677a1dd1f6575422632c/R/kernel.r#L335) returns NULL.
4. the `zmq.poll` fails

why does this only happen in `test_ir.py` and not when starting a kernel in another way?

does this happen for anyone else?

**Comment by janschulz** [comment]
Here are the test failures:

```
======================================================================
ERROR: test_display_data (__main__.OptionsDependendTests) (code='"a"')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/miniconda/envs/test-environment/lib/python3.5/site-packages/jupyter_kernel_test/__init__.py", line 230, in test_display_data
    self.assertIn(sample['mime'], output_msgs[0]['content']['data'])
  File "/Users/travis/miniconda/envs/test-environment/lib/python3.5/unittest/case.py", line 1076, in assertIn
    if member not in container:
TypeError: unhashable type: 'dict'
======================================================================
ERROR: test_display_data (__main__.OptionsDependendTests) (code='1:3')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/miniconda/envs/test-environment/lib/python3.5/site-packages/jupyter_kernel_test/__init__.py", line 230, in test_display_data
    self.assertIn(sample['mime'], output_msgs[0]['content']['data'])
  File "/Users/travis/miniconda/envs/test-environment/lib/python3.5/unittest/case.py", line 1076, in assertIn
    if member not in container:
TypeError: unhashable type: 'dict'

```

These are IMO problems on the jupyter_kernel_tests side: if dic it not hashable, it should be compared differently.

```
FAIL: test_display_data (__main__.OptionsDependendTests) (code='options(jupyter.rich_display = FALSE);cat("a")')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/miniconda/envs/test-environment/lib/python3.5/site-packages/jupyter_kernel_test/__init__.py", line 229, in test_display_data
    self.assertEqual(output_msgs[0]['msg_type'], 'display_data')
AssertionError: 'stream' != 'display_data'
- stream
+ display_data
```

This is IMO a problem on our side: `cat("a")` should print to stdout and therefor should return via the stream and not as a display_data. The text should be `code='options(jupyter.rich_display = FALSE);"a"' (without the `cat()`)

@takluyver Any idea about the first two errors?

**Comment by takluyver** [comment]
Compare our samples for code_display_data [here](https://github.com/jupyter/jupyter_kernel_test/blob/master/test_ipykernel.py#L77) with those in the example [here](https://github.com/jupyter/jupyter_kernel_test/blob/7283c8c6213718e5a4f32cfe109613afed859271/test_ipykernel.py#L77).

The 'mime' field should be a string of a mimetype, not a dictionary. The test does not currently check the content that's sent to be displayed, only that something with the right mimetype is sent. We could add content checking to that test in JKT, but for now IRkernel needs to pass the data in the form JKT expects.

**Comment by janschulz** [comment]
ok

**Comment by janschulz** [comment]
I added the fixed tests to https://github.com/IRkernel/IRkernel/pull/365, mainly because that PR also already changed tests and I didn't want to do a rebase of one into the other :-/

**Comment by janschulz** [comment]
> does this happen for anyone else?

I only run the kernel tests via the CI services (I don't want to change the R kernel I installed and the kernel tests expect a installed kernel...)

**Comment by flying-sheep** [comment]
OK, thank you for this! i’ll open an extra issue for the mac errors
