### ISSUE TITLE
IRKernel for Revo64

### ISSUE THREAD

**Issue by blahster** [IRkernel/IRkernel#364]
How do I use Revolution Analytics' [Revo64](/usr/lib64/Revo-7.3.0/bin/Revo64) with Jupyter?
When I try `library("RevoScaleR")`, it fails with
```
Error in library("RevoScaleR"): there is no package called 'RevoScaleR'
Traceback:

1. library("RevoScaleR")
2. stop(txt, domain = NA)
```

**Comment by janschulz** [comment]
Are you sure that you have the kernelspec pointing to the right R install? What does `R.home("bin")` tell you?

**Comment by blahster** [comment]
Thanks for the suggestion @janschulz 
I set
`R_HOME=/usr/lib64/Revo-7.3/R-3.1.1/lib64/R`
in .Renviron and now the kernel doesn't start.

**Comment by janschulz** [comment]
I didn't mean to set it, I wanted to know where it pointed to :-)

can you tell me the exact content of the kernel spec (mine are in `C:\Users\jschulz\AppData\Roaming\jupyter\kernels`, no idea where they are under linux...). They contain the path to the R interpreter which is used (e.g. in my case `"argv": ["C:/PROGRA~1/R/R-3.3/bin/x64/R" [...]`, so make sure that this points to the R your installed via Revolution Analytics

**Comment by takluyver** [comment]
You can see where your kernelspecs are on any system by running:

```
jupyter kernelspec list
```

Typically on Linux they're installed to `~/.local/share/jupyter/kernels/`, but depending on how you install things it can be elsewhere.

**Comment by blahster** [comment]
Thanks @janschulz, @takluyver it was fine after running installspec from Revo64.
