### ISSUE TITLE
error in devtools::install_github('IRkernel/IRkernel') / win 8 x64

### ISSUE THREAD

**Issue by martinehman** [IRkernel/IRkernel#373]
hi, I'm getting an error at this line
```
> devtools::install_github('IRkernel/IRkernel')
[...]
```
* installing *source* package 'IRkernel' ...
** R
** inst
** tests
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'stringr'
ERROR: lazy loading failed for package 'IRkernel'
* removing 'C:/Program Files/R/R-3.2.3/library/IRkernel'
Error: Command failed (1)
```
```

**Comment by martinehman** [comment]
It was a dependency issue.
Solved it with `install.packages("stringr")`

**Comment by Luxios** [comment]
Windows 10 
I have tried it but it doesn't work!


devtools::install_github('IRkernel/IRkernel')
Downloading GitHub repo IRkernel/IRkernel@master
from URL https://api.github.com/repos/IRkernel/IRkernel/zipball/master
Installing IRkernel
Downloading GitHub repo IRKernel/IRdisplay@master
from URL https://api.github.com/repos/IRKernel/IRdisplay/zipball/master
Installing IRdisplay
"D:/Program Files/R/R-3.2.5/bin/x64/R" --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/Luxio/AppData/Local/Temp/RtmpiSGMTK/devtoolsb105cbc7cbf/IRkernel-IRdisplay-8e24901"  \
  --library="D:/Program Files/R/R-3.2.5/library" --install-tests 

'D:\Program' neither inside or outside order，nor exe or bat.
Error: Command failed (1)

**Comment by flying-sheep** [comment]
whaa… it tries to execute `R CMD INSTALL`, but apparently doesn’t quote the path right, therefore it splits at the space after `D:\Program` (missing `Files\...`)

seems like an R bug. please report upstream
