### ISSUE TITLE
error in installation on ubuntu

### ISSUE THREAD

**Issue by Woodstonelee** [IRkernel/IRkernel#378]
Hi I ran into the following problem. It looks like a bug in the installation script? 

```r
> devtools::install_github(c('IRkernel/IRdisplay', 'IRkernel/IRkernel'))
Downloading GitHub repo IRkernel/IRdisplay@master
from URL https://api.github.com/repos/IRkernel/IRdisplay/zipball/master
Installing IRdisplay
Error in if (capabilities("libcurl")) { : argument is of length zero

**Comment by flying-sheep** [comment]
no, an R bug.

the error message says that `capabilities("libcurl")` returned something of length zero (so likely `logical(0)` or `NULL`), but the documentation of `capabilities` clearly says that for this input, it has to return either `c(libcurl = TRUE)` or `c(libcurl = FALSE)`, i.e. never something of length 0.

can you check what exactly `capabilities("libcurl")` returns, file a bug for R, and link it here?

**Comment by flying-sheep** [comment]
also this obviously happened during the installation of IRdisplay, so why did you file it for IRkernel?

**Comment by takluyver** [comment]
@flying-sheep I think that from the outside, people will mostly see IRkernel as one thing, and not really follow the internal distinctions when filing bugs. If you think this is unfortunate, take a look at the variety of bugs we get filed on ipython/ipython, jupyter/jupyter, jupyter/notebook, and pretty much any other ipython or jupyter repo ;-).

Even if this is an R bug, if it's something that could come up for more users, we'll consider working around it.

**Comment by flying-sheep** [comment]
sure, sorry if this wasn’t clear.

but until we know how that bug came to be i won’t include an `isTRUE` or similar.

@Woodstonelee can you please post the output of the following:

```r
capabilities() 
.Internal(capabilities())
.Internal(capabilitiesX11())
match('libcurl', names(.Internal(capabilities())), 0L)
```

**Comment by raino01r** [comment]
As @takluyver is suggesting, this is an R bug of devtools - see [install_github fails](https://github.com/hadley/devtools/issues/1244). In fact, a solution is provided by @kiwiroy - however it's yet been accepted... 

I'm setting up an R kernel in a Jupyter environment, in a Debian machine. I have the following:

```
> capabilities("libcurl")
named logical(0)
> capabilities() 
    jpeg      png     tiff    tcltk      X11     aqua http/ftp  sockets 
    TRUE     TRUE     TRUE     TRUE    FALSE    FALSE     TRUE     TRUE 
  libxml     fifo   cledit    iconv      NLS  profmem    cairo 
    TRUE     TRUE     TRUE     TRUE     TRUE     TRUE     TRUE 
> .Internal(capabilities())
    jpeg      png     tiff    tcltk      X11     aqua http/ftp  sockets 
    TRUE     TRUE     TRUE     TRUE       NA    FALSE     TRUE     TRUE 
  libxml     fifo   cledit    iconv      NLS  profmem    cairo 
    TRUE     TRUE     TRUE     TRUE     TRUE     TRUE     TRUE 
> .Internal(capabilitiesX11())
[1] FALSE
> match('libcurl', names(.Internal(capabilities())), 0L)
[1] 0
```

In fact the solution relies on:
```
> if (capabilities("libcurl")) { "1" } else {'0'}
Error in if (capabilities("libcurl")) { : argument is of length zero
> if (isTRUE(capabilities("libcurl"))) { "1" } else {'0'}
[1] "0"
```

**Comment by raino01r** [comment]
I've solved the problem in the `R version 3.1.1 (2014-07-10)` Debian machine as follows (from scratch):

```
$ sudo apt-get install libcurl4-openssl-dev libxml2-dev libxslt-dev libssl-dev -y
$ sudo apt-get install r-base r-base-dev -y
$ R
...
> options(repos='http://cran.rstudio.com/')
> install.packages("devtools")
> install.packages(c('repr', 'pbdZMQ', 'devtools'))
> options(download.file.method = "wget")
> install.packages('RCurl')
> devtools::install_github(c('IRkernel/IRdisplay', 'IRkernel/IRkernel'))
> IRkernel::installspec()
```

**Comment by flying-sheep** [comment]
ah, got it: `capabilities('libcurl')` was added in R 3.2, so for R 3.1, that’s expected behavior.

it’s fixed in devtools master, but i don’t think it’s in a release yet: https://github.com/hadley/devtools/commit/c101cb07d2f9fc99c821a415d23a29719f253547

---

but this brought to light a different issue: we claim to support back to R 3.0.1, but only test rel and oldrel, aka 3.3 and 3.2.

@takluyver @janschulz either we have to extend our testmatrix (does travis even support old R versions) or bum our dependencies to `R (>= 3.2.0)`.

**Comment by takluyver** [comment]
I'd be happy to bump our dependencies up to R 3.2 at the moment. I'm not sure if I'll always be happy supporting just the latest two releases - how often does R make releases?

**Comment by flying-sheep** [comment]
[here are dates](https://cran.r-project.org/bin/windows/base/old/):

* 3.0: April, 2013
* 3.1: April, 2014
* 3.2: April, 2015
* 3.3: April, 2016

looks pretty yearly to me

**Comment by takluyver** [comment]
Hmm, so the 'last two releases' policy would probably be annoying for people on 2-yearly updates, like Ubuntu LTS users. Ubuntu 16.04 has R 3.2, so some people will be using that until 2018, when R 3.5 will come out.

That's not ideal, but if we can't easily test on older versions of R, we can live with it.

**Comment by AisaacO** [comment]
Currently facing the same problem with R version 3.1.3 (2015-03-09)

**Comment by baranaydogan** [comment]
@raino01r 's solution for Debian worked  for me also.

**Comment by lbiemans** [comment]
Hi,

I've fixed this in Debian  by installing r-base and r-base-dev via jessie-backports. Thanks to the comment of @raino01r which pointed me in the right direction
