### ISSUE TITLE
No output for some errors

### ISSUE THREAD

**Issue by valentas-kurauskas** [IRkernel/IRkernel#383]
Why would this terminate with no output in the notebook?

```
f<-function(x) f(x)
f(0)
```

**Comment by flying-sheep** [comment]
oooh, nice find. i’ll check it

**Comment by flying-sheep** [comment]
this is super weird: the debug output shows that the error handler is never called, yet normal calling of evaluate works:

```e
err <- NULL
evaluate('f<-function(x) f(x); f(0)', output_handler = new_output_handler(error = function(e) err <<- e))
print(err)
```

**Comment by kdmurray91** [comment]
Hi @flying-sheep, I'm having similar issue here with many error cases. Particularly around `ggplot()`.

**Comment by flying-sheep** [comment]
sadly no idea yet. but i found sth weird:

```r
err <- list()
eh <- function(e) err <<- c(err, toString(e))
oh <- evaluate::new_output_handler(error = eh)
evaluate::evaluate(
    'f<-function(x) f(x); f(0)',
    output_handler = oh,
    envir = .GlobalEnv,
    stop_on_error = 1L)
print(err)
```

this leaves the list empty for some reason. doing `eh <- function(e) err <<- c(err, e$message)` leaves us with the message in the list, though.

**Comment by kdmurray91** [comment]
I'm not sure if it's related, but I get a few of these on the terminal Jupyter is running in:

```
[I 16:10:33.727 NotebookApp] Kernel restarted: 9ff3939e-bcc6-4038-832b-0ce77962d22e
Error in enc$lengths[[i]] : 
  attempt to select less than one element in get1index
Calls: <Anonymous> ... tryCatchList -> tryCatchOne -> <Anonymous> -> skip_repeated
Execution halted

```

**Comment by flying-sheep** [comment]
that one should be fixed when you update to the newest git version

**Comment by kdmurray91** [comment]
Ah ha, yep, I see that. Just did install_github again.

**Comment by xkrogen** [comment]
Running on the most current version, I am having this issue as well. In addition to the examples above, no errors are displayed at any point when I am attempting to use RJDBC. Also happy to provide debug info.

**Comment by flying-sheep** [comment]
i’ve created hadley/evaluate#70. maybe @yihui can find the issue…

**Comment by yihui** [comment]
Sorry I have no idea. This is indeed weird.

**Comment by flying-sheep** [comment]
removing the milestone as we can’t fix it here and it doesn’t seem to be fixed soon
