### ISSUE TITLE
R-essentials installed successfully, but no libraries available (MAC)

### ISSUE THREAD

**Issue by cmeier303** [IRkernel/IRkernel#384]
Hi All,

R running in Jupyter is having trouble finding the packages provided by Conda R-essentials.  

I have installed Anaconda and IRkernel both succesfully.  I also ran in Bash 'conda install -c r r-essentials' which also installed all the R packages successfully. I can see all the packages installed in Jupyter on the Conda tab, but when I start up R in Jupyter and try load a library, for instance library(caret), it says one is not installed. I suspect it is some sort of path issue, but no idea how to resolve.  

I'm new to using a MAC and Github, so apologies if I haven't supplied enough info.  Let me know what other details is needed.

Many thanks,
Chris

**Comment by takluyver** [comment]
Conda installs its own copy of R and puts the packages into there. When you installed IRkernel, if you installed it into a separate copy of R outside of conda, then it will be running with that R, and it won't see packages installed inside conda.

**Comment by takluyver** [comment]
I don't think there's any need to uninstall Anaconda.

* If you want to use Anaconda's R, remove the other R installation and reinstall IRkernel using Anaconda's R.
* If you want to use the other R, then `conda uninstall r r-essentials`, and install the packages you want using R's own `install.packages()` function.

**Comment by cmeier303** [comment]
I uninstalled the other R installation and then reinstalled irkernel `conda install -c r r-irkernel=0.6.1`

When I enter `library(caret)` it still gives me the same error:

Error in library(caret): there is no package called ‘caret’
Traceback:

library(caret)
stop(txt, domain = NA)

Maybe I'm missing a step.  Do I need to use another install statement in R within Jupyter that references the Conda install of the R packages?

**Comment by takluyver** [comment]
I don't think any extra steps should be needed, but it wouldn't hurt to run `IRkernel::installspec()` in that R.

Is `caret` definitely part of the `r-essentials` package? I don't know much about R libraries.

**Comment by cmeier303** [comment]
Weird, I ran the suggestion in the R session, but nothing happens, not even an error message.  

Correct, I picked a package that is in r-essentials. I tried others, but same error.

**Comment by cmeier303** [comment]
When I run these two scripts respectively in R and Python from within Jupyter I get the following paths:

file.path(Sys.getenv("R_HOME"), "bin", "R")

'/Library/Frameworks/R.framework/Resources/bin/R'

`
import sys
print(sys.executable)
`
/Users/christophermeier/anaconda/bin/python


I'm thinking Jupyter is still running R outside Conda even though I uninstalled R.  I'm wondering if because R was installed first, that when I installed Conda it found that R already existed and just hitched up to Jupyter to it from there...I think.  My guess to fix is either uninstall everything and then try to reinstall just Anaconda, or maybe an easier route is to tell R that the new library path is the path within Conda, that way there packages installed by Conda and packages installed by R are in the same location.

**Comment by takluyver** [comment]
That does indeed look like it's still using the non-conda R. Does that path still exist? If so, uninstalling R probably didn't work correctly.

Telling R about the conda path might work, but they might be two different versions of R.

If you find where the kernelspec for IRkernel is (`jupyter kernelspec list`), you may also be able to edit that to point to conda's version of R, which will probably be in something like `~/anaconda/bin/R`.

**Comment by cmeier303** [comment]
I tried your suggestion and R disappeared from Jupyter, but I think that helped figure out the issues.  The IRkernel installation I did in step 4 above was done in the R terminal NOT from within Anaconda, so the IRkernel was installed there, linking to the wrong one. I think I just need to run it using the R installation that resides in Conda, but I get an error when I attempt this.  

This is the code from the link for IRkernel:
```
install.packages(c('repr', 'pbdZMQ', 'devtools')) # repr is already on CRAN
devtools::install_github(c('IRkernel/IRdisplay', 'IRkernel/IRkernel'))
IRkernel::installspec()
```

After running the first line, I get a warning, but not sure if I should pay any attention to it:

> The downloaded source packages are in
> 	‘/private/var/folders/5p/c5qn3qrs6236jvqd1hzxmglw0000gn/T/RtmpFGmg1j/downloaded_packages’
> Updating HTML index of packages in '.Library'
> Making 'packages.html' ... done
> Warning message:
> In install.packages(c("repr", "pbdZMQ", "devtools")) :
>   installation of package ‘pbdZMQ’ had non-zero exit status

Running the 2nd line produces an error at the end:

> 
> Skipping install of 'IRdisplay' from a github remote, the SHA1 (2d1a0ca8) has not changed since last install.
>   Use `force = TRUE` to force installation
> Downloading GitHub repo IRkernel/IRkernel@master
> from URL https://api.github.com/repos/IRkernel/IRkernel/zipball/master
> Installing IRkernel
> trying URL 'https://cran.revolutionanalytics.com/src/contrib/jsonlite_1.0.tar.gz'
> Content type 'application/octet-stream' length 1057732 bytes (1.0 MB)
> ==================================================
> downloaded 1.0 MB
> 
> sh: /usr/bin/gnutar: No such file or directory
> sh: /usr/bin/gnutar: No such file or directory
> Error in system(cmd, intern = TRUE) : error in running command
> In addition: Warning message:
> In utils::untar(src, exdir = target, compressed = "gzip") :
>   ‘/usr/bin/gnutar -xf '/var/folders/5p/c5qn3qrs6236jvqd1hzxmglw0000gn/T//RtmpFGmg1j/jsonlite_1.0.tar.gz' -C '/var/folders/5p/c5qn3qrs6236jvqd1hzxmglw0000gn/T//RtmpFGmg1j/devtools11605ef83072'’ returned error code 127

**Comment by takluyver** [comment]
If you're using conda, try installing IRkernel with conda too:

```
conda install -c r r-irkernel
```

Then you may need to run `IRkernel::installspec()` again (I'm not 100% sure about that)

**Comment by cmeier303** [comment]
It says it is already installed.  Is there a way to uninstall the original?  I see plenty of hits on Google on how to install, but none for uninstalling.

**Comment by takluyver** [comment]
R has a `remove.packages()` function, but I don't know if it will pick the one you mean to remove. If it's already installed, though, try just running `IRkernel::installspec()`.
