### ISSUE TITLE
Dead Kernel On graphing

### ISSUE THREAD

**Issue by mgorjis** [IRkernel/IRkernel#386]
I have installed the R kernel of Jupyter based on the guide. I have R 3.3.1 on windows 10.

```r
install.packages(c('pbdZMQ', 'repr', 'devtools'))  # repr is already on CRAN
devtools::install_github('IRkernel/IRkernel')
IRkernel::installspec()  # to register the kernel in the current R installation
```

I can run the R kernel and it is working fine for calculations. But immediately after a simple plot command, it says "Dead Kernel" and kernel restarts. I can't plot anything in the notebook.

Does anyone has any experience like that? Thank you.

**Comment by flying-sheep** [comment]
what does the kernel log say? i.e. the output  of `jupyter notebook`

if it doesn’t look helpful, please run `JUPYTER_LOG_LEVEL=3 jupyter notebook` and then post the log here

**Comment by mgorjis** [comment]
Thank you for your response.
When I ran "JUPYTER_LOG_LEVEL=3 jupyter notebook " I received error from command prompt that the command is unknown.
But running the "jupyter notebook --log-level=30" shows the below error. Did you mean this command?


```
C:\Users\Mo>jupyter notebook --log-level=30
[W 00:14:16.980 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20160724001400 (127.0.0.1) 24.02ms referer=http://localhost:8888/notebooks/Untitled1.ipynb
Error in enc$lengths[[i]] :
  attempt to select less than one element in get1index
Calls: <Anonymous> ... tryCatchList -> tryCatchOne -> <Anonymous> -> skip_repeated
Execution halted
WARNING:root:kernel 70c8e72c-71e6-4797-8180-7cb18d810e0a restarted
```

**Comment by janschulz** [comment]
On windows, you probably need to run it as two commands:

```bat
set JUPYTER_LOG_LEVEL=3 
jupyter notebook 
```

In this case (the output above errors in a function which should handle an error) it will probably not show much until https://github.com/IRkernel/IRkernel/pull/377 is merged. 

The problem sees to be https://github.com/IRkernel/IRkernel/commit/ffea2bc17aa756c478b8071fc3cad014b3b3bfe1, not sure what that fixed, maybe @flying-sheep can explain it...

**Comment by flying-sheep** [comment]
ok, please try the newest git master IRkernel.

also `--log-level` is not what you want. you really need to set the `JUPYTER_LOG_LEVEL` variable.
```

**Comment by mgorjis** [comment]
Dear @flying-sheep , this is the log from kernel starting, plotting which led to restarting the kernel.

`
DEBUG: Starting the R kernel...
DEBUG: main loop: beginning
DEBUG: main loop: after poll
DEBUG: main loop: shell
DEBUG: Sending msg status
DEBUG: Sending msg kernel_info_reply
DEBUG: Sending msg status
DEBUG: main loop: beginning
DEBUG: main loop: after poll
DEBUG: main loop: shell
DEBUG: Sending msg status
DEBUG: Sending msg kernel_info_reply
DEBUG: Sending msg status
DEBUG: main loop: beginning
DEBUG: main loop: after poll
DEBUG: main loop: shell
DEBUG: Sending msg status
DEBUG: Sending msg execute_input
DEBUG: Executing code: 2+2
DEBUG: Value output...
DEBUG: Sending display_data: List of 4
 $ text/html    : chr "4"
 $ text/markdown: chr "4"
 $ text/latex   : chr "4"
 $ text/plain   : chr "[1] 4"
DEBUG: Sending msg display_data
DEBUG: Sending msg execute_reply
DEBUG: Sending msg status
DEBUG: main loop: beginning
DEBUG: main loop: after poll
DEBUG: main loop: shell
DEBUG: Sending msg status
DEBUG: Sending msg execute_input
DEBUG: Executing code: # Define the cars vector with 5 values
cars <- c(1, 3, 6, 4, 9)

# Graph the cars vector with all defaults
plot(cars)

DEBUG: Graphics output...
DEBUG: Error output: Error in loadNamespace(name): there is no package called 'Cairo'

Error in enc$lengths[[i]] :
  attempt to select less than one element in get1index
Calls: <Anonymous> ... tryCatchList -> tryCatchOne -> <Anonymous> -> skip_repeated
Execution halted
[I 11:29:41.072 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 67694928-7bf1-43c0-ba40-635caa035acb restarted
DEBUG: Starting the R kernel...
DEBUG: main loop: beginning
`

**Comment by mgorjis** [comment]
@flying-sheep Based on the log, I installed the package "Cairo" and it fixed the problem
I don't the relation between this package and jupyter graphics

**Comment by flying-sheep** [comment]
np, but that’s a bug on our side: `Cairo` shouldn’t be used if it’s not available.

we actually detect if it is and only use it if it is. something is really wrong here.

can you tell us what `requireNamespace('Cairo', quietly = TRUE)` outputs?

**Comment by mgorjis** [comment]
I use   repr_0.7.

 requireNamespace('Cairo', quietly = TRUE)   doesn't show any output in R environment.

**Comment by takluyver** [comment]
I think the result of requireNamespace is invisible, so you have to explicitly print() it.

**Comment by mgorjis** [comment]
result is "TRUE"

**Comment by flying-sheep** [comment]
> I use repr_0.7

there’s your problem. [0.8](https://github.com/IRkernel/repr/releases/tag/0.8) fixed your bug.
