### ISSUE TITLE
strange output for error report

### ISSUE THREAD

**Issue by aakhmetz** [IRkernel/IRkernel#387]
Why do I have such strange output when I get an error message?

For example, if I execute:
plor()

It gives me the output in the form:

E
r
r
o
r
 
i
n
 
e
v
a
.... etc.

**Comment by flying-sheep** [comment]
did you upgrade everything? this is a very old bug, but maybe it resurfaced.

**Comment by takluyver** [comment]
This occurs when a traceback which is supposed to be supplied as a list of lines is given as a string - something does `'\n'.join(lines)` (or a JS equivalent thereof).

**Comment by flying-sheep** [comment]
sure, and `format_stack` [always returns a list](https://github.com/IRkernel/IRkernel/blob/master/R/execution.r#L38).

**Comment by aakhmetz** [comment]
I thought that I had the last versions of the packages. I will check tomorrow

**Comment by aakhmetz** [comment]
So, the versions I had were:
```r
sessionInfo(package=c("IRKernel","IRDisplay","repr")]  

other attached packages:                                                                                                            
[1] IRkernel_0.6  IRdisplay_0.3 repr_0.7    
```
which are not the last ones available. But they are from the last conda-repo (I followed a guideline from https://samrelton.wordpress.com/2015/07/02/rconda/ with only one addition that I needed to install zeromq package after - otherwise there was the kernel death with ".onLoad failed in loadNamespace() for 'pbdZMQ'"-error)

After today's re-installation of the whole anaconda, I still get the same single-column error message

**Comment by flying-sheep** [comment]
cannot reproduce with the newest versions. please install [as we recommend](https://irkernel.github.io/installation/)

**Comment by aakhmetz** [comment]
Yup, it works with the newest versions - good! thanks!

ps: How often is the conda-repo updated?

**Comment by janschulz** [comment]
No idea, we have no control over that conda channel and the packages in there.

**Comment by aakhmetz** [comment]
ok, I see

**Comment by aakhmetz** [comment]
oh, and a code highlight is also much better with a newer version (I am happy now)

**Comment by flying-sheep** [comment]
cool :smile:
