### ISSUE TITLE
`nbconvert --to script` skips Markdown cells

### ISSUE THREAD

**Issue by shippy** [IRkernel/IRkernel#394]
In notebooks with IPython 3 kernels, `nbconvert --to script` automatically includes Markdown content in the comments. In IRKernel notebooks, Markdown cells are omitted from the exported document. This is undesirable, as it removes explanatory content for colleagues who have not yet joined the Notebook train.

This seems to be caused by subtly different treatment. The IPython notebook has a specific `"nbconvert_exporter": "python"` field, which overrides the standard `script` exporter in [nbconvert/script.py#L24](https://github.com/jupyter/nbconvert/blob/39b86e995ccfccd9d2c367b21187c61349f6189f/nbconvert/exporters/script.py#L24). This is related to #279  -- but the solution there doesn't work for me, since I only need to export when I send files to colleagues without Jupyter _or_ RMarkdown setup.

What do you think is the best solution? Writing a custom exporter and using it? Submitting an exporter upstream to `nbconvert`? Both, in due time? Or am I missing an existing method to deal with this?
### test_IPython.ipynb

``` json
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Test\n",
    "This is a *test* of the **Markdown export in Python 3 kernel**. Suspected result: this Markdown cell *will* be included in the comments of `nbconvert --to script <this file>`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Hello, world!\n"
     ]
    }
   ],
   "source": [
    "# First Python cell\n",
    "print(\"Hello, world!\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
```
### test_IPython.py

(via `jupyter nbconvert --to script test_IPython.ipynb`)

``` python

# coding: utf-8

# ## Test
# This is a *test* of the **Markdown export in Python 3 kernel**. Suspected result: this Markdown cell *will* be included in the comments of `nbconvert --to script <this file>`.

# In[1]:

# First Python cell
print("Hello, world!")
```
### test_IRKernel.ipynb

``` json
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Test\n",
    "This is a *test* of the **Markdown export in IRKernel**. Suspected result: this Markdown cell will not be included in the comments of `nbconvert --to script <this file>`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[1] \"Hello, world!\"\n"
     ]
    }
   ],
   "source": [
    "# The first R cell\n",
    "print(\"Hello, world!\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "R",
   "language": "R",
   "name": "ir"
  },
  "language_info": {
   "codemirror_mode": "r",
   "file_extension": ".r",
   "mimetype": "text/x-r-source",
   "name": "R",
   "pygments_lexer": "r",
   "version": "3.2.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
```
### test_IRKernel.r

(via `jupyter nbconvert --to script test_IRKernel.ipynb`)

``` R

# The first R cell
print("Hello, world!")
```

**Comment by flying-sheep** [comment]
thanks, great analysis. i wondered about this before, but never bothered to look into it and now you’ve done all the work.

just one thing to add: this was probably done because the markdown has to be [commented](https://github.com/jupyter/nbconvert/blob/39b86e995ccfccd9d2c367b21187c61349f6189f/nbconvert/filters/strings.py#L143-L158) and nbconvert doesn’t know a languages’ comment char. also the [python template](https://github.com/jupyter/nbconvert/blob/master/nbconvert/templates/python.tpl) does a few things more: [`coding: utf-8`](https://github.com/jupyter/nbconvert/blob/39b86e995ccfccd9d2c367b21187c61349f6189f/nbconvert/templates/python.tpl#L4) [`ipython2python`](https://github.com/jupyter/nbconvert/blob/39b86e995ccfccd9d2c367b21187c61349f6189f/nbconvert/filters/strings.py#L182-L201)

my favourite solution

1. extend the script exporter so that it derives the language line comment sequence from the langinfo
2. extend the script template so that if this comment sequence is found, it uses `comment_lines` with it.
3. add the comment sequence to the R notebook language info

(maybe we also have to add multiline comments because of languages without line comments like CSS)

**Comment by takluyver** [comment]
I think we want to try to avoid encoding all kinds of language syntax info in the notebook metadata. Comment characters seem simple, but IIRC, when we looked into it, we found that there are at least:

- languages like Python where comments go from a marker to the end of the line
- languages where comments go from one marker to another (HTML is like this; I don't have an executable example off the top of my head)
- languages which allow both styles (e.g. C, Javascript)

Encoding all that is rapidly going to get complex. So maybe if languages want something more than the basic 'script' export, we should create custom exporters for them, as we do for IPython. It's now quite easy to register an nbconvert exporter from an external package.

**Comment by flying-sheep** [comment]
well, how then?

**Comment by shippy** [comment]
Not to mention Python's triple-quoted strings, which - while not in PEP8 - also work as comments.

That said, I am not aware of a language that has start-of-line comment chars that can be *terminated* before the end of the line; R certainly doesn't. This should allow us to use nbconvert's `comment_lines` -- as an added point in favor, R uses the same comment style as Python.

More to the point, this shouldn't require adding comment-char metadata to the notebook, merely an `nbconvert_exporter` field. To make that work, it seems that we'd need to add: 

1. an exporter at `nbconvert/exporters/r.py` that trivially extends [`TemplateExporter`](https://github.com/jupyter/nbconvert/blob/39b86e995ccfccd9d2c367b21187c61349f6189f/nbconvert/exporters/templateexporter.py) (in a manner similar to [`nbconvert/exporters/python.py`](https://github.com/jupyter/nbconvert/blob/39b86e995ccfccd9d2c367b21187c61349f6189f/nbconvert/exporters/python.py)), and 
2. a template at `nbconvert/templates/r.tpl` (which could be almost identical to [`nbconvert/templates/python.tpl`](https://github.com/jupyter/nbconvert/blob/39b86e995ccfccd9d2c367b21187c61349f6189f/nbconvert/templates/python.tpl), sans `ipython2python`, which we don't need because IRKernel doesn't use magics or system calls, which is the thing that [`IPythonInputSplitter`](https://ipython.org/ipython-doc/3/api/generated/IPython.core.inputsplitter.html#IPython.core.inputsplitter.IPythonInputSplitter) -- the class called by `ipython2python` -- handles.) The actual definition of a comment char happens in the `comment_lines` call -- [the function takes a `prefix` argument, with `#` as default](http://nbconvert.readthedocs.io/en/latest/api/filters.html).

(There *shouldn't* be an issue with languages that use a "keep-getting-commands-for-this-line-from-the-next-line" syntax, e.g. Python's `\` and MATLAB's `...`

```matlab
print(['This'; ...
'thing');
% But multiline comment ...
doesn't work! (throws syntax error)
```

MATLAB doesn't extend comments based on `...` at the end of a comment line on 2016a, but perhaps prior versions or other languages are not so lucky. That said: not a problem for R.)

**Comment by takluyver** [comment]
> an exporter at nbconvert/exporters/r.py

This needn't be integrated as part of nbconvert - we can make a Python package (e.g. `nbconvert_export_r`) which includes an exporter and a template, and registers the exporter for nbconvert:

http://nbconvert.readthedocs.io/en/latest/external_exporters.html#registering-a-custom-exporter-as-an-entry-point

The `nbconvert_exporter` field probably doesn't behave very nicely with an external package that may not be installed at the moment. I'll open an issue for that.

**Comment by takluyver** [comment]
See jupyter/nbconvert#361

**Comment by billgreenwald** [comment]
I got pointed to here trying to figure out why when I do a post-save hook with a python kernel I get mark down cells, but with an IRKernel I get no markdown cells written to my script.  

Any direction would be helpful.  As of now I do nbconvert --to python and then just rename my file from .py to .r

Thanks!

**Comment by pvtodorov** [comment]
Is it still impossible to use nbcovert with IRkernel?

**Comment by flying-sheep** [comment]
Something seems to have been implemented in https://github.com/jupyter/nbconvert/issues/531. @takluyver what’s necessary to make this work on the IRkernel side?

**Comment by takluyver** [comment]
It would mean someone writing a little Python package to define and register a custom exporter for R. I went looking for an example and found... R. Someone already made it: https://github.com/whatalnk/nbconvert_exporter_r . Though it seems they didn't get around to putting it on PyPI (someone could fork it and do that). Install that package in the same environment as nbconvert, and `--to script` should use it automatically. It's a few years old, though, so it's possible nbconvert has changed underneath it.

> is it possible to use nbconvert from the command line to execute an ipynb and fill it with outputs?

That's a separate question, assuming you mean saving the outputs into the same ipynb file. It should work without any extra plugin (except IRKernel to run the code). Use the options `--to notebook --execute --inplace` ([docs](https://nbconvert.readthedocs.io/en/latest/usage.html#notebook-and-preprocessors)).

**Comment by ruthappel** [comment]
Hi, I've experienced the same issue and wanted to share the two solutions I found (the nbconvert custom exporter option didn't work in the environment where I tried to install it). The first step is to convert the notebook to an Rmd file, so this post might also speak to https://github.com/IRkernel/IRkernel/issues/279.

# Converting Juptyer Notebooks to R files while preserving comments and headings
## Using `rmarkdown` and `knitr`
To convert a Jupyter notebook to R files while preserving comments and headings, we can use the `convert_ipynb` function from the `rmarkdown` package. The first step is to convert the notebook to an RMarkdown file. In a Jupyter notebook with an R kernel, run the following cells and replace `test_notebook.ipynb` with your filename.
```
rmarkdown::convert_ipynb('test_notebook.ipynb', output = xfun::with_ext('test_notebook.ipynb', 'Rmd'))
```
As an optional step, you might want to customize the title and output of the `Rmd` file by editing the newly created `Rmd` file manually.
RMarkdown files with extension `Rmd` can be converted to `R` scripts using the `purl` function from the `knitr` package. The `documentation` option allows to specify which level of details (comments, headings) should be preserved. If you want to specify a different filename for the output file, use the `output` option (in this example, the output filename will be `test_script.R`).
```
knitr::purl('test_notebook.Rmd', output = 'test_script.R', documentation = 2) # preserve comments and headings
```
## Alternative options
Note that it is also possible to use `nbconvert` to convert a notebook to a script or Markdown file, but the script option would ignore all content that is not in code cells, and the markdown option would not result in a Markdown file that could actually be run in RStudio and would still contain cell output by default.
```
system('jupyter nbconvert --to script test_notebook.ipynb') # will ignore content outside of code cells
system('jupyter nbconvert --to markdown test_notebook.ipynb') # will not result in Markdown compatible with RStudio
```
