### ISSUE TITLE
Kernel dies on any valid R command

### ISSUE THREAD

**Issue by manniche** [IRkernel/IRkernel#398]
Using 
R version 3.2.5 (2016-04-14) -- "Very, Very Secure Dishes" 
and having installed IRkernel via `install_github`
using the kernel.json provided by the project, I get the following error when trying to do `foo<-1`
```
[D 08:32:22.143 NotebookApp] Starting kernel: [u'R', u'--slave', u'-e', u'IRkernel::main()', u'--args', u'/home/spark/.local/share/jupyter/runtime/kernel-0743e023-8d55-480c-b78d-ead47f5afc88.json']
[D 08:32:22.149 NotebookApp] Connecting to: tcp://127.0.0.1:51068
[D 08:32:25.151 NotebookApp] KernelRestarter: restart apparently succeeded
Error in ok_device(filename, ...) : X11 is not available
Calls: <Anonymous> ... evaluate -> dev.new -> do.call -> <Anonymous> -> ok_device
Execution halted
```
I have tried with `xvfb-run -a`, but gets the same error.

**Comment by takluyver** [comment]
What does capabilities() give you? It looks like it's trying to create a
graphics device that uses X.

**Comment by flying-sheep** [comment]
yeah, the `ok_device` seems not to be OK.

@manniche if a call to `png('somefile')` or `pdf('somefile')` fails, you’ll have to fix that.

a search will quickly point you to #388.

**Comment by manniche** [comment]
Thank you very much for the link. Sorry I didn't find it before posting...

**Comment by flying-sheep** [comment]
:smile: no problem, please post there or here if you can’t find a solution (tell us your OS then, please. i’m guessing OS X?)

**Comment by manniche** [comment]
I'm on a ubuntu 14.04 headless server that is being used as a jupyter server.
I solved the problem by building R with X11 support after installing libcairo2-dev.
Thanks again for your help.

**Comment by flying-sheep** [comment]
ah, cool! great you got it working!

**Comment by digrks** [comment]
Hiya, I'm having this issue as well. How did you fix this?
