### ISSUE TITLE
Dev Image broke due to missing crayon dependency not being installed

### ISSUE THREAD

**Issue by poplav** [IRkernel/IRkernel#399]
There is a regression with the dockerized development environment following https://github.com/IRkernel/IRkernel/pull/391.  
Crayon a required dependency was not added to the Dockerfile as a dependency to install.  Thus the command `make docker_dev` fails with `ERROR: dependency ‘crayon’ is not available for package ‘IRkernel’`

I'll open a quick PR to fix this.

**Comment by poplav** [comment]
Fixed by #400

**Comment by poplav** [comment]
Fixed in docker stacks...closing.

**Comment by flying-sheep** [comment]
thank you!
