### ISSUE TITLE
unit tests are not run from R CMD CHECK

### ISSUE THREAD

**Issue by poplav** [IRkernel/IRkernel#402]
From the `testthat` docs under the section [integration with r cmd check](https://github.com/hadley/testthat#integration-with-r-cmd-check) it says the test files can be .r or .R, but the main `tests/testthat.R` must be with a capital .R not .r.  
Currently we have testthat.r and it is not running on the build in the [check package travis step](https://github.com/IRkernel/IRkernel/blob/master/.travis.sh#L70).

**Comment by poplav** [comment]
Fixed by https://github.com/IRkernel/IRkernel/pull/401

**Comment by flying-sheep** [comment]
`devtools::test()` should just run all .r/.R files in `/tests`… why doesn’t it?

**Comment by poplav** [comment]
Yes, `devtools::test()` does run all the tests in [test_kernel](https://github.com/IRkernel/IRkernel/blob/master/.travis.sh#L86).  
Although, the unit level tests are not being run in [check_package](https://github.com/IRkernel/IRkernel/blob/master/.travis.sh#L70) when you do a `R CMD check`, confirmed via the logs and see [integration with r cmd check](https://github.com/hadley/testthat#integration-with-r-cmd-check).

I think there should be a clearer divide between unit and system tests as well and this PR addresses that.  The unit tests would now be run in `check_package` via `R CMD check` and the system tests would be run in `test_kernel` via directly running the python test file.

**Comment by flying-sheep** [comment]
that’s just confusing. tests are tests.

**Comment by flying-sheep** [comment]
@poplav what do you mean by “system tests”? we only have unittests.

do you mean that the kernels have to be installed for the `test_ir` script to run?

i think we should fix *that*, then. @takluyver is there a way to use `jupyter_kernel_test` with a kernel installed in a custom location (i.e. without running `installspec`)

**Comment by flying-sheep** [comment]
what i want:  you should be able to run `R CMD CHECK IRkernel-0.7.tar.gz` with only the dependencies installed but no kernelspecs and have all tests run.

**Comment by poplav** [comment]
I was making the distinction that `jupyter_kernel_test` is a system test as it requires external dependencies/is more integration.  The tests in testthat which get run in `R CMD check` should be treated as unit tests with no dependencies.  #401 seemed to address that distinction and pass.  I'll let you take over it in #404 thanks!

**Comment by flying-sheep** [comment]
the unit tests are really basic though, so they aren’t really helpful.

i think to be pragmatic we need to make the “real” tests discoverable by running them via `R CMD check` and `devtools::test()`

that’s why i chose to proceed like i did

**Comment by flying-sheep** [comment]
i thought i’d have fixed it but i didn’t:

* running tests via `devtools::test()` works
* `R CMD check` doesn’t. while it displays the following, it doesn’t actually run tests!

	```r
	* checking tests ...
	  Running ‘testthat.R’ OK
	```

**Comment by poplav** [comment]
@flying-sheep 

It looks `R CMD check` is running the tests now.  I verified that by changing one of the expects and watching it run/fail.

The concern seems to be the [kernel test](https://github.com/IRkernel/IRkernel/blob/master/tests/testthat/test_kernel.r#L26) part where something is happening, but I don't see what.  Throwing it out there is the environment setup correctly to run the tests there?  Judging by how fast the test runs (which it shouldn't as it's a larger kernel test) I am guessing it immediately breaks because of an environment issue, but somehow the test still passes.

**Comment by flying-sheep** [comment]
apparently the python tests don’t run when run through R CMD check.

i still don’t get why.

**Comment by poplav** [comment]
@flying-sheep I will test again tomorrow.  Good catch if that was the issue.  So many nuances...first the capitalization and now this.  Although, this actually makes logical sense as we were ignoring it from the build.

**Comment by flying-sheep** [comment]
i added a few tests that make sure it doesn’t happen again.

for some reason, [`setUpClass`](https://github.com/jupyter/jupyter_kernel_test/blob/7283c8c6213718e5a4f32cfe109613afed859271/jupyter_kernel_test/__init__.py#L21) fails now, but we‘re getting close

**Comment by poplav** [comment]
@flying-sheep Thanks it works great now!
