### ISSUE TITLE
.Last.value does not work in IRkernel

### ISSUE THREAD

**Issue by randy3k** [IRkernel/IRkernel#405]
I guess the reason `.Last.value` doesn't work in IRkernel is exactly the same reason why it doesn't work in `knitr`: http://stackoverflow.com/questions/31475226/using-last-value-in-rmarkdown-knitr

With the understanding that it doesn't work, I do find that it is quite handy to have the last output stored so that it could be used later, it is particularly helpful when using the autograde feature of [nbgrader](https://github.com/jupyter/nbgrader).

Does it make sense and is it difficult to enable `.Last.value`?

**Comment by flying-sheep** [comment]
[should be easy](https://github.com/IRkernel/IRkernel/blob/659435f7963aa23d7a1026fb4a45a4d9ecde9295/R/execution.r#L163)

sadly we display those things and don’t use the `Out[n]:` thing. else we could have a variable `Out` which would contain a list of lists of outputs (`Out[n]` would give a list with all values that are put out by the cell `In[n]`)

**Comment by randy3k** [comment]
IPython also has `_`, `__` and `___` to store the last three results.
And perhaps we could also bind the last result to `.Last.value` or `._` (`_` is not a valid variable name but `._` is 😵 ).

**Comment by flying-sheep** [comment]
> And perhaps we could also bind the last result to `.Last.value`

i think `.Last.value` needs to happen, `Out[*]` could be a thing in the future.

i don’t like the idea of introducing `._`
