### ISSUE TITLE
ChainLadder package installation failed 

### ISSUE THREAD

**Issue by nmeraihi** [IRkernel/IRkernel#413]
I tried to install a package on a [jupyter notebook](http://jupyter.org)  `install.packages("ChainLadder", "/Users/mymac/anaconda/lib/R/library")` and I have this message when I load `library(ChainLadder)`
any idea?
thanks!

> Error: package or namespace load failed for ‘ChainLadder’
> 
> Traceback:
> 
> library(ChainLadder)
> 
> stop(gettextf("package or namespace load failed for %s", sQuote(package)),
> 
> . call. = FALSE, domain = NA)

**Comment by flying-sheep** [comment]
no, maybe you should also try in a regular console or look at the server logs.

we can’t yet catch all output, so there might be info we’re missing.
