### ISSUE TITLE
Dead Kernel with R

### ISSUE THREAD

**Issue by edkrueger** [IRkernel/IRkernel#414]
When I try to open a notebook on Jupyter, the kernel dies instantly.

![screen shot 2016-10-06 at 7 11 19 pm](https://cloud.githubusercontent.com/assets/22670796/19175010/ce1d927e-8bf8-11e6-96d0-df7539bab7f2.png)

I checked the path given and the file seems to exist. 

Per other issues reports, I have checked and I have jsonlite. My r-irkernel version is 0.5 and my r-irdisplay is 0.3.

Please help!

**Comment by flying-sheep** [comment]
it seems that your anaconda installation is broken. when you look at the output, you can see that it wants to use `/lib/R/etc/ldpaths`, which is a weird path: usually i’d expect `/usr/lib/…`.

so i guess what it’s trying to do is something like `$PREFIX/lib/R/etc/ldpaths` while `$PREFIX` isn’t set → `/lib/R/etc/ldpaths`

please take this issue to https://github.com/ContinuumIO/anaconda-issues/issues
