### ISSUE TITLE
Unable to install IR in jupyter

### ISSUE THREAD

**Issue by chasset** [IRkernel/IRkernel#417]
I have installed jupyter via the anaconda package on ubuntu 16 and all dependencies, but I can't run the last line of your install script `IRkernel::installspec(name = 'ir33', displayname = 'R 3.3')`. I got this message.

```
Error in IRkernel::installspec() : 
  Jupyter or IPython 3.0 has to be installed but could neither run “jupyter” nor “ipython”, “ipython2” or “ipython3”.
```

**Comment by flying-sheep** [comment]
did you read the yellow box [here](https://irkernel.github.io/installation/)?

if so: is jupyter installed? does running `jupyter --help` work from the same shell that you started R in?

**Comment by chasset** [comment]
Yes, I use a terminal. I can run jupyter too.

**Comment by takluyver** [comment]
Inside R, what happens when you do:

```r
system2('jupyter', '--version', TRUE, FALSE)
```

**Comment by rgbkrk** [comment]
@chasset since you're using Anaconda, you can run:

```
conda install -c r r-essentials
```

at the command line to install R + IRkernel. It is a separate R environment though (tied to your root conda environment).
