### ISSUE TITLE
IRkernel install fails for R 3.3.1?

### ISSUE THREAD

**Issue by nhejazi** [IRkernel/IRkernel#419]
After a fresh install of Jupyter (removed all old kernels and such) on macOS, I just encountered an error when installing IRkernel and related packages from within R. The error is the incredibly generic "IRkernel not available for R 3.3.1". I haven't used my R kernel in a while, so I cannot claim that it was definitely working after my most recent R version upgrade, but I also can't point to any specific reason that this would be a problem. Have there been similar issues in the past?

**Comment by takluyver** [comment]
I don't think I've seen that before. Which step of the installation says that?

**Comment by flying-sheep** [comment]
that message simply means its not on cran:

```r
> install.packages('sdfgsdghsdf')
package ‘sdfgsdghsdf’ is not available (for R version 3.3.1) 
```

please follow our install instructions: https://irkernel.github.io/installation/

**Comment by takluyver** [comment]
Ah, OK. To clarify, we're trying to put IRkernel on CRAN, but the CRAN maintainers aren't very happy about it. So for now you have to install it from Github.

**Comment by flying-sheep** [comment]
thx. busted elbow = terse typing

**Comment by takluyver** [comment]
Sorry to hear of that. I'll ask about it in the future when typing replies is more comfortable. ;-) I hope it heals quickly.

**Comment by flying-sheep** [comment]
bouldering accident: never climb “one last route” when lacking the strength to fall controlledly.

dislodged it and ripped some ligaments, but needed no surgery. 4-6 weeks until the splint comes off

**Comment by takluyver** [comment]
Ouch :-( Feel free to take it easy on the coding front while you're splinted up!
