### ISSUE TITLE
Ability to install kernelspec without jupyter command

### ISSUE THREAD

**Issue by rgbkrk** [IRkernel/IRkernel#420]
Could [jupyter paths](http://jupyter.readthedocs.io/en/latest/projects/jupyter-directories.html) be implemented in R here and _not_ have to use the `jupyter` CLI?

My current use case is some images I'm using (at work) where we have a bunch of R packages that get set up as one image (sans Jupyter) and when Jupyter is introduced later in the build, the kernelspec is already there ready to go.

**Comment by takluyver** [comment]
I'd prefer to keep the knowledge of the paths in one place. You can always install the IRkernel package in the base image and only install the kernelspec once Jupyter is installed.
