### ISSUE TITLE
Dead R Kernel, cannot install package, Error in library(rJava

### ISSUE THREAD

**Issue by qiaoqiaozhu** [IRkernel/IRkernel#421]
Hi, 
   I recently reinstall conda on my MacOs in order to use rpy2. However, my R kernel doesn't work. it's instantly dead upon starting from jupyter. I have R installation outside of conda which works fine, including rJava. 
  The conda R is installed through ```conda install -c r r-essentials```. 
  when creating new R kernel file from jupyter, the error message is

```
KernelRestarter: restarting kernel (4/5) WARNING:root:kernel 1ed6fc92-fd56-4d19-a7e3-e9db62e504ab restarted
Error in library(rJava) : there is no package called ‘rJava’
Execution halted
```
   However, I do appear to have java. If I run: ```java -version```, I get:
```
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)
```

Also, if I run R from command prompt, I cannot install package. A similar complaint about rJava persists (Error in library(rJava)). If I run ```system("java -version")```, I get the same have version info. 

I've tried suggestions in issue #56, but they didn't work. Please help.

**Comment by takluyver** [comment]
Is there anything in your [Rprofile](http://www.statmethods.net/interface/customizing.html) about rJava? IRkernel does not do anything related to Java.

**Comment by qiaoqiaozhu** [comment]
yes, I do have a Profile that starts rJava and RJDBC for connection to a server. Will that cause r/irkernal within conda to not run properly? Is there a solution?

**Comment by qiaoqiaozhu** [comment]
I figured it out. conda IRkernel also searches for any .Rprofile even outside conda. When it can't find java it reboots itself, and after a couple tries, shut itself down. I remove the .Rprofile, install necessary package and then put .Rprofile back up, IRkernal works fine. 

Thanks for pointing me in the right direction.

**Comment by takluyver** [comment]
No problem. That sounds like expected behaviour to me - files called 'profile' are usually meant to be user-level configuration. So I'm closing this as I don't think there's a bug to fix.
