### ISSUE TITLE
can not install IRkernel for anaconda3 

### ISSUE THREAD

**Issue by Luxios** [IRkernel/IRkernel#424]
Error in IRkernel::installspec() : 
  Jupyter or IPython 3.0 has to be installed but could neither run “jupyter” nor “ipython”, “ipython2” or “ipython3”.
(Note that “ipython2” is just IPython for Python 2, but still may be IPython 3.0)

**Comment by flying-sheep** [comment]
well,  the `jupyter` binary needs to be findable by your system, i.e. be in your `$PATH`.

so:

1. make sure you use R in a terminal, not R.app when running `IRkernel::installspec()`
2. type `jupyter --version` in a terminal. if this fails, you’ll have to fix it. (modify `$PATH` in `.bashrc`)

**Comment by Luxios** [comment]
I have the jupyter in my path.The version is also OK. I used Rgui, but it still did not work. I turned to use anaconda2, this time it worked well. I want to know why, but anyway now I can use it.

**Comment by flying-sheep** [comment]
RGui?

As said: if the PATH is correct in the terminal, it doesn't need to be in R.app, RGui, or whatever other application.

I think that was it

**Comment by kguidonimartins** [comment]
Same here.

Terminal:
```
krl@kgudnmrtns:~$ jupyter --version
4.2.0
``` 


R terminal:
```
> IRkernel::installspec()
Error in IRkernel::installspec() : 
  Jupyter or IPython 3.0 has to be installed but could neither run “jupyter” nor “ipython”, “ipython2” or “ipython3”.
(Note that “ipython2” is just IPython for Python 2, but still may be IPython 3.0)
```

**Comment by flying-sheep** [comment]
so this happens?

```console
$ jupyter --version
4.2.0
$ R
> IRkernel::installspec()
Error in IRkernel::installspec() : 
...
```

if so, i’m pretty stumped.

can you try:

```console
$ echo $PATH | tr : '\n'
$ R --slave -e 'cat(Sys.getenv("PATH"))' | tr : '\n'
```

**Comment by kguidonimartins** [comment]
Thanks!

**Comment by flying-sheep** [comment]
haha, why “thanks”? did it work after all? if so: what did?

**Comment by kguidonimartins** [comment]
It's working fine, mysteriously! hehehe

```
$ echo $PATH | tr : '\n'
/home/krl/anaconda3/bin
/home/krl/bin
/home/krl/.local/bin
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
/usr/games
/usr/local/games
/snap/bin
```

```
$ R --slave -e 'cat(Sys.getenv("PATH"))' | tr : '\n'
/home/krl/anaconda3/bin
/home/krl/bin
/home/krl/.local/bin
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
/usr/games
/usr/local/games
/snap/bin
```

So, thanks again.

**Comment by flying-sheep** [comment]
no problem!

hmm, was your “R terminal” perhaps the OSX R.app, or the R application from linux?

you really need to start it in a shell (like bash or ZSH) on some systems.

**Comment by kguidonimartins** [comment]
Yeap! I'm running via shell on Ubuntu 16.04.

**Comment by flying-sheep** [comment]
well, at least it works now. @Luxios i’ll close the issue, since using RGui probably caused it for you.

feel free to tell me (with details) if that wasn’t the case.
