### ISSUE TITLE
Problems with devtools

### ISSUE THREAD

**Issue by oilujcesarv** [IRkernel/IRkernel#425]
I can't install the package 'devtools'

**Comment by takluyver** [comment]
What happens when you try? We can't help without some info about the problem!

**Comment by oilujcesarv** [comment]
I use 'install.packages("devtools")' and after de instalation been colcluded I can't activate the package using 'library(devtools)'. 
After many times I realize it has shown the mensage: 

**Warning in install.packages :
  installation of package ‘devtools’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmpaduq2F/downloaded_packages’**

**Comment by flying-sheep** [comment]
> `installation of package ‘devtools’ had non-zero exit status`

this means it didn’t install.

you also didn’t give us the whole relevant information: what comes between `install.packages("devtools")` and `**Warning in install.packages :`?

**Comment by oilujcesarv** [comment]
the whole procedure:
> install.packages("devtools")
Installing package into ‘/home/julio/R/x86_64-pc-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
also installing the dependencies ‘curl’, ‘httr’

--2016-11-23 15:34:25--  https://cran.rstudio.com/src/contrib/curl_2.2.tar.gz
Resolvendo cran.rstudio.com (cran.rstudio.com)... 54.230.227.9
Conectando-se a cran.rstudio.com (cran.rstudio.com)|54.230.227.9|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 200 OK
Tamanho: 398330 (389K) [application/x-gzip]
Salvando em: “/tmp/Rtmpaduq2F/downloaded_packages/curl_2.2.tar.gz”

     0K .......... .......... .......... .......... .......... 12%  239K 1s
    50K .......... .......... .......... .......... .......... 25%  104K 2s
   100K .......... .......... .......... .......... .......... 38%  241K 1s
   150K .......... .......... .......... .......... .......... 51%  121K 1s
   200K .......... .......... .......... .......... .......... 64%  185K 1s
   250K .......... .......... .......... .......... .......... 77%  243K 1s
   300K .......... .......... .......... .......... .......... 89% 69,2K 0s
   350K .......... .......... .......... ........             100%  180K=2,7s

2016-11-23 15:34:33 (143 KB/s) - “/tmp/Rtmpaduq2F/downloaded_packages/curl_2.2.tar.gz” salvo [398330/398330]

--2016-11-23 15:34:33--  https://cran.rstudio.com/src/contrib/httr_1.2.1.tar.gz
Resolvendo cran.rstudio.com (cran.rstudio.com)... 54.230.227.9
Conectando-se a cran.rstudio.com (cran.rstudio.com)|54.230.227.9|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 200 OK
Tamanho: 133398 (130K) [application/x-gzip]
Salvando em: “/tmp/Rtmpaduq2F/downloaded_packages/httr_1.2.1.tar.gz”

     0K .......... .......... .......... .......... .......... 38% 41,9K 2s
    50K .......... .......... .......... .......... .......... 76% 84,0K 1s
   100K .......... .......... ..........                      100%  412K=1,9s

2016-11-23 15:34:39 (69,9 KB/s) - “/tmp/Rtmpaduq2F/downloaded_packages/httr_1.2.1.tar.gz” salvo [133398/133398]

--2016-11-23 15:34:39--  https://cran.rstudio.com/src/contrib/devtools_1.12.0.tar.gz
Resolvendo cran.rstudio.com (cran.rstudio.com)... 54.230.227.9
Conectando-se a cran.rstudio.com (cran.rstudio.com)|54.230.227.9|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 200 OK
Tamanho: 467113 (456K) [application/x-gzip]
Salvando em: “/tmp/Rtmpaduq2F/downloaded_packages/devtools_1.12.0.tar.gz”

     0K .......... .......... .......... .......... .......... 10% 1,45K 4m40s
    50K .......... .......... .......... .......... .......... 21% 1,28K 4m22s
   100K .......... .......... .......... .......... .......... 32% 1,13K 4m0s
   150K .......... .......... .......... .......... .......... 43%  846  3m48s
   200K .......... .......... .......... .......... .......... 54% 1,43K 2m56s
   250K .......... .......... .......... .......... .......... 65%  799  2m24s
   300K .......... .......... .......... .......... .......... 76%  529  1m54s
   350K .......... .......... .......... .......... .......... 87% 1,16K 59s
   400K .......... .......... .......... .......... .......... 98% 1,98K 6s
   450K ......                                                100% 14,2K=7m23s

2016-11-23 15:42:03 (1,03 KB/s) - “/tmp/Rtmpaduq2F/downloaded_packages/devtools_1.12.0.tar.gz” salvo [467113/467113]

* installing *source* package ‘curl’ ...
** package ‘curl’ successfully unpacked and MD5 sums checked
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
Using PKG_CFLAGS=
Using PKG_LIBS=-lcurl
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libcurl was not found. Try installing:
 * deb: libcurl4-openssl-dev (Debian, Ubuntu, etc)
 * rpm: libcurl-devel (Fedora, CentOS, RHEL)
 * csw: libcurl_dev (Solaris)
If libcurl is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libcurl.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘curl’
* removing ‘/home/julio/R/x86_64-pc-linux-gnu-library/3.2/curl’
Warning in install.packages :
  installation of package ‘curl’ had non-zero exit status
ERROR: dependency ‘curl’ is not available for package ‘httr’
* removing ‘/home/julio/R/x86_64-pc-linux-gnu-library/3.2/httr’
Warning in install.packages :
  installation of package ‘httr’ had non-zero exit status
ERROR: dependency ‘httr’ is not available for package ‘devtools’
* removing ‘/home/julio/R/x86_64-pc-linux-gnu-library/3.2/devtools’
Warning in install.packages :
  installation of package ‘devtools’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmpaduq2F/downloaded_packages’

**Comment by flying-sheep** [comment]
this is the relevant part:

```
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libcurl was not found. Try installing:
 * deb: libcurl4-openssl-dev (Debian, Ubuntu, etc)
 * rpm: libcurl-devel (Fedora, CentOS, RHEL)
 * csw: libcurl_dev (Solaris)
If libcurl is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libcurl.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
```

just follow those instructions 😄

**Comment by oilujcesarv** [comment]
I tryed but it wont work.
I found a solution that worked to me.
The solution is here:
`http://stackoverflow.com/questions/20923209/problems-installing-the-devtools-package`

**Comment by oilujcesarv** [comment]
Thanks for help!
