### ISSUE TITLE
IRkernel::installspec converts name (installation path) to lower case

### ISSUE THREAD

**Issue by timothymillar** [IRkernel/IRkernel#427]
We're using the IRkernel (Version: 0.6) with Jupyterhub installed inside an anaconda virtual environment.
When trying to install the kernelspec inside the environment dir (this makes it available globally), the path is converted to lower case and the kernelspec gets installed in the wrong location.

example:
```
Rscript -e "IRkernel::installspec(name = '/path/to/anacondaEnvironment/share/jupyter/kernels/ir3.3.0', displayname = 'R-3.3.0')"
```
and the kernelspec will end up in: `/path/to/anacondaenvironment/share/jupyter/kernels/ir3.3.0`

A simple workaround is to move kernelspec to the correct location after installation (the kernelspec file itself is fine)

Thanks, Tim.

**Comment by takluyver** [comment]
`name` is intended to be a name, e.g. `ir3.3.0`. It's an accident that you can kind of use it to specify a full path, and it's not a good idea to rely on that.

IRkernel doesn't currently expose the options Jupyter provides to install a kernelspec to a given prefix, or to the prefix in which Jupyter runs. But it's a reasonable feature request to add those.

**Comment by timothymillar** [comment]
That's reasonable, I'll make a new feature request.
Thanks for the quick response.
