### ISSUE TITLE
Feature request: option to specify full path with installspec

### ISSUE THREAD

**Issue by timothymillar** [IRkernel/IRkernel#428]
We're using the IRkernel with Jupyterhub installed inside an anaconda virtual environment.

It would be convenient to install the kernelspec directly into the environment dir (this makes it available globally) e.g:

```
Rscript -e "IRkernel::installspec(prefix = '/path/to/anacondaEnvironment/share/jupyter/kernels/ir3.3.0', displayname = 'R-3.3.0')"
```

This can sort of be achieved by specifying the full path with the `name` argument but is not the intended behavior  (see #427).

**Comment by takluyver** [comment]
Assuming we expose the options from Jupyter directly, the call would look like:

```r
installspec(prefix='/path/to/anacondaEnvironment', name='ir3.3.0', displayname='R 3.3.0')
```

The `share/jupyter/kernels` part of the path is added in automatically.

**Comment by flying-sheep** [comment]
so what we do now (and what will be the `prefix` default) is “determine via calling `jupyter`”, right?

**Comment by takluyver** [comment]
Yeah, `jupyter kernelspec install` has a `--prefix` option to specify where to install to. I'd just pass through to that. If it's not specified, it picks a default location.

`prefix` and `user` are mutually exclusive (or setting both means one is ignored).

**Comment by timothymillar** [comment]
added in  #512
