### ISSUE TITLE
Ask for password prompt

### ISSUE THREAD

**Issue by nfx** [IRkernel/IRkernel#429]
How would it be possible to write ask-for-password prompt within this kernel's notebook, so that password chars would not be displayed?

**Comment by takluyver** [comment]
We'd need to implement the [input_request message](http://jupyter-client.readthedocs.io/en/latest/messaging.html#messages-on-the-stdin-router-dealer-channel) from the Jupyter spec, which is issue #199. Once that's done, providing a way to use that with hidden input is simple.

**Comment by jgbradley1** [comment]
I'd like to point out that the [getPass](https://github.com/wrathematics/getPass) package may provide this capability. It will depend on how [#199](https://github.com/IRkernel/IRkernel/issues/199) is solved.

**Comment by jgbradley1** [comment]
This issue should be closed now.

**Comment by flying-sheep** [comment]
thanks!
