### ISSUE TITLE
Suddenly jupyter does not handle svg plots anymore

### ISSUE THREAD

**Issue by smartinsightsfromdata** [IRkernel/IRkernel#431]
This is my environment:

OSX 10.12.2 - R 3.3.2 + RStudio Server 1.0.44 (installed together with homebrew)
Anaconda python 3.5 - jupyter 1.0.0 py35_3

I had a perfectly working installation.
Sadly I had to re-install Anaconda python 3.5.  All works fine python side.

I had some issue re-installing `IRkernel`: earlier I didn't have problems setting `IRkernel::installspec()` from RStudio, this time either from RStudio or R at the command line I had to use Sys.setenv to set up the anaconda path, otherwise IRkernel wasn't able to find python / jupyter.

Now all things I tested work fine, except `svg` graphics, i.e. when I use:

```
options(jupyter.plot_mimetypes = "image/svg+xml") 
```

With this option set, when I try to plot something I get:

```
Error in file(con, "rb"): cannot open the connection
Traceback:
```

I do not get any traceback nor any graph output.

SVG graphics works with python.

And, just in case, this is the output of `capabilities()`

```
jpeg
TRUE
png
TRUE
tiff
TRUE
tcltk
TRUE
X11
FALSE
aqua
TRUE
http/ftp
TRUE
sockets
TRUE
libxml
TRUE
fifo
TRUE
cledit
FALSE
iconv
TRUE
NLS
TRUE
profmem
TRUE
cairo
TRUE
ICU
TRUE
long.double
TRUE
libcurl
TRUE
```

**Comment by flying-sheep** [comment]
do you get any output in the console log (i.e. the terminal `jupyter notebook` runs in)?

**Comment by smartinsightsfromdata** [comment]
I resolved it.  

When I removed the library `Cairo` in R and tried to re-install, it failed due to missing libraries (I must inadvertently deleted `Cairo` in `homebrew`, probably months ago.

Interestingly everything worked till I had to re-install IRkernel.

Thanks for the help.

**Comment by flying-sheep** [comment]
great that it works!
