### ISSUE TITLE
Unable to connect to IRkernel

### ISSUE THREAD

**Issue by musigma-admin** [IRkernel/IRkernel#433]
I have installed IRkernel using devtools. R version is 3.3.1
R is working fine from Terminal.
But When try to launch it from Jupyter notebook getting the error "No connection to Kernel".

What could be the issue.

**Comment by flying-sheep** [comment]
what does the console output of `jupyter notebook` say?

**Comment by musigma-admin** [comment]
Getting the following error

root@jupyterhub:~# jupyter console kernel=ir
Jupyter Console 4.1.1


In [1]: library('IRkernel');
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-3e32a9c99180> in <module>()
----> 1 library('IRkernel');

NameError: name 'library' is not defined


root@jupyterhub:~# jupyter console kernel=irkernel
Jupyter Console 4.1.1


In [1]: sessionInfo()
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-64bc98b781dd> in <module>()
----> 1 sessionInfo()

NameError: name 'sessionInfo' is not defined

**Comment by musigma-admin** [comment]
and also I am able to initialize the library in R from terminal

root@jupyterhub:~# R

R version 3.3.1 (2016-06-21) -- "Bug in Your Hair"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library('IRkernel');

**Comment by musigma-admin** [comment]
Unable to initialize ipython kernels too

root@jupyterhub:~# jupyter kernelspec list
Available kernels:
  octave_kernel    /usr/local/share/jupyter/kernels/octave_kernel
  python3          /usr/local/share/jupyter/kernels/python3
root@jupyterhub:~# jupyter kernelspec install python3
[InstallKernelSpec] Removing existing kernelspec in /usr/local/share/jupyter/kernels/python3
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-kernelspec", line 11, in <module>
    sys.exit(KernelSpecApp.launch_instance())
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/usr/local/lib/python3.4/dist-packages/jupyter_client/kernelspecapp.py", line 269, in start
    return self.subapp.start()
  File "/usr/local/lib/python3.4/dist-packages/jupyter_client/kernelspecapp.py", line 141, in start
    replace=self.replace,
  File "/usr/local/lib/python3.4/dist-packages/jupyter_client/kernelspec.py", line 269, in install_kernel_spec
    shutil.copytree(source_dir, destination)
  File "/usr/lib/python3.4/shutil.py", line 297, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: 'python3'
root@jupyterhub:~# jupyter kernelspec install octave_kernel
[InstallKernelSpec] Removing existing kernelspec in /usr/local/share/jupyter/kernels/octave_kernel
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-kernelspec", line 11, in <module>
    sys.exit(KernelSpecApp.launch_instance())
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/usr/local/lib/python3.4/dist-packages/jupyter_client/kernelspecapp.py", line 269, in start
    return self.subapp.start()
  File "/usr/local/lib/python3.4/dist-packages/jupyter_client/kernelspecapp.py", line 141, in start
    replace=self.replace,
  File "/usr/local/lib/python3.4/dist-packages/jupyter_client/kernelspec.py", line 269, in install_kernel_spec
    shutil.copytree(source_dir, destination)
  File "/usr/lib/python3.4/shutil.py", line 297, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: 'octave_kernel'

**Comment by musigma-admin** [comment]
Tried to reinstall ipython kernel

root@jupyterhub:~#  python2 -m pip install ipykernel
Requirement already satisfied (use --upgrade to upgrade): ipykernel in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): traitlets in /usr/local/lib/python2.7/dist-packages (from ipykernel)
Requirement already satisfied (use --upgrade to upgrade): ipython>=4.0.0 in /usr/local/lib/python2.7/dist-packages (from ipykernel)
Requirement already satisfied (use --upgrade to upgrade): jupyter-client in /usr/local/lib/python2.7/dist-packages (from ipykernel)
Requirement already satisfied (use --upgrade to upgrade): tornado>=4.0 in /usr/local/lib/python2.7/dist-packages (from ipykernel)
Requirement already satisfied (use --upgrade to upgrade): decorator in /usr/local/lib/python2.7/dist-packages (from traitlets->ipykernel)
Requirement already satisfied (use --upgrade to upgrade): ipython-genutils in /usr/local/lib/python2.7/dist-packages (from traitlets->ipykernel)
Requirement already satisfied (use --upgrade to upgrade): setuptools>=18.5 in /usr/local/lib/python2.7/dist-packages (from ipython>=4.0.0->ipykernel)
Requirement already satisfied (use --upgrade to upgrade): pickleshare in /usr/local/lib/python2.7/dist-packages (from ipython>=4.0.0->ipykernel)
Requirement already satisfied (use --upgrade to upgrade): pexpect; sys_platform != "win32" in /usr/local/lib/python2.7/dist-packages (from ipython>=4.0.0->ipykernel)
Requirement already satisfied (use --upgrade to upgrade): simplegeneric>0.8 in /usr/local/lib/python2.7/dist-packages (from ipython>=4.0.0->ipykernel)
Requirement already satisfied (use --upgrade to upgrade): backports.shutil-get-terminal-size in /usr/local/lib/python2.7/dist-packages (from ipython>=4.0.0->ipykernel)
Requirement already satisfied (use --upgrade to upgrade): pyzmq>=13 in /usr/local/lib/python2.7/dist-packages (from jupyter-client->ipykernel)
Requirement already satisfied (use --upgrade to upgrade): jupyter-core in /usr/local/lib/python2.7/dist-packages (from jupyter-client->ipykernel)
Requirement already satisfied (use --upgrade to upgrade): backports.ssl_match_hostname in /usr/local/lib/python2.7/dist-packages (from tornado>=4.0->ipykernel)
Requirement already satisfied (use --upgrade to upgrade): singledispatch in /usr/local/lib/python2.7/dist-packages (from tornado>=4.0->ipykernel)
Requirement already satisfied (use --upgrade to upgrade): certifi in /usr/local/lib/python2.7/dist-packages (from tornado>=4.0->ipykernel)
Requirement already satisfied (use --upgrade to upgrade): backports_abc>=0.4 in /usr/local/lib/python2.7/dist-packages (from tornado>=4.0->ipykernel)
Requirement already satisfied (use --upgrade to upgrade): pathlib2; python_version in "2.6 2.7 3.2 3.3" in /usr/local/lib/python2.7/dist-packages (from pickleshare->ipython>=4.0.0->ipykernel)
Requirement already satisfied (use --upgrade to upgrade): ptyprocess>=0.5 in /usr/local/lib/python2.7/dist-packages (from pexpect; sys_platform != "win32"->ipython>=4.0.0->ipykernel)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/dist-packages (from singledispatch->tornado>=4.0->ipykernel)
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Below are the available versions
root@jupyterhub:~# pip freeze |grep python
ipython==4.2.0
ipython-genutils==0.1.0
python-apt===0.9.3.5ubuntu2
python-dateutil==2.5.3
root@jupyterhub:~# pip freeze |grep jupyter
jupyter-client==4.2.2
jupyter-cms==0.5.0
jupyter-core==4.1.0
jupyterhub==0.6.1
root@jupyterhub:~# pip freeze |grep notebook
notebook==4.2.0
root@jupyterhub:~# pip freeze |grep ipython
ipython==4.2.0
ipython-genutils==0.1.0
root@jupyterhub:~# pip freeze |grep ipykernel
ipykernel==4.2.2

**Comment by flying-sheep** [comment]
it’s `jupyter console --kernel=ir`

and make sure you followed the instructions on https://irkernel.github.io/installation, not others.

**Comment by musigma-admin** [comment]
I have followed the same instructions as per the above link but unable to initialize kernel from jupyterhub as it is keep on trying to connect it.

and also after some time unable to see the IRkernel from console also...... 

root@jupyterhub:~# jupyter kernelspec list
Available kernels:
  python3    /usr/local/lib/python3.4/dist-packages/ipykernel/resources
  ir         /usr/local/share/jupyter/kernels/ir
  python2    /usr/local/share/jupyter/kernels/python2

root@jupyterhub:~# jupyter kernelspec install ir
[InstallKernelSpec] Removing existing kernelspec in /usr/local/share/jupyter/kernels/ir
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-kernelspec", line 11, in <module>
    sys.exit(KernelSpecApp.launch_instance())
  File "/usr/local/lib/python3.4/dist-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/usr/local/lib/python3.4/dist-packages/jupyter_client/kernelspecapp.py", line 269, in start
    return self.subapp.start()
  File "/usr/local/lib/python3.4/dist-packages/jupyter_client/kernelspecapp.py", line 141, in start
    replace=self.replace,
  File "/usr/local/lib/python3.4/dist-packages/jupyter_client/kernelspec.py", line 269, in install_kernel_spec
    shutil.copytree(source_dir, destination)
  File "/usr/lib/python3.4/shutil.py", line 297, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: 'ir'
root@jupyterhub:~# jupyter console --kernel=ir
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-console", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-115>", line 2, in initialize
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jupyter_console/app.py", line 138, in initialize
    self.init_shell()
  File "/usr/local/lib/python2.7/dist-packages/jupyter_console/app.py", line 105, in init_shell
    JupyterConsoleApp.initialize(self)
  File "/usr/local/lib/python2.7/dist-packages/jupyter_client/consoleapp.py", line 334, in initialize
    self.init_kernel_manager()
  File "/usr/local/lib/python2.7/dist-packages/jupyter_client/consoleapp.py", line 288, in init_kernel_manager
    self.kernel_manager.start_kernel(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jupyter_client/manager.py", line 230, in start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "/usr/local/lib/python2.7/dist-packages/jupyter_client/manager.py", line 170, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "/usr/local/lib/python2.7/dist-packages/jupyter_client/manager.py", line 82, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/usr/local/lib/python2.7/dist-packages/jupyter_client/kernelspec.py", line 175, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named ir

**Comment by flying-sheep** [comment]
don’t do `jupyter kernelspec install ir`.

`IRkernel::installspec()` installs it, after that you can just use it.

**Comment by musigma-admin** [comment]
But I want to use that kernel through system wide instead of user wide

**Comment by musigma-admin** [comment]
and also same issue with ipython kernels as well
Able to access from console but not from Jupyter notebook

**Comment by flying-sheep** [comment]
> But I want to use that kernel through system wide instead of user wide

read this again 😄 https://irkernel.github.io/installation

**Comment by musigma-admin** [comment]
Yes. I did the same as per the link but unable to connect to kernel as it is keep on trying to reconnect it.
Even unable to connect to Ipython kernels as well but console is working fine...

Not sure where the problem is....

**Comment by flying-sheep** [comment]
OK, so this happened?

```console
$ sudo R --slave -e 'IRkernel::installspec(user = FALSE)'
$ jupyter notebook
[No error here, but kernel can’t connect]
```

If so, I have no idea. There should be an error in the console.

**Comment by musigma-admin** [comment]
I ran the mentioned commands and below is the output.

root@jupyterhub:~# sudo R --slave -e 'IRkernel::installspec(user = FALSE)'
[InstallKernelSpec] Removing existing kernelspec in /usr/local/share/jupyter/kernels/ir
[InstallKernelSpec] Installed kernelspec ir in /usr/local/share/jupyter/kernels/ir
root@jupyterhub:~# jupyter notebook
[W 11:46:48.303 NotebookApp] Unrecognized JSON config file version, assuming version 1
[I 11:46:48.316 NotebookApp] Writing notebook server cookie secret to /run/user/0/jupyter/notebook_cookie_secret
[I 11:46:49.123 NotebookApp] Loaded jupyter_cms
[I 11:46:49.125 NotebookApp] Serving notebooks from local directory: /root
[I 11:46:49.125 NotebookApp] 0 active kernels
[I 11:46:49.125 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 11:46:49.125 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 11:46:49.125 NotebookApp] No web browser found: could not locate runnable browser.

**Comment by flying-sheep** [comment]
can you please put code or output between two lines consisting of three backticks in the future?

like

````
```
insert stuff here
```
````

**Comment by musigma-admin** [comment]
Sure.  
I hope there is a problem with proxy seems to be using IP address from the browser kernels are working fine but with url (as it was node proxied) access is fine but unable to connect to the kernels while running the queries.

What could be the reason. Any suggestion to make it work.

**Comment by flying-sheep** [comment]
I don’t know much about jupyterhub. Could you please file your issue at https://github.com/jupyterhub/jupyterhub?

If this isn’t a problem with the kernel, that’s the right spot for the issue anyway.

**Comment by ActuarialPaul** [comment]
I've been having a nightmare trying to install the IRkernel.

I followed the instructions on the following link: https://irkernel.github.io/installation 

In the R console I typed:
install.packages(c('repr', 'IRdisplay', 'evaluate', 'crayon', 'pbdZMQ', 'devtools', 'uuid', 'digest'))

then:

devtools::install_github('IRkernel/IRkernel')

however I get the following message:

Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Couldn't connect to server

Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Couldn't connect to server

**Comment by flying-sheep** [comment]
do you have a proxy or something? the error is what it says: R can’t connect to the server (I assume github.com) in order to download IRkernel

check here for more: http://stackoverflow.com/questions/16740256/error-installing-packages-from-github
