### ISSUE TITLE
Cant instal IRkernel (Use `force = TRUE` to force installation)

### ISSUE THREAD

**Issue by Ksyula** [IRkernel/IRkernel#436]
Trying to follow the Installation Manual here https://irkernel.github.io/installation/ faced with problem.
Run this commands inside R:

```r
install.packages(c('repr', 'IRdisplay', 'evaluate', 'crayon', 'pbdZMQ', 'devtools', 'uuid', 'digest'))
devtools::install_github('IRkernel/IRkernel')
```

And have this issue:

```r
devtools::install_github('IRkernel/IRkernel')
Skipping install of 'IRkernel' from a github remote, the SHA1 (ff78a040) has not changed since last install.
  Use `force = TRUE` to force installation
```

Cant perform next steps because the system(OS X 10.10.5) doesn't see IRkernel
Didn't find the appropriate solution of this in other questions.
Please, give me an advice how to solve it.

**Comment by takluyver** [comment]
Weird. If it thinks it's installed, try uninstalling it and installing again?

**Comment by Ksyula** [comment]
Yes, I tried to instal it the second time, because first time the IRkernel also was not found and commands:
jupyter qtconsole --kernel=ir
jupyter console --kernel=ir
didnt understand "ir"

If I have to reinstall R because of this, could you give me a couple advices for right way to remove it? Or simple App removing is enough?

**Comment by takluyver** [comment]
What happens when you run `IRkernel::installspec()` in R? That step is what tells Jupyter about IRkernel.

**Comment by Ksyula** [comment]
According to the Manual I run IRkernel::installspec() in the console (not in R App) and in this case nothing happened.
Now I run IRkernel::installspec() in in R App and have this:
 ```
> IRkernel::installspec()
Error in IRkernel::installspec() : 
  Jupyter or IPython 3.0 has to be installed but could neither run “jupyter” nor “ipython”, “ipython2” or “ipython3”.
(Note that “ipython2” is just IPython for Python 2, but still may be IPython 3.0) 
```

**Comment by takluyver** [comment]
Yup, that error is why we say to run it in R in the console. Is there no error or anything when you do that?

**Comment by Ksyula** [comment]
I suppose that the one thing that goes wrong is: 
```
devtools::install_github('IRkernel/IRkernel')
Skipping install of 'IRkernel' from a github remote, the SHA1 (ff78a040) has not changed since last install.
  Use `force = TRUE` to force installation
```
Other packages was successfully installed in R.
When I try to run IRkernel::installspec() in console, then see this and nothing happens:
```
~ Ksenia$ IRkernel::installspec()
>
```
May be there is workaround how to run devtools::install_github('IRkernel/IRkernel') another way or from another source?

**Comment by takluyver** [comment]
Ah, OK. You need to run that in the console,  but using R. I.e.:

```
~ Ksenia$ R
R version ...
> IRkernel::installspec()
...output...
> q()
Save workspace image? [y/n/c]: n
```

**Comment by Ksyula** [comment]
Great! Thank you! Now all is working!
Sorry for disturbing!

**Comment by takluyver** [comment]
No problem, glad you got it working.

**Comment by DivyaPasumarthi** [comment]
devtools::install_github('IRkernel/IRkernel')
Downloading GitHub repo IRkernel/IRkernel@master
Error: Failed to install 'IRkernel' from GitHub:
  Git does not seem to be installed on your system.
> IRkernel::installspec()
Error in loadNamespace(name) : there is no package called 'IRkernel'


Can some one please help me with this error? I am trying to install R in Jupyter Lab notebook.
But when I run the above command it gives me this error.

**Comment by flying-sheep** [comment]
Well, the error clearly states the problem: You’re trying to install via git, and don’t have git itself installed. Either install via CRAN instead (`install.packages('IRkernel')`) or install git and put it on your PATH.
