### ISSUE TITLE
CRAN submission

### ISSUE THREAD

**Issue by cschwem2er** [IRkernel/IRkernel#438]
Hi,

first of all thanks for all the work you already put in ````IRkernel````. Do you have a rough schedule for when the package will hit CRAN? I'm asking because I'd like to use it for teaching but at out university installing from github is problematic.

**Comment by takluyver** [comment]
We did submit it before, but we ran into some difficulties because it doesn't conform to the normal expectations of what a package does. I don't think there was ever a definite rejection, and I still hope it will be on CRAN one day, but we didn't seem to be making much progress, and the conversation went quiet.

**Comment by methodds** [comment]
Hi there,
are there any news on this? I'd love to use the IRkernel for teaching, but getting it installed on the university computers will be hard without a CRAN version.

**Comment by flying-sheep** [comment]
no. i went through the process, there was some hiccup on their side (jupyter not installed properly i guess), and after i offered advice how to fix it, they simply stopped responding and ignored my friendly followups (like “hi, after some while i just wanted to check if i can help you with something to get this to proceed, bla bla”)

😢

**Comment by methodds** [comment]
hmmm I wonder if @kbenoit has any tips regarding the CRAN submission procedure. He recently published an [R wrapper for spacy](https://github.com/kbenoit/spacyr) on CRAN und I might have experienced similar problems.

**Comment by kbenoit** [comment]
We got it passed pretty easily wrt the Python side, because our tests don't run on CRAN, just on Travis, and our examples are `\donttest{`ed. So the check does not actually require spaCy or Python to be installed.

It also helped a great deal that the **reticulate** package was published on CRAN - before this was the case, we went through some painful experiences with Rcpp/Python integration (well, painful for Windows users at least).

**Comment by flying-sheep** [comment]
the submission procedure is no problem: i did everything they wanted from me and helped them diagnose the reason for the test failure to the best of my ability.

it’s just that they for some reason (probably lack of time) stopped trying to fix it.

**Comment by methodds** [comment]
Argh that sucks :/. Any chance you give it another try? A CRAN submission would be a big deal imo. In case I can be of any help please tell me.

**Comment by QuLogic** [comment]
Any more updates? At the very least, can `DESCRIPTION` be fixed so that `R CMD check` passes?

**Comment by takluyver** [comment]
It's telling me:

```
Required fields missing or empty:
  ‘Author’ ‘Maintainer’
```

But we're giving the author information in the same format as e.g. [testthat](https://github.com/r-lib/testthat/blob/master/DESCRIPTION). So I don't think that can really be a problem.

**Comment by methodds** [comment]
Hi,
did you read through Hadleys notes for [checking a package](http://r-pkgs.had.co.nz/check.html)? This might be useful.

**Comment by flying-sheep** [comment]
it has’t been a problem until now, they must have changed something 🙄

**Comment by QuLogic** [comment]
What version of R? I get the same results as @takluyver with 3.4.1 (2017-06-30).

**Comment by flying-sheep** [comment]
> R version 3.4.2 (2017-09-28)

**Comment by QuLogic** [comment]
OK, so the interesting thing is that `repr` works from the tarball on CRAN, but doesn't work straight from a git checkout. And `repr` has `Authors@R` and `Maintainer`, but no `Author`. The CRAN tarball _does_ have `Author`, so I guess this is something done automatically with CRAN submission.

**Comment by flying-sheep** [comment]
Hmm, I submitted IRkernel again some time ago, but heard nothing back. I wrote a mail to Uwe Ligges (CRAN maintainer) asking about it. (I CCd @takluyver)

**Comment by flying-sheep** [comment]
we’re on CRAN now wheee!

**Comment by QuLogic** [comment]
Yay, now I can [make a package for Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1666942)!

**Comment by flying-sheep** [comment]
awesome!
