### ISSUE TITLE
Limit R kernel memory

### ISSUE THREAD

**Issue by valentas-kurauskas** [IRkernel/IRkernel#439]
Due to the nature of connection I have trouble terminating Jupyter R scripts when the memory usage accidentally gets out of control.

In Linux I can limit memory by calling my script e.g. with
    #!/bin/bash
    ulimit -Sv 2000000
    R myscript.R

Is it possible to override the default R path /usr/lib/R/bin/exec/R in IRkernel?

**Comment by takluyver** [comment]
Use `jupyter kernelspec list` to see where the `ir` kernelspec is installed. There should be a `kernel.json` in there which contains the path to `R`. You should be able to edit that to use a script instead.

**Comment by valentas-kurauskas** [comment]
Thank you, takluyver, this solves my issue.
