### ISSUE TITLE
Bioconductor annotation packages

### ISSUE THREAD

**Issue by drisso** [IRkernel/IRkernel#44]
After loading the Bioconductor `org.Sc.sgd.db` package (and its dependencies)

    library(org.Sc.sgd.db)
    as.list(org.Sc.sgdGENENAME)

works in a standard console but fails in IPython notebook with the error

    Error in as.list.default(org.Sc.sgdGENENAME): no method for coercing this S4 class to a vector

In the standard console `showMethods("as.list")` returns

    Function: as.list (package base)
    x="AgiAnnDbMap"
    x="AnnDbBimap"
      (inherited from: x="Bimap")
    x="ANY"
    x="Bimap"
    x="CompressedAtomicList"
    x="CompressedNormalIRangesList"
    x="FlatBimap"
    x="GoAnnDbBimap"
    x="GOTermsAnnDbBimap"
    x="Hits"
    x="IpiAnnDbMap"
    x="List"
    x="Rle"
    x="SimpleList"
    x="Vector"

while in IPython it returns

    Function: as.list (package base)
    x="AgiAnnDbMap"
    x="ANY"
    x="Bimap"
    x="CompressedAtomicList"
    x="CompressedNormalIRangesList"
    x="FlatBimap"
    x="GoAnnDbBimap"
    x="GOTermsAnnDbBimap"
    x="Hits"
    x="IpiAnnDbMap"
    x="List"
    x="Rle"
    x="SimpleList"
    x="Vector"

So it seems that for some reason the `as.list` method for the `AnnDbBimap` doesn't get inherited from `Bimap` in IPython.

**Comment by flying-sheep** [comment]
this was probably fixed by #71, can you confirm?

**Comment by takluyver** [comment]
Closing this on the grounds that it's probably fixed; we can reopen if someone can reproduce it.
