### ISSUE TITLE
Using Revoscale R functions from Jupyterhub

### ISSUE THREAD

**Issue by sudipto84goswami** [IRkernel/IRkernel#440]
Hi Team,

Just wanted to check with you if we can use Revoscale R function with with R Kernel from Jupyterhub notepad.

The R version Installed:
platform --> "x86_64-pc-linux-gnu"
os -->  "linux-gnu"
version.string --> "R version 3.3.1 (2016-06-21)"

Is there any away we can use Microsoft R on Jupyerhub. Specifically we are more interested in using the following packages:
1. rxGetOption
2. subselect
3. XLconnect

Please let us know on how to proceed on this further.

**Comment by flying-sheep** [comment]
i don’t know how “Microsoft R” works: is it simply an alternative implementation?

you could look for the IRkernel spec:

```console
$ ls ~/.local/share/jupyter/kernels/
ir/
$ cat ~/.local/share/jupyter/kernels/ir/kernel.json
{
  "argv": ["/usr/lib64/R/bin/R", "--slave", "-e", "IRkernel::main()", "--args", "{connection_file}"],
  "display_name": "R",
  "language": "R"
}
```

and then copy/change it so that it uses whatever path leads to microsoft’s R binary.

if the modules aren’t too different from GNU R, it could work.

**Comment by sudipto84goswami** [comment]
Thanks Philipp for your response.

I have the entry something like below:
{"argv": ["R", "--slave", "-e", "IRkernel::main()", "--args", "{connection_file}"],
 "display_name":"R",
 "language":"R"
}

I didn't get anything like pip install for Microsoft R. So is it somewhere integrated with Jupyterhub.
Secondly, I would like to get the packages rxGetOption,subselect & XLconnect to be used from the current installation. How do it get this done?

**Comment by takluyver** [comment]
I don't know what Microsoft R is or how you can get it, but if you can get it, you should be able to install IRkernel inside it following the usual install instructions.

You should be able to install extra packages using the `install.packages()` function as normal.

**Comment by sudipto84goswami** [comment]
Thanks Thomas for your response!

I am not sure if anyone has implemented the version of R which supports the Revoscale R functions along with Jupyterhub notepad on Linux environment.

The intention is to check if this is compatible with each other. Or if there is any other mechanism which can be adopted to use the packages like rxGetOpton, Subselect & XLconnect. And how to achieve the same.

**Comment by flying-sheep** [comment]
> I am not sure if anyone has implemented the version of R which supports the Revoscale R functions along with Jupyterhub notepad on Linux environment.

microsoft R can just install normal R packages as usual right?

so simply follow our [install instructions](https://irkernel.github.io/installation/) using microsoft R instead of GNU R and it should work.

**Comment by sudipto84goswami** [comment]
We are trying to install the Microsoft R Packages on Linux R. I tried to invoke the install.package method 
from our Linux Jupyter host and get the following error:

> install.packages("rxGetOption")
--- Please select a CRAN mirror for use in this session ---
Error in download.file(url, destfile = f, quiet = TRUE) :
  unsupported URL scheme
HTTPS CRAN mirror

 1: 0-Cloud [https]             2: Austria [https]
 3: China (Beijing 4) [https]   4: China (Hefei) [https]
 5: Colombia (Cali) [https]     6: France (Lyon 2) [https]
 7: Iceland [https]             8: Russia (Moscow 1) [https]
 9: Switzerland [https]        10: UK (Bristol) [https]
11: UK (Cambridge) [https]     12: USA (CA 1) [https]
13: USA (KS) [https]           14: USA (MI 1) [https]
15: USA (TN) [https]           16: USA (TX) [https]
17: USA (WA) [https]           18: (HTTP mirrors)


Selection: 1
Warning: unable to access index for repository https://cran.rstudio.com/src/contrib
Warning message:
package ârxGetOptionâ is not available (for R version 3.2.2)

i did tried with other mirrors to, but the result being the same.

Regards,
Sudipta

**Comment by flying-sheep** [comment]
is that a package from microsoft r? no idea how you install those, but it’s not a problem with IRkernel, right?

**Comment by sudipto84goswami** [comment]
IR Kernel seems to be working fine. No issues with this.

Yes the packages mentioned are Revoscale R function which belongs to Microsoft R. And I am just checking with you, if there is any possibility of using those function with IR which is running on a Linux based OS as is the case with mine.

So whenever I am trying to use : install.packages("rxGetOption") from the R prompt on Linux Platform it says that the package is not present with the R -version 3.3.1.

So I raised the question in this forum to check if any one have faced this kind of issues and what will be the resolution for the same.

Let me know if I could make you understand on the exact requirement!

**Comment by takluyver** [comment]
[This page](https://msdn.microsoft.com/en-us/microsoft-r/scaler/rxgetoption) looks like rxGetOption is a function, not a package.  I can't see anything saying what package to install. [This page](https://www.blue-granite.com/tutorials/sql-server-r-services) seems to say that those functions are only available in a special version of R from Microsoft.

**Comment by RajiniSree** [comment]
Hi,

Though late, I'll try to jot down the solution so that it can help someone in future.

rxGetOption and all rx functions are Microsoft's implementation to handle parallel processing with big data ecosystem. These come packaged as part of RevoScaleR. If Microsoft R Open is installed, this comes prepackaged. If not try with the Microsoft's CRAN repo: https://mran.microsoft.com/

packages.install("RevoScaleR",repos="https://mran.microsoft.com/")

Also, if RevoScaleR is already available, check your libPaths to see if the packages from the directory are available to use. 

Check this by locating RevoScaleR in linux:
locate RevoScaleR
/opt/microsoft/rclient/3.4.1/libraries/RServer/RevoScaleR

Add this path to libPaths by
.libPaths(c(.libPaths(),"/opt/microsoft/rclient/3.4.1/libraries/RServer/RevoScaleR"))

**Comment by flying-sheep** [comment]
Thank you! I’ll close this now
