### ISSUE TITLE
Table misalignment when there is a value with an ampersand

### ISSUE THREAD

**Issue by valentas-kurauskas** [IRkernel/IRkernel#447]
With R backend `data.frame(letter=c("A",  "B&C", "D"), number=c(1000,2,30))`

Displays something like this:

| letter | value |
|--------|-------|
| A      | 1000  |
| A&B    | &nbsp; &nbsp; 2|
| C      | 30    |

The misaligned cell in html appears as `<span style="white-space:pre-wrap">   2</span>`

**Comment by flying-sheep** [comment]
huh, weird. can you file this in https://github.com/IRkernel/repr please?

**Comment by flying-sheep** [comment]
i’ll leave it open until then 😄
