### ISSUE TITLE
ggvis not completely working

### ISSUE THREAD

**Issue by valentas-kurauskas** [IRkernel/IRkernel#448]
A simple example code from this answer http://stackoverflow.com/a/24528087/2361465
```r
library(ggvis)
mtc <- mtcars
mtc$id <- 1:nrow(mtc)

all_values <- function(x) {
  if(is.null(x)) return(NULL)
  row <- mtc[mtc$id == x$id, ]
  paste0(names(row), ": ", format(row), collapse = "<br />")
}

mtc %>% ggvis(x = ~wt, y = ~mpg, key := ~id) %>%
  layer_points() %>%
  add_tooltip(all_values, "hover")
```
opens a new window with a plot but the tooltip does not work (at least on Ubuntu/Firefox). The tooltip works fine with the same code pasted into the R console.

1. Is it possible to fix interactivity for ggvis?
2. Is it possible embed interactive plots in the notebook?

**Comment by flying-sheep** [comment]
hi, why did you close it? did it work after an update or so?

**Comment by valentas-kurauskas** [comment]
It can be left open, but I realised the ggvis project is still at a too early stage (and from github activity it seems it has been for a while now) for production use integration with shiny as well, so this issue might not belong here, or may not be a priority.

**Comment by flying-sheep** [comment]
OK. we’ll revisit then!

**Comment by aakhmetz** [comment]
even if it is in early stage, the graphs look nice
it would be nice to get it worked :/

I have the same problem with opening the plot in a new window (not inline)

**Comment by flying-sheep** [comment]
sure, sorry.

it seems that `print(ggvis)` returns a `shiny.appobj` object. and `print.shiny.appobj` calls `shiny::runApp`.

i’m not sure if we can conceivably embed a shiny app, as they need a R runtime in the background. anyone an idea?
