### ISSUE TITLE
Installing R kernel on Windows 10

### ISSUE THREAD

**Issue by MoHeydarian** [IRkernel/IRkernel#450]
I following the instructions here (https://irkernel.github.io/installation/) to install the R kernel on a fresh Anaconda installation and I get the following error l on a Windows 10 machine: 

```
ERROR: dependency 'digest' is not available for package 'IRkernel'
 removing 'C:/Users/ladmin/Documents/R/win-library/3.3/IRkernel'
Error: Command failed (1)`
```

Would appreciate any insight, I don't want to go back to R Studio, I like using R in Jupyter.

**Comment by flying-sheep** [comment]
strange. it’s a dependency so it should have been installed automatically.

but maybe doing `install.packages('digest')` will fix this.

**Comment by MoHeydarian** [comment]
Thanks, that worked for me. 

Doing (in R):
`install.packages('digest')`
and then
`IRkernel::installspec()`

got my R kernel working. 

Thanks again!

I'll close this issue.

**Comment by spanesar91** [comment]
If my Notebook is not working where do i write install.packages('digest')

**Comment by flying-sheep** [comment]
just a regular R console!

**Comment by jmjamison** [comment]
I followed the above suggestions (have the same error) I tried:
Doing (in R):
install.packages('digest')
and then
IRkernel::installspec()
but I'm still getting the digest dependency error.  The install downloads the binary package then removes it because  of the digest dependency.

**Comment by flying-sheep** [comment]
i don’t get it. can you install the digest package by itself or not?

**Comment by jmjamison** [comment]
I tried installing digest by itself.

UCLA Library Data Archive
jamison@library.ucla.edu
http://orcid.org/0000-0002-5116-5724
310-825-0716


-----------------------------------------------------------------------------

"An asset is only an asset if you can access it ..."
AMIA (Association of Moving Image Archivists)/Digital Asset Symposium 2008

________________________________________

**Comment by flying-sheep** [comment]
so `install.packages('digest')` failed and you get the dependency error because of that? sadly, my crystal ball is broken so I can’t tell you why installing `digest` failed. could you study the error message and if you can’t figure it out, post it here so I can help you?

**Comment by jmjamison** [comment]
I finally have this working.  I think I may have confused R because I had an earlier 3.5 version and a later. I uninstalled, deleted any stray folders and did a clean install of 3.5.1 (windows 10). 

If helping windows users with this I find it is helpful to remind them to use R from the command line.

**Comment by flying-sheep** [comment]
we do that in the official install instructions: https://irkernel.github.io/installation/

![image](https://user-images.githubusercontent.com/291575/45345843-d30fe400-b5a7-11e8-849d-d71581b9e0ef.png)

however only for OS X. so we should also do that for windows?
