### ISSUE TITLE
Unable to print in  loop simultaneously

### ISSUE THREAD

**Issue by liqg** [IRkernel/IRkernel#453]
Help!

`for(i in 1:11){print(i); Sys.sleep(1)}`

This will print all after  finished, but I want to print information simultaneously, which is helpful for a long-time loop.

Thanks!

**Comment by flying-sheep** [comment]
duplicate of #3

**Comment by liqg** [comment]
@flying-sheep Thank you very much! I am sorry for not checking history carefully!

**Comment by flying-sheep** [comment]
no problem 😄
