### ISSUE TITLE
PDF creating failed

### ISSUE THREAD

**Issue by theasder** [IRkernel/IRkernel#454]
All of traceback is in the file.

[traceback.txt](https://github.com/IRkernel/IRkernel/files/875634/traceback.txt)

**Comment by flying-sheep** [comment]
the relevant part:

```tex
! Missing $ inserted.
<inserted text> 
                $
l.372     Substituting \$ \sigma
                                \^{}2\_\{t\textbar{}t-1\} = r\_t\^{}2 - \eta...

? 
! Emergency stop.
```

ok, please copy the notebook, remove all cells except for the one that causes the error, and then upload the notebook (e.g. as gist)

**Comment by theasder** [comment]
It doesn't work, when I try using inline mathematical formalae in text. Like this:

Since $ \eta_t = r^2_t - \sigma_{t|t-1}^2 $ and...

**Comment by flying-sheep** [comment]
like in markdown? please share an example file.

**Comment by theasder** [comment]
Yeah, in markdown. https://gist.github.com/theasder/646f9f1d0d53cc24f396fe8616355357

**Comment by flying-sheep** [comment]
don’t use spaces inside of $s, else the markdown engine doesn’t recogize it and thinks it’s literal $ signs:

```diff
-$ \sigma_{t|t-1}^2 = r_t^2 - \eta_t $
+$\sigma_{t|t-1}^2 = r_t^2 - \eta_t$
