### ISSUE TITLE
Non-printable characters cause tracebacks

### ISSUE THREAD

**Issue by QuLogic** [IRkernel/IRkernel#455]
For example, say you want to do a regular expression string replacement:
```r
library(stringr)
str_replace(month.name, "^(.).*(.)$", "\\1\\2")
```
```
     'Jy' 'Fy' 'Mh' 'Al' 'My' 'Je' 'Jy' 'At' 'Sr' 'Or' 'Nr' 'Dr' 
```
but you accidentally forget that you need to double the backslashes, so you do:
```r
str_replace(month.name, "^(.).*(.)$", "\1\2")
```
which produces a "character" of 1 and 2. This would print out fine (though incorrect) in R:
```r
> library(stringr)
> str_replace(month.name, "^(.).*(.)$", "\\1\\2")
 [1] "Jy" "Fy" "Mh" "Al" "My" "Je" "Jy" "At" "Sr" "Or" "Nr" "Dr"
> str_replace(month.name, "^(.).*(.)$", "\1\2")
 [1] "\001\002" "\001\002" "\001\002" "\001\002" "\001\002" "\001\002"
 [7] "\001\002" "\001\002" "\001\002" "\001\002" "\001\002" "\001\002"
```
But in the notebook, the cell remains busy and produces a traceback in the console:
```pytb
[E 19:38:01.400 NotebookApp] Uncaught exception GET /api/kernels/00957f93-0149-4452-ad62-a3ff185ded32/channels?session_id=CB53C2BE0FC240F38FC3B108E46CC92A (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/kernels/00957f93-0149-4452-ad62-a3ff185ded32/channels?session_id=CB53C2BE0FC240F38FC3B108E46CC92A', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Upgrade': 'websocket', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0', 'Accept-Language': 'en-CA,en-US;q=0.7,en;q=0.3', 'Cookie': 'username-localhost-8888="2|1:0|10:1490826815|23:username-localhost-8888|44:Y2U0NWNlNjgzZWIzNGQyMzlmMGUzZjVjNGJlZTFkNTU=|83d7bf60f7dc72f33e850b2e589d19461cbc60ac6e86604994124e9bd3231242"; firstVisit=1489393634410; _xsrf=2|b8d6d49b|4e510561a823723fc41e717b6c7130ee|1489856613', 'Sec-Websocket-Key': '0yQxj/oX3nDVkDRSVm2a0w==', 'Host': 'localhost:8888', 'Origin': 'http://localhost:8888', 'Sec-Websocket-Extensions': 'permessage-deflate', 'Connection': 'keep-alive, Upgrade', 'Accept-Encoding': 'gzip, deflate', 'Sec-Websocket-Version': '13', 'Cache-Control': 'no-cache', 'Pragma': 'no-cache'})
    Traceback (most recent call last):
      File "/usr/lib64/python3.5/site-packages/tornado/web.py", line 1424, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 3, in raise_exc_info
      File "/usr/lib64/python3.5/site-packages/tornado/stack_context.py", line 313, in wrapped
        ret = fn(*args, **kwargs)
      File "/usr/lib64/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/usr/lib/python3.5/site-packages/notebook/services/kernels/handlers.py", line 296, in _on_zmq_reply
        msg = self.session.deserialize(fed_msg_list)
      File "/usr/lib/python3.5/site-packages/jupyter_client/session.py", line 908, in deserialize
        message['content'] = self.unpack(msg_list[4])
      File "/usr/lib/python3.5/site-packages/jupyter_client/session.py", line 105, in <lambda>
        json_unpacker = lambda s: jsonapi.loads(s)
      File "/usr/lib64/python3.5/site-packages/zmq/utils/jsonapi.py", line 56, in loads
        return jsonmod.loads(s, **kwargs)
      File "/usr/lib64/python3.5/json/__init__.py", line 319, in loads
        return _default_decoder.decode(s)
      File "/usr/lib64/python3.5/json/decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib64/python3.5/json/decoder.py", line 355, in raw_decode
        obj, end = self.scan_once(s, idx)
    json.decoder.JSONDecodeError: Invalid control character at: line 1 column 54 (char 53)
```

**Comment by takluyver** [comment]
I think we're producing invalid JSON - the JSON spec says control characters are disallowed. I think they should be escaped like `\u0001`. @jeroen is this something you're aware of for jsonlite?

Of course, we should also be rendering them in some printable form, like you see in the R terminal - even if we produced valid JSON, the control characters wouldn't show up as something useful in the frontend.

**Comment by jeroen** [comment]
The jsonlite package [only escapes the characters](https://github.com/jeroen/jsonlite/blob/master/src/escape_chars.c#L18-L35) that should be escaped according to the spec: `\` `"` `\n` `\r` `\t` `\b` and `\f`.

**Comment by takluyver** [comment]
[This spec](https://tools.ietf.org/html/rfc7159#section-7) says:

> All Unicode characters may be placed within the quotation marks, except for the characters that must be escaped: quotation mark, reverse solidus, and the control characters (U+0000 through U+001F).

**Comment by takluyver** [comment]
i.e. I believe `\x01` and `\x02` do need to be escaped according to the spec, along with everything up to `\x1f`

**Comment by jeroen** [comment]
Hmmm I guess you're right. Strange this has never come up before.

**Comment by takluyver** [comment]
I guess there aren't that many times when you want a control character in a JSON string, other than the common ones with two-character escaped forms.

**Comment by jeroen** [comment]
It would really complicate the implementation I think because multi-char utf8 characters can contain bytes < 32 in which case they are not control characters.

**Comment by takluyver** [comment]
Not 100% sure, but I think UTF-8 bytes are never ambiguous - you can't mistake part of a multi-byte character for a single byte character. So I don't think it should be an issue.

**Comment by QuLogic** [comment]
All multi-byte Unicode characters have the first bit set, and cannot be mistaken for any of the 7-bit ASCII space.

**Comment by jeroen** [comment]
I think this is now fixed in https://github.com/jeroen/jsonlite/commit/3d8a9a3f32e0c6f5be95a718b92fc06a41b8495f. You can test in R with:

```r
devtools::install_github("jeroen/jsonlite")
```

**Comment by takluyver** [comment]
Thanks Jeroen!

We'll keep this issue open because we should still escape them for display,
separately from escaping them to make valid json. Maybe that's up to repr,
though.

**Comment by flying-sheep** [comment]
huh? are you sure? we already escape HTML for display, and text doesn’t need to be escaped.

where and why do you think we need to escape something?

**Comment by takluyver** [comment]
Non printable characters should be escaped, I think - e.g. unicode code point U+0001 should be displayed as something like `\u0001`, `\001` or `\x01`. This is orthogonal to the question of HTML escaping, which is an entirely different form of escaping.

E.g. like this in Python:

```
>>> print(repr(chr(1)))
'\x01'
```

**Comment by flying-sheep** [comment]
ah, so you’re saying that `repr_html('\1\2') == "'\001'"` should apply, just like in the R console, not as currently a literal `\1` (i.e. an invisible character)

**Comment by takluyver** [comment]
Yup, I think that the repr of a string should escape any non-printing characters. I don't particularly mind what form the escapes take, so long as it's clear and unambiguous. If R normally uses octal escapes like `\001`, let's follow that.

**Comment by flying-sheep** [comment]
@QuLogic, you said they were “incorrect”, what do you mean?

**Comment by QuLogic** [comment]
They were "incorrect" in _intent_, since they were supposed to be regex back-references, but because of the traceback, not even the wrong result appeared.

**Comment by flying-sheep** [comment]
ah, OK, so there’s nothing wrong with displaying them as `\001`, got it.

**Comment by flying-sheep** [comment]
OK. done in repr 0.11 (coming to CRAN soon)

**Comment by takluyver** [comment]
Thanks Philipp ☺

**Comment by jeroen** [comment]
FYI not sure it's still needed, but the fixed version of jsonlite 1.4 is now in cran (binaries will propagate in 1 or 2 days).

**Comment by takluyver** [comment]
👍 it may not be needed for this case, but I think it could still come up in a stream output, so I'm glad it's fixed.

**Comment by flying-sheep** [comment]
great!
