### ISSUE TITLE
rzmq is back alive

### ISSUE THREAD

**Issue by jeroen** [IRkernel/IRkernel#459]
FYI I have taken over maintenance of the [rzmq](https://cran.r-project.org/web/packages/rzmq/index.html) package and have published binaries on CRAN for both Windows and OSX with the latest `libzmq`.

A while ago IRkernel switched from `rzmq` to `pbdZMQ` because there were no binaries for `rzmq`. That problem is now solved. The main difference between `rzmq` and `pbdZMQ` is that the latter bundles a adapted version of `libzmq` source code with the R package, whereas `rmzq` uses the system version.

If you are happy with `pbdZMQ`, please close this issue, otherwise you can consider switching back.

**Comment by takluyver** [comment]
Thanks @jeroen for letting us know. @flying-sheep up to you whether we're happy with pbdZMQ or should consider switching.

**Comment by flying-sheep** [comment]
i’m definitely happy! @snoweye is a super responsive and nice guy, he happily worked with us on any issue we found or feature we missed.

**Comment by flying-sheep** [comment]
but thank you very much @jeroen! maybe @snoweye will want to join forces with you or, not, let’s see what the future brings
