### ISSUE TITLE
getPass is not shaded correctly

### ISSUE THREAD

**Issue by jgbradley1** [IRkernel/IRkernel#460]
Not sure how this should best be handled but shading getPass by adding it to the `jupyter:irkernel` environment does not properly shade the function when the getPass package is attached.

**Test that fails**
```r
library(getPass)
x <- getPass('Enter password:')
```
getPass() only works when the getPass package has not been attached.

**Possible Solution**
If getPass is assigned to the global environment, then it works as expected when explicitly attached via `library()`.
```r
assign('getPass', .self$get_pass, globalenv())
```

**Comment by flying-sheep** [comment]
we could try to load the `getPass` namespace and replace it there if it’s available, else attach it as we do now.

the global env isn’t ideal because people like to do `rm(list = ls())` or similar.
