### ISSUE TITLE
cannot install IRkernel 

### ISSUE THREAD

**Issue by houguanhua** [IRkernel/IRkernel#461]
hi, 
  thank you for your hard work to develop such a amzaing tool. but I can not intall it in my R. 
I hope you can help me out. by the way ,I'm from China.here is the message from R when I install:

Warning: failed to download mirrors file (URL'https://cran.r-project.org/CRAN_mirrors.csv'); using local file 'E:/hghtools/R-3.4.0alpha/doc/CRAN_mirrors.csv'
Warning: 无法在貯藏處https://mirror.lzu.edu.cn/CRAN/src/contrib中读写索引:
  无法打开URL'https://mirror.lzu.edu.cn/CRAN/src/contrib/PACKAGES'
Warning: 无法在貯藏處http://www.stats.ox.ac.uk/pub/RWin/src/contrib中读写索引:
  无法打开URL'http://www.stats.ox.ac.uk/pub/RWin/src/contrib/PACKAGES'
Warning: 无法在貯藏處https://mirror.lzu.edu.cn/CRAN/bin/windows/contrib/3.4中读写索引:
  无法打开URL'https://mirror.lzu.edu.cn/CRAN/bin/windows/contrib/3.4/PACKAGES'
Warning: 无法在貯藏處http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.4中读写索引:
  无法打开URL'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.4/PACKAGES'
Warning messages:
1: In download.file(url, destfile = f, quiet = TRUE) :
  InternetOpenUrl失败:’'
2: packages ‘repr’, ‘IRdisplay’, ‘evaluate’, ‘crayon’, ‘pbdZMQ’, ‘devtools’, ‘uuid’, ‘digest’ are not available (for R version 3.4.0 alpha) 

best wishes

**Comment by flying-sheep** [comment]
hi, maybe the chinese firewall or your company’s firewall is to blame?

all of those URLs should be reachable, and i assume you will see the same error when trying to install other R packages.

if you are doing this for work, maybe you can ask your department/supervisor/IT how to configure R to download packages.

good luck!

**Comment by ninjakira** [comment]
> devtools::install_github('IRkernel/IRkernel')
Downloading GitHub repo IRkernel/IRkernel@master
from URL https://api.github.com/repos/IRkernel/IRkernel/zipball/master
Installing IRkernel
Error in if (download_method_secure()) { :
  missing value where TRUE/FALSE needed
In addition: Warning message:
GitHub repo contains submodules, may not function as expected!

Hi, I have problems installing IRkernel as well...

**Comment by flying-sheep** [comment]
i found those via google (https://www.google.de/search?q=download_method_secure)

* https://github.com/IRkernel/IRkernel/issues/204#issuecomment-229938189
* http://stackoverflow.com/questions/39423491/error-in-if-download-method-secure-from-installing-native-r-kernel-for-jupyt

**Comment by ninjakira** [comment]
Ok noted! Will start a new thread in the future.

I have tried updating devtools. With both v1.12.0 and v1.11.1, I still get the same error message as above...

**Comment by ninjakira** [comment]
This works! Thanks!

**Comment by flying-sheep** [comment]
@ninjakira great! i condensed our interaction so it doesn’t take up as much space.

@houguanhua sorry for derailing this thread, did you make progress?

**Comment by houguanhua** [comment]
thank you guys!@ninjakira  your way works! many thanks!
