### ISSUE TITLE
Question regarding syntax highlighting

### ISSUE THREAD

**Issue by methodds** [IRkernel/IRkernel#463]
Hi,

it is possible to adjust highlighting for different syntax parts? As an example, syntax with style "monokai" in R Studio looks like this:

```
library(sjmisc)
data(efc)
efc %>% row_sums(c82cop1:c90cop9)

library(dplyr)
row_sums(efc, ~contains("cop") %>% row_sums(.==1)
         
cop <- select(efc, contains("cop")) %>% 
  mutate(index = rowSums(.==4))
head(cop)
```

![image](https://cloud.githubusercontent.com/assets/7460499/24755812/d9677240-1adb-11e7-9a3b-fa367ee9e605.png)

There you have different colors for strings, numbers, function calls and libraries.

I'm aware that you can use ``custom.css`` files for jupyter to configure syntax highlighting. I use this for Python:

![image](https://cloud.githubusercontent.com/assets/7460499/24755937/4bf62662-1adc-11e7-9d1f-9c78d6b23d74.png)

This does not work that well with IR though:
![image](https://cloud.githubusercontent.com/assets/7460499/24755983/6f4d6a12-1adc-11e7-8caf-7e2a4f9d77d9.png)

My current ``custom.css`` file is available [here](https://www.dropbox.com/s/v4ubk6ee88prv40/custom.css?dl=1).

**Comment by flying-sheep** [comment]
changes here have to land in [codemirror](http://codemirror.net), and after that, notebook has to update the bundled codemirror package.

you can see what color classes the most up-to-date codemirror has to offer for R in this overview of colored language features: http://codemirror.net/mode/r/ (use your browser’s inspection mode)

actually it was me who improved the R mode [the last three times](https://github.com/codemirror/CodeMirror/pulls?q=is%3Apr+author%3Aflying-sheep+is%3Aclosed) 😉

**Comment by flying-sheep** [comment]
closing, because this isn’t IRkernel specific, but affected by the codemirror language mode
