### ISSUE TITLE
Error on Installing IRkernel

### ISSUE THREAD

**Issue by CelebrateVC** [IRkernel/IRkernel#466]
`devtools::install_github('IRkernel/IRkernel')`

leads to  fairly normal instalation <see below>, until 
```
Error in loadNamespace(~)
    there is no package called 'stringi' 
```
which causes lazy load to fail and then the entire install

I run windows 10 and am using R 3.3.2

![image](https://cloud.githubusercontent.com/assets/27698263/25097938/9b3b8762-2374-11e7-9db6-b696ad88a38e.png)

**Comment by flying-sheep** [comment]
we don’t directly use anything from stringi, so some dependency does.

either that dependency doesn’t properly declare its dependencies, or devtools doesn’t properly parse and install them (devtools does install dependencies unless instructed not to)

so this isn’t an IRkernel bug, and installing stringi is an easy workaround.

**Comment by aakhmetz** [comment]
I have run into the same issue after updating my Conda distribution of Jupyter, and then IRKernel-related packages c('repr', 'IRdisplay', 'evaluate', 'crayon', 'pbdZMQ', 'devtools', 'uuid', 'digest'). The kernel died, but installing the package "stringi" solved the problem

**Comment by ranjita-naik** [comment]
I was also getting similar error 

**> devtools::install_github('IRkernel/IRkernel')**

** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'stringi'
ERROR: lazy loading failed for package 'IRkernel'
* removing 'C:/Program Files/R/R-3.4.2/library/IRkernel'
Installation failed: Command failed (1)
Warning message:
GitHub repo contains submodules, may not function as expected! 

So, I installed 'stringi' and re-tried . This time it went through
**> install.packages('stringi')**
**> devtools::install_github('IRkernel/IRkernel')**

Downloading GitHub repo IRkernel/IRkernel@master
from URL https://api.github.com/repos/IRkernel/IRkernel/zipball/master
Installing IRkernel
"C:/PROGRA~1/R/R-34~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/ranjitan/AppData/Local/Temp/RtmpWqpORt/devtools485c21462c71/IRkernel-IRkernel-49b2eb2" --library="C:/Program Files/R/R-3.4.2/library"  \
  --install-tests 

* installing *source* package 'IRkernel' ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (IRkernel)
Warning message:
GitHub repo contains submodules, may not function as expected!
