### ISSUE TITLE
“jupyter kernelspec --version” exited with code 127

### ISSUE THREAD

**Issue by ahsen1402** [IRkernel/IRkernel#469]
Hi, the code

```
IRkernel::installspec()
```
I get an error 
```
Error in IRkernel::installspec() : 
  jupyter-client has to be installed but “jupyter kernelspec --version” exited with code 127.
```
but after I did
```
conda install -c r r-essentials
```
on jupyter I can start an R network but 

```
IRkernel::installspec()
```

still gives the same error. My ultimate aim is to use hydrogen package in atom to run R code but it does not recognize the IRkernel just wondering whether I am missing something.

**Comment by takluyver** [comment]
Is jupyter_client installed? What do you get if you run `jupyter kernelspec --version` in a terminal

**Comment by ahsen1402** [comment]
I get 
```
4.4.0
```

**Comment by takluyver** [comment]
When you run `IRkernel::installspec()`, are you starting R in a terminal or using something like R Studio? Sometimes it can only find Jupyter if you start it in the terminal.

**Comment by flying-sheep** [comment]
[127 means “command not found”](http://stackoverflow.com/questions/1763156/127-return-code-from)

so yeah, jupyter is probably not on your PATH

**Comment by AbsarF** [comment]
Hi,

similar error : "jupyter-client has to be installed but “jupyter kernelspec --version” exited with code 127"

Env: client -- Ubuntu 16.04.2 LTS
- running R from terminal (NOT RStudio)
- already installed the Jupyter client 5.0.1 (conda install -c anaconda jupyter_client=5.0.1)

? --where and how to put Jupyter on PATH??..(my bashrc file already contains the path for anaconda)

- Tried both paths : running the command directly (IRkernel::installspec()) from R Terminal itself (but NO success) :  
setwd(../anaconda3/pkgs/jupyter_client-5.0.1-py35_0)
setwd(../anaconda3/pkgs/jupyter_client-5.0.1-py35_0/bin

Please help..many thanks in advance..

**Comment by takluyver** [comment]
There shouldn't be any need to call `setwd()` in R. In a terminal, can you run `jupyter kernelspec --version`?

**Comment by AbsarF** [comment]
Many thanks Thomas for such a quick response..
Yes, I am able to run "jupyter kernelspec --version"  in bash shell : 
jupyter kernelspec --version
5.0.1

thanks for your help..

**Comment by takluyver** [comment]
And that's the same shell from which you run R and call `IRkernel::installspec()`? Can you run `which jupyter` and `which jupyter-kernelspec` in bash to see where they're found? And then check `Sys.getenv('PATH')` in R?

**Comment by AbsarF** [comment]
$ which jupyter
../anaconda3/bin/jupyter

$ which jupyter-kernelspec
../anaconda3/bin/jupyter-kernelspec

> Sys.getenv('PATH')
[1] "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"

**Comment by AbsarF** [comment]
$ which jupyter
../anaconda3/bin/jupyter

$ which jupyter-kernelspec
../anaconda3/bin/jupyter-kernelspec

Sys.getenv('PATH')
 "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"

**Comment by takluyver** [comment]
How are you starting R? The `.../anaconda3/bin` directory needs to be on PATH so that it can find Jupyter.

**Comment by AbsarF** [comment]
To start R : either key-in "R" in the terminal or click the R app icon..
How to add ../anaconda3/bin in R PATH..? 

I have this path in my bash file : 
# added by Anaconda3 4.1.1 installer
export PATH=".../anaconda3/bin:$PATH"

Thanks for your help..

**Comment by AbsarF** [comment]
To start R : either key-in "R" in the terminal or click the R app icon..
How to add ../anaconda3/bin in R PATH..?

I have this path in my bash file :

added by Anaconda3 4.1.1 installer
export PATH=".../anaconda3/bin:$PATH"

Thanks for your help..

**Comment by ahsen1402** [comment]
This issue existed when i try to run it in Rstudio when i opened R from terminal theb the code run fine. I dont know why or whether this is the solution for you as well.

**Comment by takluyver** [comment]
Try starting it from bash and entering `R`, then running `IRkernel::installspec()`. It probably won't work when you use the R app icon, because it's not being run by bash, so it won't be affected by bashrc.

**Comment by AbsarF** [comment]
Many many thanks Thomas :-)

I was making the mistake of running the command (IRkernel::installspec()) in R by using the R app icon.
When i run this command in R from the terminal then it went smooth 
> IRkernel::installspec()
[InstallKernelSpec] Installed kernelspec ir in ../.local/share/jupyter/kernels/ir

Have a nice day and a great weekend ahead..

**Comment by AbsarF** [comment]
Thanks ahsen1402 for your comments..I guess your problem has been resolved too..

**Comment by ajijohn** [comment]
I had encountered a similar issue, the resolution was to start a R session with sudo, execute the below statements  

sudo -i R , and then
 `
> Sys.getenv('PATH')
[1] "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/snap/bin"
Sys.setenv(PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/snap/bin:/home/ubuntu/miniconda3/bin')
IRkernel::installspec(user=FALSE)

` 
and thus, the kernel available to all the users. 

Hope this helps

**Comment by flying-sheep** [comment]
great that it works for everyone!

**Comment by steachhr** [comment]
> Try starting it from bash and entering `R`, then running `IRkernel::installspec()`. It probably won't work when you use the R app icon, because it's not being run by bash, so it won't be affected by bashrc.

This fixed the problem for me!
