### ISSUE TITLE
How to see all rows of a data frame in a Jupyter notebook with an R kernel?

### ISSUE THREAD

**Issue by dfrankow** [IRkernel/IRkernel#470]
From http://stackoverflow.com/questions/43383591/how-to-see-all-rows-of-a-data-frame-in-a-jupyter-notebook-with-an-r-kernel:

When I put a data frame into a cell, it shows only some of the rows, with a "..." in the middle.

Edit: I'm looking for R equivalents of these Python notebook calls:

```
import pandas
# "If max_cols is exceeded, switch to truncate view"
pandas.set_option('display.max_columns', 5400)
# "The maximum width in characters of a column"
pandas.set_option('display.max_colwidth', 500)
See also http://pandas.pydata.org/pandas-docs/stable/generated/pandas.set_option.html.
```

P.S. I could "print", but that removes the HTML table. I could put together the table myself with display_html, but that feels like a work-around.

**Comment by takluyver** [comment]
I think the options you want are `repr.matrix.max.rows` and `repr.matrix.max.cols`

i.e. run

```r
options(repr.matrix.max.rows=600, repr.matrix.max.cols=200)
```

The defaults are 60 and 20.

**Comment by dfrankow** [comment]
Works, thank you!

If you want the stackoverflow cred, I'll accept your answer there. Otherwise, I'll add it.

**Comment by takluyver** [comment]
Feel free to add it - I don't need more SO cred ;-)

**Comment by LoveJS** [comment]
Hi where do I find Python file to modify that setting? 

options(repr.matrix.max.rows=600, repr.matrix.max.cols=200)

**Comment by dfrankow** [comment]
This is R, not python. You would put it in your R notebook.

I just gave the python as an example in the question.

**Comment by LoveJS** [comment]
Ok. I have a R script that generates Block Randomization.
I am very new to R by the way. 
So, do I just include in the script on the bottom (inside  IPYNB file) with current R script that I have now?
---------------------------------------------------------------------------------

require(plyr)

seed=42
blocksize = 4
N = 48
set.seed(seed)
block = rep(1:ceiling(N/blocksize), each = blocksize)
a1 = data.frame(block, rand=runif(length(block)), envelope= 1: length(block))
a2 = a1[order(a1$block,a1$rand),]
a2$arm = rep(c("Arm 1", "Arm 2"),times = length(block)/2)
assign = a2[order(a2$envelope),]

head(assign,48)

**Comment by dfrankow** [comment]
Code is executed one statement at a time. You have to put it before the statements where you're showing the data frame. But it your case, you're using "head" which only shows 48 rows of the dataset anyway.

It doesn't seem appropriate to be debugging your thing on a github issue. You should post your questions to stackoverflow.

**Comment by LoveJS** [comment]
Thank you so much! You saved my day. I was actually trying to retrieve 120 rows. BTW, I gave the point at the Stackoverflow you answered.
