### ISSUE TITLE
Run a user assigned start-up script in IRkernel::main()

### ISSUE THREAD

**Issue by uditabose** [IRkernel/IRkernel#472]
I want to start a Spark context at the start-up of each notebook with R kernel. I want supply an argument that takes either inline R script or a file path containing a small script. I can modify IRkernel::run to do that, but want to know if there is another (better) way to do that.

**Comment by flying-sheep** [comment]
put this into your `~/.Rprofile`:

```r
if (isTRUE(getOption('jupyter.in_kernel'))) {
    # code here
}
```

**Comment by mayhemm** [comment]
It doesn't. Let's think something else..

**Comment by flying-sheep** [comment]
What did you try to put in there?

**Comment by mayhemm** [comment]
I was trying to customize JupyterHub's R kernel and preload spark variables.
The path I tried was $R_HOME/.Rprofile which in my case is /opt/conda/lib/R/etc/.Rprofile

**Comment by uditabose** [comment]
I added changes to .Rprofile, added .First and .Last functions. That worked well.

**Comment by flying-sheep** [comment]
Thank you for the tip @uditabose!

Maybe putting the check I mentioned above into the `.First` function would work for you, @mayhemm?
