### ISSUE TITLE
error in devtools::install_github('IRkernel/IRkernel') / win 10 x64

### ISSUE THREAD

**Issue by Muuyaooo** [IRkernel/IRkernel#473]
![default](https://cloud.githubusercontent.com/assets/26641345/25733456/c66de608-318b-11e7-8261-1b3ecb305dea.JPG)
error is：
'C:\Program' neither inside or outside order，nor exe or bat.

**Comment by flying-sheep** [comment]
seems like a `devtools` bug, please file it there.

the issue seems to be that `C:\Program Files\R\…\bin\R` isn’t escaped properly, so it tries to call `C:\Program` with the first argument `Files\R\…\bin\R`.

**Comment by Muuyaooo** [comment]
thank u, I just move the file to another place ,it works!!

**Comment by flying-sheep** [comment]
no problem, great that it worked out!
