### ISSUE TITLE
Plot function failed for R 3.4.0

### ISSUE THREAD

**Issue by andys0975** [IRkernel/IRkernel#474]
![default](https://cloud.githubusercontent.com/assets/21152737/26046159/251ea696-3980-11e7-967f-b39ab0a26614.png)
Every plot function (ggplot2 included) I tested can't work in IRkernel with R 3.4.0
The installation guide said (currently) IRkernel is for both 3.3 & 3.2 version, 
so I guess 3.4 is not ready for IRkernel, Right?
If anyone can solve this problem without bothering updating the whole package from authors
please tell me, thanks!

**Comment by flying-sheep** [comment]
3.4 works fine, which installation guide do you mean? [**the** installation guide](https://irkernel.github.io/requirements/) AFAIK doesn’t say it.

can you start `jupyter notebook` in a shell and paste the output here?

if it’s long, please wrap it in a `<details>…</details>` tag.

**Comment by andys0975** [comment]
There was no output on jupyter notebook shell, it only shows "kernel restart" information because the kernel was dead after trying to plot something.
The weird thing is when I use python rpy2 package, the plot function works fine.
I tried to reinstalled the whole R, and when I tried to install IRkernel:
> devtools::install_github('IRkernel/IRkernel')
it shows 
![image](https://cloud.githubusercontent.com/assets/21152737/26071704/891c638a-39db-11e7-98b3-f8d73fd3e043.png)
I searched for related issue but there's no solution to date,
so I really don't know where the problem comes from...

**Comment by andys0975** [comment]
I use python 3.5.3 // jupyter 1.0.0 // notebook 5.0.0 
(When I used R 3.3.3 , everything works perfectly in IRkernel)
R 3.4.0
> sessionInfo
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 14393)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Traditional)_Taiwan.950
[2] LC_CTYPE=Chinese (Traditional)_Taiwan.950
[3] LC_MONETARY=Chinese (Traditional)_Taiwan.950
[4] LC_NUMERIC=C
[5] LC_TIME=Chinese (Traditional)_Taiwan.950

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.4.0

**Comment by flying-sheep** [comment]
are you maybe using the same library as you used in R 3.3?

when you use `install.packages`, it’ll tell you where it installs stuff to. if that path doesn’t contain `3.4`, then you re-use the packages from the `3.3` install. that’s bad.

if this is the case, delete all packages from the library and reinstall what you need. the error should be gone

**Comment by andys0975** [comment]
First I want to thank you for your help!
My package are all from 3.4 contrib
As I said, I can use all packages without a problem in R command, Rstudio, python rpy2 interface and magics.
ONLY Failed in IRkernel, so I guess the problem may not come from the plotting packages...
Maybe the startup encoding shouldn't be big5 in this case?

**Comment by flying-sheep** [comment]
> First I want to thank you for your help!

with pleasure!

>  My package are all from 3.4 contrib

OK, then my theory doesn’t hold.

---

please run

```
set JUPYTER_LOG_LEVEL=3
jupyter notebook
```

then try to plot, and afterwards paste the output here.

**Comment by andys0975** [comment]
> (Log after plot)
DEBUG: main loop: after poll
DEBUG: main loop: shell
DEBUG: Sending msg status
DEBUG: Sending msg complete_reply
DEBUG: Sending msg status
DEBUG: main loop: beginning
DEBUG: main loop: after poll
DEBUG: main loop: shell
DEBUG: Sending msg status
DEBUG: Sending msg complete_reply
DEBUG: Sending msg status
DEBUG: main loop: beginning
DEBUG: main loop: after poll
DEBUG: main loop: shell
DEBUG: Sending msg status
DEBUG: Sending msg complete_reply
DEBUG: Sending msg status
DEBUG: main loop: beginning
DEBUG: main loop: after poll
DEBUG: main loop: shell
DEBUG: Sending msg status
DEBUG: Sending msg complete_reply
DEBUG: Sending msg status
DEBUG: main loop: beginning
DEBUG: main loop: after poll
DEBUG: main loop: shell
DEBUG: Sending msg status
DEBUG: Sending msg inspect_reply
DEBUG: Sending msg status
DEBUG: main loop: beginning
DEBUG: main loop: after poll
DEBUG: main loop: shell
DEBUG: Sending msg status
DEBUG: Sending msg complete_reply
DEBUG: Sending msg status
DEBUG: main loop: beginning
DEBUG: main loop: after poll
DEBUG: main loop: shell
DEBUG: Sending msg status
DEBUG: Sending msg complete_reply
DEBUG: Sending msg status
DEBUG: main loop: beginning
DEBUG: main loop: after poll
DEBUG: main loop: shell
DEBUG: Sending msg status
DEBUG: Sending msg execute_input
DEBUG: Executing code: plot(1,2)
DEBUG: Graphics output...
DEBUG: Value output...
[I 01:29:31.087 NotebookApp] KernelRestarter: restarting kernel (1/5)

**Comment by flying-sheep** [comment]
normally it should look like this:

```
DEBUG: main loop: beginning
DEBUG: main loop: after poll
DEBUG: main loop: shell
DEBUG: Sending msg status
DEBUG: Sending msg execute_input
DEBUG: Executing code: plot(1)
DEBUG: Graphics output...
DEBUG: Value output...
DEBUG: Sending msg display_data
DEBUG: Sending msg execute_reply
DEBUG: Sending msg status
```

**Comment by flying-sheep** [comment]
so what you could do is basically

1. git clone this project
2. open it in rstudio
3. add a `log_debug('n')` with increasing numbers between all the lines that i linked to
4. tell me which line crashes the server

**Comment by andys0975** [comment]
> After I build up the revised package, I ran into this:
Error in if (file.exists(dest) && file.mtime(dest) > file.mtime(lib) &&  : 
  missing value where TRUE/FALSE needed

how to solve this?

**Comment by andys0975** [comment]
DEBUG: Executing code: plot(1,2)
DEBUG: Graphics output...
DEBUG: Value output...
DEBUG: 1
DEBUG: 4

>handle_value = function(obj, visible) {
    log_debug('Value output...')
    set_last_value(obj)
    log_debug('1')
    if (visible) {
        log_debug('2')
        mimebundle <- prepare_mimebundle_kernel(obj, .self$handle_display_error)
        log_debug('3')
        if (length(intersect(class(obj), getOption('jupyter.pager_classes'))) > 0) {
            log_debug('Showing pager: %s', paste(capture.output(str(mimebundle$data)), collapse = '\n'))
            page(mimebundle)
        } else {
            log_debug('Sending display_data: %s', paste(capture.output(str(mimebundle$data)), collapse = '\n'))
            send_response('display_data', current_request, 'iopub', mimebundle)
        }
    }
},

> if (!is_silent() && !is.null(last_recorded_plot)) {
        log_debug('4')
        send_plot(last_recorded_plot)
    }
    
    if (interrupted) {
        log_debug('5')
        reply_content <- list(
            status = 'abort')
    } else if (!is.null(err$ename)) {
        log_debug('6')
        reply_content <- c(err, list(
            status = 'error',
            execution_count = execution_count))
    } else {
        log_debug('7')
        reply_content <- list(
            status = 'ok',
            execution_count = execution_count,
            payload = payload,
            user_expressions = namedlist())
    }
    log_debug('8')
    send_response('execute_reply', request, 'shell', reply_content)

    if (interrupted || !is.null(err$ename)) {
        log_debug('9')
        # errors or interrupts should interrupt all currently queued messages,
        # not only the currently running one...
        abort_queued_messages()
    }

    if (!is_silent() && should_store_history()) {
        log_debug('10')
        execution_count <<- execution_count + 1L
    }
},

**Comment by flying-sheep** [comment]
looks good! so we know it probably crashes in `send_plot`.

could you please add those debug statements there, too?

once we know the function call that’s not from IRkernel code and crashes the kernel, we’ll know better what happens. and it has to be non-IRkernel code, since IRkernel only crashes using `stop` and not `Sys.exit(1)`.

---

the idea is that once you have a block like this:

```r
log_debug('1')
call_1()
log_debug('2')
```

and only see `1`, you know the crash is in `call_1`.

then you add the debugging stuff in the function `call_1`, and repeat until you found it crashing on a function call that isn’t in your own package.

**Comment by flying-sheep** [comment]
In case my assumption is right, I tried to improve handle_error to be more resilient.

You can try to `git fetch && git checkout harden-handle-error`, then run it again with that version.

Hopefully there will be an error message in the console then

**Comment by andys0975** [comment]
I edit the NAMESPACE, execution.R file 
However no error output
Only report this

>DEBUG: Executing code: plot(1,2)
DEBUG: Graphics output...
DEBUG: Value output...
DEBUG: 0
DEBUG: 1
DEBUG: 2
DEBUG: 3
DEBUG: 4
DEBUG: 5
DEBUG: 4
DEBUG: 5
[I 00:17:30.082 NotebookApp] KernelRestarter: restarting kernel (1/5)

>send_plot = function(plotobj) {
	log_debug('1')
    formats <- namedlist()
	log_debug('2')
    metadata <- namedlist()
	log_debug('3')
    for (mime in getOption('jupyter.plot_mimetypes')) {
		log_debug('4')
        tryCatch({
			log_debug('5')
            formats[[mime]] <- mime2repr[[mime]](plotobj, attr(plotobj, '.irkernel_width'), attr(plotobj, '.irkernel_height'))
        }, error = handle_error)
        # Isolating SVGs (putting them in an iframe) avoids strange
        # interactions with CSS on the page.
        if (identical(mime, 'image/svg+xml')) {
            log_debug('6')
			metadata[[mime]] <- list(isolated = TRUE)
        }
    }
    log_debug('7')
	publish_mimebundle(formats, metadata)
},

**Comment by flying-sheep** [comment]
as i thought, it’s probably `handle_error`.

can you please do

```console
$ git fetch origin  # assuming the remote is named origin
$ git reset --hard origin/master
$ R CMD INSTALL .
$ set JUPYTER_LOG_LEVEL=3
$ jupyter notebook
```

**Comment by andys0975** [comment]
Not working, still the same (no error output)
I wonder what "plotobj" exactly mean in execution.R ?
Is there any possibility that the plotobj is not defined well and then cause this problem ?
my getOption('jupyter.plot_mimetypes') report {'text/plain' 'image/png'}
and the problem occurs when it tries to 
> tryCatch({ formats[[mime]] <- mime2repr[[mime]](plotobj, attr(plotobj, '.irkernel_width'), attr(plotobj, '.irkernel_height'))}, error = handle_error)

for 'image/png'
is the problem comes from "repr_png" function or plotobj itself ?

**Comment by andys0975** [comment]
By the way, I found that I can use specify a ggplot as an object, and then use "plotly" function "embed_notebook()" perfectly.
If I can't solve this problom, is there any option to print a plot like that?

**Comment by flying-sheep** [comment]
hi!

so `getOption('jupyter.plot_mimetypes')` should return a vector, like `c('text/plain', 'image/png')`. is there a reason you used curly braces? is that the actual output, or is the output a vector?

for that tryCatch: you could try to do `error = function(e) cat(e, '\n')` and then there *has to* be something in the console.

>  is the problem comes from "repr_png" function or plotobj itself ?

i don’t know yet! i need to see the actual error. (which is what we’re trying for all the time 😉)
