### ISSUE TITLE
Issue installing IRkernel on Windows 

### ISSUE THREAD

**Issue by almms** [IRkernel/IRkernel#479]
I am trying to install the IRkernel on Windows. 'devtools::install_github' does not do the job. Could you point me to the tar or zip file from which I can install the library, please?

I came across IRkernel-IRkernel-0.8.6-4-gf2f4ee3.zip but cannot install this with the error shown below.

> Warning in install.packages :
>   cannot open compressed file 'IRkernel-IRkernel-0.8.6-4-gf2f4ee3/DESCRIPTION', probable reason 'No such file or directory'
> Error in install.packages : cannot open the connection

I have tried a lot by now and would really appreciate your thoughts.

**Comment by flying-sheep** [comment]
hi! obviously you can use the “Clone or download” button here on GitHub, but unlike `devtools` that won’t help you with dependencies (which you’ll have to install manually then)

> 'devtools::install_github' does not do the job

please give us more details. “does not do the job” won’t help anyone to identify the issue. you should always include the output when you write something like this.

if it’s really a `devtools` bug, you should also file an issue at their repo, but i assume it’s not.

**Comment by almms** [comment]
Hi

Obviously I must be downloading the wrong file. If I clone a zip to my local directory, installation runs but no package appears; nor does Jupyter change (after restart)

`> install.packages("mydir/IRkernel-master.zip", repos = NULL, type = "win.binary")
> library(`IRkernel-master`)
Error in library(`IRkernel-master`) : 
  there is no package called ‘IRkernel-master’
> library(`IRkernel`)
Error in library(IRkernel) : there is no package called ‘IRkernel’`

I have been using devtools without issues in the past.

It is not clear to me how the installation directly downloading from github is supposed to work for IRkernel. It might be useful to explain this in your installation how-to until this is available on CRAN.

**Comment by flying-sheep** [comment]
`install.packages` doesn’t take file paths, you need to use `R CMD INSTALL packagefolder`. please paste how you called `install_github` and its output.

please do this to get proper code blocks:

````markdown
```r
code here
```
````
