### ISSUE TITLE
Error in IRkernel::installspec()

### ISSUE THREAD

**Issue by jeonghyunwoo** [IRkernel/IRkernel#480]
When I invoke IRkernel::installspec(), following messages are occured.
Jupyter doesn't have R kernel.

> IRkernel::installspec()
Error in IRkernel::installspec() : 
  jupyter-client has to be installed but “jupyter kernelspec --version” exited with code 127.
In addition: Warning message:
running command '"jupyter" kernelspec --version' had status 127

jupyter kernelspec --version ==> 5.0.1

**Comment by flying-sheep** [comment]
please search: https://www.google.de/search?q=jupyter-client+has+to+be+installed+but+“jupyter+kernelspec+--version”+exited+with+code+127
