### ISSUE TITLE
Auto-indent within ggplot and pipes

### ISSUE THREAD

**Issue by hichana** [IRkernel/IRkernel#481]
IRkernel within Jupyter is great because I've really grown accustomed to using moveable/swappable code blocks, which RMarkdown doesn't offer in the same way. Thank you

It would be great if there was the ability to auto-indent after a carriage return for the second line in a ggplot. For example:

`ggplot(data.frame) +`
`(indent) geom_histogram(aes(x = field))`

The same thing would be nice for pipes:
`data.frame %>%`
`(indent) gather() %>%`
`(indent) ...`

**Comment by flying-sheep** [comment]
hmm, that‘s probably best filed against codemirror, jupyter notebook’s editor.
