### ISSUE TITLE
Offline installation

### ISSUE THREAD

**Issue by RichCranney** [IRkernel/IRkernel#483]
Hello,

I'm trying to install the IRkernel in my JupyterHub installation, which is held on a server isolated away from the internet. I've managed to get JupyterHub, Python3, R all installed, but was wondering if anyone had any tips on how to get the IRkernel prepped for Offline.

CRAN would be the best way, but I understand this is an ongoing process at present. 

For other installs, we usually collate the files and package up in a shell wrapper of sorts, to then deploy on the offline machine and run the install. Can anyone help?

**Comment by takluyver** [comment]
All of the components and dependencies except IRkernel itself should be available from CRAN.

For IRkernel itself, if you make a clone of this repository and move it onto the target system, you should be able to run `R CMD INSTALL path/to/repo`.

**Comment by RichCranney** [comment]
Oh excellent, I'll take a look on CRAN and see what dependencies are required. I don't suppose you have a list already do you? If there is one out there, I'd rather take that than waste time creating my own. 

Thanks in advance though, great to know its that simple to clone and install from local source.

**Comment by takluyver** [comment]
I think the list in the install instructions should be it: https://irkernel.github.io/installation/#binary-panel

**Comment by RichCranney** [comment]
takluyver, thank you, I've successfully completed the offline installation of JupyterHub and R now with IRkernel. The above command worked a tread for me in bringing down the GIT repo, unzipping it and installing via CMD process.

Thanks again
