### ISSUE TITLE
IRkernel linking to R on a separate server

### ISSUE THREAD

**Issue by RichCranney** [IRkernel/IRkernel#484]
Hello,

I'm currently working on an install where the architecture has JupyterHub on one Server and RStudio on a separate server. Both are on the same VPN and can talk to each other via SSH etc, but is there a way to link JupyterHub to the RStudio server via the IRkernel, or does R and JupyterHub need to be on the same server?

Thanks

**Comment by flying-sheep** [comment]
hmm, i don’t know enough to answer that. maybe the jupyterhub people know?

**Comment by takluyver** [comment]
There are two alternative ways you could do that:

1. Install the Jupyter notebook (the single user part) on the system with R, and have Jupyterhub launch servers for each individual user on that system. Jupyterhub is designed for the single-user servers to run on separate machines from the hub, and doing so is quite well explored. Ask on a Jupyterhub repo or mailing list for more details about that.
2. Run the notebook servers for each user on the same machine as the hub, but allow them to start kernels on the R machine. The Jupyter architecture is designed to make this possible, but not many setups separate the kernels from the notebook server, so it's not so well supported.
