### ISSUE TITLE
Installing IRkernel with Macports R

### ISSUE THREAD

**Issue by isoboroff** [IRkernel/IRkernel#489]
I'm on OSX SIerra.  I have R installed through MacPorts.  When I try to install the IRkernel, I get:

> IRkernel::installspec()
Error in IRkernel::installspec() : 
  jupyter-client has to be installed but “jupyter kernelspec --version” exited with code 1.

I can't find the kernelspec command for Jupyter or how to install it.  Clues appreciated!

**Comment by isoboroff** [comment]
I solved this problem by manually making the kernel directory, and copying the files from inst/kernelspec in there:

$ mkdir ~/Library/Jupyter/kernels/R
$ cd IRkernel/inst/kernelspec
$ cp * ~/Library/Jupyter/kernels/R
$ jupyter-notebook-3.6

and all is happiness.  I think the problem is in how Jupyter is packaged in MacPorts, and I couldn't stomach trying to use Conda.  (Too many package managers syndrome, I'm currently seeking treatment.)

**Comment by flying-sheep** [comment]
yeah, both `jupyter` and `jupyter-kernelspec` need to be on your `$PATH`.

if macports doesn’t handle this for you, you can manually figure out where the binaries are and put into your `~/.bash_profile`:

`export PATH="/path/to/bindir:$PATH"`
