### ISSUE TITLE
In devtools::install_github('IRkernel/IRkernel'), xcrun: error: invalid active developer path

### ISSUE THREAD

**Issue by prestonjschwartz** [IRkernel/IRkernel#490]
Note: Command line developer tools are already installed and have been reset, but the lazy load error persists. This issue seems to be specific to the 'IRkernel/IRkernel' install. 

```r
Downloading GitHub repo IRkernel/IRkernel@master
from URL https://api.github.com/repos/IRkernel/IRkernel/zipball/master
Installing IRkernel
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/9q/fdz5sp9503lbyhwrvcqhscl00000gn/T/RtmpWFDHZF/devtools3cdd303c5295/IRkernel-IRkernel-aa5c133'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *source* package ‘IRkernel’ ...
** R
** inst
** tests
** preparing package for lazy loading
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Warning: running command '/usr/bin/otool -L /Library/Frameworks/R.framework/Versions/3.4/Resources/library/pbdZMQ/libs/pbdZMQ.so' had status 1
Error : .onLoad failed in loadNamespace() for 'pbdZMQ', details:
  call: if (org != fn.libzmq.4.dylib) {
  error: missing value where TRUE/FALSE needed
ERROR: lazy loading failed for package ‘IRkernel’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/IRkernel’
Installation failed: Command failed (1)
Warning message:
GitHub repo contains submodules, may not function as expected! 
```

**Comment by ella-bittiger** [comment]
Getting same error too.

**Comment by flying-sheep** [comment]
the first error causing the others seems to be

> `xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun`

you should maybe figure out what that means and how to fix it.

if you fixed that and the next error still occurs:

> ```r
> Error : .onLoad failed in loadNamespace() for 'pbdZMQ', details:
>   call: if (org != fn.libzmq.4.dylib) {
>   error: missing value where TRUE/FALSE needed
> ```

then it’s probably a bug in pbdZMQ, but i doubt that this is the case.

in any case, it’s not a bug in IRkernel, as it appears while installing pbdZMQ, not IRkernel.
