### ISSUE TITLE
HTMLwidgets not rendering

### ISSUE THREAD

**Issue by anomalosepia** [IRkernel/IRkernel#492]
Hi, I think this is a new issue. When using packages like plotly i get the error. This is only in Jupyter using IRkernel, all the code works fine in RStudio

`HTML widgets cannot be represented in plain text (need html)`

following up on some other threads I've tried to look at the representation for the plots using 

`str(IRdisplay::prepare_mimebundle`

and this returns the following error, that I have not seen before. 

```r
Error: evaluation nested too deeply: infinite recursion / options(expressions=)?
Traceback:

1. str(IRdisplay::prepare_mimebundle(p))
2. IRdisplay::prepare_mimebundle(p)
3. filter_map(mimetypes, function(mime) {
 .     tryCatch(withCallingHandlers({
 .         rpr <- mime2repr[[mime]](obj)
 .         if (is.null(rpr)) 
 .             return(NULL)
 .         prepare_content(is.raw(rpr), rpr)
 .     }, error = error_handler), error = outer_handler)
 . })
4. Filter(Negate(is.null), sapply(x, f, simplify = simplify))
5. unlist(lapply(x, f))
6. lapply(x, f)
7. sapply(x, f, simplify = simplify)
8. lapply(X = X, FUN = FUN, ...)
9. FUN(X[[i]], ...)
10. tryCatch(withCallingHandlers({
  .     rpr <- mime2repr[[mime]](obj)
  .     if (is.null(rpr)) 
  .         return(NULL)
  .     prepare_content(is.raw(rpr), rpr)
  . }, error = error_handler), error = outer_handler)
11. tryCatchList(expr, classes, parentenv, handlers)
12. tryCatchOne(expr, names, parentenv, handlers[[1L]])
```

a full example that elicits this on my machine is below:
any ideas on what might be broken? 

```r
library(plotly)
options(jupyter.log_level=3)

set.seed(123)

x <- rnorm(100)
y <- rchisq(100, df = 1, ncp = 0)
group <- sample(LETTERS[1:5], size = 100, replace = T)
size <- sample(1:5, size = 100, replace = T)
ds <- data.frame(x, y, group, size)

p <- plot_ly(ds, x = x, y = y, mode = "markers", split = group, size = size) %>%
  layout(title = "Scatter Plot")
p
str(IRdisplay::prepare_mimebundle(p))
```

Thanks!

**Comment by flying-sheep** [comment]
for me, it only throws a warning “No trace type specified”, which vanishes when you supply `type = 'scatter'`.

the problem i see is that jupyter for some reason sets the container’s height to 1px, so the plot is hidden:

![grafik](https://user-images.githubusercontent.com/291575/28638750-16ca57da-7246-11e7-9392-acabd1ec635c.png)

**Comment by anomalosepia** [comment]
I'm not even getting an iframe generated on this end. This all works OK on rstudio and that HTMLwidgets work in julia notebooks making  me think i've somehow broken my installation of IRkernel. Any thoughts where I might have gone wrong?

**Comment by flying-sheep** [comment]
there’s not much a language kernel such as IRkernel does.

it just sends a “mime bundle” (i.e. output in different formats packaged together) with some metadata (in this case “please isolate the `text/html` response in an iframe”.

notebook/nbconvert/nbviewer/… is responsible for properly rendering the stuff.

---

as for what happened in your case, no idea. if any kind of output is shown, this kind should be, too.

**Comment by anomalosepia** [comment]
OK, so the recursion error from
`str(IRdisplay::prepare_mimebundle(p))`
is generated by the graphing library? I'm just trying to track this down and I'm not having a lot of luck. 
thanks

**Comment by flying-sheep** [comment]
no idea where that comes from, sorry. does it happen without the `str` as well?

[here](https://github.com/IRkernel/IRdisplay/blob/6f2757549d8902f3928e1e2eacadf1c65e3931a8/R/display.r#L53-L78) is the code of `prepare_mimebundle`. i can’t see where it could recurse infinitely.

**Comment by steverweber** [comment]
I had an issue with recursion or stack space so used `ulimit -s 16384` to get around the ir kernel crash.

however after increasing the stack space hit the:
```
HTML widgets cannot be represented in plain text (need html)
```
found one reference at the time...
https://github.com/ContinuumIO/anaconda-issues/issues/1391

however does not seem like a cause was found.

**Comment by mingwandroid** [comment]
@steverweber, not using Firefox was an unfortunate workaround.

**Comment by flying-sheep** [comment]
hi, and apologies! *I* had an old kernel version that still worked. I’m sorry!

I used git bisect to find the problem and will work on a solution: https://gist.github.com/flying-sheep/fa36fd5e041a05beb32b844b065b128e

**Comment by steverweber** [comment]
thanks! works nicely now.

**Comment by flying-sheep** [comment]
great!
