### ISSUE TITLE
Installation failed: Timeout was reached during installation of IRkernel

### ISSUE THREAD

**Issue by estebancolla** [IRkernel/IRkernel#493]
First I install 'devtools' successfully (so I assume that the connection is fine). But then, after `devtools::install_github('IRkernel/IRkernel')` I get a connection failure. Does anybody know what's going on? I am using RGui (64-bit) on Windows 7 Professional. Below are the lines that appear in the R-console:

```r
> install.packages('devtools')
probando la URL 'https://lib.ugent.be/CRAN/bin/windows/contrib/3.4/devtools_1.13.2.zip'
Content type 'application/zip' length 443150 bytes (432 KB)
downloaded 432 KB

package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\ecolla\AppData\Local\Temp\RtmpeA3zT3\downloaded_packages
> devtools::install_github('IRkernel/IRkernel')
Installation failed: Timeout was reached: Connection timed out after 10015 milliseconds
```

**Comment by flying-sheep** [comment]
well, you seem to have connectivity problems to github 🙁

no idea why this is in your specific case, there could be a thousand reasons depending on country, OS, version, …

**Comment by estebancolla** [comment]
I downloaded the zip file, unzipped it and the following worked.

> devtools::install("C:\\Users\\ecolla\\Downloads\\IRkernel-master\\IRkernel-master")
Installing IRkernel
"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/ecolla/Downloads/IRkernel-master/IRkernel-master" --library="C:/Program Files/R/R-3.4.1/library"  \
  --install-tests 

* installing *source* package 'IRkernel' ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (IRkernel)
>

**Comment by flying-sheep** [comment]
great!

**Comment by SarathDesu** [comment]
Hi, I am facing similar kind of issue. Could you please help where I can download the zip file?

**Comment by estebancolla** [comment]
You can go to https://github.com/IRkernel/IRkernel and above at the right, you will see the green button "clone or download."  Hope it works.

**Comment by zypiner** [comment]
@estebancolla 
> I downloaded the zip file, unzipped it and the following worked.

devtools::install("C:\\Users\\ecolla\\Downloads\\IRkernel-master\\IRkernel-master")

It works. Thanks a lot.

**Comment by dyjun** [comment]
It works for me . Thanks a lot.

> I downloaded the zip file, unzipped it and the following worked.
> 
> ```r
> devtools::install("C:\\Users\\ecolla\\Downloads\\IRkernel-master\\IRkernel-master")
> ```

It works for me. Thanks.

**Comment by flying-sheep** [comment]
Why don’t y’all just do `install.packages('IRkernel')`?
