### ISSUE TITLE
Progress bars and warnings are being diverted and buffered.

### ISSUE THREAD

**Issue by gwerbin** [IRkernel/IRkernel#494]
Possibly related to #184 ? However I don't see any erroneous output in the terminal.

## Setup

**R**: 3.4.1
**Jupyter**: 4.3.0
**IRkernel**: 0.8.6.9000

## Progress bars

```r
pb <- txtProgressBar(min = 1, max = 10, style = 3, label = "Test")
for (i in 1:10) {
  Sys.sleep(0.5)
  setTxtProgressBar(pb, i)
}
close(pb)
```

### Expected

Increment the progress bar every 1/2 second.

### Actual

No output until the loop completes.

## Trapping warnings

```r
# warning should be converted to errors. see ?options
options(warn = 2)

for (i in 1:10) {
  warning("This should be caught as an error")
  print(i)
}
```

### Expected

The loop stops at the first iteration with an error.

### Actual

The warnings are shown as warnings and the loop completes.

**Comment by flying-sheep** [comment]
the first part is #416. please use `flush.console()`. Interesting thing about the warnings!

**Comment by gwerbin** [comment]
@flying-sheep so `flush.console()` will fix the first problem and allow the progress bar to proceed correctly?

What about the second problem? Should I open a separate issue for that one?

**Comment by flying-sheep** [comment]
> @flying-sheep so `flush.console()` will fix the first problem and allow the progress bar to proceed correctly?

Exactly. Just flush the console after every change you want to see (e.g. every iteration)

> @gwerbin second problem seems to not occur in the currently latest version.

Oh true! then this is fixed.
