### ISSUE TITLE
Allow setting path to install kernel spec to

### ISSUE THREAD

**Issue by yuvipanda** [IRkernel/IRkernel#495]
Heya!

I'm trying to install IRKernel in a jupyter installation that's from a virtual environment. I'd like to install the kernelspec in the sys.prefix path - rather than in user path or in system path. If `installspec` took an optional target path for the kernelspec that'd be awesome for this use case!

Thanks!

**Comment by flying-sheep** [comment]
fixed in #512, i think.

if you need even more control, please say so.
