### ISSUE TITLE
Script doesn't seem to exit with error status when installspec fails?

### ISSUE THREAD

**Issue by yuvipanda** [IRkernel/IRkernel#496]
Installing IRKernel failed on my docker image with:

```
Warning message:
GitHub repo contains submodules, may not function as expected!
> IRkernel::installspec(FALSE)
[Errno 13] Permission denied: '/usr/local/share/jupyter'
Perhaps you want to install with `sudo` or `--user`?
>
>

```

However, since this did *not* return a non-zero error code, docker considered this as success and moved on. It should probably fail with a non-zero error code?

Thanks!

**Comment by flying-sheep** [comment]
you can do `R --slave -e 'quit(status = IRkernel::installspec(FALSE))'`

is that sufficient for you?

**Comment by rachitkinger** [comment]
I am facing the same issue. Any suggestions how to overcome it?

**Comment by flying-sheep** [comment]
just read the solution in my comment above?

**Comment by englianhu** [comment]
> `installspec` returns tan exit code, so you can do `R --slave -e 'quit("no", IRkernel::installspec(FALSE))'`
> 
> is that sufficient for you?

```r
~$ sudo R --slave -e 'quit("no", IRkernel::installspec(FALSE))'
[sudo] password for englianhu: 
[InstallKernelSpec] Installed kernelspec ir in /usr/local/share/jupyter/kernels/ir
```
