### ISSUE TITLE
Unable to use R's datatable in notebooks

### ISSUE THREAD

**Issue by jeffwong-nflx** [IRkernel/IRkernel#497]
I am very used to using R's datatable library to render tables in RMarkdown. It's very simple

```r
require(DT)
require(data.table)

x = data.table(a = 1:10, b= 1:10)
datatable(x)
```

In Jupyter I used to be able to do this too. However, running this now just causes Jupyter to hang. It is difficult for me to debug this issue: I cannot figure out if it is due to something from the R kernel or if it is due to something in Jupyter. Tips on how to understand the source of the issue would be great. It is very serious to me, as it has pushed me back to using Rstudio where this functionality works seamlessly in Rmarkdown.

**Comment by flying-sheep** [comment]
that’s probably #492. please update IRkernel and try again

**Comment by jeffwong-nflx** [comment]
confirmed, thanks!
