### ISSUE TITLE
R kernal keeps dying

### ISSUE THREAD

**Issue by Shad0w-f0x** [IRkernel/IRkernel#498]
Hi, this is my first time using Anaconda and I just downloaded it and installed R Essentials. When I try to open an R notebook in Jupyter Notebook , the kernal always dies and is unable to restart. I get this message: 'C:\Users\Sarah\Anaconda3\R/bin/x64/Rterm.exe' is not recognized as an internal or external command,operable program or batch file.

[W 17:50:18.727 NotebookApp] KernelRestarter: restart failed
[W 17:50:18.727 NotebookApp] Kernel 11c1660c-9e0e-41ad-9127-f220f9d152d0 died, removing from map.
ERROR:root:kernel 11c1660c-9e0e-41ad-9127-f220f9d152d0 restarted failed!
[W 17:50:18.742 NotebookApp] Kernel deleted before session

Any help would be greatly appreciated thanks.

**Comment by takluyver** [comment]
Does that file (`C:\Users\Sarah\Anaconda3\R/bin/x64/Rterm.exe`) exist on your system?

**Comment by Shad0w-f0x** [comment]
No, there's R.exe and a bunch of others but no Rterm.exe

**Comment by takluyver** [comment]
Hmm, I think that might be an issue with the Anaconda packaging. If you start R in an Anaconda command prompt and run `IRkernel::installspec()`, does that change anything?

**Comment by Shad0w-f0x** [comment]
Sorry if this is a dumb question but, to start R in Anaconda command prompt do I just type R and hit enter? When I do that I get the same error stated above.

**Comment by takluyver** [comment]
That should be how you start it. Can you have a look for a file called something like `R.bat` or `R.cmd`? I think it should be in `C:\Users\Sarah\Anaconda3\Scripts`.

**Comment by Shad0w-f0x** [comment]
I can't find R.bat but there is an Rcmd.exe file.

**Comment by takluyver** [comment]
What does `where R` give you in the command prompt? I'm not so familiar with Windows, but I think that's how you can find what the `R` command is doing.

**Comment by Shad0w-f0x** [comment]
It gives me C:\Users\Sarah\Anaconda3\Scripts\R.exe

**Comment by takluyver** [comment]
And running that gives you the error about Rterm.exe ? If so, that's definitely a problem with the conda package of R.

**Comment by Shad0w-f0x** [comment]
Yeah I guess, do you know how I can fix it?

**Comment by takluyver** [comment]
I'd suggest reporting it here: https://github.com/ContinuumIO/anaconda-issues/

There might be some other related package you can install which will add `Rterm.exe`. But that's just a guess, and I don't know what the package is.

**Comment by Shad0w-f0x** [comment]
Alright thanks for all your help!

**Comment by estebanpdl** [comment]
Someone among you find how to fix this issue? I am getting also that error after creating a new R Kernel.

**Comment by G-Slient** [comment]
There is error in creating the new notebook and the kernel is dying every time
Plz help me to solve this 

(base) C:\Anaconda>jupyter notebook
[W 19:09:35.349 NotebookApp] Permission to listen on port 8888 denied
[I 19:09:35.416 NotebookApp] JupyterLab beta preview extension loaded from C:\Anaconda\lib\site-packages\jupyterlab
[I 19:09:35.416 NotebookApp] JupyterLab application directory is C:\Anaconda\share\jupyter\lab
[I 19:09:35.563 NotebookApp] Serving notebooks from local directory: C:\Anaconda
[I 19:09:35.564 NotebookApp] 0 active kernels
[I 19:09:35.565 NotebookApp] The Jupyter Notebook is running at:
[I 19:09:35.565 NotebookApp] http://localhost:8889/?token=e1f42698d70da5761f345650fbd282fdb747293bf34e50e9
[I 19:09:35.570 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 19:09:35.572 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8889/?token=e1f42698d70da5761f345650fbd282fdb747293bf34e50e9&token=e1f42698d70da5761f345650fbd282fdb747293bf34e50e9
[I 19:09:35.928 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 19:09:57.744 NotebookApp] Creating new notebook in
The filename, directory name, or volume label syntax is incorrect.
[I 19:09:59.686 NotebookApp] Kernel started: 982fd2a9-2a52-41d7-b5e6-eab91cf5c05d
[I 19:10:02.656 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
The filename, directory name, or volume label syntax is incorrect.
[I 19:10:05.673 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
The filename, directory name, or volume label syntax is incorrect.
[I 19:10:08.675 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
The filename, directory name, or volume label syntax is incorrect.
[W 19:10:09.908 NotebookApp] Timeout waiting for kernel_info reply from 982fd2a9-2a52-41d7-b5e6-eab91cf5c05d
[I 19:10:11.691 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
kernel 982fd2a9-2a52-41d7-b5e6-eab91cf5c05d restarted
The filename, directory name, or volume label syntax is incorrect.
[W 19:10:14.708 NotebookApp] KernelRestarter: restart failed
[W 19:10:14.708 NotebookApp] Kernel 982fd2a9-2a52-41d7-b5e6-eab91cf5c05d died, removing from map.
kernel 982fd2a9-2a52-41d7-b5e6-eab91cf5c05d restarted failed!

**Comment by flying-sheep** [comment]
Well, the syntax in kernel.json seems o be wrong. no idea why and what to do about it.

**Comment by RobertNolet** [comment]
Several of my students were having this issue, it turns out their virus scanner was blocking Rterm.exe.

**Comment by flying-sheep** [comment]
Thank you, hilarious.

Tell them using anything but windows defender is a waste of time and (if applicable) money. Antivirus software is a cancer that only increases the attack surface (by being buggy and having elevated privileges).
