### ISSUE TITLE
IRkernel::installspec() fails with jupyter in virtual environment

### ISSUE THREAD

**Issue by shapiromatron** [IRkernel/IRkernel#499]
I don't have jupyter installed in my base python; it's installed in a Python virtual environment. So when I tried to install the R jupyter kernel I got an error that jupyter could not be found. To fix, I temporarily added the path to `jupyter` to my PATH, opened a new terminal window, and installed the kernel system-wide using `IRkernel::installspec(user = FALSE)`.

Is this the recommended solution? If so, should we add to docs? I'll happily volunteer if this is the correct solution.

**Comment by takluyver** [comment]
That sounds about right. The easiest way to add it to PATH is to activate the virtualenv before starting R (using `source path/to/env/bin/activate`, or `workon env` if you use virtualenvwrapper).

**Comment by 1HughSawbridge** [comment]
Hi guys, I've not been able to get this working,
I'm on Ubuntu, with jupyter in a python virtual environment and I've been using Jupyter with a Python kernel for a while now.
I've activated the environment through a console window in R studio but I'm getting the same error.

> Error in IRkernel::installspec() : 
>   jupyter-client has to be installed but “jupyter kernelspec --version” exited with code 127.

I can see the jupyter-kernelspec file in the bin directory of my virtual env but I can't get R to look at it, even by using

> IRkernel::installspec(prefix='/path/virtual/environment/bin/jupyter-kernelspec')

**Comment by takluyver** [comment]
`jupyter-kernelspec` needs to be on PATH. I'd recommend starting a terminal (in a separate window, not in Rstudio), activating the virtual environment, and then launching R in that terminal.

**Comment by 1HughSawbridge** [comment]
That worked, I've never used the terminal for running R.

Thanks so much for the quick response.
