### ISSUE TITLE
IRkernel::installspec() fails: error 127; Debian

### ISSUE THREAD

**Issue by tkiral** [IRkernel/IRkernel#500]
installspec() has been failing; it throws error 127 when R is run in the terminal.  When installspec() 9s run, the terminal reads "jupyter-client has to be installed but 'jupyter kernelspec --version' exited with code 127."  It seems there's an issue with Jupyter being in the path, but I don't know what to add to the path to resolve the issue.  I am running Debian and have installed Jupyter-notebook using apt-get and Jupyter using pip3 (I installed Jupyter because installspec() wasn't working).  What should I add to the path to allow R to access Jupyter?  Should I be doing something else instead?

**Comment by flying-sheep** [comment]
there should be `jupyter.exe` and `jupyter-kernelspec.exe` somewhere on your system. add the folder with those files in it.

**Comment by takluyver** [comment]
No `.exe` extension on Linux. ;-)

**Comment by flying-sheep** [comment]
i must have been asleep still, i somehow missed everything and assumed it was windows.

**Comment by tkiral** [comment]
That's actually what I was looking for-that directory.  I've been adding a few directories to the path now and none of them allow me to run installspec without throwing exit code 127.

**Comment by flying-sheep** [comment]
well, what are those paths?

if you used `pip3 install --user`, the path should be e.g. `~/.local/bin`

**Comment by tkiral** [comment]
The paths I added are:
/usr/share/doc/python3-jupyter-client
/usr/share/doc/
/usr/share/
/usr/share/jupyter/
/usr/lib/python3/dist-packages/
/usr/local/lib/python3.5/dist-packages/
/usr/local/share/
~/.local/share/
/etc/jupyter/

These are all the places where `find / -type d | grep jupyter` found anything related to jupyter.

**Comment by flying-sheep** [comment]
haha, that’s pretty excessive. i think none of them is right.

you need a path ending in `/bin`, e.g. `/usr/local/bin`, `/usr/bin`, or `$HOME/.local/bin`.

try `locate jupyter-kernelspec`. if “locate” isn’t installed, install `mlocate` and execute `sudo updatedb` before searching.

**Comment by tkiral** [comment]
eh, I was willing to try whatever

I ran `locate jupyter-kernelspec` but nothing was printed to the terminal.

**Comment by flying-sheep** [comment]
well, as you said the error message reads `jupyter-client has to be installed but 'jupyter kernelspec --version' exited with code 127.`

if `jupyter-client` does not exist on your system, you don’t have `jupyter-client` installed.

**Comment by tkiral** [comment]
when I run `pip3 install jupyter-client`, the terminal reads "requirement already satisfied: jupyter-client in /usr/lib/python3/dist-packages."  I'm pretty sure it's just an issue with the path.  Also, that's one of the (many; lol) directories I added to the path, so I'm not sure why R isn't accessing it.

**Comment by tkiral** [comment]
I got it working.  I installed jupyter-client using pip instead of pip3 and it had no trouble.

**Comment by flying-sheep** [comment]
great that it worked!

**Comment by tkiral** [comment]
thanks for the help

**Comment by flying-sheep** [comment]
sure!
