### ISSUE TITLE
I have a problem of  devtools::install_github('IRkernel/IRkernel')

### ISSUE THREAD

**Issue by jiduwuyu** [IRkernel/IRkernel#501]
When I run ` devtools::install_github('IRkernel/IRkernel')` ,the return a problem like this:
Installation failed: An unknown option was passed in to libcurl, please help me, thanks.

**Comment by clasnake** [comment]
Any update on this? I met the same issue.

**Comment by flying-sheep** [comment]
some problem with either devtools or the version of libcurl you have installed.

maybe [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=666089). but not a bug here.
