### ISSUE TITLE
IRkernel::installspec() fails:  win7

### ISSUE THREAD

**Issue by lixu89** [IRkernel/IRkernel#502]
IRkernel::installspec() has been failing; it throws the following error. 
"Error in IRkernel::installspec() :  jupyter-client has to be installed but “jupyter kernelspec --version” exited with code 1."
I googled a lot but couldn't found the answer.

**Comment by takluyver** [comment]
- Do you have Jupyter installed?
- Are you running R in a terminal? Sometimes it doesn't work from e.g. R studio because the environment variables are different.
- Can you run that command `jupyter kernelspec --version` in a terminal?

**Comment by flying-sheep** [comment]
there are a few people who had a similar problem, e.g. #269, #469, #480, #486, #500, but for them it was code 127 (“command not found”)

here we have code 1, i.e. `jupyter kernelspec --version` just failed in some way, so as @takluyver said, we need to know if `jupyter kernelspec --version` works in the terminal and if not, what the error message is.

**Comment by lixu89** [comment]
Thank you @takluyver @flying-sheep . I installed anaconda to use jupyter at first, and couldn't install Rkernel. Now I install jupyter from Python, and the problem solved.  
I wasn't farmilar with github before. I'm sorry for my delays in replying to the messages.

**Comment by flying-sheep** [comment]
great!
