### ISSUE TITLE
system() with different conda environment

### ISSUE THREAD

**Issue by nick-youngblut** [IRkernel/IRkernel#505]
In Jupyter notebooks, I often need a mix of using dplyr, tidyr, ggplot2 and using system() to call various bioinformatics software (eg., qiime or bowtie2). An issue that I always run into is that `system()` will use the conda environment that are started Jupyter Notebook with, regardless of whether I'm using an R kernel for a specific conda environment. For instance, if I start up Jupyter Notebook in the `root` conda environment, but then run `system()` in a R kernel for a specific conda environment, the conda environment used by `system()` is still the `root` environment. I tried changing the conda environment with the system call:

`system("source activate my_conda_env; conda info -e", intern=TRUE)`

... but that doesn't change the conda environment used. 

Can I change the conda environment that is being used by `system()`?  I can't find any documentation on this anywhere.

**Comment by flying-sheep** [comment]
you probably need to execute this in a shell, like `system("bash -e 'source activate my_env; conda info -e'")`

**Comment by nick-youngblut** [comment]
It's convoluted, but it works. Thanks! 
Just to be clear, I'm guessing you meant `bash -c`  instead of `bash -e`

**Comment by flying-sheep** [comment]
sure! bash uses `-c`, R uses `-e`…
