### ISSUE TITLE
Installation failed: Couldn't resolve host 'raw.githubusercontent.com'

### ISSUE THREAD

**Issue by SarathDesu** [IRkernel/IRkernel#506]
The issue could be very basic. But when I am trying to install R kernel as mentioned in https://irkernel.github.io/installation/

```r
> install.packages(c('repr', 'IRdisplay', 'evaluate', 'crayon', 'pbdZMQ', 'devtools', 'uuid', 'digest'))
> devtools::install_github('IRkernel/IRkernel')
```

The following error is seen both in R console or RStudio! Please help. TIA.
Installation failed: Couldn't resolve host 'raw.githubusercontent.com'

**Comment by flying-sheep** [comment]
that’s an issue with your internet. raw.githubusercontent.com should be reachable unless some proxy or firewall or whatever interferes.
