### ISSUE TITLE
irkernel wirting to history.sqlite

### ISSUE THREAD

**Issue by FaGuoMa** [IRkernel/IRkernel#507]
Hi I'm running jupyterhub 0.7.2 and the current irk version. I'm looking in to command history, but looking in .ipython/profile_default/history.sqlite only yields python commands sent using the notebook.
So, where does IRkernel sends it's log of commands ?

**Comment by takluyver** [comment]
IRkernel does not currently record the commands you run. 

(Also, `.ipython` is only meant to contain stuff related to Python, since all the multi-language code was split off as *Jupyter*)

**Comment by FaGuoMa** [comment]
Thanks a lot for the quick answer. It does make me a bit of a sad panda, since I'm trying to profile user load on a server. Any suggestion about how I could get a sense of what people do (if 10 guys run some RNN training at the same time vs plotting, it's a very different greed profile)

**Comment by takluyver** [comment]
There was some discussion before about logging all code executed through Jupyter: https://groups.google.com/d/topic/jupyter/sLKCCBwlKEc/discussion

**Comment by FaGuoMa** [comment]
Welp, I suppose I'll look into a pull request
