### ISSUE TITLE
Kernel stops responding after kernel reconnect in jupyter notebook

### ISSUE THREAD

**Issue by skukhtichev** [IRkernel/IRkernel#508]
There is an issue while reconnecting to the kernel when the kernel is in busy state: kernel stops responding to the code execution requests if reconnect happened during code execution. I opened the issue in the notebook project some time ago: https://github.com/jupyter/notebook/issues/2633. It describes the python issue, but for R kernel the behavior is the same.  
I've done additional investigation and found that the issue could be related to the ZMQ connection handling (ROUTER - DEALER channels). The issue happens because shell ZMQ channel could not correctly handle notebook server disconnect when the kernel is in busy state. When the websocket is disconnected Notebook server finishes websocket connection and closes stream and socket connection on the notebooks server (DEALER connection), but it looks like that information about identity continues exist in the kernel ZMQ infrastructure. ZMQ is designed in the following way: when the client (DEALER) connects to the kernel (ROUTER) with the same identity and this identity exists on ROUTER (kernel) then the new connection is dropped. ZMQ supports additional option ZMQ_ROUTER_HANDOVER that allows to drop already existent connection on the ROUTER if the new connection requests comes. By default this option is disabled.
Enabling ZMQ_ROUTER_HANDOVER option while initializing ROUTER sockets (shell, control, stdin channels) could solve the issue

**Comment by flying-sheep** [comment]
here, that would probably be

```r
zmq.setsockopt(s, ZMQ.SO()$ROUTER_HANDOVER, 1L)
```

**Comment by skukhtichev** [comment]
It should be done only for `ROUTER` sockets (shell, control, stdin channels)

**Comment by flying-sheep** [comment]
OK, done!
