### ISSUE TITLE
Error in IRkernel::installspec() :    jupyter-client has to be installed but “jupyter kernelspec --version” exited with code 127. In addition: Warning message: running command '"jupyter" kernelspec --version' had status 127 

### ISSUE THREAD

**Issue by mf201710** [IRkernel/IRkernel#510]
Hello, 
I am COMPLETELY new to code (basically have no idea what I'm doing) and need some help. I was asked to follow the following instructions: 
-	Install R from https://cran.r-project.org/
-	Install R Studio from https://www.rstudio.com/
-	Install Anaconda from https://www.continuum.io/downloads#windows
-	Install R kernel by following instructions from https://irkernel.github.io/installation/ (I have had problems with this in the past. Look here for guidance: http://stackoverflow.com/questions/31293325/r-install-github-fails)
-	Copy runJupyter.bat from "Q:\....... "  onto your desktop

Now I just keep getting stuck at the second step in installing the IRkernel:   IRkernel::installspec()
and I get this error message: 

Error in IRkernel::installspec() :    jupyter-client has to be installed but “jupyter kernelspec --version” exited with code 127. In addition: Warning message: running command '"jupyter" kernelspec --version' had status 127 

I read through other posts in the site but I couldn't follow and would really appreciate if someone could help me out. 

Thank you so much.

**Comment by ViniAvas** [comment]
I have the same issue!!

**Comment by takluyver** [comment]
I would guess that Anaconda is not on PATH when you run `IRkernel::installspec()`. Is it possible to start R from an Anaconda command prompt and then run that command?

**Comment by ViniAvas** [comment]
No, it is not possible to start R from anaconda prompt. Any idea how to fix it?

**Comment by takluyver** [comment]
Two options:

- Find `R.exe` somewhere on your system and run this from the Anaconda prompt. Then you should be able to install IRkernel from your existing R environment.
- Install R through conda. If I recall correctly, the command is `conda install -c r r-irkernel`. This is simpler because it lets conda manage everything, but it creates a separate R installation from the one Rstudio uses, which may be confusing.

**Comment by mf201710** [comment]
Hi Thomas, 

Yes you were right Anaconda was not on my path - It was only added to the System variables and not the user variables! All is working for me now. Thank you !!

**Comment by flying-sheep** [comment]
great!

**Comment by kamua** [comment]
> Find R.exe somewhere on your system and run this from the Anaconda prompt. Then you should be able to install IRkernel from your existing R environment.

**takluyver**, thank you for a good idea!

**Comment by rockp1** [comment]
On Linux, you can also place a symlink to jupyter in a directory that's on the path (eg /usr/bin).
`cd /usr/bin
sudo ln -s /full/path/to/anaconda3/bin/jupyter jupyter`

In Ubuntu 17.10, I have jupyter installed with Anaconda. But my R is not installed via conda. I was getting this error, even though ../anaconda3/bin was added to ~/.bashrc

**Comment by nizamstatistics** [comment]
Hi, I found R.exe file on my computer but how can I run in it Anaconda command prompt. Can anybody please help me, I am new to this.

**Comment by takluyver** [comment]
The simplest way is to copy the full path `C:\...\R.exe` into the Anaconda prompt.

**Comment by nizamstatistics** [comment]
When I used the path "C:\Users\Nizam>C:\Program Files\R\R-3.4.3\bin\x64\R.exe" I got an error as:

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

Can you please help?

**Comment by takluyver** [comment]
Sorry, if it's got a space in you'll need to put the whole path in quotes:

```
C:\Users\Nizam>"C:\Program Files\R\R-3.4.3\bin\x64\R.exe"
```

**Comment by nizamstatistics** [comment]
Thank you very very much. It worked. Would I need to do this every time I run jupyter notebook?

**Comment by takluyver** [comment]
No, just once when you're installing IRkernel.

**Comment by nizamstatistics** [comment]
I just installed it so it won't be needed in future? Thanks a lot for your help.

**Comment by takluyver** [comment]
Yup, that should be it, unless you want to install it on another computer, or with another version of R.

**Comment by nizamstatistics** [comment]
Thank you very very much. It was very very helpful.

**Comment by jarango2020** [comment]
excelent

**Comment by agailloty** [comment]
> Two options:
> 
> * Find `R.exe` somewhere on your system and run this from the Anaconda prompt. Then you should be able to install IRkernel from your existing R environment.
> * Install R through conda. If I recall correctly, the command is `conda install -c r r-irkernel`. This is simpler because it lets conda manage everything, but it creates a separate R installation from the one Rstudio uses, which may be confusing.

This works for me, thank @takluyver

**Comment by yangqianq** [comment]
hello guys, i sloved this problem by runing:
"conda install jupyter_client"
and under R : IRkernel::installspec(name = 'yourenvname', displayname = 'yourenvname') 

Hope to help you
