### ISSUE TITLE
Error installing IRkernel

### ISSUE THREAD

**Issue by nabriis** [IRkernel/IRkernel#513]
Hi, from an anaconda version 4.3.23 when running (a live server used in university courses)
```
conda create -n r-env-forestfloor -c brown-data-science r-forestfloor -y
source activate r-env-forestfloor
R
install.packages("devtools")
install.packages(c('repr', 'IRdisplay', 'evaluate', 'crayon', 'pbdZMQ', 'devtools', 'uuid', 'digest'))
devtools::install_github('IRkernel/IRkernel')
```
I get the error
```

Downloading GitHub repo IRkernel/IRkernel@master
from URL https://api.github.com/repos/IRkernel/IRkernel/zipball/master
Installation failed: error in running command
Warning message:
GitHub repo contains submodules, may not function as expected!
```

Just yesterday I installed this on a test server with anaconda version 4.3.25 with no problems.

**Comment by flying-sheep** [comment]
that’s either a problem with a flaky connection or a proxy or something. it (usually) isn’t a bug in devtools, and it certainly isn’t one in IRkernel (IRkernel isn’t installed at this point)

i can only suggest to try again or try annother internet connection.

**Comment by steffenheyne** [comment]
I get exactly same message/problem, for sure no connection problem...
I'm also using a central anaconda with R 3.4.1, I have to find out which anaconda version it is...

**Comment by steffenheyne** [comment]
ah reinstalling curl with install.packages("curl") seems to solve it, now it continues and the R kernel works fine

**Comment by jakereps** [comment]
Ran into the same issue, which is not answered anywhere in the IRkernel issue tracker (open or closed issues).

```R
> devtools::install_github('IRkernel/IRkernel')
Downloading GitHub repo IRkernel/IRkernel@master
from URL https://api.github.com/repos/IRkernel/IRkernel/zipball/master
Installation failed: error in running command
Warning message:
GitHub repo contains submodules, may not function as expected! 
```

Searching around for `devtools::` errors specifically brought up another _answered_ (stop-gapped) issue, which seems to have resolved it for me, and let the package install IRkernel properly: https://github.com/RevolutionAnalytics/RRO/issues/37#issuecomment-67718721

Environment
-
```bash
(env) $ R --version
R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
http://www.gnu.org/licenses/.


(env) $ conda --version
conda 4.3.30
```

**Comment by takluyver** [comment]
Thanks, good find. Do you want to add a note to the website - maybe as another side box on the install page, or a FAQ entry?

**Comment by jakereps** [comment]
Sure, I can take a swing at it this week!
