### ISSUE TITLE
Incorrect visualisation of R array in Jupyter notebook

### ISSUE THREAD

**Issue by damnko** [IRkernel/IRkernel#515]
Hello, I'm pretty new to both Jupyter and R so I hope I'm not missing something, but I've found no solution to this problem so far.

I'm simply trying this code
```
nms <- list(DeathPen=c('Yes', 'No'), Defendant=c('White', 'Black'), Victim=c('White', 'Black'))
count <- c(53, 414, 11, 37, 0, 16, 4, 139)
deaths <- array(count, c(2,2,2), dimnames=nms)
deaths
```

Which gives different outputs in the R console and in Jupyter.
**R console output**
```
, , Victim = White
        Defendant
DeathPen White Black
     Yes    53    11
     No    414    37

, , Victim = Black
        Defendant
DeathPen White Black
     Yes     0     4
     No     16   139
```

**Jupyter R notebook output**
`53 414 11 37 0 16 4 139`

Am I doing something wrong?
Thanks for your help

**Comment by flying-sheep** [comment]
Hi, thanks for the report.

I moved it to IRkernel/repr/issues/88

**Comment by mucioosorio** [comment]
whith print(deaths), the visualization is correct...
