### ISSUE TITLE
kernel dying due to failure to shadow getPass

### ISSUE THREAD

**Issue by wresch** [IRkernel/IRkernel#520]
I installed the required R packages in our (non-anaconda) R 3.4.0 following the instructions on the web site. Here is the sessionInfo:
```
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.8 (Final)

Matrix products: default
BLAS/LAPACK: /usr/local/OpenBLAS/0.2.19/gcc-4.9.1/lib/libopenblas_nehalemp-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.utf8       LC_NUMERIC=C
 [3] LC_TIME=en_US.utf8        LC_COLLATE=en_US.utf8
 [5] LC_MONETARY=en_US.utf8    LC_MESSAGES=en_US.utf8
 [7] LC_PAPER=en_US.utf8       LC_NAME=C
 [9] LC_ADDRESS=C              LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.utf8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] digest_0.6.12        uuid_0.1-2           pbdZMQ_0.2-6
[4] crayon_1.3.4         evaluate_0.10.1      repr_0.12.0
[7] IRdisplay_0.4.4      IRkernel_0.8.12.9000

loaded via a namespace (and not attached):
[1] compiler_3.4.0 R6_2.2.2       magrittr_1.5   tools_3.4.0    stringi_1.1.5
[6] jsonlite_1.5   stringr_1.2.0                                                
```

I installed the kernel spec into our python 2.7.13 anaconda environment, started a notebook server with

```
jupyter --ip localhost --port 22111 --no-browser
```
and connected through an ssh tunnel.  Starting a R notebook worked fine, but when trying to run any R command the kernel died with (debugging turned on):

```
DEBUG: main loop: beginning
DEBUG: main loop: after poll. ZMQ code: 1; Errno: 11
DEBUG: main loop: shell
DEBUG: Sending msg status
DEBUG: Sending msg execute_input
Error in as.environment(paste0("package:", pkg)) :
  no item called "package:getPass" on the search list 
Calls: <Anonymous> ... <Anonymous> -> add_to_user_searchpath -> replace_in_package
```

So for some reason the attempt to shadow the getPass function fails. It actually turns out that
loading the getPass package ahead of starting the kernel fixed this issue - i.e. i changed the
kernel spec to

```
{
  "argv": ["/usr/local/apps/R/gcc_4.9.1/3.4.0/lib64/R/bin/R",
           "--slave", "-e", "library(getPass); IRkernel::main()",
           "--args", "{connection_file}"],
  "display_name": "R/3.4.0",
  "language": "R"
}
```

I'm sure this is just me being stupid and missing something basic...

**Comment by sam-m-gardiner** [comment]
I had the same problem on windows 10 64 bit. I had a pre-existing version of R installed and I attempted to install the R kernel into a fresh reinstall of anaconda. My install of R is 3.4.2

In my case, any r script (e.g., 2+2) in the notebook would cause the kernel to crash.

The above fix worked for me. I found my kernel json file install location by doing this:
jupyter kernelspec list and modifying the file as above. So thanks a lot @wresch !

Python notebooks were working, and i verified that the getpass library was able to be loaded by running the following in a python 3 notebook.
import getpass
getpass.getuser()


here's the output from jupyter that i was getting when R kernel was dying, the message "Hello from the home folder" is my startup script in R, so R is able to start up. :

# log
[I 11:10:51.560 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 11:10:54.869 NotebookApp] Creating new notebook in
[I 11:10:56.006 NotebookApp] Kernel started: 89244be8-ede3-4e93-a3f1-d5dcdc9ed628
[1] "Hello from the home folder..."
[I 11:10:57.318 NotebookApp] Adapting to protocol v5.0 for kernel 89244be8-ede3-4e93-a3f1-d5dcdc9ed628
Error in as.environment(paste0("package:", pkg)) :
  no item called "package:getPass" on the search list
Calls: <Anonymous> ... <Anonymous> -> add_to_user_searchpath -> replace_in_package
Execution halted
[I 11:10:58.987 NotebookApp] KernelRestarter: restarting kernel (1/5)
kernel 89244be8-ede3-4e93-a3f1-d5dcdc9ed628 restarted
[1] "Hello from the home folder..."

**Comment by takluyver** [comment]
@flying-sheep is it possible that the `getPass` package is loaded in some situations but not in others? Would it be OK to unconditionally load it in our code?

**Comment by flying-sheep** [comment]
i’m not sure everyone has it installed, right?

maybe i changed something that unconditionally tries to get that namespace

**Comment by sam-m-gardiner** [comment]
Hi,
I couldn't quite bring myself to do a fully clean install, but it looks good! 

I did this:
* install_github on the package again, it picked up your change
* removing the library(getPass) from the kernel.json
* re-run jupyter notebook
* create a new R notebook and ran 2+2
* it worked!

If I'd thought about it a bit more I should have put it back into a broken state first, before re-installing.

thanks a lot

**Comment by flying-sheep** [comment]
awesome, thanks!

**Comment by wresch** [comment]
Sorry for the late reply. Patch looks good. Thank you very much!
