### ISSUE TITLE
Anaconda installation issue

### ISSUE THREAD

**Issue by larssonbajra** [IRkernel/IRkernel#521]
![anaconda](https://user-images.githubusercontent.com/25429466/32818432-acb9513e-ca06-11e7-8a59-1e7a515cc26c.PNG)

I have been trying to install anaconda but this error seems to appear everytime before the completion of installation. Does anyone have idea on this issue?

**Comment by flying-sheep** [comment]
Sadly not. I think you should ask in the anaconda community support group: https://www.anaconda.com/community-support/
