### ISSUE TITLE
AequilibraE  : qgis plugins

### ISSUE THREAD

**Issue by lixu89** [IRkernel/IRkernel#522]
When I use "AequilibraE--GIS tools--Desire Lines” in qgis, shows the following error:

```
Binary Error: Please download it from the repository using the downloader from the menu. 
```

When I use "AequilibraE--Download binaries” in qgis,  shows the following Pyhon error:

```pytb
Traceback (most recent call last): 
  File "C:/Users/dell/.qgis2/python/plugins\AequilibraE\binary_downloader_class.py",
    line 53, in download_binary urllib.urlretrieve(self.binary_path, self.local_path)
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\urllib.py", line 94, in urlretrieve 
    return _urlopener.retrieve(url, filename, reporthook, data)
  ……
  IOError: [Errno socket error] [Errno 10060].
```

I'm so confused. Why?

**Comment by takluyver** [comment]
This doesn't look related to IRkernel - you probably need to ask AequilibraE or QGis. Let me know if I've missed something!

**Comment by lixu89** [comment]
I now install the formal version of AequilibraE , and the problem resolved.   @takluyver     
I have no more other solutions.

**Comment by takluyver** [comment]
OK, great.
