### ISSUE TITLE
Problem installation IRKernel

### ISSUE THREAD

**Issue by eltorito12** [IRkernel/IRkernel#525]
Hi all,

I'm trying to install the IRKernel following the steps stated here (https://github.com/IRkernel/IRkernel):

```r
install.packages('devtools')
devtools::install_github('IRkernel/IRkernel') 
```

But the second instruction returns the following error:

```r
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Couldn't resolve host name
```

Could you please help me with it? I'm quite new to R and I don't know how to figure it out, I have also tried to install it directly downloading but without success

Thank you very much.

**Comment by takluyver** [comment]
@flying-sheep Do you think it's worth having another go at getting IRkernel on CRAN? We seem to get a lot of issues about just getting it installed, none of which we can directly do much about.

**Comment by eltorito12** [comment]
thank you @takluyver 

I have managed to manually install it but when trying to execute the order:

IRkernel::installspec()

The following error shows up:

Error in IRkernel::installspec() : 
  jupyter-client has to be installed but “jupyter kernelspec --version” exited with code 127.
Además: Warning message:
comando ejecutado '"jupyter" kernelspec --version' tiene estatus 127 

Thank you

**Comment by takluyver** [comment]
Are you running that in a terminal? If you run `jupyter kernelspec --version` in the terminal, does it work?

**Comment by eltorito12** [comment]
@takluyver  I was not but I tried it and it is still showing the same message

**Comment by takluyver** [comment]
And if you run `jupyter kernelspec --version` yourself in that terminal (outside R), does it work?

**Comment by eltorito12** [comment]
It doesn't work either... I don't know if I may be doing something wrong

**Comment by takluyver** [comment]
Have you installed Jupyter? If you've used Anaconda, you may need to run R inside the 'Anaconda command prompt' so that it can find Jupyter.

**Comment by eltorito12** [comment]
I just did and it showed the version 5.1.0

**Comment by eltorito12** [comment]
And managed to execute IRkernel::installspec()  too!! Thank you so much!

**Comment by takluyver** [comment]
Great :-)
