### ISSUE TITLE
missing images when using nbconvert --to markdown

### ISSUE THREAD

**Issue by holgerbrandl** [IRkernel/IRkernel#527]
I'm tring to convert a markdown file with embedded r-chunks using nbconvert,
```
mdFile=ir_missing_image.md
mdBaseName=$(basename $mdFile .md)

notedown $mdFile > ${mdBaseName}.ipynb

jupyter nbconvert --ExecutePreprocessor.kernel_name=ir  --execute --to markdown ${mdBaseName}.ipynb --stdout > ${mdBaseName}.rendered.md
```

It runs without errors, but the image referenced in the resulting markdown file does not exist:
```
plot(1:10)
...
![png](ir_missing_image_files/ir_missing_image_3_0.png)
```

[ir_missing_image.md.txt](https://github.com/IRkernel/IRkernel/files/1513481/ir_missing_image.md.txt)

**Comment by takluyver** [comment]
This is really an nbconvert issue, but I think that's expected if you use `--stdout` - it only writes the associated images if you let nbconvert write the files, not if you pipe it. Try this:

```shell
jupyter nbconvert --ExecutePreprocessor.kernel_name=ir  --execute --to markdown ${mdBaseName}.ipynb --output ${mdBaseName}.rendered
```

**Comment by holgerbrandl** [comment]
Indeed, replacing `--stdout` with `--output` fixes the problem. Thanks, and sorry for the tracker spam.
