### ISSUE TITLE
ETA for installing from CRAN?

### ISSUE THREAD

**Issue by davidedelvento** [IRkernel/IRkernel#528]
The front page has the following message since a lot of time:

> We will soon submit the IRkernel package to CRAN. Until then, you can install it via the devtools package:
> 
> ```
> install.packages('devtools')
> devtools::install_github('IRkernel/IRkernel')
> # or devtools::install_local('IRkernel-master.tar.gz')
> IRkernel::installspec()  # to register the kernel in the current R installation
> ```

Is there an ETA on when the package may actually appear in CRAN?

I ask because I need to use ansible to deploy IRkernel on my server, and doing the above in ansible is a pain. If "soon" is next month, I'd rather wait. On the other hand if "soon" is in a year or two...

Thanks!

**Comment by davidedelvento** [comment]
Can a user like me ask them to help nudge?

**Comment by flying-sheep** [comment]
sure, idk if they will respond, but it seems like i’m just ignored by now 😞

**Comment by spennihana** [comment]
Hi again! 
FYI, `JuniperKernel` is available on CRAN today:
https://CRAN.R-project.org/package=JuniperKernel

**Comment by takluyver** [comment]
Nice work! :-)

**Comment by flying-sheep** [comment]
Congrats! you probably don’t have the problem that you need to use all kinds of R-level hacks to use internal R machinery, since you can just use them from C++.

Maybe this is why you succeeded in getting it on CRAN while we didn’t.

**Comment by spennihana** [comment]
Thank you!

Getting into CRAN was not very easy for this package either (due to the need for x-platform compilation). I also remember it being difficult when the H2O R package was pushed to CRAN. It depends on the complexity of the package, and also a little on which CRAN gate keeper you get.

What helped me a lot was having `R CMD check` as part of my CI (https://github.com/JuniperKernel/JuniperKernel/blob/master/scripts/r_cmd_check_validate.R) and being able to test on multiple local OSs.

**Comment by davidedelvento** [comment]
FWIW, they did not respond to me either

**Comment by hhoeflin** [comment]
Do you have some more information on what the original issue was with the submission? The process is pretty automated and usually succeeds if you can run R CMD check successfully.

**Comment by flying-sheep** [comment]
it needs jupyter to be installed (listed as SystemRequirement).

jupyter isn’t installed on the test systems (anymore), the automatic checks fail, the officials are unresponsive, the end.

**Comment by hhoeflin** [comment]
ah - I see. I just ran it on a system without jupyter installed, and everything seemed to pass fine, except for the "testthat" tests at the end? I assume this is also what you are seeing?

Have you tried to simply disable these tests on CRAN? Then the automatic check would pass without error?

**Comment by hhoeflin** [comment]
Addendum: The 
`skip_on_cran()`
function in testthat should help with skipping any failing tests that only fail due to missing SystemRequirements. Maybe this would be acceptable to the CRAN maintainers.

**Comment by flying-sheep** [comment]
I finally did it in 69e5ca89b0687c25d65052b5a3847dfe3cc38c0b

**Comment by spennihana** [comment]
Congrats!!!🎉 

Windows checks passed for IRkernel, typically it takes a few extra days for binaries to populate. You may be able to install via source.

**Comment by flying-sheep** [comment]
YES! it’s on windows now too :grin: 

thanks y’all for your patience
