### ISSUE TITLE
SOS - Error Building IRKernel - Making 'packages.html' ...Error in flush.console()

### ISSUE THREAD

**Issue by gavihs** [IRkernel/IRkernel#530]
I am trying to build the IRKernel and I am having the following error

All the other steps are fine

```r
> install_github('IRkernel/IRkernel')
Downloading GitHub repo IRkernel/IRkernel@master
from URL https://api.github.com/repos/IRkernel/IRkernel/zipball/master
Installing IRkernel
'/usr/lib64/R/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/tmp/RtmparX6sj/devtools116776c0c530/IRkernel-IRkernel-dfa7f4e'  \
  --library='/usr/lib64/R/library' --install-tests

* installing *source* package ‘IRkernel’ ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
  converting help for package ‘IRkernel’
    finding HTML links ... done
    Comm-class                              html
    CommManager-class                       html
    IRkernel                                html
    comm_manager                            html
    installspec                             html
    log_-times                              html
    main                                    html
** building package indices
** testing if installed package can be loaded
* DONE (IRkernel)
Making 'packages.html' ...Error in flush.console() : attempt to apply non-function
Making 'packages.html' ...Error in flush.console() : attempt to apply non-function
Execution halted
Installation failed: Command failed (1)
Warning message:
GitHub repo contains submodules, may not function as expected!
```

**Comment by takluyver** [comment]
Weird, I don't recall any reports of that one before. What version of R are you using?

**Comment by gavihs** [comment]
@flying-sheep @jgbradley1 
there is a commit either of you have made on 24th October 7e36cfe - "fixed env replacing"
in this commit the file IRKernel/R/environment_shadow.r has been overwritten - This file was first changed on 2nd October with 5f8ac38 works fine

**Comment by gavihs** [comment]
R version 3.4.1 (2017-06-30) -- "Single Candle"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)

The latest Version

Also, when I download the version indicated above 5f8ac38 and installed locally - it works

**Comment by SkullCrusher** [comment]
I have the same issue as @gavihs.

version.string R version 3.4.2 (2017-09-28)
platform       x86_64-redhat-linux-gnu

**Comment by flying-sheep** [comment]
Hmm, the error sounds like either `flush.console` or the following replacement function from `init_shadowenv` is being called, but either `backup_env$utils_flush_console` or `flush_console` isn’t a function, right?

https://github.com/IRkernel/IRkernel/blob/7e36cfe9dc9d245ca8d4a36d811bac9b8d7b4991/R/environment_shadow.r#L82-L85

what my code is supposed to do is:

1. The IRkernel package is loaded, which calls `.onload`: https://github.com/IRkernel/IRkernel/blob/7e36cfe9dc9d245ca8d4a36d811bac9b8d7b4991/R/onload.r#L1-L4
2. This `init_backup_env` is called: https://github.com/IRkernel/IRkernel/blob/7e36cfe9dc9d245ca8d4a36d811bac9b8d7b4991/R/environment_shadow.r#L36-L39
3. now `backup_env` contains the original `base::flush.connection` and `utils::flush.console`.
4. once `IRkernel$new()`→`initialize()` is called, we call `init_shadowenv`, which replaces the built-in flushing functions with our version (see `replace_in_package` code block above)

What I don’t understand now:

- The original `flush.console` is just `function() invisible(.Call(C_flushconsole))`
- The replacement code calls `backup_env$utils_flush_console` and `flush_console`, both of which should be functions, **except if the `.onload` code isn’t run**.

**Comment by gavihs** [comment]
@flying-sheep - my guess is that the file environment_shadow.r has been overwritten subsequently - can you check this!!!

**Comment by flying-sheep** [comment]
yeah, in those commits: https://github.com/IRkernel/IRkernel/commits/dfa7f4ef2c855d289df451cb8af18b3fd0c96fda/R/environment_shadow.r

which one introduced the problem?

**Comment by gavihs** [comment]
the current code is the problem the one with the commit of "replace flush.console in utils::" works fine

**Comment by flying-sheep** [comment]
which commit introduced the problem?

- [ ] 7e36cfe9dc9d245ca8d4a36d811bac9b8d7b4991
- [ ] eefa287899068a78606ed73b1d130affcd40f831
- [ ] 9a7730ee50d51601eabbdc83f8801bfa913502f9

**Comment by gavihs** [comment]
7e36cfe - is what I think introduced the problem

**Comment by flying-sheep** [comment]
OK, and could you please try what I said above?

> Could you try adding [here](https://github.com/IRkernel/IRkernel/blob/7e36cfe9dc9d245ca8d4a36d811bac9b8d7b4991/R/environment_shadow.r#L75) the following code? `if (is.null(backup_env$utils_flush_console)) backup_env$utils_flush_console <- identity`

**Comment by mingwandroid** [comment]
@flying-sheep, I tried your suggestion:

> Making 'packages.html' ...Error in backup_env$utils_flush_console() :
>  argument "x" is missing, with no default

**Comment by mingwandroid** [comment]
.. for now, to complete my build-out, I'm passing `--no-html`. Will the packages I make be broken in other ways though?

**Comment by jpiaskowski** [comment]
Same problem - running R from centos 7 terminal in sudo.

**Comment by bxu1999** [comment]
Encountered the sane issue with R version 3.4.3 (2017-11-30) on Centos 7.4.

From the error message,  it seems to be making some kind of .html pachages so the code should still work, right?

Is this issue still been investigated at this time?

Thanks much.

**Comment by mhugen** [comment]
Same problem for me as well, also Centos 7.

**Comment by gavihs** [comment]
There is some code which has been overwritten very early
check my initial emails for details

As I am not a full fledged developer in this area - I have opted not to
make that change
I have used a older commit of the code and it works just fine atleast for
now

Someone with the knowledge of this kernel should correct this

**Comment by cablegui** [comment]
Faced the same issue with R3.4.4 on a new machine install. I then installed R3.4.0 and ran the IRkernel installation from there and everything was fine (i.e. Jupyter now is able to run R)

**Comment by AjarKeen** [comment]
Same here on Amazon Linux with R >= 3.4.

**Comment by markschwarz** [comment]
Same here on Amazon Linux with R.  I'm using Amazon's [deep learning AMI](https://aws.amazon.com/marketplace/pp/B077GF11NF) (CentOS-based) FWIW.

**Comment by flying-sheep** [comment]
sorry for not responding for so long!

Could one of you you try adding [here](https://github.com/IRkernel/IRkernel/blob/7e36cfe9dc9d245ca8d4a36d811bac9b8d7b4991/R/environment_shadow.r#L75) the following code? `if (is.null(backup_env$utils_flush_console)) backup_env$utils_flush_console <- function(...) {}`

and test with that?

**Comment by mingwandroid** [comment]
I have added this to the `Anaconda Distribution` recipe as a patch and will try it when I get on to the Windows build-out, which is the only one that had this issue for us. I do build-outs for macOS and Linux before Windows usually.

**Comment by mingwandroid** [comment]
(and thanks BTW!)

**Comment by flying-sheep** [comment]
sure, sorry for taking so long!

**Comment by hanyunfan** [comment]
@flying-sheep could you merge it or told what command I should use to have it patched.

Because command: install_github('IRkernel/IRkernel') still pulling dfa7f4e, which is the last release of IRkernel on github as below: 
 

> devtools::install_github('IRKernel/IRKernel')
Downloading GitHub repo IRKernel/IRKernel@master
from URL https://api.github.com/repos/IRKernel/IRKernel/zipball/master
Installing IRkernel
'/usr/lib64/R/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/tmp/RtmpS6c4Cv/devtools2819840e8f924/IRkernel-IRkernel-dfa7f4e'  \
  --library='/usr/lib64/R/library' --install-tests

* installing *source* package ‘IRkernel’ ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
  converting help for package ‘IRkernel’
    finding HTML links ... done
    Comm-class                              html
    CommManager-class                       html
    IRkernel                                html
    comm_manager                            html
    installspec                             html
    log_-times                              html
    main                                    html
** building package indices
** testing if installed package can be loaded
* DONE (IRkernel)
Making 'packages.html' ...Error in flush.console() : attempt to apply non-function
Making 'packages.html' ...Error in flush.console() : attempt to apply non-function
Execution halted
Installation failed: Command failed (1)
Warning message:
GitHub repo contains submodules, may not function as expected!


Sorry I can very new with R.
Frank

**Comment by flying-sheep** [comment]
Done!
