### ISSUE TITLE
Default image dimensions are too large for notebooks

### ISSUE THREAD

**Issue by valentas-kurauskas** [IRkernel/IRkernel#531]
The default repr.plot.width=7 and repr.plot.height=7 is inconveniently large. The image does not fit on a 1366 x 768 screen. Even if R defaults are (7,7), could the notebook set them to smaller? Compare them to Python matplotlib defaults.

If there is some reason to leave these defaults, `options(repr.plot.width=x, repr.plot.height=y)`  is a very long expression to type, maybe some separate function `f` could be introduced to do this just with a line `f(x,y)`.

![screenshot from 2017-12-06 11-40-32](https://user-images.githubusercontent.com/11426795/33655352-7affea88-da7b-11e7-8bec-ba68b3899a2e.png)

![screenshot from 2017-12-06 11-41-46](https://user-images.githubusercontent.com/11426795/33655360-7ef3da46-da7b-11e7-842c-70167b2cdb55.png)

**Comment by flying-sheep** [comment]
you’re right on both accounts. also options also don’t allow for code completion.

we had `get`/`set_plot_options` at one point but removed it. The rationale at that point in time was that `set_plot_options(width = 3)` wasn’t an improvement over `options(repr.plot.width = 3)`, and the latter was more general and alluded to more `repr.*` options.

@takluyver what do you think? maybe some convenience function that can set `jupyter.*`, `irdisplay.*` and `repr.*` options? there are quite a few:

```r
> names(repr::repr_option_defaults)
 [1] "repr.plot.width"           "repr.plot.height"         
 [3] "repr.plot.pointsize"       "repr.plot.bg"             
 [5] "repr.plot.antialias"       "repr.plot.res"            
 [7] "repr.plot.quality"         "repr.plot.family"         
 [9] "repr.vector.quote"         "repr.matrix.max.rows"     
[11] "repr.matrix.max.cols"      "repr.matrix.latex.colspec"
[13] "repr.function.highlight"
> names(IRkernel::jupyter_option_defaults)
[1] "jupyter.rich_display"   "jupyter.log_level"      "jupyter.logfile"       
[4] "jupyter.pager_classes"  "jupyter.plot_mimetypes" "jupyter.in_kernel"
> names(IRdisplay::irdisplay_option_defaults)
[1] "jupyter.display_mimetypes" "jupyter.base_display_func"

**Comment by takluyver** [comment]
Is there a good reason not to just tweak the defaults a bit smaller? The example does look unreasonably large.

I'm not super fond of making convenience functions - if different people set the same options in different ways, it makes code less clear collectively. But the tab completion argument is valid.

Are all these options documented somewhere? I just had a quick look around our website, but I couldn't see them.

**Comment by flying-sheep** [comment]
sure, every package has a `<package>_option_defaults` manpage:

- https://irkernel.github.io/docs/IRkernel/0.7/IRkernel.html
- https://irkernel.github.io/docs/IRdisplay/0.4.4/IRdisplay-options.html
- https://irkernel.github.io/docs/repr/0.9/repr-options.html

**Comment by takluyver** [comment]
Can you get to those by clicking links? I just tried for IRkernel and repr and I get to these pages, with no obvious sign that there are other parts of the docs:

https://irkernel.github.io/docs/IRkernel/0.7/
https://irkernel.github.io/docs/repr/0.9/

Also:

- I'd quite like to have one list of all the options from the three packages. I don't think users should need to understand how functionality is divided between IRKernel, IRdisplay and repr.
- Maybe this is an R thing, but when I first reached [this page](https://irkernel.github.io/docs/IRkernel/), I assumed that the changelog was the only docs, and the links would go to something like the release on Github. I didn't realise that the links took me to the docs for version 0.7. I usually expect to land on the docs for the latest version, with maybe a link somewhere to docs for previous versions.

**Comment by flying-sheep** [comment]
our last page update probably removed the link to the reference. 😒

> I'd quite like to have one list of all the options from the three packages.

sure, makes much sense.

>  I assumed that the changelog was the only docs, and the links would go to something like the release on Github. I didn't realise that the links took me to the docs for version 0.7

valuable feedback. we should restructure our docs and make them similar to how readthedocs works (i.e. with a selector for old versions, and the links on the overview leading to the latest version)

**Comment by Rabeez** [comment]
Has an option to change the global defaults for `options(repr.*)` been added?

**Comment by flying-sheep** [comment]
add an `options(...)` call to your `~/.Rprofile`?
