### ISSUE TITLE
No error output if call to svg() fails

### ISSUE THREAD

**Issue by terhorst** [IRkernel/IRkernel#533]
If the `svg()` command does not work in R, IRkernel will silently emit no output when using `options(jupyter.plot_mimetypes = "image/svg+xml")`. Your plots will not show up in the notebook, and no error is reported even when setting `--debug` and `options(jupyter.log_level = 3L)`.

This can occur if your version of R was compiled with `--without-cairo`, which includes the Homebrew version as of very recently (homebrew/homebrew-core#15925). Without Cairo, `svg()` fails with:

    > svg()
    Warning messages:
    1: In svg() :
      unable to load shared object '/usr/local/Cellar/r/3.4.3/lib/R/library/grDevices/libs//cairo.so':
      dlopen(/usr/local/Cellar/r/3.4.3/lib/R/library/grDevices/libs//cairo.so, 6): image not found
    2: In svg() : failed to load cairo DLL

(Since the Homebrew version of R has ~15k installs a month, I figure it's likely that someone else has encountered this issue. Hence the report.)

**Comment by flying-sheep** [comment]
Hmm, those are warnings, which is weird: if the device failed to open, there should be an error, right?

furthermore, warnings are handled by the kernel (try `warning('hi')`), so you should see them…

finally, there’s a workaround: `install.packages('Cairo')`
