### ISSUE TITLE
JuniperKernel

### ISSUE THREAD

**Issue by damianavila** [IRkernel/IRkernel#534]
Howdy all,

I found this today, it is probably something interesting for you: https://github.com/JuniperKernel/JuniperKernel

Cheers.

cc @takluyver

**Comment by takluyver** [comment]
Thanks! They let us know about it a few weeks ago as well. They've managed to get the package on CRAN, while the CRAN maintainers seem to be ignoring us, so they're already ahead on that count. ;-)

**Comment by flying-sheep** [comment]
we’re on CRAN now as well, wee!
