### ISSUE TITLE
plot.new has not been called yet

### ISSUE THREAD

**Issue by fansgit** [IRkernel/IRkernel#535]
Same error as #240 when running IR-Kernel 0.8.12.9000 on Jupyter console.

**Comment by takluyver** [comment]
I guess you've looked at the suggestions from #240, but it's hard to put
all the plotting commands in one cell when using the console interface? I
don't immediately see a way to resolve that - the notebook is used so much
more than other interfaces, so we tend to design for that. I don't know if
there's something cleverer we can do about the graphics framework.

**Comment by flying-sheep** [comment]
sevaral ways to compose a plot:

1. wrap it in a block:

    ```r
    {
        plot(...)
        lines(...)
    }
    ```

2. wrap it in a function and call it.
3. use ggplot, or plotly, which work with composable plot objects instead of some intangible device state.
