### ISSUE TITLE
Unable to install IRkernel: getting error code 127

### ISSUE THREAD

**Issue by shivendra90** [IRkernel/IRkernel#536]
As advised at the homepage, the last step is outputting the following error:

`Error in IRkernel::installspec(user = FALSE) : 
  jupyter-client has to be installed but “jupyter kernelspec --version” exited with code 127.`

The required packages installed with no problems. R did suggest to use `force = TRUE` at the second step: `devtools::install_github('IRkernel/IRkernel')` wherein I received a warning:

`Warning message:
GitHub repo contains submodules, may not function as expected!`

However, executing `IRkernel::installspec(user = FALSE)` is giving me the error described above. How do I proceed?

**Comment by takluyver** [comment]
@flying-sheep Maybe we should have a dedicated page of the docs about troubleshooting this? It seems to cause problems for a lot of people (unsurprisingly, since it's the point where two different systems have to coordinate).

**Comment by shivendra90** [comment]
Temporarily ran R through the terminal and IRkernel installed fine.

Closing.
