### ISSUE TITLE
how to install IRkernel on Mac

### ISSUE THREAD

**Issue by nwwangnan** [IRkernel/IRkernel#537]
I am a Mac user (High Sierra, 10.13.2). I am trying to install IRkernel on my laptop. I am following the instructions on https://irkernel.github.io/installation/, but it is not helpful at all. when I was trying to install devtools::install_github('IRkernel/IRkernel'), my computer always warn me " no devtools name is available". Can anyone help me out?

**Comment by takluyver** [comment]
The step before that should have installed devtools:

```R
install.packages(c('repr', 'IRdisplay', 'evaluate', 'crayon', 'pbdZMQ', 'devtools', 'uuid', 'digest'))
```
