### ISSUE TITLE
Vectors in output cells are displayed incorrectly when exported to PDF

### ISSUE THREAD

**Issue by mkozturk** [IRkernel/IRkernel#540]
I'm using Jupyter notebook 5.0.0 with the R 3.4.2 kernel on Ubuntu MATE 17.10. I have cells that have a vector variable as the last expression. When I export the notebook to PDF, the vectors are displayed incorrectly, such as:
> x <- c(5,6,7)
> x
> 1. 5 2. 6 3. 7

It appears that elements are preceded with their indices. This occurs only with PDF, not with HTML. The problem does not occur when I call print() directly to display the variable.

Here is a screenshot from the resulting PDF file:
![screenshot at 2018-02-12 16-37-06](https://user-images.githubusercontent.com/2970616/36099412-a17e2b48-1013-11e8-9834-ec16571652fe.png)

**Comment by flying-sheep** [comment]
That’s intended. Please check the [enumitem docs](https://ctan.org/pkg/enumitem) how to configure this, e.g.:

```r
IRdisplay::display_latex('\\setlist[enumerate,1]{label = \\arabic*}')
```
