### ISSUE TITLE
install fail on mac 10.11.6

### ISSUE THREAD

**Issue by vv111y** [IRkernel/IRkernel#542]
git2r package install failed:
```
/Users/xxx/anaconda3/include/tclUnixPort.h:158:13: fatal error: '../compat/unistd.h' file not found
#   include "../compat/unistd.h"
```
system info:
```
platform       x86_64-apple-darwin15.6.0
arch           x86_64
os             darwin15.6.0
system         x86_64, darwin15.6.0
status
major          3
minor          4.3
year           2017
month          11
day            30
svn rev        73796
language       R
version.string R version 3.4.3 (2017-11-30)
nickname       Kite-Eating Tree
```

**Comment by vv111y** [comment]
okay, modified solution in https://github.com/ropensci/git2r/issues/259

```
install.packages("git2r", type = 'mac.binary.elcapitan')
```
worked for me. But now I get 
```
 *** caught segfault ***
address 0x140, cause 'memory not mapped'
```

**Comment by vv111y** [comment]
I wonder if this has anything to do with https://github.com/IRkernel/IRkernel/issues/313
I installed R via homebrew a while ago, and then installed anaconda - I wonder if there are some conflicts somehow.

**Comment by flying-sheep** [comment]
Sorry I didn’t reply. I don’t have a mac and can’t help here.

However, there’s officially built CRAN versions of everything now, so that should work!
