### ISSUE TITLE
jupyter can't interrupt R kernel

### ISSUE THREAD

**Issue by Simon-Zhen** [IRkernel/IRkernel#543]
I'm writing R through Jupyter. But when I try to interrupt kernel(Kernel-Interrupt), it doesn't work. Than how can I stop R kernel?

**Comment by flying-sheep** [comment]
interrupts don’t exit shells. neither bash nor python nor R nor IRkernel.

you can use ctrl-d or `q()` or `quit()`

**Comment by Simon-Zhen** [comment]
Thanks.
But when using python interrupt kernel can stop my python program. I just wonder how to stop
my R program. Ctrl-d or q() doesn't work.

**Comment by flying-sheep** [comment]
it should! are you using the notebook or the terminal via `jupyter console --kernel=ir`?

are you using the newest versions of IRkernel, repr, and IRdisplay?

**Comment by Simon-Zhen** [comment]
Well, I just re-install it again, so I think it may be the latest version. I'm a newcomer to Jupyter, may be I just didn't get your point. Can you tell me again in detail, or may be some pictures?
Thanks a lot!

**Comment by flying-sheep** [comment]
> are you using the notebook or the terminal via `jupyter console --kernel=ir`?

i still don’t know *what* you want to quit from :smile:

**Comment by Simon-Zhen** [comment]
I'm using the notebook

**Comment by flying-sheep** [comment]
you shouldn’t exit the R kernel from notebook cells then. there’s UI for that! “Close and Halt”

![](https://www.ibm.com/support/knowledgecenter/SSSMS8/content/userImages/close_and_halt.jpg)

**Comment by Simon-Zhen** [comment]
![image](https://user-images.githubusercontent.com/36781925/36642635-6965ad34-1a7d-11e8-9b4a-ac8cfcaa581a.png)
I want to stop this running program and edit it, not going to quit it. Can I?

**Comment by Simon-Zhen** [comment]
When using Python, the interrupt button may stop the running program, so that I can edit it without quiet. 
But through R kernel, the interrupt button doesn't work. I don't know what's wrong.
![image](https://user-images.githubusercontent.com/36781925/36642889-6a6d6548-1a80-11e8-9b1e-e3ba4fe88de3.png)

**Comment by flying-sheep** [comment]
it works for me. but if you invoke code that calls into C, the code has to be written in a way that allows interrupting from R. e.g. in RCpp, the package developer needs to be aware of `Progress::check_abort()`.

what call do you want to interrupt and it fails?

**Comment by Simon-Zhen** [comment]
![image](https://user-images.githubusercontent.com/36781925/36643145-c03e1bb4-1a82-11e8-980a-fbae4309b6a5.png)
Actually I don't know what does it mean……

**Comment by flying-sheep** [comment]
what code do you execute in R that you need to be able to interrupt?

```r
ptm <- proc.time()
options(digits = 22)
... # what comes here that runs for a long time that you want to stop?
```

**Comment by Simon-Zhen** [comment]
Well, there are several hundred lines code than……
I think you are right. I checked my codes carefully and found that may be one R package that calls into C++.
So sorry to bother you. And thank you so much!

**Comment by flying-sheep** [comment]
no problem! if i can help you with something else, don’t be afraid to ask!

**Comment by Simon-Zhen** [comment]
Thank you for your kindness.
