### ISSUE TITLE
Plot generated from R library is not showing in R Jupyter notebook

### ISSUE THREAD

**Issue by kohaugustine** [IRkernel/IRkernel#545]
I am repeating here a [post](https://stackoverflow.com/questions/48972807/plot-generated-from-r-library-is-not-showing-in-r-jupyter-notebook) which I made on Stackoverflow, where I'm not receiving much help from on this matter, unfortunately.

I am using the [SensoMineR package `coltable` function](https://www.rdocumentation.org/packages/SensoMineR/versions/1.23/topics/coltable) to generate a heatmap like plot of sensory data I've analyzed.

The problem I'm facing is that while executing this function in the R terminal will display the figure, executing this function in the R Jupyter notebook does not display the figure. The figure is not showing in Jupyter.

The documentation I've linked above contains example code which easily emulates plot generation. Both my own analysis code and this example code do not work in my Jupyter notebook.

What could the cause of this problem be? I am wondering if it might have something to do with the way the `coltable` function is implemented. Perhaps its missing an explicit call to display plots or something. Considering that I have no problems at all generating and displaying `ggplot2` figures in my R Jupyter notebook, I am not sure what the problem is here....

Here is [another post](https://stackoverflow.com/questions/44148435/pca-plots-in-r-kernel-when-using-jupyter-notebook) on stackoverflow which is likely a same problem as mine, except it involves a different but closely related library, FactoMineR.

Thank you.

**Comment by flying-sheep** [comment]
well, it depends how the plot gets displayed. usually libraries do one of the following:

1. directly paint to the plot device via `grDevices` package calls
2. return a ggplot object (which does 1. in the automatically invoked `plot.ggplot` call)
3. return another class that has a custom `print` method.

could you please link to the code that is at work here?

**Comment by kohaugustine** [comment]
Thanks for suggesting the possibilities. 

My apologies, I'm not too sure which code you are referring to. Do you mean the code that works in my notebooks to generate plots? It would be any simple code such as simple calls to `ggplot`:

`ggplot(data = p2001, mapping = aes(x = Pungent, color = Session)) + geom_histogram(binwidth = 1)`

On the other hand, the code that is currently not working to display plots would be something like this:

`coltable(res.panelperf$p.value[order(res.panelperf$p.value[,1]),], col.lower="gray")`

where `coltable()` is a function in the SensoMineR library. The documentation for `coltable()` also contains example code such as:

```
## Example 1
data(chocolates)
resdecat<-decat(sensochoc, formul = "~Product+Panelist", firstvar = 5,
    graph = FALSE)
resaverage<-averagetable(sensochoc, formul = "~Product+Panelist", 
    firstvar = 5)
resaverage.sort = resaverage[rownames(magicsort(resdecat$tabT)),
    colnames(magicsort(resdecat$tabT))]
coltable(resaverage.sort, magicsort(resdecat$tabT), 
    level.lower = -1.96, level.upper = 1.96,
    main.title = "Average by chocolate")
```
and this also does not work at all when running in the notebook. However, in the R shell, it works.

Could it be that neither of the 3 actions are implemented in the `coltable()`, that is causing the problem?

**Comment by kohaugustine** [comment]
Nice finding! Apart from possibly modifying the backing code in the library, is there any other workaround in the meantime?

**Comment by flying-sheep** [comment]
yes, i just found it!

```r
imports <- parent.env(getNamespace('SensoMineR'))
unlockBinding('dev.new', imports)
assign('dev.new', function() {}, envir = imports)
```

**Comment by flying-sheep** [comment]
haha thanks!

it does something else though. so R namespaces and environments are not well documented but not that hard.

what happens in packages is that each package has three environments in a vertical relationship:

1. package imports (`importFrom(...)` in NAMESPACE file)
2. package namespace (things defined in the package’s `.R` files)
3. package exports (`export(...)` in NAMESPACE file)

user code can only see the exports of loaded packages. but the code inside of functions there can see the package namespace (“private functions”) and the imports.

what my code does is:

1. gets the import environment
2. unlocks the name binding (i.e. makes me able to execute the next line)
3. replaces the thing named `dev.new` in the import environment with a function that does nothing

now all code in the SensoMiner package that looks up what `dev.new` is will find my empty function before everything else

**Comment by kohaugustine** [comment]
I believe I'm getting the gist of your explanation, almost there but not completely!  Please bear with me as my immediate question to your last line would be, how does making the code in SensoMineR find the empty function `function() {}` actually help? 

Is it because it now prevents the creation of a new png device that points nowhere and thus allow the subsequent plot calls to be recorded? I'm basically following the idea of your earlier answer about an hour ago. So where do the plot calls get recorded now?

**Comment by flying-sheep** [comment]
yeah, exactly. creating new plot devices here is unnecessary, so in this case not doing anything is the right thing.

and my code is a hack to make it do nothing at the right places.

**Comment by kohaugustine** [comment]
Got it! Thank you @flying-sheep !

**Comment by xavierbourretsicotte** [comment]
Hello, I have the same problem with the library (FactoMineR) and in particular the function PCA

https://github.com/cran/FactoMineR/blob/master/man/PCA.Rd

Calling the function as follows: 

```
imports <- parent.env(getNamespace('FactoMineR'))
unlockBinding('dev.new', imports)
assign('dev.new', function() {}, envir = imports)
res <- PCA(temperature, quanti.sup=13:16,quali.sup=17) 
```
Gives the following error message: 

> Error in dev.new(width = min(14, 8 * (xmax - xmin)/(ymax - ymin)), height = 8): unused arguments (width = min(14, 8 * (xmax - xmin)/(ymax - ymin)), height = 8)
> Traceback:
> 
> 1. PCA(temperature, quanti.sup = 13:16, quali.sup = 17)
> 2. plot.PCA(res, choix = "ind", axes = axes, new.plot = TRUE)

I have raised an issue on the FactoMiner support forum - will keep you updated: 

https://groups.google.com/forum/#!topic/factominer-users/trO0J-nKntc

**Comment by julierennes** [comment]
You should perform PCA but don't draw the graphs, using the argument graph=FALSE, and then you draw the graph with the plot function:
data(decathlon)

res <- PCA(decathlon,quanti.sup=11:12, quali.sup=13, graph=FALSE)
plot(res, choix="ind")
plot(res, choix="var")

**Comment by flying-sheep** [comment]
@xavierbourretsicotte you could try something like

```r
assign('dev.new', function(..., width, height) {
    options(repr.plot.width = width, repr.plot.height = height)
}, envir = imports)
```

**Comment by MatildeVaghi** [comment]
Hello, I seem to have the same problem but I can't get things working using the suggested solutions. 

I am using the **jtools** package ( v. jtools_2.1.3; https://cran.r-project.org/web/packages/jtools/jtools.pdf) effect_plot function to plot model predictions from lm. 

Similarly to what happens to kohaugustine,  executing my code in the R terminal will display the figure. In contrast, executing this function in R jupyter notebook does not display the figure. The figure is not showing in Jupyter. 

I have no problems at all generating and displaying ggplot2 figures in m yR jupyter notebook. 

By running from the %%R magic cell the following 

```
imports <- parent.env(getNamespace('jtools'))
imports
```

I have the following
```
<environment: 0xa0846d8>
attr(,"name")
[1] "imports:jtools"
```

and by doing 

```
imports <- parent.env(getNamespace('jtools'))
unlockBinding('dev.new', imports)
```

I get the following error message: 
Error in unlockBinding("dev.new", imports) : no binding for "dev.new"

How could I fix this? 
Thank you, 
Matilde
