### ISSUE TITLE
IRkernel keeps dying

### ISSUE THREAD

**Issue by gpetrini** [IRkernel/IRkernel#546]
I'm trying to install R kernel to Jupyter notebook but I can't do anything. Every time I try to do something, I recieve the following message: 

> The kernel has died, and the automatic restart has failed. It is possible the kernel cannot be restarted. If you are not able to restart the kernel, you will still be able to save the notebook, but running code will no longer work until the notebook is reopened.

In the terminal, it shows

```
(base) C:\Users\Gabriel Petrini>jupyter notebook
[I 23:04:06.011 NotebookApp] JupyterLab beta preview extension loaded from C:\Users\Gabriel Petrini\Anaconda3\lib\site-packages\jupyterlab
[I 23:04:06.012 NotebookApp] JupyterLab application directory is C:\Users\Gabriel Petrini\Anaconda3\share\jupyter\lab
[W 23:04:06.021 NotebookApp] Error loading server extension jupyterlab
    Traceback (most recent call last):
      File "C:\Users\Gabriel Petrini\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 321, in __init__
        self._run(['node', 'node-version-check.js'], cwd=HERE, quiet=True)
      File "C:\Users\Gabriel Petrini\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 1165, in _run
        proc = Process(cmd, **kwargs)
      File "C:\Users\Gabriel Petrini\Anaconda3\lib\site-packages\jupyterlab\process.py", line 73, in __init__
        self.proc = self._create_process(cwd=cwd, env=env)
      File "C:\Users\Gabriel Petrini\Anaconda3\lib\site-packages\jupyterlab\process.py", line 131, in _create_process
        cmd[0] = which(cmd[0], kwargs.get('env'))
      File "C:\Users\Gabriel Petrini\Anaconda3\lib\site-packages\jupyterlab\jlpmapp.py", line 59, in which
        raise ValueError(msg)
    ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Gabriel Petrini\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1454, in init_server_extensions
        func(self)
      File "C:\Users\Gabriel Petrini\Anaconda3\lib\site-packages\jupyterlab\extension.py", line 111, in load_jupyter_server_extension
        info = get_app_info(app_dir)
      File "C:\Users\Gabriel Petrini\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 244, in get_app_info
        handler = _AppHandler(app_dir, logger)
      File "C:\Users\Gabriel Petrini\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 324, in __init__
        raise ValueError(msg)
    ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
[I 23:04:07.244 NotebookApp] Serving notebooks from local directory: C:\Users\Gabriel Petrini
[I 23:04:07.245 NotebookApp] 0 active kernels
[I 23:04:07.246 NotebookApp] The Jupyter Notebook is running at:
[I 23:04:07.246 NotebookApp] http://localhost:8888/
[I 23:04:07.249 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 23:04:14.842 NotebookApp] Kernel started: eaa1f89e-7faa-444a-9132-dad0bcd73f85
[I 23:04:15.884 NotebookApp] Adapting to protocol v5.1 for kernel eaa1f89e-7faa-444a-9132-dad0bcd73f85
[I 23:04:48.282 NotebookApp] Starting buffering for eaa1f89e-7faa-444a-9132-dad0bcd73f85:e7d01aaab35140e48de3ede1ccf7a146
[I 23:04:51.606 NotebookApp] Kernel started: 07cc0f56-609b-4268-85bc-0f05e39e801f
A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta.
[I 23:04:54.589 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta.
[I 23:04:57.617 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta.
[I 23:05:00.644 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta.
[W 23:05:01.668 NotebookApp] Timeout waiting for kernel_info reply from 07cc0f56-609b-4268-85bc-0f05e39e801f
[I 23:05:03.693 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
kernel 07cc0f56-609b-4268-85bc-0f05e39e801f restarted
A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta.
[W 23:05:06.740 NotebookApp] KernelRestarter: restart failed
[W 23:05:06.740 NotebookApp] Kernel 07cc0f56-609b-4268-85bc-0f05e39e801f died, removing from map.
kernel 07cc0f56-609b-4268-85bc-0f05e39e801f restarted failed!
[W 23:05:06.755 NotebookApp] 410 DELETE /api/sessions/a799e194-e220-4176-b39b-287e3c48a6fd (::1): Kernel deleted before session
[W 23:05:06.755 NotebookApp] Kernel deleted before session
[W 23:05:06.757 NotebookApp] 410 DELETE /api/sessions/a799e194-e220-4176-b39b-287e3c48a6fd (::1) 3.01ms referer=http://localhost:8888/notebooks/Untitled.ipynb
```

And when I try to run IR-Kernel,

> Skipping install of 'IRkernel' from a github remote, the SHA1 (dfa7f4ef) has not changed since last install. Use `force = TRUE` to force installation

What can I do? I've tried to install with pip and conda.

**Comment by flying-sheep** [comment]
The error is clearly stated in the traceback in the terminal.

just look at the `ValueError: ` line for clear instructions what to do!

if you have further problems, don’t be afraid to ask

**Comment by flying-sheep** [comment]
The error is clearly stated in the traceback in the terminal.

just look at the `ValueError: ` line for clear instructions what to do!

if you have further problems, don’t be afraid to ask

**Comment by gpetrini** [comment]
Thanks for your answer. I've installed nodejs and the kernel still doesn't work. I tried to update irkernel and the terminal returns

(base) C:\Users\Gabriel Petrini>conda update irkernel

PackageNotInstalledError: Package is not installed in prefix.
  prefix: C:\Users\Gabriel Petrini\Anaconda3
  package name: irkernel

**Comment by gpetrini** [comment]
I tried to unsinstall everything and start from scratch, still de same problem

[I 08:44:10.778 NotebookApp] JupyterLab beta preview extension loaded from C:\Users\Gabriel Petrini\Anaconda3\lib\site-packages\jupyterlab
[I 08:44:10.778 NotebookApp] JupyterLab application directory is C:\Users\Gabriel Petrini\Anaconda3\share\jupyter\lab
[I 08:44:13.167 NotebookApp] Serving notebooks from local directory: C:\Users\Gabriel Petrini
[I 08:44:13.167 NotebookApp] 0 active kernels
[I 08:44:13.167 NotebookApp] The Jupyter Notebook is running at:
[I 08:44:13.167 NotebookApp] http://localhost:8888/
[I 08:44:13.167 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 08:44:13.657 NotebookApp] 302 GET /tree (::1) 52.21ms
[I 08:44:17.724 NotebookApp] 302 POST /login?next=%2Ftree (::1) 12.56ms
[I 08:44:22.272 NotebookApp] Kernel started: 7f0b9603-c727-43ca-b038-1428a9f50ed1
[I 08:44:23.319 NotebookApp] Adapting to protocol v5.1 for kernel 7f0b9603-c727-43ca-b038-1428a9f50ed1
[I 08:44:29.442 NotebookApp] Starting buffering for 7f0b9603-c727-43ca-b038-1428a9f50ed1:98496684b90548809d7c1053cd9dc023
[I 08:44:29.762 NotebookApp] Kernel shutdown: 7f0b9603-c727-43ca-b038-1428a9f50ed1
[I 08:44:29.836 NotebookApp] Kernel started: 73a3f85b-83a4-41f5-8855-f3d10af6f128
A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta.
[I 08:44:32.829 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta.
[I 08:44:35.854 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta.
[I 08:44:38.889 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta.
[W 08:44:39.864 NotebookApp] Timeout waiting for kernel_info reply from 73a3f85b-83a4-41f5-8855-f3d10af6f128
[I 08:44:41.911 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
kernel 73a3f85b-83a4-41f5-8855-f3d10af6f128 restarted
A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta.
[W 08:44:44.952 NotebookApp] KernelRestarter: restart failed
[W 08:44:44.952 NotebookApp] Kernel 73a3f85b-83a4-41f5-8855-f3d10af6f128 died, removing from map.
kernel 73a3f85b-83a4-41f5-8855-f3d10af6f128 restarted failed!
[W 08:44:44.973 NotebookApp] 410 DELETE /api/sessions/79779e85-01a5-49af-93d9-5a52df33e060 (::1): Kernel deleted before session
[W 08:44:44.973 NotebookApp] Kernel deleted before session
[W 08:44:44.975 NotebookApp] 410 DELETE /api/sessions/79779e85-01a5-49af-93d9-5a52df33e060 (::1) 3.01ms referer=http://localhost:8888/notebooks/Pr%C3%A1tica%20R.ipynb

**Comment by flying-sheep** [comment]
please try using the official installation instructions: https://irkernel.github.io/installation/

i don’t like anaconda, it always makes problems.

**Comment by gpetrini** [comment]
I've trying the official instalattion and now the python kernel isn't dying. Only the R kernel doesn't work. Also, I'm using R 3.4.3, there is any chance that is an incompatibility problem?

**Comment by gpetrini** [comment]
Another information that might help: A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta mens

The syntax for the file name, directory name, or volume label is incorrect.

**Comment by gpetrini** [comment]
Another question (Sorry for bodering), I have to set something to System PATH variables?

**Comment by flying-sheep** [comment]
hi, usually you don’t: `IRkernel::installspec()` should handle it if it’s able to run.

“doesn't work” is always unhelpful 😉 could you please give me something to work with?

is the R kernel not listed in the menu? did `IRkernel::installspec()` fail with some message?

**Comment by gpetrini** [comment]
Sorry, I'm really new in working with terminal haha. There is soma comand that I can run to show you more info?

This is the message after running `IRkernel::installspec()`

```
> IRkernel::installspec()
[InstallKernelSpec] Removing existing kernelspec in C:\Users\Gabriel Petrini\AppData\Roaming\jupyter\kernels\ir
[InstallKernelSpec] Installed kernelspec ir in C:\Users\Gabriel Petrini\AppData\Roaming\jupyter\kernels\ir
```

How can I know that R kernel is listed?
Thanks

PS I also tried to set R and kernels\ir to my system path variebles

**Comment by gpetrini** [comment]
Also

`C:\Users\Gabriel Petrini>jupyter console --kernel=ir`
`The syntax for the file name, directory name, or volume label is incorrect.`

**Comment by gpetrini** [comment]
Update:

```
C:\Users\Gabriel Petrini>jupyter console --kernel=ir
A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta.
Traceback (most recent call last):
  File "c:\users\gabriel petrini\appdata\local\programs\python\python36\lib\site-packages\jupyter_console\ptshell.py", line 323, in init_kernel_info
    reply = self.client.get_shell_msg(timeout=1)
  File "c:\users\gabriel petrini\appdata\local\programs\python\python36\lib\site-packages\jupyter_client\client.py", line 77, in get_shell_msg
    return self.shell_channel.get_msg(*args, **kwargs)
  File "c:\users\gabriel petrini\appdata\local\programs\python\python36\lib\site-packages\jupyter_client\blocking\channels.py", line 57, in get_msg
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\gabriel petrini\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\gabriel petrini\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Gabriel Petrini\AppData\Local\Programs\Python\Python36\Scripts\jupyter-console.EXE\__main__.py", line 9, in <module>
  File "c:\users\gabriel petrini\appdata\local\programs\python\python36\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "c:\users\gabriel petrini\appdata\local\programs\python\python36\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-117>", line 2, in initialize
  File "c:\users\gabriel petrini\appdata\local\programs\python\python36\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\users\gabriel petrini\appdata\local\programs\python\python36\lib\site-packages\jupyter_console\app.py", line 141, in initialize
    self.init_shell()
  File "c:\users\gabriel petrini\appdata\local\programs\python\python36\lib\site-packages\jupyter_console\app.py", line 114, in init_shell
    client=self.kernel_client,
  File "c:\users\gabriel petrini\appdata\local\programs\python\python36\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "c:\users\gabriel petrini\appdata\local\programs\python\python36\lib\site-packages\jupyter_console\ptshell.py", line 272, in __init__
    self.init_kernel_info()
  File "c:\users\gabriel petrini\appdata\local\programs\python\python36\lib\site-packages\jupyter_console\ptshell.py", line 326, in init_kernel_info
    raise RuntimeError("Kernel didn't respond to kernel_info_request")
RuntimeError: Kernel didn't respond to kernel_info_request
```

**Comment by takluyver** [comment]
If you run `jupyter kernelspecs list`, it should show you a path to a folder ending in `ir`. Have a look in that folder for a file called `kernel.json`. That's what tells Jupyter about the R kernel. I'm not sure what's gone wrong, but have a look at it and see if there's any obvious problems (like pointing to a file that doesn't exist).

**Comment by gpetrini** [comment]
I've runned jupter kernel list:

```
C:\Users\Gabriel Petrini>jupyter kernelspecs list
Error executing Jupyter command 'kernelspecs': [Errno 'jupyter-kernelspecs' not found] 2
```

Any idea? There is any argument for `IRkernel::installspec()`?

Tks

**Comment by takluyver** [comment]
My mistake, it's `jupyter kernelspec list` (*spec* not specs).

**Comment by gpetrini** [comment]
`Available kernels:
  ir         C:\Users\Gabriel Petrini\AppData\Roaming\jupyter\kernels\ir
  ir33       C:\Users\Gabriel Petrini\AppData\Roaming\jupyter\kernels\ir33
  ir34       C:\Users\Gabriel Petrini\AppData\Roaming\jupyter\kernels\ir34
  python3    C:\Users\Gabriel Petrini\AppData\Roaming\jupyter\kernels\python3`

I have to do something with this?

**Comment by takluyver** [comment]
Have a look in `C:\Users\Gabriel Petrini\AppData\Roaming\jupyter\kernels\ir`, and see if there's anything obviously wrong in `kernel.json` there.

**Comment by gpetrini** [comment]
It has just it:

`{
  "argv": ["C:/PROGRA~1/R/R-34~1.3/bin/x64/R", "--slave", "-e", "IRkernel::main()", "--args", "{connection_file}"],
  "display_name": "R",
  "language": "R"
}`

I'm not finding anything obviously wrong in kernel.json

Sorry, I'm really new here.

**Comment by gpetrini** [comment]
Update: I've tried to chance the diretory in argv to my path to R and got the same result: kernel continously dying and restarting

**Comment by G-Slient** [comment]
My Ir kernel is dying and i am not able to fix it . kindly help me out to fix it 


(base) C:\Anaconda>jupyter notebook
[W 19:09:35.349 NotebookApp] Permission to listen on port 8888 denied
[I 19:09:35.416 NotebookApp] JupyterLab beta preview extension loaded from C:\Anaconda\lib\site-packages\jupyterlab
[I 19:09:35.416 NotebookApp] JupyterLab application directory is C:\Anaconda\share\jupyter\lab
[I 19:09:35.563 NotebookApp] Serving notebooks from local directory: C:\Anaconda
[I 19:09:35.564 NotebookApp] 0 active kernels
[I 19:09:35.565 NotebookApp] The Jupyter Notebook is running at:
[I 19:09:35.565 NotebookApp] http://localhost:8889/?token=e1f42698d70da5761f345650fbd282fdb747293bf34e50e9
[I 19:09:35.570 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 19:09:35.572 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8889/?token=e1f42698d70da5761f345650fbd282fdb747293bf34e50e9&token=e1f42698d70da5761f345650fbd282fdb747293bf34e50e9
[I 19:09:35.928 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 19:09:57.744 NotebookApp] Creating new notebook in
The filename, directory name, or volume label syntax is incorrect.
[I 19:09:59.686 NotebookApp] Kernel started: 982fd2a9-2a52-41d7-b5e6-eab91cf5c05d
[I 19:10:02.656 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
The filename, directory name, or volume label syntax is incorrect.
[I 19:10:05.673 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
The filename, directory name, or volume label syntax is incorrect.
[I 19:10:08.675 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
The filename, directory name, or volume label syntax is incorrect.
[W 19:10:09.908 NotebookApp] Timeout waiting for kernel_info reply from 982fd2a9-2a52-41d7-b5e6-eab91cf5c05d
[I 19:10:11.691 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
kernel 982fd2a9-2a52-41d7-b5e6-eab91cf5c05d restarted
The filename, directory name, or volume label syntax is incorrect.
[W 19:10:14.708 NotebookApp] KernelRestarter: restart failed
[W 19:10:14.708 NotebookApp] Kernel 982fd2a9-2a52-41d7-b5e6-eab91cf5c05d died, removing from map.
kernel 982fd2a9-2a52-41d7-b5e6-eab91cf5c05d restarted failed!
