### ISSUE TITLE
Kernel deleted before session

### ISSUE THREAD

**Issue by gpetrini** [IRkernel/IRkernel#547]
I'm trying to use IRKernel. My older issues are related in [#546](https://github.com/IRkernel/IRkernel/issues/546),Now, I'm not using conda e I use de offical instalation instructions in cmd as administrator. Also, I checked de json file and set the properly R path. Still, my IRKernl is dying. The results are below:

```
C:\Users\Gabriel Petrini>jupyter notebook
[I 19:15:45.142 NotebookApp] JupyterLab beta preview extension loaded from c:\users\gabriel petrini\appdata\local\programs\python\python36\lib\site-packages\jupyterlab
[I 19:15:45.150 NotebookApp] JupyterLab application directory is c:\users\gabriel petrini\appdata\local\programs\python\python36\share\jupyter\lab
[I 19:15:46.829 NotebookApp] Serving notebooks from local directory: C:\Users\Gabriel Petrini
[I 19:15:46.844 NotebookApp] 0 active kernels
[I 19:15:46.845 NotebookApp] The Jupyter Notebook is running at:
[I 19:15:46.848 NotebookApp] http://localhost:8888/
[I 19:15:46.848 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 19:15:59.540 NotebookApp] Creating new notebook in
[I 19:16:00.616 NotebookApp] Kernel started: df203906-1c24-468d-bbba-d5c7833ba215
A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta.
[I 19:16:03.594 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta.
[I 19:16:06.654 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta.
[I 19:16:09.704 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta.
[W 19:16:10.656 NotebookApp] Timeout waiting for kernel_info reply from df203906-1c24-468d-bbba-d5c7833ba215
[I 19:16:12.753 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
kernel df203906-1c24-468d-bbba-d5c7833ba215 restarted
A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta.
[W 19:16:15.783 NotebookApp] KernelRestarter: restart failed
[W 19:16:15.783 NotebookApp] Kernel df203906-1c24-468d-bbba-d5c7833ba215 died, removing from map.
kernel df203906-1c24-468d-bbba-d5c7833ba215 restarted failed!
[W 19:16:15.828 NotebookApp] 410 DELETE /api/sessions/0772bf7f-9366-4ea0-9106-1afabc4d20f1 (::1): Kernel deleted before session
[W 19:16:15.829 NotebookApp] Kernel deleted before session
[W 19:16:15.831 NotebookApp] 410 DELETE /api/sessions/0772bf7f-9366-4ea0-9106-1afabc4d20f1 (::1) 6.26ms referer=http://localhost:8888/notebooks/Untitled1.ipynb?kernel_name=ir
[I 19:18:00.618 NotebookApp] Saving file at /Untitled1.ipynb
```

My json has:

```json
{
  "argv": ["C:/Program Files/R/R-3.4.3/bin/R.exe","-e", "IRkernel::main()", "--args", "{connection_file}"],
  "display_name": "R",
  "language": "R"
}
```

**Info:** "A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta." means

The syntax for the file name, directory name, or volume label is incorrect.

What can I do? 

Tks a lot
PS I'm really greatful for the help before
PSS I'm writing again to open a new issue

**Comment by flying-sheep** [comment]
weird. just a hunch: can you try replacing the `/` slashes in the JSON with `\\`?

**Comment by takluyver** [comment]
I had a similar hunch, so hopefully that means we're on the right track ;-)

**Comment by gpetrini** [comment]
Still the same error :'( 

`C:\Users\Gabriel Petrini>jupyter notebook
[I 07:56:05.513 NotebookApp] JupyterLab beta preview extension loaded from c:\users\gabriel petrini\appdata\local\programs\python\python36\lib\site-packages\jupyterlab
[I 07:56:05.513 NotebookApp] JupyterLab application directory is c:\users\gabriel petrini\appdata\local\programs\python\python36\share\jupyter\lab
[I 07:56:06.921 NotebookApp] Serving notebooks from local directory: C:\Users\Gabriel Petrini
[I 07:56:06.921 NotebookApp] 0 active kernels
[I 07:56:06.921 NotebookApp] The Jupyter Notebook is running at:
[I 07:56:06.921 NotebookApp] http://localhost:8888/
[I 07:56:06.921 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 07:56:14.824 NotebookApp] Kernel started: 72386bf5-ff9c-4fa5-a32b-2175d717d2ed
A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta.
[I 07:56:17.804 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta.
[I 07:56:20.828 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta.
[I 07:56:23.855 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta.
[W 07:56:24.856 NotebookApp] Timeout waiting for kernel_info reply from 72386bf5-ff9c-4fa5-a32b-2175d717d2ed
[I 07:56:26.886 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
kernel 72386bf5-ff9c-4fa5-a32b-2175d717d2ed restarted
A sintaxe do nome do arquivo, do nome do diretório ou do rótulo do volume está incorreta.
[W 07:56:29.916 NotebookApp] KernelRestarter: restart failed
[W 07:56:29.916 NotebookApp] Kernel 72386bf5-ff9c-4fa5-a32b-2175d717d2ed died, removing from map.
kernel 72386bf5-ff9c-4fa5-a32b-2175d717d2ed restarted failed!
[W 07:56:29.938 NotebookApp] 410 DELETE /api/sessions/912bc127-9a75-431a-957e-23a4c0296ef8 (::1): Kernel deleted before session
[W 07:56:29.939 NotebookApp] Kernel deleted before session
[W 07:56:29.943 NotebookApp] 410 DELETE /api/sessions/912bc127-9a75-431a-957e-23a4c0296ef8 (::1) 6.02ms referer=http://localhost:8888/notebooks/Pr%C3%A1tica%20R.ipynb`

My json below:

`{
  "argv": ["C:\\Program Files\\R\\R-3.4.3\\bin\\R.exe","-e", "IRkernel::main()", "--args", "{connection_file}"],
  "display_name": "R",
  "language": "R"
}`

**Comment by gpetrini** [comment]
Two dumb questions:

1. The R.exe should be on the path?
2. I've tried "C:\\Program Files\\R\\R-3.4.3\\bin\\x64\\R.exe" and run into the same error. A x-64 OS makes difference?

Tks again

**Comment by takluyver** [comment]
It shouldn't need to be on PATH, but the path in the argv does need to point to a valid R.exe that you can run. I don't know enough about R installations on Windows to know which file that is, or where that error message is coming from.

**Comment by gpetrini** [comment]
Should be the case to try with conda? There is an alternative to IRKernel for windows?

**Comment by flying-sheep** [comment]
can you try if the path is right? i.e. if executing `C:\Program Files\R\R-3.4.3\bin\x64\R.exe` in a powershell window works?

**Comment by takluyver** [comment]
There is an alternative you could try: https://github.com/JuniperKernel/JuniperKernel
