### ISSUE TITLE
`Error in IRkernel::installspec()` in docker

### ISSUE THREAD

**Issue by darribas** [IRkernel/IRkernel#550]
Hello,
I'm trying to install `IRkernel` in a docker container that a) sources a full R install from [`rocker/geospatial`](https://github.com/rocker-org/geospatial), b) then install `miniconda`, c) then installs some additional R packages and d) finally sets up  `IRkernel`. I've got a), b), c) working [here](https://github.com/darribas/gds_env/blob/master/Dockerfile) but I'm struggling to get d). I get the usual:

```r
> library(IRkernel); IRkernel::installspec();
Error in IRkernel::installspec() :
  jupyter-client has to be installed but “jupyter kernelspec --version” exited with code 127.
```

I've built a container that does a), b) and c), then dropped in to try to do it manually in several ways and have not been successful. From reading online, I know it's because R can't see conda, but it's on `$PATH`, the environment is activated, etc. I can't think of any additional thing to try (installing R through conda was an option but several of the libraries I require -e.g. `tmap`- are not available). Any help?

]d[

**Comment by takluyver** [comment]
You're doing `ln -s /opt/conda/envs/gds/bin/jupyter /usr/local/bin` - I think this should be sufficient, but maybe try linking `jupyter-kernelspec` as well. Also, double check that `/usr/local/bin` is on PATH when you're building the docker container.
