### ISSUE TITLE
R kernel in Jupyter Notebook keeps dying and restarting

### ISSUE THREAD

**Issue by yunusemregacti** [IRkernel/IRkernel#553]
Hello,
I tried to find the solution but i couldn't please,Could you help me?
when im opening the jupyter notebooks i took this errors;

```
[I 17:43:14.604 NotebookApp] The port 8888 is already in use, trying another port.
[I 17:43:14.605 NotebookApp] The port 8889 is already in use, trying another port.
[I 17:43:14.606 NotebookApp] The port 8890 is already in use, trying another port.
[W 17:43:14.630 NotebookApp] Terminals not available (error was DLL load failed: %1 is not a valid Win32 application.)
[I 17:43:15.108 NotebookApp] Serving notebooks from local directory: C:\Users\Yunus Emre Gaçti
[I 17:43:15.108 NotebookApp] 0 active kernels
[I 17:43:15.109 NotebookApp] The Jupyter Notebook is running at:
[I 17:43:15.109 NotebookApp] http://localhost:8891/?token=d9e665c7da369360ce406f74430553909996d8f7c1706547
[I 17:43:15.109 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 17:43:15.112 NotebookApp] 

Copy/paste this URL into your browser when you connect for the first time,
to login with a token:
http://localhost:8891/?token=d9e665c7da369360ce406f74430553909996d8f7c1706547
[I 17:43:15.277 NotebookApp] Accepting one-time-token-authenticated connection from ::1
```

My operating system is Windows 8.1 and jupyter notebook is 5.4.0.
Im new in the this environment. Please if you can help me i will glad. Thank you in advance.

**Comment by takluyver** [comment]
None of those messages look like an error (apart from the 'Terminals not available' line, but that shouldn't affect R at all). What do you see when you try to create an R notebook?

**Comment by yunusemregacti** [comment]
when im opening new R notebook or old R notebooks, im getting this errors;
[https://i.hizliresim.com/1J3omb.jpg](url)

**Comment by H3yfinn** [comment]
I'm also getting the dead kernel error. My notebooks work well for python but when I create a new notebook for R kernel then I get the problem like in the Picture above.

**Comment by Einsley** [comment]
Me too. Works for python, but not R.

**Comment by janxkoci** [comment]
Just pasting here the pic from the comment above, it's not an error message but a dialog.

![obrazek](https://user-images.githubusercontent.com/19331850/102713550-58c38380-42c9-11eb-8f0a-32be11b1cc1d.png)
