### ISSUE TITLE
Errors when using R Jupyter notebook

### ISSUE THREAD

**Issue by emankhalaf** [IRkernel/IRkernel#555]
I am a beginner in R and Jupyter notebook.  I have the following issue:
When running 
sampledata <- import_qiime_sample_data(metadatafile)
I got the following error
Error in file(file, "rt"): cannot open the connection
Traceback:

1. import_qiime_sample_data(metadatafile)
2. read.table(file = mapfilename, header = TRUE, sep = "\t", comment.char = "")
3. file(file, "rt")
I am not sure, what exactly needed?
Thanks

**Comment by takluyver** [comment]
It looks like `metadatafile` isn't set to the right path. Try asking on a general R mailing list if you're still having trouble - I don't think this is specific to IRkernel.

**Comment by emankhalaf** [comment]
All files are placed in the same folder, I just re-start everything and it
works.
Thanks
