### ISSUE TITLE
R kernel keeps dying

### ISSUE THREAD

**Issue by Gracefan021** [IRkernel/IRkernel#557]
I was trying to using Jupyter note book to connect R kernel, I download r-essentials followed by the steps  https://docs.anaconda.com/anaconda/user-guide/tasks/use-r-language

But, when I run 'jupyter notebook' from terminal and start an R kernel, the kernel keeps dying. 
I also tried the steps of installing the packages from R in terminal by runing the below code/link

```r
install.packages(c('repr', 'IRdisplay', 'evaluate', 'crayon', 'pbdZMQ', 'devtools', 'uuid', 'digest'))
devtools::install_github('IRkernel/IRkernel')
```

https://irkernel.github.io/installation/#binary-panel

<details>
<summary>And the terminal returns me error as</summary>

```r
An irrecoverable exception occurred. R is aborting now ...
[W 01:00:17.841 NotebookApp] Timeout waiting for kernel_info reply from 1282ef30-a1e2-41e6-b0bd-fa07b9c082a8
[I 01:00:19.818 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
kernel 1282ef30-a1e2-41e6-b0bd-fa07b9c082a8 restarted

 *** caught segfault ***
address 0x18, cause 'memory not mapped'

Traceback:
 1: dyn.load(file, DLLpath = DLLpath, ...)
 2: library.dynam(lib, package, package.lib)
 3: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
 4: asNamespace(ns)
 5: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
 6: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
 7: asNamespace(ns)
 8: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
 9: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
10: asNamespace(ns)
11: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
12: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
13: asNamespace(ns)
14: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
15: loadNamespace(name)
16: doTryCatch(return(expr), name, parentenv, handler)
17: tryCatchOne(expr, names, parentenv, handlers[[1L]])
18: tryCatchList(expr, classes, parentenv, handlers)
19: tryCatch(loadNamespace(name), error = function(e) stop(e))
20: getNamespace(ns)
21: asNamespace(ns)
22: getExportedValue(pkg, name)
23: IRkernel::main
An irrecoverable exception occurred. R is aborting now ...
[W 01:00:22.827 NotebookApp] KernelRestarter: restart failed
[W 01:00:22.827 NotebookApp] Kernel 1282ef30-a1e2-41e6-b0bd-fa07b9c082a8 died, removing from map.
kernel 1282ef30-a1e2-41e6-b0bd-fa07b9c082a8 restarted failed!
[W 01:00:22.848 NotebookApp] 410 DELETE /api/sessions/a9611fd7-0b82-4188-ba82-9de5a1479081 (::1): Kernel deleted before session
[W 01:00:22.849 NotebookApp] Kernel deleted before session
[W 01:00:22.850 NotebookApp] 410 DELETE /api/sessions/a9611fd7-0b82-4188-ba82-9de5a1479081 (::1) 4.30ms referer=http://localhost:8/notebooks/Documents/a_Python_Practice/Untitled5.ipynb?kernel_name=ir
```

</details>

**Comment by dhirschfeld** [comment]
NB: I wouldn't mix conda installed packages with other methods of installing as it's highly likely to result in exactly these types of error. If using conda (which I recommend) I'd try to use it exclusively

For someone to help further you may have to paste the output of `conda list` (entered in a terminal / command prompt)

**Comment by flying-sheep** [comment]
exactly, please either use exclusively conda pacakages or exclusively packages you installed via `install.packages`. i suggest the latter

you can reset your system to a working state by uninstalling everything, reinstalling R (without reinstalling anaconda) and then use `install.packages` for everything.

**Comment by Gracefan021** [comment]
@flying-sheep  thanks, I am quite new to jupyter notebook, how do I uninstall all R packages that without reinstall anaconda?

**Comment by takluyver** [comment]
`conda list` should show you which conda packages you have installed. I think all the R packages in conda begin with `r-`. You can uninstall those with `conda uninstall`.

**Comment by Gracefan021** [comment]
I think I have all the r-packages uninstalled, and still seeing R kernel under python3 on Jupyter notebook. Note sure if I can restart to install R-base/essentials from here.. Thanks everyone.

 conda list
# packages in environment at /anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py36h2fc01ae_0  
_r-mutex                  1.0.0               anacondar_1  
alabaster                 0.7.10           py36h174008c_0  
anaconda                  custom           py36ha4fed55_0  
anaconda-client           1.6.9                    py36_0  
anaconda-navigator        1.7.0                    py36_0  
anaconda-project          0.8.2            py36h9ee5d53_0  
appnope                   0.1.0            py36hf537a9a_0  
appscript                 1.0.1            py36h9e71e49_1  
asn1crypto                0.24.0                   py36_0  
astroid                   1.6.1                    py36_0  
astropy                   2.0.3            py36h1de35cc_0  
attrs                     17.4.0                   py36_0  
babel                     2.5.3                    py36_0  
backports                 1.0              py36ha3c1827_1  
backports.shutil_get_terminal_size 1.0.0            py36hd7a2ee4_2  
beautifulsoup4            4.6.0            py36h72d3c9f_1  
bitarray                  0.8.1            py36h1de35cc_1  
bkcharts                  0.2              py36h073222e_0  
blaze                     0.11.3           py36h02e7a37_0  
bleach                    2.1.2                    py36_0  
bokeh                     0.12.15                  py36_0  
boto                      2.48.0           py36hdbc59ac_1  
bottleneck                1.2.1            py36hbd380ad_0  
bwidget                   1.9.11                        0  
bzip2                     1.0.6                hd86a083_4  
ca-certificates           2018.03.07                    0  
cairo                     1.14.12              hab642c4_1  
cctools                   895                  h7512d6f_0  
certifi                   2018.4.16                py36_0  
cffi                      1.11.4           py36h342bebf_0  
chardet                   3.0.4            py36h96c241c_1  
clang                     4.0.1                h662ec87_0  
clang_osx-64              4.0.1               h1ce6c1d_10  
clangxx                   4.0.1                hc9b4283_0  
clangxx_osx-64            4.0.1               h22b1bf0_10  
click                     6.7              py36hec950be_0  
cloudpickle               0.5.2                    py36_1  
clyent                    1.2.2            py36hae3ad88_0  
colorama                  0.3.9            py36hd29a30c_0  
compiler-rt               4.0.1                h5487866_0  
conda                     4.5.1                    py36_0  
conda-build               3.4.1                    py36_0  
conda-env                 2.6.0                h36134e3_0  
conda-verify              2.0.0            py36he837df3_0  
contextlib2               0.5.5            py36hd66e5e7_0  
cryptography              2.1.4            py36h842514c_0  
curl                      7.58.0               ha441bb4_0  
cycler                    0.10.0           py36hfc81398_0  
cython                    0.27.3           py36h6ecb376_0  
cytoolz                   0.9.0            py36h1de35cc_0  
dask                      0.16.1                   py36_0  
dask-core                 0.16.1                   py36_0  
datashape                 0.5.4            py36hfb22df8_0  
dbus                      1.12.2               h5243cc1_1  
decorator                 4.2.1                    py36_0  
distributed               1.20.2                   py36_0  
docutils                  0.14             py36hbfde631_0  
entrypoints               0.2.3            py36hd81d71f_2  
et_xmlfile                1.0.1            py36h1315bdc_0  
expat                     2.2.5                hb8e80ba_0  
fastcache                 1.0.2            py36h1de35cc_2  
filelock                  2.0.13           py36hf9de95b_0  
flask                     0.12.2           py36h5658096_0  
flask-cors                3.0.3            py36h7387b97_0  
fontconfig                2.12.6               h9850fc5_0  
freetype                  2.8                  h12048fb_1  
fribidi                   1.0.2                h1de35cc_0  
get_terminal_size         1.0.0                h7520d66_0  
gettext                   0.19.8.1             h15daf44_3  
gevent                    1.2.2            py36ha70b9d6_0  
gfortran_osx-64           4.8.5                h22b1bf0_3  
glib                      2.53.6               h33f6a65_2  
glob2                     0.6              py36h94c9186_0  
gmp                       6.1.2                hb37e062_1  
gmpy2                     2.0.8            py36hf9c35bd_2  
graphite2                 1.3.11               h337f25e_1  
greenlet                  0.4.12           py36hf09ba7b_0  
gsl                       2.4                  h3efe00b_3  
h5py                      2.7.1            py36h39cdac5_0  
harfbuzz                  1.7.6                h08e020e_0  
hdf5                      1.10.1               ha036c08_1  
heapdict                  1.0.0                    py36_2  
html5lib                  1.0.1            py36h2f9c1c0_0  
icu                       58.2                 h4b95b61_1  
idna                      2.6              py36h8628d0a_1  
imageio                   2.2.0            py36h5e01289_0  
imagesize                 0.7.1            py36h3495948_0  
intel-openmp              2018.0.0             h8158457_8  
ipykernel                 4.8.2                    py36_0  
ipython                   6.2.1            py36h3dda519_1  
ipython_genutils          0.2.0            py36h241746c_0  
ipywidgets                7.1.1                    py36_0  
isort                     4.2.15           py36hceb2a01_0  
itsdangerous              0.24             py36h49fbb8d_1  
jbig                      2.1                  h4d881f8_0  
jdcal                     1.3              py36h1986823_0  
jedi                      0.11.1                   py36_0  
jinja2                    2.10             py36hd36f9c5_0  
jpeg                      9b                   he5867d9_2  
jsonschema                2.6.0            py36hb385e00_0  
jupyter                   1.0.0                    py36_4  
jupyter_client            5.2.2                    py36_0  
jupyter_console           5.2.0            py36hccf5b1c_1  
jupyter_core              4.4.0            py36h79cf704_0  
jupyterlab                0.31.5                   py36_0  
jupyterlab_launcher       0.10.2                   py36_0  
krb5                      1.14.2               h9a779f2_6  
lazy-object-proxy         1.3.1            py36h2fbbe47_0  
ld64                      274.2                h7c2db76_0  
libcurl                   7.58.0               hf30b1f0_0  
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1                  hb4e282d_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
libpng                    1.6.34               he12f830_0  
libsodium                 1.0.15               hd9e47c5_0  
libssh2                   1.8.0                h322a93b_4  
libtiff                   4.0.9                h0dac147_0  
libxml2                   2.9.7                hab757c2_0  
libxslt                   1.1.32               hb819dd2_0  
llvm                      4.0.1                hc748206_0  
llvm-lto-tapi             4.0.1                h6701bc3_0  
llvm-openmp               4.0.1                hda82c8b_0  
llvmlite                  0.21.0           py36hff739e7_0  
locket                    0.2.0            py36hca03003_1  
lxml                      4.1.1            py36hef8c89e_1  
lzo                       2.10                 h362108e_2  
markupsafe                1.0              py36h3a1e703_1  
matplotlib                2.1.2            py36h6d6146d_0  
mccabe                    0.6.1            py36hdaeb55d_0  
mistune                   0.8.3                    py36_0  
mkl                       2018.0.1             hfbd8650_4  
mkl-service               1.1.2            py36h7ea6df4_4  
mpc                       1.0.3                h7a72875_5  
mpfr                      3.1.5                h711e7fd_2  
mpmath                    1.0.0            py36hf1b8295_2  
msgpack-python            0.5.1            py36h04f5b5a_0  
multipledispatch          0.4.9            py36hc5f92b5_0  
navigator-updater         0.1.0            py36h7aee5fb_0  
nbconvert                 5.3.1            py36h810822e_0  
nbformat                  4.4.0            py36h827af21_0  
ncurses                   6.0                  hd04f020_2  
networkx                  2.1                      py36_0  
nltk                      3.2.5            py36h1190bce_0  
nose                      1.3.7            py36h73fae2b_2  
notebook                  5.4.1                    py36_0  
numba                     0.36.2          np114py36hc2f221f_0  
numexpr                   2.6.4            py36habcfcfe_0  
numpy                     1.14.0           py36h8a80b8c_1  
numpydoc                  0.7.0            py36he54d08e_0  
odo                       0.5.1            py36hc1af34a_0  
olefile                   0.45.1                   py36_0  
openpyxl                  2.4.10                   py36_0  
openssl                   1.0.2o               h26aff7b_0  
packaging                 16.8             py36he5e8135_0  
pandas                    0.22.0           py36h0a44026_0  
pandoc                    1.19.2.1             ha5e8f32_1  
pandocfilters             1.4.2            py36h3b0b094_1  
pango                     1.42.0               h0f8274a_0  
parso                     0.1.1            py36hc90e01c_0  
partd                     0.3.8            py36hf5c4cb8_0  
path.py                   10.5             py36h7bcb313_0  
pathlib2                  2.3.0            py36h877a6d8_0  
patsy                     0.5.0                    py36_0  
pcre                      8.41                 hfb6ab37_1  
pep8                      1.7.1                    py36_0  
pexpect                   4.3.1                    py36_0  
pickleshare               0.7.4            py36hf512f8e_0  
pillow                    5.0.0            py36hfcce615_0  
pip                       9.0.1            py36h1555ced_4  
pixman                    0.34.0               hca0a616_3  
pkginfo                   1.4.1            py36h25bf955_0  
pluggy                    0.6.0            py36hb1d0581_0  
ply                       3.10             py36h10e714e_0  
prompt_toolkit            1.0.15           py36haeda067_0  
psutil                    5.4.3            py36h1de35cc_0  
ptyprocess                0.5.2            py36he6521c3_0  
py                        1.5.2            py36ha69170d_0  
pycodestyle               2.3.1            py36h83e8646_0  
pycosat                   0.6.3            py36hee92d8f_0  
pycparser                 2.18             py36h724b2fc_1  
pycrypto                  2.6.1            py36h1de35cc_7  
pycurl                    7.43.0.1         py36hdbc3d79_0  
pyflakes                  1.6.0            py36hea45e83_0  
pygments                  2.2.0            py36h240cd3f_0  
pylint                    1.8.2                    py36_0  
pyodbc                    4.0.22           py36h0a44026_0  
pyopenssl                 17.5.0           py36h51e4350_0  
pyparsing                 2.2.0            py36hb281f35_0  
pyqt                      5.6.0            py36he5c6137_6  
pysocks                   1.6.7            py36hfa33cec_1  
pytables                  3.4.2            py36hfbd7ab0_2  
pytest                    3.3.2                    py36_0  
python                    3.6.4                hc167b69_1  
python-dateutil           2.6.1            py36h86d2abb_1  
python.app                2                py36h54569d5_7  
pytz                      2017.3           py36hf0bf824_0  
pywavelets                0.5.2            py36h2710a04_0  
pyyaml                    3.12             py36h2ba1e63_1  
pyzmq                     16.0.3           py36he48b5ad_0  
qt                        5.6.2               h9975529_14  
qtawesome                 0.4.4            py36h468c6fb_0  
qtconsole                 4.3.1            py36hd96c0ff_0  
qtpy                      1.3.1            py36h16bb863_0  
readline                  7.0                  hc1231fa_4  
requests                  2.18.4           py36h4516966_1  
rope                      0.10.7           py36h68959ac_0  
ruamel_yaml               0.15.35          py36h1de35cc_1  
scikit-image              0.13.1           py36h1de35cc_1  
scikit-learn              0.19.1           py36hffbff8c_0  
scipy                     1.0.0            py36h1de22e9_0  
seaborn                   0.8.1            py36h595ecd9_0  
send2trash                1.4.2                    py36_0  
setuptools                38.4.0                   py36_0  
simplegeneric             0.8.1                    py36_2  
singledispatch            3.4.0.3          py36hf20db9d_0  
sip                       4.18.1           py36h2824476_2  
six                       1.11.0           py36h0e22d5e_1  
snowballstemmer           1.2.1            py36h6c7b616_0  
sortedcollections         0.5.3            py36he9c3ed6_0  
sortedcontainers          1.5.9                    py36_0  
sphinx                    1.6.6                    py36_0  
sphinxcontrib             1.0              py36h9364dc8_1  
sphinxcontrib-websupport  1.0.1            py36h92f4a7a_1  
spyder                    3.2.6                    py36_0  
sqlalchemy                1.2.1            py36h1de35cc_0  
sqlite                    3.22.0               h3efe00b_0  
statsmodels               0.8.0            py36h9c68fc9_0  
sympy                     1.1.1            py36h7f3cf04_0  
tblib                     1.3.2            py36hda67792_0  
terminado                 0.8.1                    py36_1  
testpath                  0.3.1            py36h625a49b_0  
tk                        8.6.7                h35a86e2_3  
tktable                   2.10                 h1de35cc_0  
toolz                     0.9.0                    py36_0  
tornado                   4.5.3                    py36_0  
traitlets                 4.3.2            py36h65bd3ce_0  
typing                    3.6.2            py36haa2d9ef_0  
unicodecsv                0.14.1           py36he531d66_0  
unixodbc                  2.3.4                h4cb4dde_1  
urllib3                   1.22             py36h68b9469_0  
wcwidth                   0.1.7            py36h8c6ec74_0  
webencodings              0.5.1            py36h3b9701d_1  
werkzeug                  0.14.1                   py36_0  
wheel                     0.30.0           py36h5eb2c71_1  
widgetsnbextension        3.1.0                    py36_0  
wrapt                     1.10.11          py36hc29e774_0  
xlrd                      1.1.0            py36h336f4a2_1  
xlsxwriter                1.0.2            py36h3736301_0  
xlwings                   0.11.5                   py36_0  
xlwt                      1.2.0            py36h5ad1178_0  
xz                        5.2.3                h0278029_2  
yaml                      0.1.7                hc338f04_2  
zeromq                    4.2.2                ha360ad0_2  
zict                      0.1.3            py36h71da714_0  
zlib                      1.2.11               hf3cbc9b_2

**Comment by Gracefan021** [comment]
@dhirschfeld  deleted, I guess now I will need to follow my first link to reinstall. Although, I am still confusing about
**conda create -n mro_env r-essentials**
Activate the environment:
**conda activate mro_env**
with 
conda install r-essentials

**Comment by dhirschfeld** [comment]
`conda install r-essentials` will install `r-essentials` into the currently activated environment whereas `conda create -n mro_env r-essentials` will create a new environment called `mro_env` and install `r-essentials` into that environment. To then use the environment that you just created you have to first activate it.
