### ISSUE TITLE
Error in open HD5F file 

### ISSUE THREAD

**Issue by OhGarrys** [IRkernel/IRkernel#558]
when i trying to load the dataset it return this error

# Loading the data (cat/non-cat)
train_set_x_orig, train_set_y, test_set_x_orig, test_set_y, classes = load_dataset()
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-4-edd22496ab38> in <module>()
      1 # Loading the data (cat/non-cat)
----> 2 train_set_x_orig, train_set_y, test_set_x_orig, test_set_y, classes = load_dataset()

~\lr_utils.py in load_dataset()
      4 
      5 def load_dataset():
----> 6     train_dataset = h5py.File('train_catvnoncat.h5', "r")
      7     train_set_x_orig = np.array(train_dataset["train_set_x"][:]) # your train set features
      8     train_set_y_orig = np.array(train_dataset["train_set_y"][:]) # your train set labels

d:\asoftware\python-3.5.4\benti\lib\site-packages\h5py\_hl\files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, **kwds)
    267             with phil:
    268                 fapl = make_fapl(driver, libver, **kwds)
--> 269                 fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
    270 
    271                 if swmr_support:

d:\asoftware\python-3.5.4\benti\lib\site-packages\h5py\_hl\files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
     97         if swmr and swmr_support:
     98             flags |= h5f.ACC_SWMR_READ
---> 99         fid = h5f.open(name, flags, fapl=fapl)
    100     elif mode == 'r+':
    101         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\_objects.pyx in h5py._objects.with_phil.wrapper()

h5py\h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (unable to open file: name = 'datasets/train_catvnoncat.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by OhGarrys** [comment]
this is work in jupyter notebook , i try to open the HDF5 file 

_Error! C:\Users\95853\test_catvnoncat.h5 is not UTF-8 encoded
Saving disabled.
See Console for more details._

I don't know if this error relevant to my first error ,if it is ,what should i do ,thank you

**Comment by OhGarrys** [comment]
@honghu-zero

**Comment by takluyver** [comment]
This is the issue tracker for the R kernel. From the error message in your first post, you're using Python, not R. Maybe you've got confused between that `lr_utils` module and `IRkernel`? IRkernel is spelled with a capital i.

The first error looks like you've got the path to the data wrong: it says "No such file or directory".

The second error indicates that you've tried to open the HDF5 file in Jupyter's text editor. That won't work, because HDF5 is not a text format.

**Comment by OhGarrys** [comment]
using github the first time,I am so sorry post it in a wrong place.
Following your advice,I try a new python 3.I can open the HDF5 successfully ,but it still didn't work in 
train_set_x_orig, train_set_y, test_set_x_orig, test_set_y, classes = load_dataset()



CODE:
import h5py
import numpy as np
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"]="3"
# 打开文件
train_dataset= h5py.File('train_catvnoncat.h5', 'r')

train_dataset.keys()
# Direct calling keys will get the following output
# Which can not determin what's inside
# KeysView(<HDF5 file "train_catvnoncat.h5" (mode r)>)
# While we could loop over it
for key in train_dataset.keys():
    print(key)

child_keys = [k for k in train_dataset.keys()]
-------------------------------------------------------------
list_classes
train_set_x
train_set_y
-----------------------------------------
all_child_keys = []
train_dataset.visit(all_child_keys.append)
train_dataset['train_set_x'][:]
--------------------------------------------------
array([[[[ 17,  31,  56],
         [ 22,  33,  59],
         [ 25,  35,  62],
         ...,
         [  1,  28,  57],
         [  1,  26,  56],
         [  1,  22,  51]],

        [[ 25,  36,  62],
         [ 28,  38,  64],
         [ 30,  40,  67],
         ...,
         [  1,  27,  56],
         [  1,  25,  55],
         [  2,  21,  51]],

        [[ 32,  40,  67],
         [ 34,  42,  69],
         [ 35,  42,  70],
         ...,
         [  1,  25,  55],
         [  0,  24,  54],
         [  1,  21,  51]],

        ...,

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]],

        [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [[  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0],
         ...,
         [  0,   0,   0],
         [  0,   0,   0],
         [  0,   0,   0]]]], dtype=uint8)

**Comment by takluyver** [comment]
Sorry, I don't think I can help you with that.

**Comment by OhGarrys** [comment]
That is  ok, I am also greatful to you.
