### ISSUE TITLE
using showtext with jupyter

### ISSUE THREAD

**Issue by slowkow** [IRkernel/IRkernel#559]
showtext is a great library by Yixuan Qiu for drawing font glyphs as shapes so
the viewer does not need to have the fonts installed:

- https://github.com/yixuan/showtext
- https://CRAN.R-project.org/package=showtext

## Summary

The package works on Linux with Jupyter, but only if you write the plot to a
PNG file `"filename.png"` and then load it with
`IRdisplay::display_png("filename.png")`.

Is there a way to get automatically-printed plots to work with showtext?

Here's a notebook with an example:
https://gist.github.com/slowkow/771238703396bd006f3aeb0943147c85

I first posted about this issue here:

https://github.com/yixuan/showtext/issues/19

But now I have a hunch that maybe one path forward might be use the code in the
IRkernel package... could I ask if you have any advice on this?

**Comment by flying-sheep** [comment]
can you try putting everything in a code block? like this:

```r
plot(1, type = "n")
{
    showtext_begin()
    text(1, 1.2, "Let me tell you a story", cex = 3, family = "newrocker")
    text(1, 0.8, "Long long ago...", cex = 3, family = "cutetumblr")
    showtext_end()
}
```

**Comment by flying-sheep** [comment]
hmm, then i have no idea! showtext seems to internally poke around in R and replace functions.

@yixuan are you willing to help me diagnose this?

**Comment by yixuan** [comment]
Indeed there are some "ugly" code in showtext that changes the internals. I'll try to take a look.

**Comment by slowkow** [comment]
I'm able to circumvent the default behavior of IRkernel with this function:

```r
show_plot <- function(p, width = NULL, height = NULL) {
  if (is.null(width)) {
    width <- getOption("repr.plot.width", 3)
  }
  if (is.null(height)) {
    height <- getOption("repr.plot.height", 3)
  }
  filename <- paste(tempfile(pattern = "jupyter-"), ".png", sep = "")
  png(filename, width = width, height = height, units = "in", res = 120)
  print(p)
  dev.off()
  IRdisplay::display_png(file = filename)
}
```

Here's an example of what I get when I try to show a ggplot2 figure:

```r
# This is the default display by IRkernel
options(repr.plot.width = 5, repr.plot.height = 2)

p <- ggplot() +
geom_text(
  mapping = aes(x = 1, y = 1, label = "This should be italic"),
  fontface = "italic",
  family = "sans",
  size = 12
) +
theme_void()

p
```

![image](https://user-images.githubusercontent.com/209714/40949106-667a50ce-683a-11e8-983c-0be782fbf22c.png)

It seems that the `show_plot()` function works:

```r
show_plot(p)
```

![image](https://user-images.githubusercontent.com/209714/40949114-712f11f8-683a-11e8-81d0-6ab4515a911e.png)

**Comment by flying-sheep** [comment]
I think it’s hard to do something in IRkernel here, maybe showtext needs to accomodate it.
