### ISSUE TITLE
Troubleshooting Kernel Crashes

### ISSUE THREAD

**Issue by WalterDalton** [IRkernel/IRkernel#56]
Is there a way to produce more output from kernel crashes. Executing code, and then Jupyter says the kernel has crashed with no other output.  If we could understand some troubleshooting steps we could report back to the project on the issue. 

Thanks!

**Comment by takluyver** [comment]
If you launched the notebook from a terminal, check there for error information when a kernel crashes.

**Comment by WalterDalton** [comment]
I am launching it from JupyterHub, I'll have to run it by itself to
determine what's happening. Thanks for the tip

**Comment by WalterDalton** [comment]
This is what I got:  Not sure what it means. I am not an R expert, just
trying to get some stuff setup for some experts: )


(process:19208): GLib-GIO-ERROR **: Settings schema
'org.gnome.system.proxy' is not installed


[I 07:52:27.660 NotebookApp] KernelRestarter: restarting kernel (1/5)

**Comment by takluyver** [comment]
I searched for that error message and found a couple of mentions of RWeka, e.g. [this bug report](https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=16193). But it sounds like it might be coming from Java.

Maybe R, or some R library, isn't expecting to run on a headless server, so it's trying to look up desktop settings.

**Comment by flying-sheep** [comment]
please reopen if the error still exists
