### ISSUE TITLE
support for highlighting pipe operators

### ISSUE THREAD

**Issue by lwshang** [IRkernel/IRkernel#560]
I'm using pipe operators from `magrittr`. Currently, when I using jupyter notebook, the operators like `%>%` are shown as plain text without highlighting. The new jupyterlab shows all symbol which surrounded by `%`s (`%>%` and even `%123%`) with purple color just as other built-in operators of R. I guess that is a bug or feature of jupyterlab. 

All in all, I request a feature of IRkernel that those pipe operators can be highlighted.

* in jupyter notebook
![screenshot from 2018-05-08 11 05 29](https://user-images.githubusercontent.com/13881324/39765446-df58f07c-52af-11e8-9379-50249abf9498.png)

* in jupyterlab
![screenshot from 2018-05-08 11 05 53](https://user-images.githubusercontent.com/13881324/39765453-e28558bc-52af-11e8-9175-415fcc61d492.png)

**Comment by flying-sheep** [comment]
hi!

IRkernel is just the kernel, the whole UI part is https://github.com/jupyter/notebook. jupyter notebook uses CodeMirror as code editor.

i personally fixed your problem long ago in codemirror/CodeMirror#4298

so either you have an ancient notebook version or somehow your codemirror theme is different.

**Comment by philippschw** [comment]
This issue should be opened, because the problem is still persistent in current versions of Jupyter notebook.

jupyter_client            6.1.2                      py_0  
jupyter_core              4.6.3                    py37_0
notebook                  6.0.3                    py37_0

**Comment by flying-sheep** [comment]
As said, it’s not my bug. It’s a jupyterlab bug or a codemirror bug. Please ask in one of those projects.
