### ISSUE TITLE
Does anyone know how to install the R Kernel without using the conda command?

### ISSUE THREAD

**Issue by OmarKhanGithub** [IRkernel/IRkernel#561]
I can't use conda, I installed jupyter notebook separately so is it possible to get the R kernel  without conda?

**Comment by flying-sheep** [comment]
the readme tells you everything you need to know. it actually advises you to *not* use conda.

https://github.com/IRkernel/IRkernel#readme

**Comment by flying-sheep** [comment]
feel free to ask questions if you’re stuck :smile:

**Comment by OmarKhanGithub** [comment]
Oh sorry, I forgot to include the fact that this is on a Windows OS, so install.package doesn't work either.
I wanted to know this approach for windows specifically if that's doable.
