### ISSUE TITLE
[Verification of Support] IRKernel for IBM Power8/9 systems

### ISSUE THREAD

**Issue by charlieeeeeee** [IRkernel/IRkernel#562]
Hi, 

I was searching through the web and I couldn't find any IRKernel packages for PPC64LE. Does IRKernel support POWER architecture?

Thanks,
Charlie

**Comment by charlieeeeeee** [comment]
Hi @takluyver  Thanks for the quick reply. I was looking for something that can be installed by conda, 

for example 
`conda install --yes --quiet -c r r-essentials r-irkernel
Solving environment: ...working... failed

PackagesNotFoundError: The following packages are not available from current channels:

- r-essentials
- r-irkernel

Current channels:

- https://conda.anaconda.org/r/linux-ppc64le
- https://conda.anaconda.org/r/noarch
- https://repo.continuum.io/pkgs/main/linux-ppc64le
- https://repo.continuum.io/pkgs/main/noarch
- https://repo.continuum.io/pkgs/free/linux-ppc64le
- https://repo.continuum.io/pkgs/free/noarch
- https://repo.continuum.io/pkgs/r/linux-ppc64le
- https://repo.continuum.io/pkgs/r/noarch
- https://repo.continuum.io/pkgs/pro/linux-ppc64le
- https://repo.continuum.io/pkgs/pro/noarch
`

**Comment by charlieeeeeee** [comment]
@takluyver Thank you. I will check with Continuum.

**Comment by charlieeeeeee** [comment]
@takluyver Hi Thomas, thank you for the help. The problem is resolved. We have to install the R packages using internal repo.

Thanks,
Charlie

**Comment by sebacea** [comment]
@charlieeeeeee which internal repo did you use?

**Comment by sebacea** [comment]
Hi @charlieeeeeee, which internal repo did you use? Thanks
