### ISSUE TITLE
installspec: Should jupyter kernelspec be replaced by jupyter-kernelspec for Windows?

### ISSUE THREAD

**Issue by byouness** [IRkernel/IRkernel#563]
In windows 10, the command `IRkernel::installspec()` fails with the following error:
```
Error in IRkernel::installspec() : 
jupyter-client has to be installed but “jupyter kernelspec --version” exited with code 1
```

I have had a look at the code:

https://github.com/IRkernel/IRkernel/blob/e1396db82365a548aa99ee8014f56fad2720bf00/R/installspec.r#L17-L19

Indeed, on my machine: `system2('jupyter', c('kernelspec', '--version'), FALSE, FALSE)` returns `1`, while `system2('jupyter-kernelspec', '--version', FALSE, FALSE)` returns `0`

Could you fix this? Is there any way to work around this meanwhile?

Here is my OS version
```
>ver
Microsoft Windows [Version 10.0.16299.431]
```
And my session info:
```
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252
[4] LC_NUMERIC=C                   LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16         digest_0.6.15        crayon_1.3.4         IRdisplay_0.5.0      repr_0.15.0         
 [6] jsonlite_1.5         magrittr_1.5         evaluate_0.10.1      stringi_1.1.7        uuid_0.1-2          
[11] rstudioapi_0.7       IRkernel_0.8.12.9000 tools_3.5.0          stringr_1.3.1        yaml_2.1.19         
[16] compiler_3.5.0       base64enc_0.1-3      pbdZMQ_0.3-3         htmltools_0.3.6     
```

**Comment by flying-sheep** [comment]
if `system2('jupyter', c('kernelspec', '--version'), FALSE, FALSE)` returns one, that means that you cannot execute `jupyter kernelspec --version` on your machine.

You have to add the folder containing `jupyter.exe` and `jupyter-kernelspec.exe` to your `%PATH%`. that folder could be e.g. `C:\Program files\Python36\Scripts`.

1. My Computer → Properties → Advanced → Environment Variables → Path
2. enter the new path:
![](http://zdnet4.cbsistatic.com/hub/i/2016/06/02/d3123d7a-c428-457c-bbc3-b56701c5c990/edit-system-path.jpg)

**Comment by flying-sheep** [comment]
well, the `jupyter` command just works by delegating to `jupyter-*` commands.

maybe you don’t have the package installed that provides `jupyter` itself, which is called `jupyter_core`:

https://github.com/jupyter/jupyter_core/blob/f1e18b8a52cd526c0cd1402b6041778dd60f20dc/jupyter_core/command.py#L184-L188

i closed the issue because it has nothing to do with IRkernel, but i’ll respond and help people in closed issues as well :wink:

**Comment by byouness** [comment]
You are right, the issue turns out to have nothing to do with IRKernel.
That's why I opened a question on [stackoverflow](https://stackoverflow.com/q/50484397/2699660).
Thanks again!

**Comment by flying-sheep** [comment]
i just modified my answer, maybe the edit helps you!

**Comment by byouness** [comment]
I think I narrowed the problem.

When I call which `which jupyter-kernelspec`  in a command line I get this:
`/cygdrive/d/Anaconda3/Scripts/jupyter-kernelspec`

However, in this line:
https://github.com/jupyter/jupyter_core/blob/f1e18b8a52cd526c0cd1402b6041778dd60f20dc/jupyter_core/command.py#L102

`which('jupyter-kernelspec')`  returns None



However the

**Comment by flying-sheep** [comment]
exactly that’s what I assumed. great that it worked out!

**Comment by byouness** [comment]
Just for future reference or if anybody stumbles on this issue. The issue is the missing `.exe` at the end of `kernelspec`. So, checking if it's there and adding it otherwise fixes it, e.g. by adding
```python
if cmd[-4:] != '.exe':
    cmd = cmd + '.exe'
``` 
right before this line:
https://github.com/jupyter/jupyter_core/blob/f1e18b8a52cd526c0cd1402b6041778dd60f20dc/jupyter_core/command.py#L102

Thanks.

**Comment by flying-sheep** [comment]
Shouldn’t be necessary. on windows the PATHEXT variable controls where you can leave out the file extension…

**Comment by byouness** [comment]
I know, but although I have both `.EXE` and `.exe` in `PATHEXT`, it doesn't work unless I add the extension manually as explained above.

**Comment by flying-sheep** [comment]
The [docs for shutil.which say](https://docs.python.org/3/library/shutil.html):

> Additionally, when finding the cmd in the path, the PATHEXT environment variable is checked. For example, if you call shutil.which("python"), which() will search PATHEXT to know that it should look for python.exe within the path directories.

I have absolutely no idea how it’s possible that this is happening on your system.
