### ISSUE TITLE
Source R code written in Jupyter Notebook R Kernel

### ISSUE THREAD

**Issue by wushengzhong** [IRkernel/IRkernel#565]
I understand that **%run** magic can run the ipython notebok. And **%load** can import the python script.

Is there a way I can use one Jupyter Notebook to include the R code written in another Jupyter Notebook(IRKernel enabled)? 

In R, I usually keep the setup and functions in **setup.R** and in another R scrtip **main.R** use **source( )** fucntion.

**Comment by flying-sheep** [comment]
yeah, that’s the way i’m doing it as well. @takluyver said that they went away from magics a bit since often functions can do the same.

however clearly, running the code of a notebook seems like a complex task.

**Comment by takluyver** [comment]
You can still use a `.R` script and load it with the `source()` function. It probably wouldn't be hard to have a `sourceNotebook()` function that would run the contents of another notebook inside the same namespace. But I don't think it exists yet.

**Comment by wushengzhong** [comment]
Thanks for your clarification! @takluyver

**Comment by ppramang** [comment]
Hi everybody,

at the moment there is hack which in my opinion a quick and dirty hack to solve this issue. First, you will have to convert your notebook as R Script (so from  .pynb to .R) with the below command:

system("/data/anaconda/envs/py35/bin/jupyter nbconvert --to script <path of the notebook>", intern=TRUE)

and then use the normal source() function combined with the here() function (from the "here" package):

- if you have a subdirectory:
source(here::here('subdirectory, 'your.R.script.File'))

-if you dont use subdirectory,
source(here::here('your.R.script.File'))

I hope this helps.

**Comment by ppramang** [comment]
Hi everybody,

at the moment there is hack which in my opinion a quick and dirty hack to solve this issue. First, you will have to convert your notebook as R Script (so from .pynb to .R) with the below command:

system("/data/anaconda/envs/py35/bin/jupyter nbconvert --to script  'your jupyter nobook path', intern=TRUE)

and then use the normal source() function combined with the here() function (from the "here" package):
•if you have a subdirectory:
 source(here::here('subdirectory, 'your.R.script.File'))

-if you dont use subdirectory,
 source(here::here('your.R.script.File'))

I hope this helps.

**Comment by flying-sheep** [comment]
Since doing this is not an intended feature, I’d call it the intended way to do it, not a hack.

```r
f <- 'this notebook.ipynb'
eval(parse(text = system2('jupyter', c('nbconvert', f, '--to=script', '--stdout', stdout = TRUE)))
```

**Comment by Ak784** [comment]
Hello,

Can you let me know how can this be done?

When I type the above command, I get the below error

```
Error in parse(text = x, srcfile = src): <text>:3:0: unexpected end of input
1: f <- 'Settings.ipynb'
2: eval(parse(text = system2('jupyter', c('nbconvert', f, '--to=script', '--stdout', stdout = TRUE)))
  ^
Traceback:
```

**Comment by Ak784** [comment]
Hi @flying-sheep ,

When I try the above for my file, I get `0` as output. May I know what does that mean?

```
f <- 'Settings.ipynb'
eval(parse(text = system2('jupyter', c('nbconvert', f, '--to=script', '--stdout', stdout = TRUE))))
```
And later when I issue

source('Settings.R'), I get the below error. Can you please help?
```

Error in source("Settings.R"): Settings.R:2:11: unexpected '['
1: {
2:  "cells": [
             ^
Traceback:

1. source("Settings.R")

```

**Comment by flying-sheep** [comment]
I set a parenthesis wrong and updated the code above. Try it again.

**Comment by Ak784** [comment]
Hi @flying-sheep ,

May I know what happens after I execute the above command? Because I don't see an R file generated when I execute the above command?

Meaning I did the below

`f <- 'Settings.ipynb'
eval(parse(text = system2('jupyter', c('nbconvert', f, '--to=script', '--stdout'), stdout = TRUE)))`

Now, I would like to source('Settings.R') file into my other notebook which is ('main_data.ipynb')

can help me with this?

**Comment by flying-sheep** [comment]
My code doesn’t create an R file. The `--stdout` argument is for avoiding temporary files. There is no `Settings.R`, and you can just use the same code in another notebook.

Please stop asking me and start trying to understand what you’re doing. You can do `jupyter nbconvert --help` in a console to get help on how to use it, and `?system2` to understan what it does.
