### ISSUE TITLE
Unable to print output while code is still running

### ISSUE THREAD

**Issue by apoorva-js** [IRkernel/IRkernel#566]
I wrote a C++ tensorflow code which is working just as expected (using Cmake & make). But when executing the same code on QT Creator (using qmake), the code is not printing the output while it's still running. So we see no output till the execution is completed. Once its done executing, it then prints all the output at once.
I came across a [similar issue](https://github.com/IRkernel/IRkernel/issues/3) while looking for a solution. But it is for python. I appreciate any help.
I tried using std::flush, its printing the first 2 outputs but then its the same again for the rest. I added `cout << flush;` before every `cout` statement in the code.

**Comment by takluyver** [comment]
It's not clear how this relates to IRkernel. This project is a Jupyter kernel for the R programming language.
