### ISSUE TITLE
Question: Shift-Tab Functionality in IRKernel

### ISSUE THREAD

**Issue by kmishra9** [IRkernel/IRkernel#568]
Hey there,

I was wondering if there was any way to display documentation in the way that Python3 does so with Jupyter Notebooks using the Shift-Tab command to quick-look, then a second Shift-Tab to expand documentation from the bottom up?

I’ve looked for this before and its the single biggest thing that keeps me using RStudio + RNoteboooks rather than Jupyter Notebooks (which I would much prefer!)

**Comment by takluyver** [comment]
Shift-tab sends an `inspect_request`, and there is code to handle that, though I don't know if it works:

https://github.com/IRkernel/IRkernel/blob/49b2eb29f91519242f00fa9229740c2810ba8e87/R/kernel.r#L267

**Comment by flying-sheep** [comment]
OK, continuing discussion in #299
