### ISSUE TITLE
devtools::install_github('IRkernel/IRkernel') gives namespace error

### ISSUE THREAD

**Issue by nith1989** [IRkernel/IRkernel#572]
Hi,

I tried installing the IRkernel based on the instructions provided, I get the following error when I run the devtools command:

```
In R CMD INSTALL
Error: package or namespace load failed for 'RevoUtilsMath':
 .onLoad failed in loadNamespace() for 'RevoUtilsMath', details:
  call: NULL
  error: Remove Microsoft R using Add/Remove Programs, then re-install.
Be sure to select MKL as an install option.
Execution halted
Installation failed: Command failed (1)
Warning message:
GitHub repo contains submodules, may not function as expected!
```

Please help!

**Comment by flying-sheep** [comment]
Well, just read it, it tells you what to do!

> error: Remove Microsoft R using Add/Remove Programs, then re-install.

**Comment by nith1989** [comment]
Yes, the thing is, I did read that already and checked my control panel for Microsoft R, found nothing even similar to that!

**Comment by G-Slient** [comment]
I am facing the same error and i tried uninstalling and installing Microsoft R open 3.5.0.0 but it is not solved .can anyone help me with this ?
