### ISSUE TITLE
Control number of forks/child processes?

### ISSUE THREAD

**Issue by mih** [IRkernel/IRkernel#575]
We are using IRKernel in a JupyterHub deployment were around 70 people have (one or more, typically around 2-4) notebooks open concurrently. Each running notebook has an R session attached to it, which in turn has 25 (forks?) with child processes associated with it, so 26 R processes per notebook in total. So in a typical scenario we have about 7-9k concurrent processes running.

I would like to understand what triggers/influences this number. The machine has 100GB RAM and 24 CPU cores, and even with that many people is largely idle, but the number of processes seems to be a bit much from time to time. Is there any way to control/limit the number of R processes per notebook?

thx!

**Comment by takluyver** [comment]
As far as I know, we don't do anything to start up additional R processes besides the one which runs the kernel. It's probably up to whatever packages you're using inside the kernel. From the numbers you give, I would guess that something is starting one process per CPU core to do parallel processing.

Are these definitely independent processes, and not threads? Some tools show individual threads as if they were separate processes, but a thread is actually much more lightweight.

**Comment by mih** [comment]
@takluyver Thanks for the question re threads vs procs! It was indeed this kind of confusion. There is one R process per notebook, and 25 threads. So indeed much more lightweight then it seemed. Thx for the feedback.

**Comment by takluyver** [comment]
Besides the main thread, IRkernel probably has one extra thread created by zmq, which runs a thread to handle sending and receiving data. So that leaves 24 more created by something else.
