### ISSUE TITLE
Execution count not incrementing with Emacs IPython Notebook client

### ISSUE THREAD

**Issue by millejoh** [IRkernel/IRkernel#576]
I'm 100% sure I am doing something wrong in EIN, as the execution count increments correctly in the jupyter notebook client, but I figure this place is as good as any to get some expert advice.

As far as I can tell my `execute_request` is formatted correctly, but the `execute_count in the corresponding `execute_reply` never increments. Everything works fine with the IPython kernel, in case anyone was wondering.

Here is an example of what EIN is sending on the websocket connection:

```javascript
{
  "header": {
    "msg_id": "599a168e-6adc-49f6-abcd-11b8a3814dbd",
    "username": "username",
    "session": "9dabd5f8-ab01-408e-b049-cb170b7264f8",
    "version": "5.0",
    "date": "2018-08-03T15:40:31",
    "msg_type": "execute_request"
  },
  "metadata": null,
  "content": {
    "code": "2+2",
    "silent": false,
    "show-history": true,
    "user_expressions": null,
    "allow_stdin": true,
    "stop-on-error": false
  },
  "parent_header": null,
  "channel": "shell"
}
``` 

And this is what the corresponding `execute_reply` looks like:

```javascript
{
  "header": {
    "msg_id": "76ab034c-975d-11e8-a70b-0b670e3127b9",
    "username": "username",
    "session": "9dabd5f8-ab01-408e-b049-cb170b7264f8",
    "msg_type": "execute_reply",
    "version": "5.0",
    "date": "2018-08-03T20:40:31.352182Z"
  },
  "msg_id": "76ab034c-975d-11e8-a70b-0b670e3127b9",
  "msg_type": "execute_reply",
  "parent_header": {
    "msg_id": "599a168e-6adc-49f6-abcd-11b8a3814dbd",
    "username": "username",
    "session": "9dabd5f8-ab01-408e-b049-cb170b7264f8",
    "version": "5.0",
    "date": "2018-08-03T15:40:31-05:00",
    "msg_type": "execute_request"
  },
  "metadata": null,
  "content": {
    "status": "ok",
    "execution_count": 1,
    "payload": [],
    "user_expressions": null
  },
  "buffers": [],
  "channel": "shell"
}
```

If I execute a code cell a second time the execution_count will still be 1 in the next reply. Any ideas what I am doing wrong?

**Comment by takluyver** [comment]
I think `"show-history": true,` is the problem - the field name is `"store_history"`.

http://jupyter-client.readthedocs.io/en/latest/messaging.html#execute

**Comment by millejoh** [comment]
That was it, silly me. Thanks!
