### ISSUE TITLE
AequilibraE repository problem

### ISSUE THREAD

**Issue by RobyIS** [IRkernel/IRkernel#578]
In QGis vers. 2.18  the function "AequilibraE-->Path and assignment-->shortest path or impedance matrix"
creates the following error:"Binary Error: Please download it from the repository using the downloader from the menu"
Repository is not available
What can I do?

**Comment by RobyIS** [comment]
after uninstalling and renstalled the Aequilibrae plug-in and restarted the computer ... now it works!
thanks

**Comment by flying-sheep** [comment]
OK very good!
