### ISSUE TITLE
Better help display

### ISSUE THREAD

**Issue by flying-sheep** [IRkernel/IRkernel#58]
currently `?something` outputs the raw help ANSI like `_D_e_s_c_r_i_p_t_i_o_n:` (underscore backspace letter)

the Rd help should be converted using `Rd2HTML`, not `Rd2TXT`

**Comment by takluyver** [comment]
IRkernel is currently not calling either of those. We display help by setting a function for the `pager` option. IPython only currently displays text (ipython/ipython#7824), so it might be better if we called Rd2txt for starters; once that's fixed in IPython, we can display HTML help.

**Comment by flying-sheep** [comment]
got it. in the meantime we could add an option to display help in a `.output_scroll` container instead of the pager.

**Comment by flying-sheep** [comment]
fixed in IRkernel/repr@3ff5ba87b426ecaba0babe1d53925a6e08c52a3e. let’s revisit once ipython/ipython#7824 is fixed
