### ISSUE TITLE
R process still running even after Notebook is shutdown.

### ISSUE THREAD

**Issue by praveenkanamarlapudi** [IRkernel/IRkernel#582]
Hi,

I started R Kernel notebook and used it for a while. I shutdown the notebook but still the R process it running in the host. Is there a fix for it?

**Comment by mcg1969** [comment]
I just encountered this myself, but to be fair, I’m doing some testing with a dev version of nb_conda_kernels that may be influencing what I see.

Are you running on Windows?

**Comment by praveenkanamarlapudi** [comment]
I am running on RHEL host. We are using jupyterhub and [cull idle](https://github.com/jupyterhub/jupyterhub/tree/master/examples/cull-idle) service is setup to cleanup non active user servers.

The actual problem we are seeing is - the cull idle service is killing the idle jupyter user servers. But it's not able to kill the R notebooks started. For now we have put a logic to kill those as well. 

But I am wondering why R process is not getting killed when parent process dies?

**Comment by kevin-bates** [comment]
You might try taking this change: #570

**Comment by flying-sheep** [comment]
In case updating didn’t help, please tell me and I’ll reopen this

**Comment by praveenkanamarlapudi** [comment]
It helped. Thanks @kevin-bates
