### ISSUE TITLE
rstan sampling messages not displayed

### ISSUE THREAD

**Issue by rongmu** [IRkernel/IRkernel#584]
`rstan` outputs the sampling progress of Markov chains by default (like below), however such messages are not displayed in Jupyter Notebook or JupyterLab with IRkernel.

```
SAMPLING FOR MODEL 'x' NOW (CHAIN 1).

Iteration:     1 / 50500 [  0%]  (Warmup)
Iteration:   501 / 50500 [  0%]  (Sampling)
Iteration:  5550 / 50500 [ 10%]  (Sampling)
Iteration: 10600 / 50500 [ 20%]  (Sampling)
Iteration: 15650 / 50500 [ 30%]  (Sampling)
Iteration: 20700 / 50500 [ 40%]  (Sampling)
Iteration: 25750 / 50500 [ 50%]  (Sampling)
Iteration: 30800 / 50500 [ 60%]  (Sampling)
Iteration: 35850 / 50500 [ 70%]  (Sampling)
Iteration: 40900 / 50500 [ 80%]  (Sampling)
Iteration: 45950 / 50500 [ 90%]  (Sampling)
Iteration: 50500 / 50500 [100%]  (Sampling)

 Elapsed Time: 0.00354 seconds (Warm-up)
               0.273752 seconds (Sampling)
               0.277292 seconds (Total)
```

**Comment by flying-sheep** [comment]
i can imagine that the package produces output from C or C++ code instead of using the R mechanisms.

see #416 and jupyter/enhancement-proposals#14

**Comment by rongmu** [comment]
I think you are right because Stan is a C++ library and rstan is the R interface to it.
Unfortunately I don't know much about the internals of rstan so I can't locate the code.

**Comment by flying-sheep** [comment]
Well, you could try redirecting the output using `sink('filename'); …` or `capture.output({ … })`

If not we’ll close this and, you could file an issue with rstan saying that they should redirect the stdout to the R streams

**Comment by rongmu** [comment]
I couldn't capture the output with `sink` or `capture.output`. The result was just blank.
I will file an issue with rstan and it's okay to close this issue.

**Comment by flying-sheep** [comment]
great, thank you!

**Comment by aakhmetz** [comment]
> I couldn't capture the output with `sink` or `capture.output`. The result was just blank.
> I will file an issue with rstan and it's okay to close this issue.

I dit the following
```r
capture.output({
    fit <- stan("model_test_1.stan",
        data = stan_data)},
    file="model_test_1.stan.output")
fit
```
and I was able to catch the output progressively.
