### ISSUE TITLE
R kernel keeps dying

### ISSUE THREAD

**Issue by San-Mir** [IRkernel/IRkernel#585]
Dear all,

I am trying to use Juypter for the first time. I have installed the notebook, lab and different jupyter kernels (R, Python, Javascript (node.js) on my laptop. I am using Anaconda environment. I downloaded the R kernel for Jupyter by following isntructions from official github repository:

https://github.com/IRkernel/IRkernel

Python and JS kernels are working fine. However, my R kernel keeps dying and I keep getting this message:

> The kernel has died, and the automatic restart has failed. It is possible the kernel cannot be restarted. If you are not able to restart the kernel, you will still be able to save the notebook, but running code will no longer work until the notebook is reopened.

On my Anaconda Prompt I get this message:

```
The filename, directory name, or volume label syntax is incorrect.
[W 22:26:29.085 NotebookApp] KernelRestarter: restart failed
[W 22:26:29.085 NotebookApp] Kernel 0dc0a948-320b-44ad-a2e4-36b2480421f6 died, removing from map.
kernel 0dc0a948-320b-44ad-a2e4-36b2480421f6 restarted failed!
[W 22:26:29.102 NotebookApp] 410 DELETE /api/sessions/9d0a8c73-b413-4934-8be8-64b2687e6904 (::1): Kernel deleted before session
[W 22:26:29.104 NotebookApp] Kernel deleted before session
[W 22:26:29.105 NotebookApp] 410 DELETE /api/sessions/9d0a8c73-b413-4934-8be8-64b2687e6904 (::1) 5.00ms referer=http://localhost:8888/notebooks/Untitled9.ipynb?kernel_name=ir
[I 22:28:14.188 NotebookApp] Saving file at /Untitled9.ipynb
[W 22:37:01.781 NotebookApp] 404 DELETE /api/sessions/9d0a8c73-b413-4934-8be8-64b2687e6904 (::1): Session not found: session_id='9d0a8c73-b413-4934-8be8-64b2687e6904'
[W 22:37:01.782 NotebookApp] Session not found: session_id='9d0a8c73-b413-4934-8be8-64b2687e6904'
[W 22:37:01.785 NotebookApp] 404 DELETE /api/sessions/9d0a8c73-b413-4934-8be8-64b2687e6904 (::1) 5.00ms referer=http://localhost:8888/notebooks/Untitled9.ipynb?kernel_name=ir
[I 22:37:01.856 NotebookApp] Kernel started: a0a1dbbc-adbf-4105-a140-b9fdf0f532bf
The filename, directory name, or volume label syntax is incorrect.
[I 22:37:04.828 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
The filename, directory name, or volume label syntax is incorrect.
[I 22:37:07.848 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
The filename, directory name, or volume label syntax is incorrect.
[I 22:37:10.860 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
The filename, directory name, or volume label syntax is incorrect.
```

How to get a working R kernel for Jupyter? Kindly help me out. Thanks a bunch.

**Comment by flying-sheep** [comment]
> The filename, directory name, or volume label syntax is incorrect.

seems like the problem is in the path in your kernelspec json. please find itspath to in `jupyter kernelspec list` and post its contents here.

also anaconda installs aren’t supported, please use the official install instructions: https://irkernel.github.io/installation/

**Comment by San-Mir** [comment]
Hello,

Here is the path of my R kernel.

C:\Users\Hassan Mirza>jupyter kernelspec list
Available kernels:
  ir            C:\Users\Hassan Mirza\AppData\Roaming\jupyter\kernels\ir
  javascript    C:\Users\Public\Anaconda\share\jupyter\kernels\javascript
  python3       C:\Users\Public\Anaconda\share\jupyter\kernels\python3

**Comment by flying-sheep** [comment]
> ir C:\Users\Hassan Mirza\AppData\Roaming\jupyter\kernels\ir

this is the path where the “IR” (this) kernel’s JSON is in. open the json file in that folder and find the path to your R binary inside of that file.

> I got this error message after giving this input command:

that’s not an error message, it says that the current version of the package is already installed.

**Comment by San-Mir** [comment]
Hello, 

I here is my JSON file:

{
  "argv": ["C:/Users/Public/Anaconda/lib/R/bin/x64/R", "--slave", "-e", "IRkernel::main()", "--args", "{connection_file}"],
  "display_name": "R",
  "language": "R"
}

**Comment by flying-sheep** [comment]
hmm, maybe try to replace the `/` with `\\` (needs to be double)

**Comment by San-Mir** [comment]
R kernel is still not working. I am getting this error on command prompt:

[I 12:06:04.270 LabApp] Accepting one-time-token-authenticated connection from ::1
[W 12:06:06.276 LabApp] Notebook Untitled10.ipynb is not trusted
[I 12:06:06.297 LabApp] Build is up to date
[I 12:06:07.284 LabApp] Kernel started: 6fffa6f3-4f58-4647-a661-2962a7226210
[I 12:06:08.779 LabApp] Adapting to protocol v5.1 for kernel 6fffa6f3-4f58-4647-a661-2962a7226210
[I 12:06:08.781 LabApp] Adapting to protocol v5.1 for kernel 6fffa6f3-4f58-4647-a661-2962a7226210
[I 12:06:19.685 LabApp] Creating new notebook in /
[I 12:06:22.975 LabApp] Kernel started: eabd6917-e8aa-4571-8ae4-3b3e8dd5d5c7
The filename, directory name, or volume label syntax is incorrect.
[I 12:06:25.954 LabApp] KernelRestarter: restarting kernel (1/5), new random ports
The filename, directory name, or volume label syntax is incorrect.
[I 12:06:28.971 LabApp] KernelRestarter: restarting kernel (2/5), new random ports
The filename, directory name, or volume label syntax is incorrect.
[I 12:06:31.984 LabApp] KernelRestarter: restarting kernel (3/5), new random ports
The filename, directory name, or volume label syntax is incorrect.
[W 12:06:33.012 LabApp] Timeout waiting for kernel_info reply from eabd6917-e8aa-4571-8ae4-3b3e8dd5d5c7
[I 12:06:35.008 LabApp] KernelRestarter: restarting kernel (4/5), new random ports
kernel eabd6917-e8aa-4571-8ae4-3b3e8dd5d5c7 restarted
kernel eabd6917-e8aa-4571-8ae4-3b3e8dd5d5c7 restarted
kernel eabd6917-e8aa-4571-8ae4-3b3e8dd5d5c7 restarted
The filename, directory name, or volume label syntax is incorrect.
[W 12:06:38.027 LabApp] KernelRestarter: restart failed
[W 12:06:38.027 LabApp] Kernel eabd6917-e8aa-4571-8ae4-3b3e8dd5d5c7 died, removing from map.


Actually R kernel was working fine in my previous windows 10 installation. I changed the hard disk and reinstalled windows 10 in my new SSD and since then my R kernel is not working properly.

**Comment by San-Mir** [comment]
Can you redirect me to some other help thread for more help? 

My python and JS(.node) kernel are working fine, only R kernel is creating problems.  Here are the JSON paths of Python and JS kernels.


{
 "argv": [
  "C:\\Users\\Public\\Anaconda\\python.exe",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Python 3",
 "language": "python"
}

{"argv":["ijskernel.cmd","--hide-undefined","{connection_file}","--protocol=5.0"],"display_name":"Javascript (Node.js)","language":"javascript"}

**Comment by flying-sheep** [comment]
> Actually R kernel was working fine in my previous windows 10 installation. I changed the hard disk and reinstalled windows 10 in my new SSD and since then my R kernel is not working properly.

seems like a file system problem. maybe something broke during the move. I sometimes have to delete my R package library and reinstall everything

**Comment by San-Mir** [comment]
Should I delete Jupyter and R studio as well, along with my R installation and R package liabrary?

**Comment by flying-sheep** [comment]
for me, deleting and re-installing the package library has always been sufficient.

but i don’t understand this error, so anything might be responsible.

**Comment by San-Mir** [comment]
I have tried uninstalling and reinstalling R package system in anaconda environment as well, the problem remains. I dont know. 

Do you use R kernel in jupyter via Anaconda environment (as prescribed by their official website) or do you have an independent installation of jupyter (independent of anaconda distribution)?????

**Comment by flying-sheep** [comment]
I don’t have anaconda anywhere on my systems. Neither Python nor R. Maybe it’s worth a shot to install everything independently instead.

I’m very sorry that I can’t help you debug this problem, I just don’t know where that error comes from.

If you want, you can also try [JuniperKernel](https://github.com/JuniperKernel/JuniperKernel), it might work differently enough that it avoids the bug you see.

**Comment by San-Mir** [comment]
Okay, I will try Juniper out. Thanks for your extensive help. :)

**Comment by flying-sheep** [comment]
OK, feel free to come back for more :smiley:
