### ISSUE TITLE
Support for mimetype representations to render Altair 

### ISSUE THREAD

**Issue by mattijn** [IRkernel/IRkernel#587]
In a discussion at https://github.com/altair-viz/altair/issues/1141 we were wondering if there is any possibility to make the IRkernel recognize mimebundle rendering.

This would make it possible to render Altair visualizations from within an R kernel!

Maybe using something similar to `IRdisplay::display_html()`?

**Comment by mattijn** [comment]
Not exactly sure where to continue as in https://github.com/jupyterlab/jupyter-renderers it mentions that they provide: 

> This is a monorepo that consists of generic renderers for common file types and mime types as well as renderer extensions for JupyterLab.

Including `application/vnd.vegalite.v2+json`.

But if I try the following in Jupyter with R kernel these seems not supported in IRdisplay:

```
library(IRdisplay)
options('jupyter.display_mimetypes')
```
<img width="359" alt="in0" src="https://user-images.githubusercontent.com/5186265/45865692-a6658480-bd7e-11e8-8b1e-608a84641590.png">



Where using `IPython` it seems to be handled using the `display()` function ([source](https://github.com/altair-viz/altair/issues/732#issuecomment-379882946)).

My notebook looks as follow for Altair using reticulate:

```R
library(reticulate)
use_python("/usr/local/bin/python3", required = T)
library(IRdisplay)
py_config()
```
<img width="623" alt="in2" src="https://user-images.githubusercontent.com/5186265/45865607-5be40800-bd7e-11e8-9a73-7a58589b4d08.png">

```R
alt <- import("altair")
alt$data_transformers$enable('json')
```

<img width="620" alt="in3" src="https://user-images.githubusercontent.com/5186265/45865739-bb421800-bd7e-11e8-87e0-bfe9a662312a.png">


```R
vega_datasets <- import("vega_datasets")
cars <- vega_datasets$data$cars()
```
```R
chart <- alt$Chart(cars)$mark_point()$encode(
    x = "Horsepower:Q",
    y = "Miles_per_Gallon:Q",
    color = "Origin:N"
)
```
```R
IRdisplay::display_json(chart$data)
```

<img width="620" alt="in4" src="https://user-images.githubusercontent.com/5186265/45865753-c7c67080-bd7e-11e8-8699-66367e0f7ca1.png">


```R
chart$`_repr_mimebundle_`(include = NULL, exclude = NULL)
```
<img width="794" alt="in7" src="https://user-images.githubusercontent.com/5186265/45865773-d745b980-bd7e-11e8-8867-155f73a35754.png">


Full notebook as described is here: https://github.com/mattijn/pynotebook/blob/master/r_altair.ipynb

**Comment by flying-sheep** [comment]
Hi! I’ll simply describe the way IRdisplay and repr work (the two packages working in concert to enable IRkernel’s output):

repr provides generic functions to convert R objects into data (HTML, text, images, …) and some implementations (For R base types and popular ones). If you have an R class you want displayed, just define `repr_html.myclass <- function(obj) '<tag>...</tag>'` and be done with it. Return `NULL` if you can’t represent a specific object.

`IRdisplay::display` tries out all repr functions and creates a mime bundle from the results that aren’t NULL. `IRdisplay::display_html` and friends are convenience functions that take data (in this case a HTML string) and create a mime bundle with just one entry.

**Comment by flying-sheep** [comment]
Got it? OK, there’s just two more things:

`display` is basically `function(obj) publish_mimebundle(prepare_mimebundle(obj))`, with `prepare_mimebundle` being the part that tries all `repr`s and `publish_mimebundle` being the part that sends it to jupyter.

This means that when you have a mimebundle, just use `publish_mimebundle(mimebundle)`. In your case:

```r
publish_mimebundle(chart$`_repr_mimebundle_`(include = NULL, exclude = NULL))
```

Remember when I explained how the automation works via `

**Comment by mattijn** [comment]
Ok, all of this scares me deeply, but when I try the manual display I got the following error:

```R
publish_mimebundle(chart$`_repr_mimebundle_`(include = NULL, exclude = NULL))
```
><ol class=list-inline>
> 	<li>No renderer could be found for output. It has the following MIME types: 0, 1</li>
></ol>

That make somehow sense to me, since there is no registered  display mimetype `'application/vnd.vegalite.v2+json'`.

Then you suggest a way to register this type to the `display_mimetypes`, but when I try this I got an error related to `mime2repr[[mime]](obj): attempt to apply non-function`. Afterward it prints the supported `display_mimetypes` including `'application/vnd.vegalite.v2+json'`, but trying to use this with an `'application/vnd.vegalite.v2+json'` object (from Altair) will result in the same error.

```R
library(IRdisplay)
options('jupyter.display_mimetypes')
```


> <strong>$jupyter.display_mimetypes</strong> = <ol class=list-inline>
> 	<li>'text/plain'</li>
> 	<li>'text/html'</li>
> 	<li>'text/markdown'</li>
> 	<li>'text/latex'</li>
> 	<li>'application/json'</li>
> 	<li>'application/javascript'</li>
> 	<li>'application/pdf'</li>
> 	<li>'image/png'</li>
> 	<li>'image/jpeg'</li>
> 	<li>'image/svg+xml'</li>
> </ol>


```R
library(repr)
repr_vega <- function(obj, ...) UseMethod('repr_vega', obj)
```


```R
options(jupyter.display_mimetypes = c(getOption('jupyter.display_mimetypes'), 'application/vnd.vegalite.v2+json'))
IRkernel:::replace_in_package('repr', 'mime2repr', c(repr::mime2repr, list(`application/vnd.vegalite.v2+json` = repr_vega)))
```


```R
options('jupyter.display_mimetypes')
```

>     ERROR while rich displaying an object: Error in mime2repr[[mime]](obj): attempt to apply non-function
>     
>     Traceback:
>     1. FUN(X[[i]], ...)
>     2. tryCatch(withCallingHandlers({
>      .     rpr <- mime2repr[[mime]](obj)
>      .     if (is.null(rpr)) 
>      .         return(NULL)
>      .     prepare_content(is.raw(rpr), rpr)
>      . }, error = error_handler), error = outer_handler)
>     3. tryCatchList(expr, classes, parentenv, handlers)
>     4. tryCatchOne(expr, names, parentenv, handlers[[1L]])
>     5. doTryCatch(return(expr), name, parentenv, handler)
>     6. withCallingHandlers({
>      .     rpr <- mime2repr[[mime]](obj)
>      .     if (is.null(rpr)) 
>      .         return(NULL)
>      .     prepare_content(is.raw(rpr), rpr)
>      . }, error = error_handler)
> 
> 
> 
> <strong>$jupyter.display_mimetypes</strong> = <ol class=list-inline>
> 	<li>'text/plain'</li>
> 	<li>'text/html'</li>
> 	<li>'text/markdown'</li>
> 	<li>'text/latex'</li>
> 	<li>'application/json'</li>
> 	<li>'application/javascript'</li>
> 	<li>'application/pdf'</li>
> 	<li>'image/png'</li>
> 	<li>'image/jpeg'</li>
> 	<li>'image/svg+xml'</li>
> 	<li>'application/vnd.vegalite.v2+json'</li>
> </ol>

**Comment by mattijn** [comment]
Somehow this mimetype should be mapped to the JupyerLab extension https://github.com/jupyterlab/jupyterlab/tree/c3fff81d3f053c4f94e84263ae785eda56cb55aa/packages/vega4-extension but this mapping I don't see anywhere in these code snippets?

**Comment by mattijn** [comment]
I got the manual display working!
<img width="725" alt="ouputewf" src="https://user-images.githubusercontent.com/5186265/45914864-63bdae00-be4b-11e8-8087-caca560bcb3f.png">
Documented in following notebook: https://github.com/mattijn/pynotebook/blob/master/r_altair_reticulate_mimebundle.ipynb

The registration of the type for the automatic way still gives the errors as mentioned above.

**Comment by flying-sheep** [comment]
hey! I think it’s not super hard to unserstand – why are you scared? what’s missing?

So again. High level:

1. Someone prepares a mime bundle
2. The kernel publishes the mime bundle
3. The frontend (jupyterlab) decides which part of the mimebundle to display

Manually displaying things via `publish_mimebundle` is simply step 2.

For step 3, Jupyterlab itself or a plugin (e.g. an extension) says “hey, I know what to do with that mimetype” and displays it.

`IRdisplay::display` does step 1&2, as does IRkernel itself when you just put an object in a cell (or call a function returning an object):

1. `options('jupyter.display_mimetypes')` determines what mime types are tried out by IRdisplay or the IRkernel
2. the functions to try and convert the object to the mime types are taken from `mime2repr`
3. the published mimebundle contains all return values of those functions

---

With that knowledge you’ll unserstand the error: I forgot that you also need `repr_vega.default <- function(obj, ...) NULL`. The error comes from the fact that now IRkernel also tries `repr_vega`, which has no implementations. therefore `UseMethod('repr_vega', obj)` will call `NULL(object)` or so, resulting in the error.

**Comment by mattijn** [comment]
I'm not that scared anymore and after a few hours of mime bundling I know how to render some of these mime types while understanding what I do and can expect. Thanks for all these great explanations!

There is still an issue though. I can now render by manual specifying the `_repr_mimebundle_`, but Jupyter-Lab doesn't auto recognize the `chart` object as a mimebundle to render. 

<img width="758" alt="error_mimebundling" src="https://user-images.githubusercontent.com/5186265/46095750-91915280-c1bd-11e8-9000-f1a81832e75f.png">

See also the following notebook for details: https://github.com/mattijn/pynotebook/blob/master/r_mimebundle_irdisplay.ipynb

In the display troubleshooting of Altair is this explained as an IPython issue when rendering with a Python kernel (https://altair-viz.github.io/user_guide/troubleshooting.html#jupyterlab-textual-chart-representation). 
So using an R kernel this is also an IRkernel and/or IRdisplay issue?

**Comment by flying-sheep** [comment]
In your example notebook, you defined `repr_vega`, installed it to `repr::mime2repr`, and provided `repr_vega.default` to prevent errors.

But you didn’t provide a `repr_vega.Chart` method! (Be sure to check if `'chart' %in% class(chart)`)

**Comment by flying-sheep** [comment]
hey @mattijn, did you succeed?

**Comment by mattijn** [comment]
No.. spent those days around September 27 a dozen of hours on this, but had to give up since it was not work related work..

<img width="843" alt="grr" src="https://user-images.githubusercontent.com/5186265/48284337-6908a380-e45f-11e8-82a7-b50ad3a3fcfb.png">

the error was and is still:
```html
Javascript Error: undefined
```
Then I thought, maybe there is something with this `_repr_mimebinde_` function, why we've to pass this `include = NULL, exclude = NULL, manually? In which case is this not `NULL`?

Also the `class(chart)` you define as method, I cannot understand. It seems you only can access these methods once you've a `chart` as object. But I thought there need to be something in place that can auto-render any altair/vega4 object.

**Comment by flying-sheep** [comment]
I made you a notebook. “Javascript Error: undefined” looks like the R side works. What doesn’t is the rendering.

https://gist.github.com/flying-sheep/ff67d4a37a59785b7b0875dbb521dd1b

You see that there’s

```json
"data":{
  "url":["altair-data-32719fd5dfa9b6fabd12b66c33e9e445.json"],
  "format":{
    "type":["json"]
  }
}
```

I also see that JSON file, and I have no idea what’s going wrong while jupyter tries to render this. I’ll ask in https://github.com/altair-viz/altair/issues/1141

**Comment by mattijn** [comment]
This is great! Really big step. Nicely done! 

I tried and it works when I run the following code before I start importing `reticulate` etc (just like your notebook).

```R
library(repr)
repr_vega <- function(obj, ...) UseMethod('repr_vega', obj)
repr_vega.default <- function(obj, ...) NULL
options(jupyter.display_mimetypes = c(getOption('jupyter.display_mimetypes'), 'application/vnd.vegalite.v2+json'))
IRkernel:::replace_in_package('repr', 'mime2repr', c(repr::mime2repr, list(`application/vnd.vegalite.v2+json` = repr_vega)))
py_mimebundle <- function(obj) obj$`_repr_mimebundle_`(include = NULL, exclude = NULL)[[1L]]

repr_text.altair.vegalite.v2.api.Chart <- function(chart)
    py_mimebundle(chart)$`text/plain`
repr_vega.altair.vegalite.v2.api.Chart <- function(chart)
    py_mimebundle(chart)$`application/vnd.vegalite.v2+json`
```

Eventually these lines of code will be included in IRdisplay as well?

**Comment by mattijn** [comment]
I would advocate to include the render functions for Altair mimetypes as well.

There is already the development of https://vegawidget.github.io/altair/ that enables the usage of Altair in RStudio as htmlwidget.

But htmlwidgets are not existent in Jupyter so R users in Jupyter cannot enjoy the developments of R altair - vegawidget. 

Therefore the inclusion of direct rendering of Altair mimetypes would be great. 

Eventually it would be nice to have some examples featuring an R kernel notebook on https://github.com/jupyterlab/jupyterlab/tree/master/packages/vega4-extension

**Comment by flying-sheep** [comment]
I think you got something confused, but maybe I’m just wrong:

Isn’t there only the vega and vegalite mimetypes? and altair is a library able to render to those?

There’s already a PR by me for those mime types: https://github.com/IRkernel/repr/pull/103

Do you mean I should add a repr method for the class `altair.vegalite.v2.api.Chart`? I think that one should go into the altair R package you link: https://github.com/vegawidget/altair/issues/91

**Comment by mattijn** [comment]
That PR you are working on looks like a great addition to rendering multiple new mime types within the IRkernel!

The main Altair API is based on version 2.X* of Vega-Lite, but Altair provide wrappers to multiple versions for Vega and Vega-Lite. ([source](https://altair-viz.github.io/user_guide/importing.html)). 

The altair R package I refer to and where you opened an issue is focussing -in my understanding- solely on displaying Vega-Lite charts configured within altair using [R htmlwidgets](https://www.htmlwidgets.org). I believe these htmlwidgets are not supported by JupyterLab. 
See my discussion with @ijlyttle in https://github.com/vegawidget/altair/issues/90, these htmlwidgets are also not needed in JupyterLab since there is direct support of mime types rendering.

I know that Altair has different built-in renderers for multiple front-ends like JupyterLab, nteract, Jupyter Notebook and Google Colab ([source](https://altair-viz.github.io/user_guide/custom_renderers.html)), but as can be seen it is not always based on the `'application/vnd.vegalite.v2+json'` mime type.

If the Altair mime type is not a custom Jupyter mime type than I'm not certain where the Altair mime type support should be placed: IRkernel or vegawidget/altair. Or as another custom renderer in Altair. Maybe @jakevdp can give some suggestions.

.* Vega-Lite will soon release version 3 so Altair will probably follow soon support these scheme as well.

**Comment by flying-sheep** [comment]
I still don’t get what you mean by “altair mime type”: `application/vnd.vegalite.v2+json` is a mime type. Altair renders to some vega or vegalite mimetype, but there’s no `application/vnd.altair` mimetype as far as I know.

It seems like you might mean the method `repr.altair.vegalite.v2.api.Chart`. That would be an R method, not a mime type. I asked them in vegawidget/altair#91if they’ll add it in their package because the class `altair.vegalite.v2.api.Chart` is a python one and comes to R only via `reticulate`. that seems to me like an implementation detail and not something to rely on and bake into `repr`.

**Comment by jakevdp** [comment]
> I still don’t get what you mean by “altair mime type”

Altair renders with the Vega-Lite mime type.

**Comment by flying-sheep** [comment]
so there’s no altair mime type, as I thought. and yes, altair does that in IPython + Jupyterlab.

vegawidget/altair#91 (and this issue) is about IRkernel + Jupyterlab.

**Comment by jakevdp** [comment]
Understood – just trying to answer your questions.

**Comment by mattijn** [comment]
You are right @flying-sheep, I was referring to `repr.altair.vegalite.v2.api.Chart`, which is not a mime type but a method indeed. My bad! 

In this perspective this method might be best placed in the vegawidget/altair repo now the Vega(-Lite) mime types are supported within IRKernel. Let's transfer the discussion to https://github.com/vegawidget/altair/issues/91 

Thanks for all these developments and this continuous discussion in general!

Thanks @jakevdp for your clarifications as well. I will close this issue.

**Comment by flying-sheep** [comment]
thank you guys!

**Comment by flying-sheep** [comment]
hey @mattijn: https://github.com/vegawidget/altair/pull/92 is merged!

the next version of vegawidget/altair should have native support for IRkernel.

just be sure to update repr and IRdisplay!

**Comment by ijlyttle** [comment]
It is merged into master branch now - you can `install_github(vegawidget/altair)`. A CRAN release will likely wait for the next Altair release, which will likely follow the Vega-Lite 3 release.

**Comment by flying-sheep** [comment]
wait, vegalite 3 already? damn, I thought that stuff had stabilized. will I have to add `repr_vegaliteX` methods till the end of dawn?

**Comment by ijlyttle** [comment]
Price of progress...

**Comment by mattijn** [comment]
WoW! Big double thumbs up for you guys! Really nice!

**Comment by jakevdp** [comment]
> which will likely follow the Vega-Lite 3 release.

I think we'll do an Altair 2.3 release in the next couple days, and a 3.0 release once Vega-Lite 3 is out (as of a couple weeks ago there was no specific targeted release data for VL3)

**Comment by ijlyttle** [comment]
Great news for Altair - but I will have to amend my statement. The vegawidget package, imported by the altair (R) package, will likely wait for VL3 to go to CRAN. The altair package would then follow Altair.
