### ISSUE TITLE
Return printed output as stream

### ISSUE THREAD

**Issue by kylebarron** [IRkernel/IRkernel#589]
I don't usually use R, but have been trying to get colleagues to use Jupyter more. I was surprised to see that IRkernel only returns results once a command has completed, and not as lines are printed as output. Is this desired behavior?

![peek 2018-09-28 11-14](https://user-images.githubusercontent.com/15164633/46217336-b7c70780-c30f-11e8-84d0-1db1cb139902.gif)

In contrast, Python shows results as a stream
![peek 2018-09-28 11-19](https://user-images.githubusercontent.com/15164633/46217585-62d7c100-c310-11e8-8be9-8e1efe799463.gif)

R version 3.4.4
IRkernel version 0.8.12.9000

**Comment by spennihana** [comment]
Yup JuniperKernel does this! Trick is to sink stdout/stderr to a TCP `socketConnection` that has a zmq tcp socket listener on the other end (that will create the appropriate `stream` message). I do not think that the `evaluate` package (which IRKernel uses) handles this situation.

**Comment by kylebarron** [comment]
I see. So it's unrealistic to hope for this functionality in IRKernel without replacing `evaluate`?

**Comment by flying-sheep** [comment]
It does, but you have to call `flush.console()` when you want to see output.

AFAIK there’s no way around it on R level.
