### ISSUE TITLE
add setting for using HTML print function

### ISSUE THREAD

**Issue by flying-sheep** [IRkernel/IRkernel#59]
like shown [here](http://nbviewer.ipython.org/gist/deeplook/5162445), ipython/jupyter has display hooks that can be registered with display formatters (e.g. png, html)

it would be nice if IRDisplay and IRKernel would work together so that

1. we define a S3 or S4 generic (e.g. `jupyterdisplay.default`)
2. IRDisplay defines it for some classes (e.g. `jupyterdisplay.matrix`)
3. users can override it

**Comment by takluyver** [comment]
I think that makes sense - the default would just send the text/plain representation. We'd call `jupyterdisplay(obj)` on expressions at the end of a cell (the 'value' handler in evaluate), and packages could override it to display richer data for their objects, right? I'm not especially familiar with R's class mechanisms.

**Comment by flying-sheep** [comment]
well, my idea was that

1. directly calling it will work like you described
2. `options(jupyter.display = 'rich')` would make it the default function to be called instead of `print`

i gather that `print` simply outputs to stdout (and returns its argument invisibly), and if something gets returned but not assigned in a REPL, then `print` is called on it.

---

also we basically already do something like this with plots, and have to think about what else should be treated specially (i.e. where don’t we just display the stdout of `print` even if `getOption('jupyter.display') == 'text'`?)

---

finally we should probably replace `set_plot_options` with `options(jupyter.plot = list(...))` if we’re going to add more options.

**Comment by flying-sheep** [comment]
we should also add a class that allows HTML passthrough (like the `IPython.display.HTML` class).

then we could e.g. do:

```r
data.frame(
	escaped=c('<', '&', '<script>doEvil()</script>'),
	unescaped=c(as.html('<a href="..."></a>'), html('&amp;', '2<sup>nd</sup> cell')),
	factor=as.factor(........),
	stringsAsFactor=FALSE)
```

and only columns with `class(column) == 'html'` wouldn’t be escaped.

**Comment by flying-sheep** [comment]
also we need to treat output differently from displaying.

normally things that are non-invisibly returned (e.g. by calling a function or typing a variable name without assigning it to a name) are `print`ed in R.

this already works: `print(foo)` does the same as `foo`, except that the latter produces an  `Out [1]:` thingy next to it (`execute_result`) and the former doesn’t (`display_data`)

---

i think we should do it like this:

1. define some rich display option
2. if it’s not set, print and output behaves normally (monospace string representation without and with `Out[1]`, respectively)
3. if it is, we should use some conversion function (maybe called sth like `jupyter_repr`) on everything to be printed or outputted before it is returned (we might have to override some generic implementations for `print` to do so)

**Comment by JanSchulz** [comment]
I think there is already somethig in knitr, which could be reused: http://blog.rapporter.net/2014/09/pander-tables-inside-of-knitr.html 
http://cran.r-project.org/web/packages/knitr/vignettes/knit_print.html

**Comment by flying-sheep** [comment]
the first link isn’t really relevant (it’s about markdown conversion via pandoc, whereas we just need data→html, and pandoc is a heavy dependency)

but the second one is pretty nice!

it seems that they use the same approach as i proposed, with `asis_output` being the class which is rendered prettily, as well as a function assigning this class to some object.

`knit_print` is a generic function converting stuff to fitting `asis_output` objects. their `knit_print.data.frame` example is basically a function calling `asis_output(kable(some_data.frame))`, where `kable` converts matrix/dataframe like objects to HTML.

---

the only problem is

> In the future, I may provide a companion package with knitr that includes appropriate printing methods so that users only need to load this package to get attractive printed results.

so the plug-and-play functionality doesn’t exist yet.

---

but if we depend on knittr, we can reuse this:

1. call `knit_print` on objects before displaying/outputting them if our option is set (which will generate a object of class `asis_output`)
2. print `class('asis_output') == TRUE` objects directly (as HTML, PNG, …)

they have an chunk option called `render`, initially set to `knit_print`, we can reuse this too (only the concept, though, as this is not an option as in `options(render=knit_print)`, but a knitr chunk option.)

**Comment by JanSchulz** [comment]
Seems that knit_print is now in https://github.com/yihui/printr, which seems to be the " companion package".

The first one demonstrates the system: the pander output (via the knit_print system) returns Markdown which is then used by knitr to turn it into "anything" via pandoc. So, in this case the `knit_print` returns markdown and the kernel could send that in a "text/markdown" display message back to IPython, which would then display markdown.

One problem I see is that in knitr and the IPython display system work quite differently:
* knitr puts the output of the 'asis_output' and puts it 'asis' into into the document which is then converted via pandoc. knitr actually seems to not know the format of the string which is included (so it can be latex, html, or markdown) and this also can't be changed during the print run but is specified by the call which produces the 'asis_output' (in the above example pander, which outputs markdown). This works (and breaks) as long as pandoc can convert the string into the desired output format. 
*  IPython on the other hand needs to know the mimetype of the data being send from the kernel to IPython (qtconsole/notebook) and it also tries to send multiple versions of the same data (see http://ipython.org/ipython-doc/dev/development/messaging.html#id4), so in the example it would make sense to send plain printed output (mimetype "text/plain"), a html version ("text/html") and a markdown ("text/markdown") version.

Maybe it makes sense to use the above package and ask there to get a way to ask for specific output (cc: @yihui)?

If you have to choose one format, please don't use html but markdown. The notebook can display markdown as nicely as html and pandoc can transform it to anything (html, latex/pdf or even docx) but currently can't convert html tables to anything but html. This sucks if you want to build a PDF with included pandas tables (e.g. via the nbconvert or via my knitr clone [knitpy](https://github.com/JanSchulz/knitpy)).

**Comment by flying-sheep** [comment]
> Maybe it makes sense to use the above package and ask there to get a way to ask for specific output

yes, but only if we don’t need to depend on pandoc. it’s really huge for what we want to do. i’d rather write a bunch of (help|matrix|data.frame|…) displaying functions myself.

pandoc isn’t packaged in e.g. arch linux, and it’s only an optional dependency of the notebook (only for exporting), so we shouldn’t make our R kernel depend on it.

> If you have to choose one format, please don't use html but markdown. The notebook can display markdown as nicely as html

ah, didn’t know that! yeah, sounds better this way regarding PDF export.

**Comment by JanSchulz** [comment]
No, this don't depend in pandoc at all: the conversation "from markdown via pandoc" is done on the output of the knit_print call.

**Comment by flying-sheep** [comment]
yeah, just wanted to be clear

**Comment by JanSchulz** [comment]
Just to add something here: html tables are probably fine, when pandoc 1.13.3 is available: currently pandoc does not understand `<tr><th>text</th><td>text2</td></tr>` (th mixed with td in one tr). See https://github.com/jgm/pandoc/issues/2015 and https://github.com/jgm/pandoc/issues/1859. So this means that html is fine but I would still prefer markdown as that is still more portable. 

In any case, the solution has to know the mimetype to not get funny things like `pander` markdown output in a `text/html`message.

**Comment by flying-sheep** [comment]
> currently pandoc does not understand `<tr><th>text</th><td>text2</td></tr>` (th mixed with td in one tr)

…which we will definitely want for row names in tables and data.frames.

**Comment by JanSchulz** [comment]
@flying-sheep That will probably not work for *row* names (column names are ok), as I think the solution was to treat th as td in all but the first row.

This is from https://github.com/jgm/pandoc/issues/1859
> okay, I pushed to #1885. Now we parse basically any combination of opening, closing, non-opening, non-closing thead and tbody tags. The first complete row of ths will always be the headers, subsequent ths will be treated as tds.

Not sure what to do about this...

But I think the more important thing is to define a function system which works for ipythons mimetype based system. Something like `print_mimetype(obj, mimetype)` and then let Rs multi-dispatch system do the rest. I still think that this should be proposed to the knitr/printr guys, as this will have more chances to be adopted in th R world. I think that would also be better for knitr, as currently the 'asis' thing breaks if one specifies a the wrong asis format for the output format (=pandoc can't convert).

**Comment by flying-sheep** [comment]
hmm, we should think about how to allow users to register new ones then:

S3 and S4 generics both work on classes, not mime types. and if we want to e.g. provide a `data.frame` method returning `text/html`, but allow someone to provide e.g. a `text/x-markdown` representation, this doesn’t work as easily, except if we want to allow only a limited amount of mime types (e.g. `jupyterdisplay_html`, `jupyterdisplay_md`, `jupyterdisplay_png`, `jupyterdisplay_svg`)

**Comment by takluyver** [comment]
For reference: in Python, the equivalent are repr methods - the default method to produce a plain text representation is called `__repr__` (this is, AIUI, roughly equivalent to `print.<classname>` in R). Then IPython looks for additional methods called `_repr_html_`, `_repr_png_`, etc. to compute the rich representations. These are similar to the proposed `jupyterdisplay_html` etc. functions, I think.

 We're just discussing the possibility of having a `_repr_mimetypes_` method that would return a dict keyed by mimetypes, but I think it would rarely be used even if we had it.

**Comment by JanSchulz** [comment]
the printr method has the possibility to get an option parameter (see here: https://github.com/yihui/printr/blob/master/R/table.R), so this would be similar to my version above. But I think I like a `jupyterdisplay_<mimetype>` version better, it's at least clear that you have to implement html and not simple "forget" about the mimetype and just return whatever.

**Comment by flying-sheep** [comment]
yea, and it will work as generic, so `methods('jupyterdispay_html')` will return a useful list of classes for which a html display is defined.

---

i’m not sure about the `display` part of the method name though, as there are distinct `execute_result` and `display_data` functions. so the common denominator should be something that *returns* the representation, and doesn’t display it, as well as a function displaying those representations.

maybe `jupyter` or `as.jupyter` or something?

**Comment by takluyver** [comment]
So as I understand this, we would define a series of functions `jupyterhub_<format>.default()` in IRdisplay, and then class authors or third parties would define `jupyterhub_<format>.<classname>()` functions for different classes, right? Then in IRkernel, we just call `jupyterhub_<format>()` for the different formats on the object we've got to get the different formats that it knows about.

@flying-sheep you're right that it should return some data rather than displaying it directly, because we'll want to collect multiple alternative formats together in a single output (e.g. a table can have text, HTML and Latex representations).

Other possible names: `jupyterformat_html`, `jupyterrepr_html`.

**Comment by JanSchulz** [comment]
I'm still for collaborating with the knitr/printr guis (@yihui) and going for something which is best for both. It's a lot easier to get support from multiple packages if knitr/rmarkdown and the jupyter kernel will work with it than only jupyter.

**Comment by flying-sheep** [comment]
> I'm still for collaborating with the knitr/printr guis `jupyterhub_<format>.default()` […] we've got to get the different formats that it knows about.

yeah! that’s it.

the `.default` function would probably just call `print` on it while capturing stdout, and return a literal block (`<pre/>`, markdown code block, LaTeX `\lstlisting`).

> I'm still for collaborating with the knitr/printr guis

yes! i just thought about the ideal solution for us here. the ideal, environment-agnostic way would probably be the same, but with function names like `as.html`, `as.markdown`, and so on, or with another prefix, like `as.repr_html` or `repr_html`

this would be discoverable if it were its own package instead of bundled with us or knitr.

**Comment by takluyver** [comment]
> the .default function would probably just call print on it while capturing stdout, and return a literal block (`<pre/>`, markdown code block, LaTeX \lstlisting).

In the Jupyter model, if we don't know how to make a proper HTML/markdown/latex representation of something, it shouldn't return anything for that format. The code displaying/converting the output has a precedence order of different formats and will always fall back to text if no richer format is available. Pretending that we can generate other formats will mess up that precedence - e.g. if you define a markdown representation for your object, but the HTML representation is the plain text wrapped in `<pre>` tags, you'll see the plain text in the notebook instead of the Markdown, because it prefers HTML format.

**Comment by JanSchulz** [comment]
@flying-sheep Here is a execute_result for a `pandas.DataFrame()`:

```
{'parent_header': {u'username': u'username', u'version': u'5.0', u'msg_type': u'execute_request', u'msg_id': u'8042069a-c9c8-413d-b0e0-c987516105ff', u'session': u'7c4a5b7a-b527-4f66-9ff0-2c743f6c8905', u'date': datetime.datetime(2015, 3, 23, 13, 47, 24, 38000)}, 'msg_type': u'execute_result', 'msg_id': u'403e7b7a-5568-48f0-8eee-667fb4000775', 'content': {u'execution_count': 24, u'data': {u'text/html': u'<div style="max-height:1000px;max-width:1500px;overflow:auto;">\n<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>a</th>\n      <th>b</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td> 1</td>\n      <td> This is longer text</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td> 2</td>\n      <td>                   b</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td> 3</td>\n      <td>                   c</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td> 4</td>\n      <td> This is longer text</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td> 5</td>\n      <td>                   e</td>\n    </tr>\n  </tbody>\n</table>\n</div>', u'text/plain': u'   a                    b\n0  1  This is longer text\n1  2                    b\n2  3                    c\n3  4  This is longer text\n4  5                    e'}, u'metadata': {}}, 'header': {u'username': u'username', u'version': u'5.0', u'msg_type': u'execute_result', u'msg_id': u'403e7b7a-5568-48f0-8eee-667fb4000775', u'session': u'6f06363b-e92c-4859-8ce1-0469be03ff3f', u'date': datetime.datetime(2015, 3, 23, 13, 47, 24, 40000)}, 'buffers': [], 'metadata': {}}
```

-> two mime types under `content.data`: text/html and text/plain.

(this is via 'knitpy --kernel-debug examples/knitpy_overview.pymd` in https://github.com/JanSchulz/knitpy. The "handling" is in `_handle_return_message` in  https://github.com/JanSchulz/knitpy/blob/master/knitpy/knitpy.py#L435 -> knitpy tries the multiple formats until it finds one which it understands. I think the notebook handles it in a similar way)

**Comment by flying-sheep** [comment]
> Pretending that we can generate other formats will mess up that precedence

then the `.default` method should probably return NULL or some other value indicating that there is nothing defined… or even call `stop()`?

**Comment by JanSchulz** [comment]
@flying-sheep "call everything and return what it's got": yes, that's as far as I understood the way the kernel works behind a notebook.

Yes, there is always a plain text representation in the default "execution_result". Only "display_data" (when you send something via `from IPython.core.display import display, HTML;display(HTML("<strong>strong text</strong>"))` will return only the required data. And probably something which will error on `repr(<object>)´.

**Comment by takluyver** [comment]
I think returning NULL makes sense - the Python code returns None to indicate that it's not generating that format.

I think even `display(HTML('...'))` should send a plain text repr, though it might be something useless like `<HTML object at 0xabcdef1234>`. If `repr(foo)` throws an error, I think you'll see the traceback.

**Comment by flying-sheep** [comment]
after starting to write a vignette using knitr, i find that `printr`/`knit_print` isn’t very well thought out.

there’s the options `knitr:::out_format()`, `getOption("knitr.table.format")`, `opts_chunk$render.args$kable$format`, …

then `knit_print` can either return a `asis` object or directly call `print`, so not only there’s no different layers that return and printing representations, respectively, but the only existing layer does both.

---

and @yihui said in yihui/printr#2:

> Sorry, but I don't have the bandwidth to work on that at the moment. I understand a separate lean package can be nice, though.

bottom line: let’s create that lean package with a bunch of generic functions for each output format, every single of them having a equally-named class, let’s rip out the useful parts of printr, and yihui can rebase printr on it as soon as he’s got time again.

it’ll work like this:

```r
library(repr)
obj <- data.frame(...)
class(obj) == 'data.frame'
repr <- repr_html(obj)  # this calls repr_html.data.frame(obj)
class(repr) == 'repr_html'
```

all `repr_*` fucntions will be generic and each `repr_*.default` will return `NULL`. the exception is `repr_text` (which is no generic function):

```r
repr_text = function(x) capture.output(print(x))
```

in IRkernel-land we can do something like

```r
mime_formats = list(
	'text/html'=repr_html,
	'text/latex'=repr_latex,
	'text/x-markdown'=repr_markdown,
	'text/plain'=repr_text)

response$data = list()
for (mime in names(mime_formats)) {
	repr = mime_formats[[mime]](obj)
	if (!is.null(repr))
		response$data[[mime]] = repr
}
```

and everyone wanting a specific format can call the appropriate function

**Comment by flying-sheep** [comment]
more thoughts. we can also provide a repr function that does take a format parameter, and mappings from mimetype or format to the correct `repr_*` function.

```r
mime2repr = list('text/plain' = repr_text, ...)
format2repr = list('text' = repr_text, ...)

repr = function(x, format = 'text') {
    delegate = format2repr[[format]]
    if (is.null(delegate)) stop(sprintf('Repr format %s not known', format))
    delegate(x)
}
```

**Comment by JanSchulz** [comment]
As far as I understand the R code, this looks great. Looking forward to it!

**Comment by takluyver** [comment]
Do you want to do this as part of IRdisplay, or in a new repo? If the latter, what should it be called?

@JanSchulz , would you like to be a collaborator on this?

**Comment by JanSchulz** [comment]
@takluyver thanks, but no: my R isn't good enough for this and I'm more on the consumer side of this problem. If I have anything to add I will do it via PRs, that's easy enough. :-)

**Comment by JanSchulz** [comment]
I think this should go into a new repo ("repr"? Has a nice R feeling :-)), so that other packages can use it without pulling in any jupyter dependencies.

**Comment by flying-sheep** [comment]
i think so, too, but i have zero free time from now to monday…

**Comment by flying-sheep** [comment]
created the skeleton, but it should live in this organization, i think: flying-sheep/repr#1

**Comment by takluyver** [comment]
https://github.com/IRkernel/repr now exists - @flying-sheep , you should have push access.

**Comment by flying-sheep** [comment]
great, thanks.
