### ISSUE TITLE
Question : How to display a dataframe as a searchable table in R jupyter notebook 

### ISSUE THREAD

**Issue by kanekalla** [IRkernel/IRkernel#591]
Can you please suggest a solution to display data frame as a searchable table in jupyter notebook IRkernel.

**Comment by flying-sheep** [comment]
How about this?

http://www.htmlwidgets.org/showcase_datatables.html

If not sufficent, please tell me

**Comment by kanekalla** [comment]
I get the following error when I used it, 


Warning message in instance$preRenderHook(instance):
“It seems your data is too big for client-side DataTables. You may consider server-side processing: https://rstudio.github.io/DT/server.html”ERROR while rich displaying an object: Error in file(file, "rb"): invalid 'description' argument

Traceback:
1. FUN(X[[i]], ...)
2. tryCatch(withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr)) 
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr)) 
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler), error = outer_handler)
3. tryCatchList(expr, classes, parentenv, handlers)
4. tryCatchOne(expr, names, parentenv, handlers[[1L]])
5. doTryCatch(return(expr), name, parentenv, handler)
6. withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr)) 
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr)) 
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler)
7. repr::mime2repr[[mime]](obj)
8. repr_html.htmlwidget(obj)
9. lapply(obj$dependencies, function(dep) {
 .     html <- c()
 .     if (length(dep$script) > 0) {
 .         f <- file.path(dep$src$file, dep$script)
 .         html <- c(html, sprintf("<script src=\"%s\"></script>", 
 .             dataURI(mime = "application/javascript", file = f)))
 .     }
 .     if (length(dep$stylesheet) > 0) {
 .         f <- file.path(dep$src$file, dep$stylesheet)
 .         html <- c(html, sprintf("<link href=\"%s\" rel=\"stylesheet\" />", 
 .             dataURI(mime = "text/css;charset-utf-8", file = f)))
 .     }
 .     paste(html, collapse = "\n")
 . })
10. FUN(X[[i]], ...)
11. sprintf("<link href=\"%s\" rel=\"stylesheet\" />", dataURI(mime = "text/css;charset-utf-8", 
  .     file = f))
12. dataURI(mime = "text/css;charset-utf-8", file = f)
13. file(file, "rb")

**Comment by flying-sheep** [comment]
Come on, you can do better!

The second line of that error gives you a link on how to fix it!

**Comment by kanekalla** [comment]
Thanks for pointing, I did try the shiny implementation :) I am trying to display it locally in a Jupyter notebook.

**Comment by flying-sheep** [comment]
OK, then it’s harder. Someone needs to use the `comm_manager` function in a jupyterlab extension…

https://github.com/IRkernel/IRkernel/blob/master/example-notebooks/Comm_Demo.ipynb

**Comment by robertour** [comment]
I have been trying this in 4 different machines and it does not work. It doesn't output any error in the notebook, only in the javascript console:

```
Warning: Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
TypeError: body is null
     create_output_subarea outputarea.js:418
```
It corresponds to this: https://github.com/jupyter/notebook/blob/6174498ab0c4047aaed81a1bb5aa71b1fd8c842b/notebook/static/notebook/js/outputarea.js#L418

I get the same error with this other library: https://github.com/jrowen/rhandsontable/

I also test here and it didn't work:
https://jupyter.org/try

```
install.library('DT')
library('DT')
datatable(iris, options = list(pageLength = 5))
```

**Comment by flying-sheep** [comment]
Hmm, with a local jupyterlab installation, it should work without problem. Did you try it there or only with https://jupyter.org/try and https://rnotebook.io?

**Comment by robertour** [comment]
Thanks @flying-sheep, I tried two local installations in two different machines. I tried again with a new virtual environment an a from-scratch installation of jupyter (`pip install jupyter`), the problem remains (I am adding the output of `pip freeze` at the end).

I noticed that leaflet as in [this example](https://www.r-bloggers.com/r-htmlwidgets-in-jupyter-notebooks/) work. So, I modified  my code to look like this:

```
library(IRdisplay)
library('DT')

m = datatable(iris, options = list(pageLength = 5))

saveWidget(m, 'demo.html', selfcontained = FALSE)
display_html('<iframe src="demo.html" width=100% height=400></iframe>')
```

It works but it does not place nicely with jupyter. I introduced the `width=100% height=400` to improve the visualization, but it looks crooked:

![grafik](https://user-images.githubusercontent.com/1033512/59670500-58ba6300-91bc-11e9-9b3e-e6d29f583913.png)

Maybe I am missing a library?

```
attrs==19.1.0
backcall==0.1.0
bleach==3.1.0
decorator==4.4.0
defusedxml==0.6.0
entrypoints==0.3
ipykernel==5.1.1
ipython==7.5.0
ipython-genutils==0.2.0
ipywidgets==7.4.2
jedi==0.13.3
Jinja2==2.10.1
jsonschema==3.0.1
jupyter==1.0.0
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-core==4.4.0
MarkupSafe==1.1.1
mistune==0.8.4
nbconvert==5.5.0
nbformat==4.4.0
notebook==5.7.8
pandocfilters==1.4.2
parso==0.4.0
pexpect==4.7.0
pickleshare==0.7.5
prometheus-client==0.7.0
prompt-toolkit==2.0.9
ptyprocess==0.6.0
Pygments==2.4.2
pyrsistent==0.15.2
python-dateutil==2.8.0
pyzmq==18.0.1
qtconsole==4.5.1
Send2Trash==1.5.0
six==1.12.0
terminado==0.8.2
testpath==0.4.2
tornado==6.0.2
traitlets==4.3.2
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.4.2
```

**Comment by flying-sheep** [comment]
Are your IRkernel, IRdisplay, and repr versions up to date?

**Comment by robertour** [comment]
So here are the versions:
```
IRkernel_1.0.1.9000 
IRdisplay_0.7.0.9000 
repr_1.0.1.9000  
```

For some reason, they seem ahead of the ones listed here:
IRKernel (0.7):  https://irkernel.github.io/docs/IRkernel/
IRDisplay(0.4.4): https://irkernel.github.io/docs/IRdisplay/
repr(0.9): https://irkernel.github.io/docs/repr/

In order to obtain the versions, I just executed the following:

```
library('DT')
datatable(iris, options = list(pageLength = 5))
sessionInfo()
```` 

And here is the ouput:

```
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] DT_0.7

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1           magrittr_1.5         uuid_0.1-2          
 [4] xtable_1.8-4         R6_2.4.0             rlang_0.3.4         
 [7] tools_3.4.4          htmltools_0.3.6      crosstalk_1.0.0     
[10] yaml_2.2.0           digest_0.6.19        crayon_1.3.4        
[13] shiny_1.3.2          IRdisplay_0.7.0.9000 repr_1.0.1.9000     
[16] later_0.8.0          base64enc_0.1-3      htmlwidgets_1.3     
[19] promises_1.0.1       IRkernel_1.0.1.9000  evaluate_0.14       
[22] mime_0.6             pbdZMQ_0.3-3         compiler_3.4.4      
[25] pillar_1.4.1         jsonlite_1.6         httpuv_1.5.1        
```

**Comment by robertour** [comment]
So, I tried another package (`RJSplot`) and it works.  The only minor problem is that this package create files in a directory inside the project, but this will solve **my** problem. 

Nevertheless, it might be important to see what is wrong with the DT package, let me know how can I help you reproducing the error.

For those, looking for a solution, you can try this:
```
install.packages('RJSplot')
library('RJSplot')
tables_rjs(swiss, jupyter = TRUE)
```

**Comment by flying-sheep** [comment]
> For some reason, they seem ahead of the ones listed here: https://irkernel.github.io/docs/[…]

ah, sadly those docs are outdated. You seem to have new versions of everything though.

for me, your DT code works fine.

**Comment by richdevboston** [comment]
RJSplot works for me too, but I have the same issue because I need to display the table INSIDE the R JupyteR notebook.   I am using RJSPlot 2.5 in the following environment built this month.

```
Server Information:
You are using Jupyter notebook.

The version of the notebook server is: 6.0.3
The server is running on this version of Python:
Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]

Current Kernel Information:
R version 3.6.2 (2019-12-12)
```

**Comment by raffaem** [comment]
Unfortunately RJSplot seems not to work anymore :(

I keep getting 404 error.

May be it doesn't work with JupyterLab 4?
