### ISSUE TITLE
R kernel doesn't show up in Jupyter

### ISSUE THREAD

**Issue by mdivk** [IRkernel/IRkernel#595]
I installed R kernel through Conda by following the instruction from [Anaconda](https://anaconda.org/r/r-irkernel)
conda install -c r r-irkernel 

From the Web interface I stop and start my server, but still do not see the new R kernel in the Jupyter, below is the kernel list (both the two kernels resides in Anaconda):

> root@cedgedev03 jupyterhub]# jupyter kernelspec list
> Available kernels:
> python2 /opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/ipykernel/resources
> ir /opt/cloudera/parcels/Anaconda/share/jupyter/kernels/ir
> ....
> 

What am I missing here and how do I fix? Thank you very much.

**Comment by flying-sheep** [comment]
you should follow our instructions instead: https://irkernel.github.io/installation/

you’re missing step 2.

**Comment by mdivk** [comment]
Thank you but where do I run the command for step2? I cannot even see the IR kernel, let alone starting a notebook with that kernel.

**Comment by janxkoci** [comment]
Thanks for the link @flying-sheep. Btw after step 3 I get a warning:

```
$ jupyter labextension install @techrah/text-shortcuts
(Deprecated) Installing extensions with the jupyter labextension install command is now deprecated and will be removed in a future major version of JupyterLab.

Users should manage prebuilt extensions with package managers like pip and conda, and extension authors are encouraged to distribute their extensions as prebuilt packages 
```

Consider updating the instructions.

**Comment by flying-sheep** [comment]
hmm, update to what?

- https://github.com/techrah/jupyterext-text-shortcuts/issues/32
- https://github.com/techrah/jupyterext-text-shortcuts/issues/33

Would you like to make a PR with something like this instead? https://github.com/jupyterlab/jupyterlab/issues/10114#issuecomment-821993321
