### ISSUE TITLE
Instructions for installation on current Debian stable don't seem to be correct

### ISSUE THREAD

**Issue by N7DR** [IRkernel/IRkernel#596]
The installations at https://irkernel.github.io/installation/#linux-panel
for Debian say to execute:

sudo apt-get install libzmq3-dev libcurl-openssl1.0-dev libssl-dev

When I do this on the current official release of Debian stable, this happens:

[HN:radio] sudo apt-get install libzmq3-dev libcurl-openssl1.0-dev libssl-dev
[sudo] password for n7dr:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libcurl-openssl1.0-dev
E: Couldn't find any package by glob 'libcurl-openssl1.0-dev'
E: Couldn't find any package by regex 'libcurl-openssl1.0-dev'
[HN:radio]

So I am unsure how to proceed so as to install irkernel on this system.

Looking at the packages available in Debian stable, there is a libcurl4-openssl-dev (which is not installed) but I don't know if that's an adequate replacement for libcurl-openssl1.0-dev.

**Comment by N7DR** [comment]
I think you mean "libcurl4-openssl-dev". The short answer is "No", although it's possible to make a lot more progress:

Installing libcurl4-openssl-dev and then executing (following the instructions at https://irkernel.github.io/installation/#linux-panel):
 install.packages(c('crayon', 'pbdZMQ', 'devtools'))
eventually produces output that says:

------------------------- ANTICONF ERROR ---------------------------
Configuration failed because openssl was not found. Try installing:
 * deb: libssl-dev (Debian, Ubuntu, etc)
 
So I then installed libssl-dev and re-executed:
  install.packages(c('crayon', 'pbdZMQ', 'devtools'))

That appeared to run without error.

Still following the instructions, I then executed:
  devtools::install_github(paste0('IRkernel/', c('repr', 'IRdisplay', 'IRkernel')))

That also seemed to execute correctly.

The last instruction says to execute, within R:
  IRkernel::installspec()

That one fails:
> IRkernel::installspec()
Error in IRkernel::installspec() :
  jupyter-client has to be installed but “jupyter kernelspec --version” exited with code 127.
>

So now I am stuck again... jupyter-client *is* installed (and notebooks for python2 and python3 work fine). So I don't know what to do to actually allow jupyter to see the R kernel :-(

**Comment by flying-sheep** [comment]
the command `jupyter-kernelspec` is in the debian package [jupyter-client](https://packages.debian.org/stretch/jupyter-client). The command `jupyter` is in the package [jupyter-core](https://packages.debian.org/stretch/all/jupyter-core/filelist)

If both packages are installed, it has to work.

**Comment by N7DR** [comment]
Yes; that works after I installed those packages. Thank you very much.

So the instructions should add that the packages jupyter-client and jupyter-core must also be installed.

**Comment by flying-sheep** [comment]
OK, done! Should be visible in a minute
