### ISSUE TITLE
Jupyter IR kernel cant

### ISSUE THREAD

**Issue by guitar58** [IRkernel/IRkernel#599]
I can't start an R kernel in jupyter (python 3 works fine). Get the following error:
/usr/lib/R/bin/R: line 193: /usr/bin/sed:
Turns out that sed is in: /bin/sed

Any suggestions?
Thanks

**Comment by flying-sheep** [comment]
That’s an issue in `/usr/lib/R/bin/R`, i.e. R itself, not IRkernel.

Or alternatively, an issue with your system. Very weird to not have sed there. What Linux distribution do you have? Or do you use OS X?

**Comment by guitar58** [comment]
Thanks for the response. I am using Antix (a debian derivative).
I copied sed to /usr/bin and now the kernel is not crashing.
Thanks for the help.

**Comment by flying-sheep** [comment]
Yeah, that should do no harm at all. No problem!
