### ISSUE TITLE
Unable to install R kernel in Jupyter

### ISSUE THREAD

**Issue by San-Mir** [IRkernel/IRkernel#600]
Hello,

I am using this command to install R kernel for jupyter.

conda install -c r r-irkernel

The installation goes fine almost till the very end, then I get this error message on my Anaconda terminal:

m2w64-speex-1.2rc2   | 593 KB    | ############################################################ | 100%
m2w64-zeromq-4.1.4   | 1.8 MB    | ############################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(502): An error occurred while uninstalling package 'defaults::certifi-2018.8.24-py37_1'.
PermissionError(13, 'Access is denied')
Attempting to roll back.

Rolling back transaction: done

PermissionError(13, 'Access is denied')

Can anyone tell me what is happening? How can I install R kernel for my newly installed Anaconda / Jupyter installation?

**Comment by flying-sheep** [comment]
Please use the official installation instructions on https://irkernel.github.io/installation/#binary-panel or report this to anaconda.
