### ISSUE TITLE
Kernel installs, starts, then never returns output

### ISSUE THREAD

**Issue by CerebralMastication** [IRkernel/IRkernel#601]
I'm installing IRkernel in a Docker image that's based on CentOS. The configuration is a JupyterHub that spawns JupyterLab user image using Docker Spawner (`dockerspawner.SystemUserSpawner`). It's been working great with Python and I added IRkernel a month ago and it seemed to work. Then a week or two ago it stopped working in my test environment. I suspect some sort of compatibility issue with one of the packages which I had not pinned to a version in my dockerfile. However I can't determine what's causing the issue. 

The install of R and IRkernel seems to work without error. I can start R from a command prompt and R shows up as an installed kernel. If I start an R console session I get an R version response. But if I put in an R command it never returns an answer. It just looks like this:

![image](https://user-images.githubusercontent.com/126879/49910948-9aa3ce80-fe52-11e8-8a68-04c1200cd256.png)

Same with a notebook. It just hangs and never returns an answer. From the terminal I can see that R is starting when I fire up the Console session of R. The first `ps aux` below was before starting R Console and the second was after. We can see R is running:

![image](https://user-images.githubusercontent.com/126879/49911430-6204f480-fe54-11e8-9d7f-3f6191a87e27.png)

I suspect that somehow the notebook/console is not able to chat appropriately with the running kernel. How can I debug this and figure out what's up? Debugging Jupyter kernels is a bit of a mystery to me, so any help is appreciated. Thanks for maintaining this project!

**Comment by CerebralMastication** [comment]
I'm trying to determine how to debug this and I'm struggling to figure out how to debug what the kernel is sending back to the in the browser. So forgive me if this is overly verbose but I'm going to dump some debugging info here in case it is of use. 

```
bash-4.2$ jupyter troubleshoot
$PATH:
        /bin
        /sbin
        /bin
        /usr/sbin
        /usr/bin

sys.path:
        /usr/bin
        /usr/lib64/python36.zip
        /usr/lib64/python3.6
        /usr/lib64/python3.6/lib-dynload
        /usr/lib64/python3.6/site-packages
        /usr/lib/python3.6/site-packages

sys.executable:
        /usr/bin/python3.6

sys.version:
        3.6.5 (default, Apr 10 2018, 17:08:37)
        [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

platform.platform():
        Linux-4.9.93-linuxkit-aufs-x86_64-with-centos-7.5.1804-Core

which -a jupyter:
        /bin/jupyter
        /bin/jupyter
        /usr/bin/jupyter

pip list:
        Package           Version
        ----------------- ----------
        alembic           1.0.5
        async-generator   1.10
        backcall          0.1.0
        bleach            3.0.2
        certifi           2018.11.29
        chardet           3.0.4
        decorator         4.3.0
        defusedxml        0.5.0
        entrypoints       0.2.3
        idna              2.8
        ipykernel         5.1.0
        ipython           7.2.0
        ipython-genutils  0.2.0
        jedi              0.13.1
        Jinja2            2.10
        jsonschema        2.6.0
        jupyter-client    5.2.4
        jupyter-core      4.4.0
        jupyterhub        0.9.4
        jupyterlab        0.35.4
        jupyterlab-server 0.2.0
        Mako              1.0.7
        MarkupSafe        1.1.0
        mistune           0.8.4
        nbconvert         5.4.0
        nbformat          4.4.0
        notebook          5.7.2
        pamela            0.3.0
        pandocfilters     1.4.2
        parso             0.3.1
        pexpect           4.6.0
        pickleshare       0.7.5
        pip               18.1
        prometheus-client 0.5.0
        prompt-toolkit    2.0.7
        ptyprocess        0.6.0
        Pygments          2.3.0
        python-dateutil   2.7.5
        python-editor     1.0.3
        python-oauth2     1.1.0
        pyzmq             17.1.2
        requests          2.21.0
        Send2Trash        1.5.0
        setuptools        39.0.1
        six               1.12.0
        SQLAlchemy        1.2.14
        terminado         0.8.1
        testpath          0.4.2
        tornado           5.0
        traitlets         4.3.2
        urllib3           1.24.1
        wcwidth           0.1.7
        webencodings      0.5.1
```

**Comment by CerebralMastication** [comment]
making a little bit of progress. I figured out I was not seeing my user instance logs in the console, I was only seeing the JupyterHub output. So I figured out which container ID was the JupyterLab instance and then ran `docker logs container_id`, `docker logs b1eadf68a8d1` in my case. 

that yielded a bunch of output at the bottom of which is this bit:

```
Error in dev.control(displaylist = "enable") : 
  dev.control() called without an open graphics device
Calls: <Anonymous> ... tryCatch -> tryCatchList -> evaluate -> dev.control
In addition: Warning messages:
1: S3 method 'repr_plotly1.gg' was declared in NAMESPACE but not found 
2: In ok_device(filename, ...) :
  unable to load shared object '/usr/lib64/R/library/grDevices/libs//cairo.so':
  /lib64/libpango-1.0.so.0: undefined symbol: g_log_structured_standard
3: In ok_device(filename, ...) : failed to load cairo DLL
Execution halted
[I 2018-12-13 13:24:36.213 SingleUserLabApp log:158] 200 GET /user/jal/api/contents/?content=1&1544707476189 (jal@172.17.0.1) 3.30ms
[I 2018-12-13 13:24:36.734 SingleUserLabApp restarter:110] KernelRestarter: restarting kernel (1/5), keep random ports
kernel fc521ba5-923f-4521-92d2-70c1651c3046 restarted
[I 2018-12-13 13:24:36.813 SingleUserLabApp log:158] 200 GET /user/jal/api/sessions?1544707476791 (jal@172.17.0.1) 1.71ms
[I 2018-12-13 13:24:36.815 SingleUserLabApp log:158] 200 GET /user/jal/api/terminals?1544707476791 (jal@172.17.0.1) 1.46ms
```
Looks like I have some things to research there.

**Comment by flying-sheep** [comment]
OK, something in your installation is borked. who distributes the docker image? you should file an issue there. maybe this is helpful: https://github.com/ContinuumIO/anaconda-issues/issues/4656

**Comment by CerebralMastication** [comment]
For future time travelers who stumble in here: 

My issue ended up being lack of Cairo and Cairo-devel on my image. Since I am using CentOS, I remedied this by installing R and associated packages this way:

```
RUN yum clean all && \
    yum install -y libXext && \
    yum install -y libXt-devel && \
    yum install -y libXrender && \
    yum install -y cairo-devel && \
    yum install -y cairo
    
RUN yum install -y openssl-devel && \
    yum install -y libcurl-devel && \ 
    yum install -y libssh2-devel && \
    yum install -y libxml2-devel && \
    yum install -y czmq-devel && \ 
    yum install -y R 
```

**Comment by flying-sheep** [comment]
Great! I hope the link I gave helped!

**Comment by CerebralMastication** [comment]
It did indeed. Thank you for taking the time to nudge me that direction. Much appreciated. And thank you for maintaining this project!
