### ISSUE TITLE
Cant install package from github in R studio

### ISSUE THREAD

**Issue by ShrinivasIyer** [IRkernel/IRkernel#603]
Hi Guys,

I am trying to run these lines in R studio and R console both but get this same error everytime -

```
Skipping install of 'cricketdata' from a github remote, the SHA1 (1c4c9e11) has not changed since last install.
  Use `force = TRUE` to force installation_

# install.packages("devtools")
devtools::install_github("ropenscilabs/cricinfo")
```

Any kind of help is appreciated, Thanks,

**Comment by flying-sheep** [comment]
It’s not an error. It’s just an information that “cricketdata” is already installed.

And if that’s not the case, the message tells you how to force it to install it again.

**Comment by ShrinivasIyer** [comment]
Okay thanks. My apologies for posting here.

*Shrinivas Iyer*

*linkedin.com/in/shrinivasiyer <http://linkedin.com/in/shrinivasiyer>*

+91 9515673173

**Comment by flying-sheep** [comment]
no problem! I hope everything works

**Comment by ShrinivasIyer** [comment]
yes things are working fine now, Thanks...

*Shrinivas Iyer*

*linkedin.com/in/shrinivasiyer <http://linkedin.com/in/shrinivasiyer>*

+91 9515673173
