### ISSUE TITLE
Possible HTML syntax problem for displaying `data.frame`

### ISSUE THREAD

**Issue by gaow** [IRkernel/IRkernel#605]
## Problem

After exporting the ipynb file to markdown file and converting that to HTML using `jeklly` I get the following:

![2019-01-07-10-47-33_scrot](https://user-images.githubusercontent.com/917985/50780967-ea1ac600-1269-11e9-93cf-183ac2c665d7.png)

The `thead` line is clearly messed up. After digging into the issue (see https://github.com/choldgraf/jupyter-book/issues/72) we found the culprit is the `scope=col` tag in displaying R data.frame in Jupyter notebook. When modified it to `scope="col"` , `jeklly` is able to properly format it. 

## Reproducing it

Here is a minimal working example:

[mwe-issue605.tar.gz](https://github.com/IRkernel/IRkernel/files/2738082/mwe-issue605.tar.gz)

The `Untitled.ipynb` is a notebook using R kernel. If you open it with plain text editor you see the corresponding HTML code for the table already misses quote around `col`. 

## Software environment

```r
> packageVersion('IRkernel')
[1] ‘0.8.15’
```

```bash
> jupyter notebook --version
5.6.0

```

**Comment by flying-sheep** [comment]
You mean `jekyll`? `<th scope=col>` is valid HTML. Did you report it to them?

**Comment by gaow** [comment]
Thank you @flying-sheep I agree with your assessment in the other ticke thttps://github.com/choldgraf/jupyter-book/issues/72.  For now I added a simple `sed` step to add those quotes, until after the new `kramdown` release. Thank you for the hard work digging into this issue!

**Comment by flying-sheep** [comment]
great! no problem :smile:
