### ISSUE TITLE
I can't install IRkernel properly: exited with code 127 no matter what I do

### ISSUE THREAD

**Issue by ckp95** [IRkernel/IRkernel#608]
I've read through dozens of threads here and at StackOverflow about this problem and nothing there seems to be working for me. I tried installing IRkernel like how the github page says:
```
install.packages('IRkernel')
IRkernel::installspec()
```

Didn't work, got error:

```
Error in IRkernel::installspec() : 
  jupyter-client has to be installed but “jupyter kernelspec --version” exited with code 127.
In addition: Warning message:
In system2("jupyter", c("kernelspec", "--version"), FALSE, FALSE) :
  error in running command
```
Per the answers I read, I have tried

- Running these commands from within an R instance launched from the terminal, rather than RStudio. Didn't work.
- Checking Jupyter kernelspec version:
```
jupyter kernelspec --version
5.2.4
```
- Checking that jupyter and jupyter kernelspec are on my PATH:
```
which jupyter
~/anaconda3/bin/jupyter
which jupyter-kernelspec
~/anaconda3/bin/jupyter-kernelspec
```
- Checking that R knows about the PATH:
```
> Sys.getenv("PATH")
[1] "~/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/us
/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
```

I don't understand why it's not working, I'm at my wits end here. How do I get this kernel to install?

I'm running Manjaro Linux.

**Comment by chriselrod** [comment]
It would be nice if I could just pass a path to `installspec()`:
Hmm. Does R handle `~/` as `/home/[USERNAME]/` correctly?
What if you try the full path?

I defined an alias for jupyter instead of adding it to my path:
```bash
$ jupyter kernelspec --version
5.1.0
$ which jupyter 
alias jupyter='/opt/intel/intelpython3/bin/jupyter'
	/opt/intel/intelpython3/bin/jupyter
```
which gave me the same error:
```R
> IRkernel::installspec()
Error in IRkernel::installspec() : 
  jupyter-client has to be installed but “jupyter kernelspec --version” exited with code 127.
In addition: Warning message:
In system2("jupyter", c("kernelspec", "--version"), FALSE, FALSE) :
  error in running command
```
but it worked as soon as I prepended `/opt/intel/intelpython3/bin` to my path.

**Comment by flying-sheep** [comment]
I think your guess is right! `$PATH` shouldn’t contain a literal `~`. R usually handles `~` at a high level (e.g. in R functions), but I’m pretty sure it doesn’t magically make `$PATH` work with `~` for subprocesses.

Therefore wherever you do `export PATH="~/anaconda3/bin:$PATH"` (`.bashrc`?), change the `~` to `$HOME` and it should work (make sure it’s within single quotes though, `'$HOME/...'` will not expand the variable.

**Comment by ckp95** [comment]
> I think your guess is right! `$PATH` shouldn’t contain a literal `~`. R usually handles `~` at a high level (e.g. in R functions), but I’m pretty sure it doesn’t magically make `$PATH` work with `~` for subprocesses.
> 
> Therefore wherever you do `export PATH="~/anaconda3/bin:$PATH"` (`.bashrc`?), change the `~` to `$HOME` and it should work (make sure it’s within single quotes though, `'$HOME/...'` will not expand the variable.)

Ayyy this worked perfectly, thanks! I didn't know using the tilde in PATH exports could break things, good to know.

**Comment by flying-sheep** [comment]
perfect!
