### ISSUE TITLE
IRkernel does not start on ubuntu 16.04

### ISSUE THREAD

**Issue by HenrikEckermann** [IRkernel/IRkernel#611]
I encounter the following error while trying to work in IRKernel on my ubuntu server:

It worked fine for many times. Now I did not connect to my server for a while and ran some updates (sudo apt-get update and upgrade).

```
 *** caught illegal operation ***
address 0x7f25a68863aa, cause 'illegal operand'

Traceback:
 1: zmq.socket(zmqctx, .pbd_env$ZMQ.ST$PUB)
 2: .Object$initialize(...)
 3: initialize(value, ...)
 4: initialize(value, ...)
 5: methods::new(def, ...)
 6: Kernel$new(connection_file = connection_file)
 7: IRkernel::main()
An irrecoverable exception occurred. R is aborting now ...
[W 13:06:20.644 NotebookApp] KernelRestarter: restart failed
[W 13:06:20.644 NotebookApp] Kernel 8c8e33db-8ec7-4454-954c-ae62c3d4edd3 died, removing from map.
``` 

I tried reinstalling everything using newest anaconda and newest R for Ubuntu etc... Does not work.

Any help would be apprecieated.

**Comment by flying-sheep** [comment]
When you created this issue, the very first item in the template that you deleted was 

> - [ ] Did you follow the [official installation instructions](https://irkernel.github.io/installation/)?
> 
>     If you have an installation problem and used e.g. Anaconda, please report your issue to them instead.

You should have read and followed it instead.

Please try installing IRkernel with our install instructions or report your issue to anaconda, thank you

**Comment by HenrikEckermann** [comment]
That might have been misleading but I do not use Anaconda R and also followed your installation instructions. The only piece I use from Anaconda is Jupyter notebook. But The R distribution incl. IRKernel is independent of Anaconda on my system.

**Comment by flying-sheep** [comment]
Ah! then I misunderstood your “reinstalling everything using newest anaconda”: You just referred to Jupyter.

Hmm, sounds like a problem with `pbdZMQ`. Could you try to reinstall that lib?

**Comment by HenrikEckermann** [comment]
I don't know why but yeah....that works :D 
Thank you!

**Comment by flying-sheep** [comment]
Well, I guess you did a system update in which libzmq.so was updated, and pbdZMQ had to be recompiled to work with the new library version.
