### ISSUE TITLE
How to comment uncomment lines ?

### ISSUE THREAD

**Issue by MichWeb75** [IRkernel/IRkernel#612]
I want to comment / uncomment lines with [Shift][Ctrl] + C in my IRKernel Jupyter notebooks. How can I configure this ? Thanks for your help!

**Comment by flying-sheep** [comment]
Are you using Jupyter lab or Jupyter notebook?

In lab, you can configure shortcuts yourself I think.

**Comment by MichWeb75** [comment]
Thanks for your help. There are Settings -> Keyboard Shortcuts -> System Defaults can be changed but I cannot find any comment / uncomment shortcut here. The default [Ctrl] + [/] does not work here

**Comment by flying-sheep** [comment]
well, you’re better off reporting this to jupyterlab or codemirror then. background:

1. jupyterlab uses codemirror for its code cells.
2. codemirror has its own keyboard shortcuts by default, but jupyterlab integrates it into its own shortcut system (this integration could be broken, resulting in this bug)
3. each cell contains one editor set to a mode. R mode definitely is selected for R cells, so there’s no bug here.
4. what characters are actually inserted depends on the mode of the code cell, and if the comment extension is loaded. (the [line comment char is defined](https://github.com/codemirror/CodeMirror/blob/863d5e42f00d8d74542de072acfbbc218ef5127d/mode/r/r.js#L184), so maybe the comment extension isn’t loaded? but it works in other languages, doesn’t it?)
