### ISSUE TITLE
Pandoc source path to jupyter notebook for plotly (jupyter lab)

### ISSUE THREAD

**Issue by kanekalla** [IRkernel/IRkernel#613]
Hi Folks,

I am trying to use plotly in jupyter lab.
I have installed pandoc as mentioend in plotly webpage.
Can anyone suggest how do I need to keep pnadoc source files in irkernel ?

When I plot a plotly plot,nothing is plotted.

**Comment by flying-sheep** [comment]
you deleted the issue template. don’t do that. please answer the questions.

**Comment by kanekalla** [comment]
Before submitting an issue please be sure to answer these questions with **yes**:

- [ ] Did you follow the [official installation instructions](https://irkernel.github.io/installation/)?
**yes**
    If you have an installation problem, a segfault, `caught illegal operation`, `cannot open shared object file`,  …
    and installed IRkernel using Anaconda, please report your issue to them instead.
**I have a classical installation**
- [ ] Did you reproduce the error with the newest versions? If the following code installs packages, you didn’t yet!
**I have latest version of packages**
    ```r
    old_pkgs <- intersect(old.packages()[, 'Package'], c('IRkernel', 'IRdisplay', 'repr'))
    if (length(old_pkgs) > 0) install.packages(old_pkgs)
    ```

- [ ] Did you include a [minimal reproducible example](https://stackoverflow.com/a/5963610/247482)?

p <- plot_ly(ggplot2::diamonds, y = ~price, color = ~cut, type = "box")
p
- [ ] Is this the right repository?
**yes**
    If the way a value is displayed is ugly or you got `ERROR while rich displaying an object`,
    go to [IRkernel/repr/issues/new](https://github.com/IRkernel/repr/issues/new) instead.
**no, I don't get any output**

**Comment by flying-sheep** [comment]
Cannot reproduce. With the newest version of everything, the code you posted gives me output:

```py
library(plotly)  # you forgot this
p <- plot_ly(ggplot2::diamonds, y = ~price, color = ~cut, type = "box")
p
```

**Comment by kanekalla** [comment]
Was it in Jupyter notebook /Jupyter Lab ?

**Comment by flying-sheep** [comment]
I tried both

**Comment by kanekalla** [comment]
Thank you for testing !!
