### ISSUE TITLE
tibble displays all rows instead of first 10

### ISSUE THREAD

**Issue by aguang** [IRkernel/IRkernel#614]
Before submitting an issue please be sure to answer these questions with **yes**:

- [x] Did you follow the [official installation instructions](https://irkernel.github.io/installation/)?

    If you have an installation problem, a segfault, `caught illegal operation`, `cannot open shared object file`,  …
    and installed IRkernel using Anaconda, please report your issue to them instead.

- [x] Did you reproduce the error with the newest versions? If the following code installs packages, you didn’t yet!

    ```r
    old_pkgs <- intersect(old.packages()[, 'Package'], c('IRkernel', 'IRdisplay', 'repr'))
    if (length(old_pkgs) > 0) install.packages(old_pkgs)
    ```

- [x] Did you include a [minimal reproducible example](https://stackoverflow.com/a/5963610/247482)?
- [x] Is this the right repository?

    If the way a value is displayed is ugly or you got `ERROR while rich displaying an object`,
    go to [IRkernel/repr/issues/new](https://github.com/IRkernel/repr/issues/new) instead.

When I try to print out tibbles in Jupyter notebook, I end up with all of the rows printed instead of the first 10. In other words, tibbles have the same behavior as regular data frames. I am not sure if this is the intended behavior since the tibble is formatted, but I would prefer if the tibble print out was truncated according to how tibble was designed, since they can be quite large, and also I find providing the dimensions and types of the columns in the tibble useful to see.

Reproducible example:
```{r}
library(tibble)
mtcars
as_tibble(mtcars)
```

**Comment by flying-sheep** [comment]
That’s intended behavior. You can either change the behavior just for `tbl_df`:

```r
repr_html.tbl_df <- function(obj, ..., rows = 10) repr:::repr_html.data.frame(obj, ..., rows = rows)
tibble::as_tibble(iris)
```

or for all `data.frame`s:

```r
options(repr.matrix.max.rows = 10)
tibble::as_tibble(iris)
```
```

**Comment by flying-sheep** [comment]
But I’ve thought about showing the types per column (for all data frames).

Could you please create a new issue asking for that specifically? (you don’t need to retain the issue template for feature requests. I should add this to the issue template.)
