### ISSUE TITLE
Can't install IRkernel within a conda environment

### ISSUE THREAD

**Issue by rbavery** [IRkernel/IRkernel#615]
Before submitting an issue please be sure to answer these questions with **yes**:

- [ ] Did you follow the [official installation instructions](https://irkernel.github.io/installation/)?

    If you have an installation problem, a segfault, `caught illegal operation`, `cannot open shared object file`,  …
    and installed IRkernel using Anaconda, please report your issue to them instead.

**yes**

- [ ] Did you reproduce the error with the newest versions? If the following code installs packages, you didn’t yet!
**yes**
    ```r
    old_pkgs <- intersect(old.packages()[, 'Package'], c('IRkernel', 'IRdisplay', 'repr'))
    if (length(old_pkgs) > 0) install.packages(old_pkgs)
    ```

- [ ] Did you include a [minimal reproducible example](https://stackoverflow.com/a/5963610/247482)?

This might not be totally reproducible since I am on a Jupyterhub instance.
on fedora 29 run the following
```
conda create -n r-essentials -c r r-essentials r-base
source activate r-essentials
R
```
in R console (use which R to confirm you are using the conda env R)
```
install.packages('IRkernel')
IRkernel::installspec()
```
check kernel specs, there is no kernel for R in the environment.

```
(r-essentials) bash-4.4$ jupyter kernelspec list
Available kernels:
  geo        /home/rave/.local/share/jupyter/kernels/geo
  ir         /home/rave/.local/share/jupyter/kernels/ir
  python3    /home/rave/miniconda3/envs/r-essentials/share/jupyter/kernels/python3
```

and furthermore the R kernel that does exist after these steps dies when trying to load libraries, see this github issue: https://github.com/jupyter/jupyter/issues/397

- [ ] Is this the right repository?
    **I think so since following the installation instructions but let me know if installing into a conda environment is the issue. Otherwise should I post this to anaconda/conda?**

    If the way a value is displayed is ugly or you got `ERROR while rich displaying an object`,
    go to [IRkernel/repr/issues/new](https://github.com/IRkernel/repr/issues/new) instead.

**Comment by flying-sheep** [comment]
Hi! I’m sorry but you didn’t read the first item! It says:

> **If you have an installation problem**, a segfault, `caught illegal operation`, `cannot open shared object file`,  … **and installed IRkernel using Anaconda**, please report your issue to them instead.

So please do this instead.

**Comment by rbavery** [comment]
Thanks for checking this out @flying-sheep, if anyone feels like there is an easy fix that can go into `IRkernel::installspec` I can try to help with testing on my end.
