### ISSUE TITLE
some errors issued while running jupyter with IRkernel

### ISSUE THREAD

**Issue by brdauria** [IRkernel/IRkernel#616]
Hi,
I have JupyterLab and Jupyter installed on an Ubuntu server and I have various kernels, among them IRkernel.

They all work, IRkernel included. But now I was trying to execute `jupyter` commands by bash and I found out that some hidden errors are sent to stderr that are quite annoying.

I do not know which information you need to help me get rid of this error messages. 
I'm copying here my command and what I get.

```bash
jupyter console --kernel=ir  
R_zmq_setsockopt errno: 22 strerror: Invalid argument
R_zmq_setsockopt errno: 22 strerror: Invalid argument
R_zmq_setsockopt errno: 22 strerror: Invalid argument
Jupyter console 6.0.0

R version 3.4.4 (2018-03-15)
```
- [X] Did you follow the [official installation instructions](https://irkernel.github.io/installation/)? **yes**
- [X] Did you reproduce the error with the newest versions? **yes**. To be sure I installed IRKernel now again by using the _github_ version. No change detected in the output.
- [X] Did you include a [minimal reproducible example](https://stackoverflow.com/a/5963610/247482)? I actually do not know how to reproduce this on another machine. Here it is a copy of the `sessioninfo()`output
```r
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.18.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.4.4       IRdisplay_0.7.0      pbdZMQ_0.3-3        
 [4] tools_3.4.4          htmltools_0.3.6      base64enc_0.1-3     
 [7] crayon_1.3.4         Rcpp_1.0.0           uuid_0.1-2          
[10] IRkernel_0.8.15.9000 jsonlite_1.6         digest_0.6.18       
[13] repr_0.19.2          evaluate_0.13   
```
- [X] Is this the right repository? **yes**

**Comment by flying-sheep** [comment]
please make sure to tick all the boxes in the issue template instead of deleting it

**Comment by brdauria** [comment]
Hi, I modified my *Issue* by ticking all the boxes in the issue template.

**Comment by flying-sheep** [comment]
OK, so [`R_zmq_setsockopt`](https://github.com/cran/pbdZMQ/blob/8c2c54eb1eb12759a0b1ca5f83ebd1a4e63a8ab9/src/R_zmq_socket.c#L100-L135) only gets called here:

https://github.com/IRkernel/IRkernel/blob/97c492b2e55b9fa556019d4b8625318614c9db87/R/kernel.r#L389-L392

Which refers to #508. The option `ZMQ_ROUTER_HANDOVER` is documented [here](http://api.zeromq.org/4-1:zmq-setsockopt#toc35), and the function seems to be used correctly: The control, stdin, and shell sockets are all ROUTER sockets, and I pass an integer that’s in {0, 1}.

No idea what could be going wrong.
