### ISSUE TITLE
Feature idea (maybe too farfetched)

### ISSUE THREAD

**Issue by jonrobinson2** [IRkernel/IRkernel#62]
Am curious if there is at any point any way/plan to convert R scripts to iPython Notebooks with the R kernel. Similar to how one can transform a .py file into a .ipynb file like so:

```python
import IPython.nbformat.current as nbf
nb = nbf.read(open('test.py', 'r'), 'py')
nbf.write(nb, open('test.ipynb', 'w'), 'ipynb')
```
Is this farfetched? Seems like it would be a great way to increase adoption.

**Comment by takluyver** [comment]
We're actually cutting that feature out of IPython, but it should be easy
to do separately. See also https://github.com/aaren/notedown for R markdown
to ipynb conversion.

**Comment by jonrobinson2** [comment]
Why is that feature getting cut out of IPython?

**Comment by takluyver** [comment]
We had originally planned that notebooks should have different storage
formats - json, XML, py - but we decided that was a bad idea, and we'd just
do json. It's still very easy to write code to turn a script into a
notebook.

**Comment by jonrobinson2** [comment]
Makes sense, just curious. Thought filing the issue here would be relatively appropriate

**Comment by flying-sheep** [comment]
ok, so i guess this is wontfix then?
