### ISSUE TITLE
Add `env` parameter to `installspec`

### ISSUE THREAD

**Issue by hhoeflin** [IRkernel/IRkernel#620]
Hi,

I wanted to ask for a feature. Currently in installspec, there is only the option to point to an .Rprofile. I wanted to ask if there could also be the option to add a script that could be sourced before the R-kernel is even started, in order to set certain environment variables that R may need (e.g. pointer to necessary libraries).

Thanks

**Comment by flying-sheep** [comment]
You could manually edit the [`kernel.json`](https://jupyter-client.readthedocs.io/en/stable/kernels.html#kernel-specs) it created, and add the `env` key there.

    ~/.local/share/jupyter/kernels/ir/kernel.json

**Comment by hhoeflin** [comment]
Hi,

Thank you for the response and that is the solution I came up with so far.
But I regularly create new kernels and I thought it would be a nice feature
instead of a manual process.

Best

Holger

**Comment by flying-sheep** [comment]
So you’d like the installspec function to be able to do that? Fair enough!

**Comment by hhoeflin** [comment]
yep exactly :)

**Comment by flying-sheep** [comment]
Do you want to do a PR? I detailed the (little) necessary work above

**Comment by hhoeflin** [comment]
I can do that - hopefully soon-ish.

**Comment by flying-sheep** [comment]
If not, just say a word, it shouldn’t be too much work for me either.

**Comment by Skellyboy38** [comment]
I'm not sure if this is related, but there is a feature in the IPython kernel that allows you to execute lines of python code right after the kernel starts. It would be really useful to have a similar function in the IRkernel (to import libraries behind the scenes, so users don't have to every time). 


![image](https://user-images.githubusercontent.com/8304839/67320958-ec8a9b80-f4dc-11e9-9627-d912982b465a.png)


Relevant IPython documentation:
https://ipython.org/ipython-doc/rel-0.13.2/config/ipython.html

**Comment by flying-sheep** [comment]
See https://github.com/IRkernel/IRkernel/issues/472#issuecomment-298418347

**Comment by jwclark** [comment]
I have a different use case but the original title of this ticket is relevant. If we could pass arbitrary environment variables like we can with `ipykernel install --env ENV VALUE` that would be pretty beneficial.

**Comment by flying-sheep** [comment]
This would be exactly the PR described here, no? https://github.com/IRkernel/IRkernel/issues/620#issuecomment-472785620

**Comment by jwclark** [comment]
> 

My R is a bit rough, but yes that looks like it would

**Comment by Frank-Steiner** [comment]
Hi,
any chance this gets implemented...? It would indeed be useful.
cu,
Frank
