### ISSUE TITLE
Running it in Hydrogen -> Remote Kernel -> IRKernel

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [IRkernel/IRkernel#622]
I'm stuck with this since more than two days now..

All kernelspecs i have on my server work perfectly. Only one not wanting to start is R
Jupyter notebook recognizes R on the server.
When I try to run a script on my local computer, I can't connect to the notebook using IRKernel.

I get:  No Kernel Specs Available

**Comment by flying-sheep** [comment]
All good?
