### ISSUE TITLE
jupyter 1.0.0 doesn't provide `jupyter` exectuable

### ISSUE THREAD

**Issue by dongzhuoer** [IRkernel/IRkernel#623]
I install IRkernel CRAN release (0.8.15), but `IRkernel::installspec()` doesn't work.

I find that jupyter 1.0.0 provides `jupyter-kernelspec`, `jupyter-notebook`, etc instead of `jupyter`.

Then I replace all 

```r
system2('jupyter', c('kernelspec', ...')
```

with 

```r
system2('jupyter-kernelspec', c(...))
``` 

, rebuilt the R package, and it does work.

**Comment by flying-sheep** [comment]
What is “jupyter 1.0.0”? a debian package? a pip-installed wheel?

**Comment by dongzhuoer** [comment]
A pip-installed wheel, I use `pip3 install --user jupyter`

**Comment by flying-sheep** [comment]
jupyter depends on jupyter_core, which has the script.

It should be installed into `~/.local/bin` which you have to add to your $PATH.

**Comment by dongzhuoer** [comment]
Thanks for your patient explanation.

I try `pip3 install --user --force-reinstall jupyter`, then `jupyter` does exist in `~/.local/bin`. Maybe there are some problems with my former installation.

**Comment by flying-sheep** [comment]
No problem, I’m happy to help!
