### ISSUE TITLE
R Kernel loads but doesn't connect to jupyter

### ISSUE THREAD

**Issue by pmeiners** [IRkernel/IRkernel#631]
Hello,
I installed the IRkernel following the instructions here: https://irkernel.github.io/installation/ 
However, in the jupyter notebook, the connection with the R kernel fails. 
Trying 
`jupyter console --kernel=ir`
gives the error message, that the package 'digest' is missing.
What went wrong here? Thanks for your help.

**Comment by flying-sheep** [comment]
did you install that package? maybe `install.packages` failed to install everything right.

the only other thing I can think of is that the wrong R binary is used.

execute `jupyter kernelspec list` and find the path for `ir`, for me that’s `/home/angerer/.local/share/jupyter/kernels/ir`. in that directory, open `kernel.json` and check with R is used. you should be able to import `IRkernel` from that R binary.

**Comment by noori11** [comment]
I can see the JSON file. But it only contains this: 
{"argv": ["R", "--slave", "-e", "IRkernel::main()", "--args", "{connection_file}"],
 "display_name":"R",
 "language":"R"
}

Could I maybe just reinstall R in anaconda?

**Comment by flying-sheep** [comment]
no, just replace `["R",` with `["C:\\path\\to\\R.exe",` or  `["/path/to/R",` (depending on your OS and of course with the real path)
