### ISSUE TITLE
The default packages was not found - they do not exists in the path. Any way to download them? 

### ISSUE THREAD

**Issue by noori11** [IRkernel/IRkernel#632]
To access the notebook, open this file in a browser:
        file:///C:/Users/Admin/AppData/Roaming/jupyter/runtime/nbserver-9304-open.html
    Or copy and paste one of these URLs:
        http://localhost:8891/?token=c44d7d8b396ea17a9a28dc42bca0b1bb327eb099a0ff8255
[I 15:41:13.260 NotebookApp] Kernel started: 5a6fa57b-e9b8-43db-a42a-1f87ded007f9
During startup - Advarselsbeskeder:
1: package 'grDevices' in options("defaultPackages") was not found
2: package 'graphics' in options("defaultPackages") was not found
3: package 'stats' in options("defaultPackages") was not found
Fejl: pakke 'grDevices' har ikke et navnerum
K°rsel stoppet
[I 15:41:16.134 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
During startup - Advarselsbeskeder:
1: package 'grDevices' in options("defaultPackages") was not found
2: package 'graphics' in options("defaultPackages") was not found
3: package 'stats' in options("defaultPackages") was not found
Fejl: pakke 'grDevices' har ikke et navnerum
K°rsel stoppet

**Comment by flying-sheep** [comment]
This is one of the many issues caused by a weird R installation. See my comments in e.g. #631
