### ISSUE TITLE
Capture output once browser tab is closed and code is still running

### ISSUE THREAD

**Issue by orr161** [IRkernel/IRkernel#633]
Is there a way to capture and store the output while code is still running but the browser tab is closed? 

In IPython it is done by the magic line %%capture output, then one can run time consuming code, and when back run output.show(). Is there any way around this issue in IRkernel?

Thank you!

**Comment by flying-sheep** [comment]
Yes, plain old [`output <- capture.output({ code })`](https://stat.ethz.ch/R-manual/R-devel/library/utils/html/capture.output.html) will do the trick.

**Comment by orr161** [comment]
thanks
