### ISSUE TITLE
Syntax Highlighting and Saving as Rscript Not Working For New Notebooks in Jupyterlab 1.0.1

### ISSUE THREAD

**Issue by groverj3** [IRkernel/IRkernel#635]
Before submitting an issue please be sure to answer these questions with **yes**:

- [x] Did you follow the [official installation instructions](https://irkernel.github.io/installation/)?

    If you have an installation problem, a segfault, `caught illegal operation`, `cannot open shared object file`,  …
    and installed IRkernel using Anaconda, please report your issue to them instead.

- [x] Did you reproduce the error with the newest versions? If the following code installs packages, you didn’t yet!

    ```r
    old_pkgs <- intersect(old.packages()[, 'Package'], c('IRkernel', 'IRdisplay', 'repr'))
    if (length(old_pkgs) > 0) install.packages(old_pkgs)
    ```

- [x] Did you include a [minimal reproducible example](https://stackoverflow.com/a/5963610/247482)?
- [x] Is this the right repository?

    If the way a value is displayed is ugly or you got `ERROR while rich displaying an object`,
    go to [IRkernel/repr/issues/new](https://github.com/IRkernel/repr/issues/new) instead.

## Issue

Title says it all. No syntax highlighting in latest jupyterlab when a new notebook is created. However, if saved and reopened highlighting shows up as expected. No such problem with the default Python kernel. No issue with the old notebook UI.

New Notebook
![image](https://user-images.githubusercontent.com/10768175/60564364-370cc000-9d14-11e9-9782-cf2f2df570bc.png)

Saved Notebook
![image](https://user-images.githubusercontent.com/10768175/60564333-1ba1b500-9d14-11e9-96c5-d3c4f4a4f600.png)

Exporting notebooks as executable scripts results in a .txt extension for the new notebook and a .r extension for an existing re-opened notebook.
![image](https://user-images.githubusercontent.com/10768175/60564477-a5518280-9d14-11e9-8ef0-8ecccad932c1.png)

This is on both Ubuntu Server 18.04LTS and an up-to-date Manjaro Linux.

**Comment by flying-sheep** [comment]
This very much looks like a jupyterlab bug. Did you report it there?

The Python kernel and mine look very very similar:

```json
{
 "argv": ["python", "-m", "ipykernel_launcher", "-f", "{connection_file}"],
 "display_name": "Python 3",
 "language": "python"
}
```

```json
{
  "argv": ["/usr/lib64/R/bin/R", "--slave", "-e", "IRkernel::main()", "--args", "{connection_file}"],
  "display_name": "R",
  "language": "R"
}
```

**Comment by groverj3** [comment]
I can report it there as well. I wasn't sure where was best since it only affected the R kernel, but also the jupyterlab interface.

**Comment by flying-sheep** [comment]
Well, did you try with other language kernels than the builtin python one?

**Comment by groverj3** [comment]
I take back what I said about it always recognizing previously saved notebooks. Even those are not consistently recognized. I'll try out another kernel. If the problem persists I'll open an issue with jupyterlab itself.

**Comment by groverj3** [comment]
This is not an issue with the BASH kernel from what I can tell, it seems to highlight syntax as expected. But the Julia kernel is affected. Though, I've never used Julia so the fact that syntax highlighting should be working there I am taking on faith from a google image search. I'll open an issue with Jupyterlab as well.

**Comment by krassowski** [comment]
I commented in the JupyterLab thread and pinged the author of the changes underlying the issues.

It originates from an unmet assumption that all kernel replies carry a status field, and in here, the response to `kernel_info_request` is rejected as it does not have one (see https://github.com/jupyterlab/jupyterlab/commit/726ce5e19dc141a5d3a7b45f89299d57218b5709).

A hotfix on the IRkernel side would be to add a status message in here: https://github.com/IRkernel/IRkernel/blob/9134e35e59903972355aedd7d88cb84849840181/R/kernel.r#L308-L322 although, maybe there will be a change on JL side (as many kernels are affected).

**Comment by flying-sheep** [comment]
Great, thanks! I’ll wait for the [spec](https://jupyter-client.readthedocs.io/en/stable/messaging.html#kernel-info) to actually mention this field before I accept a PR to circumvent the jupyterlab bug.

**Comment by flying-sheep** [comment]
Ah, the specs actually say that [“All reply messages have a `'status'` field”](https://jupyter-client.readthedocs.io/en/stable/messaging.html#request-reply) which means this is a IRkernel bug.

**Comment by flying-sheep** [comment]
Since the specs are a bit vague, I made a PR: can anyone confirm that #636 is correct?

**Comment by KrisDavie** [comment]
Hey, I just want to add that we were having an issue with our JupyterHub (running JupyterLab 1.0.1) causing our Apache server to run out of connections before this fix. JupyterLab was constantly establishing new websockets because it didn't get a status from the kernel, but the old conenctions were being left open with Apache labelling them as "Sending Reply". Eventually leading to our webserver running out of available connections and preventing access to anything hosted there.

Installing the github version through devtools has solved this, but given the severity of this, may I suggesting putting out a new version via CRAN?, especially given that JupyterLab is now released and others may run into this issue.

**Comment by flying-sheep** [comment]
Sure, done! 1.0.2 incoming
