### ISSUE TITLE
I have installed R kernel for Microsoft R open successfully，however jupyter indicates there is no kernel

### ISSUE THREAD

**Issue by Whale-fall** [IRkernel/IRkernel#638]
I have installed R kernel for MRO 3.5.3 , when I open jupyter it indicates that No kernel or kernel dead like this one 
![Snipaste_2019-08-22_13-08-47](https://user-images.githubusercontent.com/22662209/63487509-21c73d00-c4de-11e9-8a06-49ba17c9e67a.png)

on the other hand, I installed kernel for R 3.6 too, it did work:
![Snipaste_2019-08-22_13-11-17](https://user-images.githubusercontent.com/22662209/63487565-5fc46100-c4de-11e9-8bc8-cdee3ab63a5b.png)

I checked the location of kernels, it seems correct, so what can I do to fix it 
![Snipaste_2019-08-22_13-13-27](https://user-images.githubusercontent.com/22662209/63487651-add96480-c4de-11e9-9e93-036d81b840ac.png)
![Snipaste_2019-08-22_13-14-25](https://user-images.githubusercontent.com/22662209/63487688-cc3f6000-c4de-11e9-9a89-db5c12fa7309.png)

**Comment by flying-sheep** [comment]
What’s the console output for the kernel that fails to start?

**Comment by Whale-fall** [comment]
There is no output like this：
![Snipaste_2019-08-22_18-02-01](https://user-images.githubusercontent.com/22662209/63505904-fc025e00-c506-11e9-8ca3-24a7271f87f5.png)
Do you need other information?

**Comment by flying-sheep** [comment]
Yes, the error message is the console where you started jupyterlab. If you didn’t start it by console somehow, you need to start a new jupyterlab from a console and paste the error message from there.

**Comment by Whale-fall** [comment]
got it :
![Snipaste_2019-08-22_18-16-53](https://user-images.githubusercontent.com/22662209/63506915-1c331c80-c509-11e9-8fb4-91569e482833.png)
![Snipaste_2019-08-22_18-17-11](https://user-images.githubusercontent.com/22662209/63506917-1ccbb300-c509-11e9-8ded-7fd354ceed4a.png)
I got message above

**Comment by flying-sheep** [comment]
For the future: please paste text as text instead of screenshots.

You have this problem: https://github.com/IRkernel/IRkernel/issues/627#issuecomment-490038014
