### ISSUE TITLE
DESCRIPTION: Add URL and BugReports field

### ISSUE THREAD

**Issue by HenrikBengtsson** [IRkernel/IRkernel#639]
Hi. It's not clear that this repos is the official repository for CRAN package [IRkernel](https://cran.r-project.org/package=IRkernel). Please consider adding

```
URL: https://irkernel.github.io
BugReports: https://github.com/IRkernel/IRkernel/issues/
```
to the DESCRIPTION file.  Those links will then also appear on https://cran.r-project.org/package=IRkernel

**Comment by flying-sheep** [comment]
Thank you!
