### ISSUE TITLE
I can't seem to install IRkernel no matter what I do

### ISSUE THREAD

**Issue by ptr-64** [IRkernel/IRkernel#640]
Hello, 
I had to reinstall my OS (Manjaro-GNOME) and I set up my anaconda environment. I then installed R from the Arch repository and ran r form the terminal and followed the [full instructions here](https://irkernel.github.io/installation/#linux-panel) as best as I could. But every time try step 2 I get the following message 

```
Error in loadNamespace(name) : there is no package called ‘IRkernel’
```

and when I tried to look at the installed kernels via ` jupyter kernelspec list` I get the following:
```
Available kernels:
  julia-1.2    /home/peter/.local/share/jupyter/kernels/julia-1.2
  python3      /home/peter/anaconda3/share/jupyter/kernels/python3

```
So apparently the kernel doesn't get installed via
 ```
$ R  
> install.packages('IRkernel')
```

I have no idea what I could be doing wrong- In my old OS I followed the same procedures and everything worked out of the box.

**Comment by flying-sheep** [comment]
Well, step 1 installs the “IRkernel” package, step 2 installs the kernelspec that makes the kernel visible to Jupyter.

When you do `install.packages('IRkernel')` it should install the package to a library accessible from the R interpreter you ran that code in. If you try to run `IRkernel::installspec()` and it says “there is no package called ‘IRkernel’”, then you didn’t install the package to the R package library used by the R interpreter you’re executing that line of code in.

So you didn’t do steps 1 and 2 in the same interpreter.
