### ISSUE TITLE
Jupyter Notebook R can't connect to kernel

### ISSUE THREAD

**Issue by JohanyDufour** [IRkernel/IRkernel#641]
Hi, 
I installed Anaconda Navigator and r-base and r-essentials packages and then launched Jupyter. I can create a R Notebook, but I can't get a line of code to execute because it can't connect to kernel. An error keeps coming back (see attached file). 
Also, when I launch the jupyter application from the Navigator, I get the Following error :

```
 [W 11:46:57.407 NotebookApp] Terminals not available (error was DLL load failed: %1 n’est pas une application Win32 valide.)
[I 11:46:57.475 NotebookApp] JupyterLab extension loaded from C:\Users\Johany\Anaconda3\lib\site-packages\jupyterlab
[I 11:46:57.476 NotebookApp] JupyterLab application directory is C:\Users\Johany\Anaconda3\share\jupyter\lab
[I 11:46:57.479 NotebookApp] Serving notebooks from local directory: C:\Users\Johany
[I 11:46:57.479 NotebookApp] The Jupyter Notebook is running at:
[I 11:46:57.480 NotebookApp] http://localhost:8888/?token=93985860077ae5bc4ed32573ebc5fe5b13714646469a7f03
[I 11:46:57.483 NotebookApp] or http://127.0.0.1:8888/?token=93985860077ae5bc4ed32573ebc5fe5b13714646469a7f03
[I 11:46:57.484 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 11:46:57.590 NotebookApp]

To access the notebook, open this file in a browser:
file:///C:/Users/Johany/AppData/Roaming/jupyter/runtime/nbserver-11428-open.html
Or copy and paste one of these URLs:
http://localhost:8888/?token=93985860077ae5bc4ed32573ebc5fe5b13714646469a7f03
or http://127.0.0.1:8888/?token=93985860077ae5bc4ed32573ebc5fe5b13714646469a7f03
[E 11:47:00.223 NotebookApp] Could not open static file ''
[W 11:47:00.280 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (::1) 23.00ms referer=http://localhost:8888/tree?token=93985860077ae5bc4ed32573ebc5fe5b13714646469a7f03
```

What is weird is that if I change the kernel to Python3, the kernel connects and I can run the code. 
I tried to uninstall Anaconda Navigator, then re-install it, but it didn't do anything. 
I installed R Studio on the Navigator and it works fine, but I get the following message : 

WARNING: You are configured to use the CRAN mirror at https://cran.rstudio.com/. This mirror supports secure (HTTPS) downloads however your system is unable to communicate securely with the server (possibly due to out of date certificate files on your system). Falling back to using insecure URL for this mirror.

Can someone help me ? 
Thank you so much

![erreur_notebookR](https://user-images.githubusercontent.com/55201791/64714208-3cad2180-d48c-11e9-9bab-f50f2ed117a8.PNG)

**Comment by flying-sheep** [comment]
Anaconda isn’t a supported means of installation. If you have problems with their packages, please report your issue with them.

You can also try installing everything from CRAN like documented here: https://irkernel.github.io/installation/ and come back if the error still occurs.

**Comment by JohanyDufour** [comment]
Thanks you for your comment, I will talk to them. One problem remains : I can't get an R terminal to open, only R studio works.
