### ISSUE TITLE
IRkernel installed, but still get "No kernel grammar for Null grammar found" in hydrogen

### ISSUE THREAD

**Issue by Maxico11** [IRkernel/IRkernel#642]
Hi,

I installed the IRkernel via the official instructions (using miniconda prompt with R.exe), and by adding the PATH variables necessary to bypass the 127 error when running IRkernel::installspec().

When I run jupyter kernelspec list in the conda command prompt, it returns
![image](https://user-images.githubusercontent.com/49170767/66407293-f67bad00-e9ba-11e9-8a97-87863695f7c3.png)
which shows that the ir kernel is not on the same path as the python one.

I dragged and dropped the kernel in my miniconda path and the file is there as we can see
![image](https://user-images.githubusercontent.com/49170767/66407380-1ad78980-e9bb-11e9-9216-b6fcb1889350.png)
The problem is that when I try running a simple R code in atom (1+1), it still gives me the error message "No kernel grammar for Null grammar found"

I wrote the IRkernel as such in hydrogen
![image](https://user-images.githubusercontent.com/49170767/66407516-52decc80-e9bb-11e9-98f0-45b5d0c76f16.png)

Could you help me please to understand why hydrogen wont recognize the language? Thank you very much

Maxime

**Comment by flying-sheep** [comment]
Well, read the description in your last screenshot, your mapping is the wrong way around.
