### ISSUE TITLE
tibble in exported html is not as beautiful as it is in jupyter

### ISSUE THREAD

**Issue by Youguang** [IRkernel/IRkernel#643]
See: 
<img width="749" alt="Screen Shot 2019-10-09 at 16 15 22" src="https://user-images.githubusercontent.com/7878120/66463721-3b354000-eab0-11e9-8363-a4000b401c5a.png">

**Comment by flying-sheep** [comment]
I don’t add any styling, it’s up to your frontend to do that.

You should use a [custom template](https://nbconvert.readthedocs.io/en/latest/customizing.html#Custom-Templates). Make sure you read the rest of that docs page (e.g. “Template structure”) to know how to build one. I assume you just need to inherit from the default and override the `html_head` block to contain a `<style/>` tag.

Thank you for thinking my table rendering is beautiful!
