### ISSUE TITLE
Error on Installing IRkernel

### ISSUE THREAD

**Issue by kumodjha** [IRkernel/IRkernel#644]
I have to install IRkernel

devtools::install_github('IRkernel/IRkernel')

The installation goes normal till below

![image](https://user-images.githubusercontent.com/24988992/66545306-0086e280-eb58-11e9-9a10-c3f22f9232be.png)

I tried removing digest and installing it again. I got the same error.
Please help.

**Comment by kumodjha** [comment]
I have to install IRkernel

devtools::install_github('IRkernel/IRkernel')

The installation goes normal till below

![image](https://user-images.githubusercontent.com/24988992/66545082-8b1b1200-eb57-11e9-90c0-7d8826dfe078.png)

I tried removing digest and installing it again. Got the same error.
Please help.

**Comment by flying-sheep** [comment]
It tells you it can’t remove the prior installation of “digest”, which is clearly unrelated to IRkernel.

No idea what causes this, maybe you should google or search/ask on stackoverflow?
