### ISSUE TITLE
Help: unable to use keyboard shortcuts for R

### ISSUE THREAD

**Issue by smartinsightsfromdata** [IRkernel/IRkernel#645]
I thought IRKernel offered in upyter / jupyterlab shortcuts for `<-`  `%>%` etc., which I understand are available in IRKernel.

I work (it's so great! - thanks) on jupyterlab on Apple Mac but I'm unable to select the shortcuts.

What should I do?

Just in case, this is my sessioninfo:
```
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin18.7.0 (64-bit)
Running under: macOS Catalina 10.15

Matrix products: default
BLAS/LAPACK: /usr/local/Cellar/openblas/0.3.7/lib/libopenblasp-r0.3.7.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.6.1      IRdisplay_0.7.0     pbdZMQ_0.3-3       
 [4] tools_3.6.1         htmltools_0.4.0     pillar_1.4.2       
 [7] base64enc_0.1-3     crayon_1.3.4        Rcpp_1.0.2         
[10] uuid_0.1-2          IRkernel_1.0.2.9000 jsonlite_1.6       
[13] digest_0.6.21       repr_1.0.1          rlang_0.4.0        
[16] evaluate_0.14  
```

**Comment by flying-sheep** [comment]
Sadly jupyterlab doesn’t support kernel.js. See here for more info: jupyterlab/jupyterlab#4109

**Comment by krassowski** [comment]
This is now possible (for quite a while) by configuring the keyboard shortcuts, see: https://github.com/jupyterlab/jupyterlab/issues/10114#issuecomment-821993321. I wonder if IRkernel could just add these to user settings (which are JSON files).

**Comment by flying-sheep** [comment]
Huh! I thought one needed this: https://github.com/techrah/jupyterext-text-shortcuts

**Comment by krassowski** [comment]
That's a nice extension! Definitely good to have simple text insertion capability in the JupyterLab core, and delegate more fancy stuff like kernel-specific snippets and padding to extensions.

**Comment by flying-sheep** [comment]
for the record, that extension happens to come preloaded with those two shortcuts :innocent:
