### ISSUE TITLE
Python test suite (`test_ir.py`) fails for 1.1

### ISSUE THREAD

**Issue by chronitis** [IRkernel/IRkernel#648]
- [x] Did you follow the [official installation instructions](https://irkernel.github.io/installation/)?
- [x] Did you reproduce the error with the newest versions?
- [x] Did you include a [minimal reproducible example](https://stackoverflow.com/a/5963610/247482)?

```bash
export IR_KERNEL_NAME=ir
cd tests/testthat
python3 -m test_ir
```

- [x] Is this the right repository?

Several changes in 1.1, eg

 - https://github.com/IRkernel/IRkernel/commit/d7f0b08582c66a1b5119b50e3e6aa56a03b06d1b adding newlines after some messages
 - https://github.com/IRkernel/IRkernel/commit/44a92feba841e9959788f3c6750c73d293ca9387 encapsulating SVG

don't appear to be reflected in the tests in `tests/testthat/test_ir.py`.

I can propose a PR which updates the test-suite if the new behaviour should be considered canonical.

**Comment by flying-sheep** [comment]
Right. That’s what happens when CRAN can’t run your tests.

Thank you for the offer, but I quickly fixed it myself in 2bff1aec915895c764f0fcbae35533f1f6f70c5e
