### ISSUE TITLE
Cannot install on Ubuntu 14.04.02

### ISSUE THREAD

**Issue by HyperionAnalytics** [IRkernel/IRkernel#65]
When running:

```
> library(devtools)
> install_github("takluyver/IRdisplay")
Downloading github repo takluyver/IRdisplay@master
Error in system(full, intern = quiet, ignore.stderr = quiet, ...) : 
  error in running command
```

**Comment by jenshnielsen** [comment]
I think the readme should be updated. 

install_github("takluyver/IRdisplay") -> install_github("IRkernel/IRdisplay")

and dito for the next command. (the repo has moved from takluyver's private github to it IRkernel org

**Comment by takluyver** [comment]
Thanks Jens, I forgot about that. And thanks Phil for the quick fix.
