### ISSUE TITLE
Kernel Restarting on irkernel 3.6.3

### ISSUE THREAD

**Issue by tariktourougui** [IRkernel/IRkernel#653]
Before submitting an issue please be sure to answer these questions with **yes**:

- [ ] Did you follow the [official installation instructions](https://irkernel.github.io/installation/)?
Yes
    If you have an installation problem, a segfault, `caught illegal operation`, `cannot open shared object file`,  …
    and installed IRkernel using Anaconda, please report your issue to them instead.
Everything is up to date
- [ ] Did you reproduce the error with the newest versions? If the following code installs packages, you didn’t yet!
Yes
    ```r
    old_pkgs <- intersect(old.packages()[, 'Package'], c('IRkernel', 'IRdisplay', 'repr'))
    if (length(old_pkgs) > 0) install.packages(old_pkgs)
    ```

i am having issues setting up multiple R notebooks on the same Jupyterlab instance.
the consoles are working perfectly fine. but the notebooks aren't.
i had a server with R-3.4.4 as a first installation, used for Rstudio running on the same server.
i enabled the Jupyterlab in jupyterhub config, i added multi python environnement which also worked correctly.
but when i do the same thing with R, the only version that works is the 3.4.4, while the 3.6.3 is giving me this.
i also would like to know if the is a way to debug what happen at the server end ? are there any log files to check to debug this kinda issues?

> Kernel Restarting
> The kernel for test.ipynb appears to have died. It will restart automatically.

As i said, the Terminal works correctly as i am able to run command to get the version and i get a response. but when i do that on the notebook i doesn't work and gives the above error

Working from Console on both versions
![chrome-capture (3)](https://user-images.githubusercontent.com/62100963/77429157-87afd600-6dd9-11ea-9f71-254188e00282.gif)

Not working from notebook 3.6.3
![chrome-capture (4)](https://user-images.githubusercontent.com/62100963/77429516-0f95e000-6dda-11ea-8d0f-28b466cf78a9.gif)

**Comment by flying-sheep** [comment]
What does the log messages in the console say? please set to a higher log level if nothing helpful is there using the env variable `JUPYTER_LOG_LEVEL=3`

**Comment by tariktourougui** [comment]
i did this and it doesn't change anything 
```
[Unit]
Description=JupyterHub
After=syslog.target network.target

[Service]
User=root
Environment="PATH=/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/jupyterhub/bin"
Environment="JUPYTER_LOG_LEVEL=3"
ExecStart=/opt/jupyterhub/bin/jupyterhub -f /opt/jupyterhub/etc/jupyterhub/jupyterhub_config.py

[Install]
WantedBy=multi-user.target
```
![image](https://user-images.githubusercontent.com/62100963/77636431-66bfc000-6f54-11ea-94cd-93bb21f78700.png)

**Comment by tariktourougui** [comment]
here's the log i was able to get

![image](https://user-images.githubusercontent.com/62100963/77659059-df844380-6f77-11ea-9756-7d95ea1eca93.png)

**Comment by flying-sheep** [comment]
There you have it, the hidden `.RData` file in your directory is corrupt. Delete it and it should work.

Very weird that you don't see IRkernel's logs though.

**Comment by tariktourougui** [comment]
I was able to launch the server on attached mode which allowed me to see the logs.
The issue was the installation from source was a default one, this means capabilities() like png we're set to false. unlike installation from repo.
in case of having the same issue, this could be solved by configuring the R build like this:

- `./configure --prefix=/usr/local/R/${R_VERSION} --enable-R-shlib --with-x --with-libpng --with-jpeglib --with-libtiff` 

- make sure that the .Rprofile is there for all the users. i am no R expert but the below content solved my issue.

```
#~/.Rprofile
# Set default 'type' for png() calls - useful when X11 device is not available!
## NOTE: Needs 'cairo' capability
options(bitmapType='cairo')
```

**Comment by flying-sheep** [comment]
Ah, well that's also a known problem. Source installations with default options are kinda useless if you want to do basic stuff like plotting.
