### ISSUE TITLE
Error in readRDS(nsInfoFilePath) : error reading from connection

### ISSUE THREAD

**Issue by Sandyaoh** [IRkernel/IRkernel#654]
After typing ` install.packages('IRkernel') ` I got:

```
* installing *source* package ‘IRkernel’ ...
** package ‘IRkernel’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
Error in readRDS(nsInfoFilePath) : error reading from connection
ERROR: lazy loading failed for package ‘IRkernel’ 
* removing ‘/home/user/R/x86_64-pc-linux-gnu-library/3.4/IRkernel’ 

The downloaded source packages are in
	‘/tmp/Rtmp7gbQLC/downloaded_packages’
Warning message:
In install.packages("IRkernel") :
  installation of package ‘IRkernel’ had non-zero exit status
```
Don't know what to do

**Comment by flying-sheep** [comment]
https://stackoverflow.com/questions/31935516/installing-r-packages-error-in-readrdsfile-error-reading-from-connection

**Comment by Sandyaoh** [comment]
I already tried all the suggestions in that link and still doesn't work, that's why I wrote the isuue here, I apologize I didn't point it out before, but the issue shouldn't be closed unless it is solved, should be?

**Comment by flying-sheep** [comment]
This isn’t a bug, this is data corruption on your PC. It’s not specific to this (or any) package, it just generally happens sometimes with R packages, and (as the stackoverflow post says) is fixed by reinstalling all affected packages.

**Comment by Sandyaoh** [comment]
Ok, I understand. I'll try to find the error, hope it works. Thanks !

**Comment by flying-sheep** [comment]
Great! I hope you were able to fix it!
