### ISSUE TITLE
mapview isn't automatically shown

### ISSUE THREAD

**Issue by mdeff** [IRkernel/IRkernel#656]
No browser tab is opened if I run
```
library(mapview)
mapview(breweries)
```
I can however open it with `browseURL('/tmp/RtmpGFDtgo/viewhtml561682b65116/index.html')`. A browser tab is opened if I run the above at the R prompt instead. Any reason for this not to be automatic? Or for the map not to show in the cell output?

**Comment by flying-sheep** [comment]
Assuming that `mapview` just returns a thing with class `'mapview'`, IRkernel would display it if it had a `repr_html.mapview` method returning HTML code as string. You can ask the library devs to implement that method.
