### ISSUE TITLE
I get one number every second in Rstudio, but not in Jupyter 

### ISSUE THREAD

**Issue by DawnEve** [IRkernel/IRkernel#659]
I get one number every second in Rstudio, but in Jupyter I get nothing in the 1st 9 seconds, then all 10 numbers at last second. How to sove this problem?

```
for(i in seq(1,10,1)){
    print(i)
    Sys.sleep(1) # a computing intensive step
}
```

**Comment by flying-sheep** [comment]
by using the search function or looking at the single pinned issue.

**Comment by DawnEve** [comment]
I searched, perhapse the keyword was not proper.

Thank you for the hint, I have got a solution
```
for(i in 1:10){
    message(i) # like paste0(), can show instantly
    print(i)
    Sys.sleep(0.5)
}
```

**Comment by flying-sheep** [comment]
you can also use `flush.console()`
