### ISSUE TITLE
IRkernel is not available on R v.4.0.0.

### ISSUE THREAD

**Issue by coco90417** [IRkernel/IRkernel#660]
Dear team,

It seems that IRkernel is not available for the latest version of R. Could you please assist us trouble shooting this issue?

Coco

![image](https://user-images.githubusercontent.com/8430330/82939916-07852880-9f62-11ea-8703-5234c067e520.png)

**Comment by flying-sheep** [comment]
Please read the messages you show here: Evidently R has problems connecting to the internet. This have nothing to do with IRkernel.

**Comment by coco90417** [comment]
Thank you so much for your quick response!! That helps a lot!

**Comment by flying-sheep** [comment]
Great! Happy to be of help
