### ISSUE TITLE
Detect that code is running in IRKernel

### ISSUE THREAD

**Issue by dfalbel** [IRkernel/IRkernel#664]
Sorry for not using the template. This is more like a general question.

Is there any way to detect if the code is run inside a jupyter notebook. 
I tried `base::interactive()` but it returns `FALSE` in notebooks.

**Comment by flying-sheep** [comment]
see here:

https://github.com/IRkernel/IRkernel/blob/44a92feba841e9959788f3c6750c73d293ca9387/man/IRkernel-package.Rd#L26

**Comment by dfalbel** [comment]
That's awesome! Thanks!
