### ISSUE TITLE
Add metadata about reply time to response messages

### ISSUE THREAD

**Issue by udaykapur** [IRkernel/IRkernel#667]
- [x] Did you follow the [official installation instructions](https://irkernel.github.io/installation/)?
- [x] Did you reproduce the error with the newest versions?
- [x] Did you include a [minimal reproducible example](https://stackoverflow.com/a/5963610/247482)?
- [x] Is this the right repository?

**IRkernel version:** 1.1.1
**jupyterlab version:** 2.1.5
**Anaconda version:** Anaconda3-2020.07-Linux-x86_64
**R version:** R version 4.0.2 (2020-06-22) -- "Taking Off Again"
**Python version:** 3.8.3
**Node.js version:** 14.13.0
**Browser:** Firefox 81.0 (64-bit)

**OS info:** Ubuntu 20.04.1 LTS
![image](https://user-images.githubusercontent.com/15121710/94818783-d5b92c80-0441-11eb-9a14-7b2772b6787b.png)

**Output when using python3 kernel within jupyterlab**
![image](https://user-images.githubusercontent.com/15121710/94819550-bd95dd00-0442-11eb-9e2f-46d571cabdb1.png)

**Output when using IR kernel within jupyterlab**
![image](https://user-images.githubusercontent.com/15121710/94820003-4d3b8b80-0443-11eb-9eae-048c228c3a04.png)

As can be seen from the above image, the jupyterlab-execute-time extension only shows the datetime stamp when using IR kernel but the execution duration is missing. Works fine for python kernel though. 

Have already validated the issue with at least one other user using a different version of OS/kernel than mine and have also reached out to the jupyterlab-execute-time devs who have confirmed that this likely appears to be an issue with the kernel and not with jupyterlab or the jupyterlab-execute-time plugin.

This issue seems to be related to the metadata that gets generated for each cell by the kernel.

Please see the comments here - https://github.com/deshaw/jupyterlab-execute-time/issues/14

Thanks

Edit: added text for clarity.

**Comment by flying-sheep** [comment]
Kernels don’t know or do anything about cells. Kernels just [answer to messages with other messages](https://jupyter-client.readthedocs.io/en/stable/messaging.html#general-message-format).

IRkernel (AFAIK) is a fully spec-compliant kernel for messaging format 5.0, so the issue title isn’t correct.

However, I see the following in the linked document:

> **Changed in version 5.1**: `date` in the header was accidentally omitted from the spec prior to 5.1, but it has always been in the canonical implementation, so implementers are strongly encouraged to include it. It will be mandatory in 5.1.

I created #668 to implement this. Please check if it adds the feature you’re requesting.

**Comment by flying-sheep** [comment]
Fixed in #668
