### ISSUE TITLE
No Output on Console

### ISSUE THREAD

**Issue by hakasapl** [IRkernel/IRkernel#669]
- [x] I followed the [official installation instructions](https://irkernel.github.io/installation/)
  
- [x] I reproduced the error with the newest versions of `IRkernel`, `IRdisplay`, and `repr`
  
- [x] I included a [minimal reproducible example](https://stackoverflow.com/a/5963610/247482)
- [x] This the right repository: I think the issue is with IRkernel, not
      [IRkernel/repr](https://github.com/IRkernel/repr/issues/new) or a third party repository
  

Hello,

I have an HPC jupyterlab installation which uses JupyterHub to dispatch lab instances across the cluster. JupyerLab/Hub is installed within a conda environment. I have a system-wide R v4.0.2 installation, with the IRkernel package installed. I was able to generate the kernelspec just fine, and I moved those files to the `conda environment root/share/jupyter/kernels/ir`. The kernel does show up in the JupyterLab launcher and I can even initialize it. However, if I run anything (such as `1+1`), I don't get any output either in the notebook or on the console, the command runs (according to the star next to it), but doesn't output anything. I verified there is an output in the traditional R console.

To Reproduce:
1. Using miniconda create an environment with JupyterLab installed
1. Using the system-level R, install IRkernel and install kernelspec
1. Move kernelspec files to the conda environment location

I am running on Ubuntu 20.04, and the python kernel works fine.

**Comment by hakasapl** [comment]
![Screenshot 2020-10-22 112018](https://user-images.githubusercontent.com/40907639/96893368-a00fce00-1458-11eb-8397-9ab26f82eedc.png)

Here is a screenshot of what I am looking at in the console. As you can see, the kernel initializes because I get the R version header, but everytime I run a command there is no output and the header just appears again.

**Comment by flying-sheep** [comment]
Hi! Can you please try starting jupyterlab something like this and reporting the output:

```console
$ JUPYTER_LOG_LEVEL=3 jupyter lab
```

**Comment by hakasapl** [comment]
That seems to have revealed the issue:
```
^[[32mDEBUG^[[39m: Sending msg execute_input
Error in ok_device(filename, ...) : X11 module cannot be loaded
Calls: <Anonymous> ... evaluate -> dev.new -> do.call -> <Anonymous> -> ok_device
In addition: Warning message:
In grSoftVersion() :
  unable to load shared object '/modules/apps/R/4.0.2/lib/R/modules//R_X11.so':
  libXmu.so.6: cannot open shared object file: No such file or directory
```
I should be able to install that package and give it a shot again, but why is R calling R_X11.so for a simple `1+1` query?

**Comment by hakasapl** [comment]
After installing that library the kernel is still restarting:
```
^[[32mDEBUG^[[39m: Sending msg execute_input
Error in .External2(C_X11, paste0("png::", filename), g$width, g$height,  :
  unable to start device PNG
Calls: <Anonymous> ... evaluate -> dev.new -> do.call -> <Anonymous> -> ok_device
In addition: Warning message:
In ok_device(filename, ...) : unable to open connection to X11 display ''
Execution halted
```

**Comment by flying-sheep** [comment]
Your R was compiled with the wrong options for a headless server.

Search the closed issues for “X11” and you’ll see how people got around it.

E.g. here: https://github.com/IRkernel/IRkernel/issues/653#issuecomment-606648063
