### ISSUE TITLE
How can I cite you?

### ISSUE THREAD

**Issue by NatalieThurlby** [IRkernel/IRkernel#670]
- [x] I followed the [official installation instructions](https://irkernel.github.io/installation/)
- [x] I included a [minimal reproducible example](https://stackoverflow.com/a/5963610/247482)
- [x] This the right repository: I think the issue is with IRkernel, not anything else

Hi, thanks for making this package, it's been really useful to me!

I want to cite it, but:
`cite('IRkernel')` 
returns the following error:
`Error in fn(keys, bib, ...) : argument "bib" is missing, with no default`

How would you like to be cited?

**Comment by flying-sheep** [comment]
Well, you have the wrong function, use `citation('IRkernel')` instead!

**Comment by NatalieThurlby** [comment]
Haha oops thanks!

**Comment by flying-sheep** [comment]
np :smiley:
