### ISSUE TITLE
Parallelization broken 

### ISSUE THREAD

**Issue by alvinwt** [IRkernel/IRkernel#68]
I'm running the NMF package in R and with parallelization and I found that It broken in the IRkernel with ta *invalid value of 'seed' [in call to 'nextRNGStream']* error. I tested this in R and in the IPython Notebook with %%R magics and it works. I'm not sure but can this be a ZMQ/rzmq/pyzmq issue?

**Comment by takluyver** [comment]
Probably not related to rzmq. Most errors related to R running things differently seem to come down to things that assume they're run from the global environment. I hadn't realised how special that was to R.

**Comment by takluyver** [comment]
I hope that #71 will fix this.

**Comment by alvinwt** [comment]
Fixed. Parallelization works like a charm.

**Comment by flying-sheep** [comment]
great to hear!
