### ISSUE TITLE
Errors when running multiple lines of codes in one cell in Jupyter for VSCode

### ISSUE THREAD

**Issue by Misaka-19090** [IRkernel/IRkernel#694]
- [x] I followed the [official installation instructions](https://irkernel.github.io/installation/)
Yes.
- [x] I reproduced the error with the newest versions of `IRkernel`, `IRdisplay`, and `repr`
Yes.
- [x] I included a [minimal reproducible example](https://stackoverflow.com/a/5963610/247482)
Yes.
- [x] This the right repository: I think the issue is with IRkernel, not
      [IRkernel/repr](https://github.com/IRkernel/repr/issues/new) or a third party repository
Yes.

I could only write one line on each cell when using Jupyter for VSCode, the example is given below:
![image](https://user-images.githubusercontent.com/16248068/131122117-4c3121d6-c44d-4945-84a0-5078a4f4cc8a.png)

However, everything is fine when running on the webpage:
![image](https://user-images.githubusercontent.com/16248068/131122558-a69fa0e8-ee41-4483-9f9b-5a893fb3d7cc.png)

Besides, R for VSCode has been correctly installed and I can run .r files with the same codes successfully. Really don't know what goes wrong, has anyone suffered from the same issue?

**Comment by drrui** [comment]
emmm   I have the same question... how to do with it ?

**Comment by flying-sheep** [comment]
I can’t reproduce this, works fine for me.

If you want help, you’ll have to

1. figure out how to access the kernel logs (ask the VS code people for that)
2. now can set set `options(jupyter.log_level = 3L)` to generate those logs
3. Run that cell and paste the log output into a code block here.

I’m going to close this for now as I can’t reproduce it, but I’ll happily reopen when I have that log.

**Comment by Misaka-19090** [comment]
Well, I have finally figured out where the problem comes from, it relates to end of line (Eol) character. By default it is "auto", which works well for other extension but fails to automatically change windows style `\r\n` to `\n` when using IRkernel.

**Comment by Misaka-19090** [comment]
It is in VSCode Settings -> Files -> Eol. Usually it works well, and writing R with jupyter notebook is the only exception. If you set this option to be `\r\n`, I think you can reproduce the original problem I reported.
