### ISSUE TITLE
help function fails to render output

### ISSUE THREAD

**Issue by erentar** [IRkernel/IRkernel#697]
- [x] I followed the [official installation instructions](https://irkernel.github.io/installation/)
  
- [x] I reproduced the error with the newest versions of `IRkernel`, `IRdisplay`, and `repr`
  
- [x] I included a [minimal reproducible example](https://stackoverflow.com/a/5963610/247482)
- [x] This the right repository: I think the issue is with IRkernel, not
      [IRkernel/repr](https://github.com/IRkernel/repr/issues/new) or a third party repository
  

![image](https://user-images.githubusercontent.com/40326736/138564391-41437574-7a1d-418c-acf8-0d3fb2a24f22.png)

Not sure if this is my fault, but uninstalling everything and reinstalling them did not help, so i assume my environment is close to a fresh one.

**Comment by CarlosZM** [comment]
You should do what is indicated on [last comment](https://github.com/IRkernel/repr/pull/144) and after installing that library with the specified version you should restart kernel and now you will be able to use help and ? without any problems. That's how I solved.

**Comment by flying-sheep** [comment]
Release 1.1.4 is on its way, soon there’s no need for workarounds
