### ISSUE TITLE
Kernel restarting due to an exception in completions (in core R)

### ISSUE THREAD

**Issue by krassowski** [IRkernel/IRkernel#702]
- [x] I followed the [official installation instructions](https://irkernel.github.io/installation/)
- [x] I reproduced the error with the newest versions of `IRkernel`, `IRdisplay`, and `repr`
  
- [ ] I included a [minimal reproducible example](https://stackoverflow.com/a/5963610/247482)
- [x] This the right repository: I think the issue is with IRkernel, not
      [IRkernel/repr](https://github.com/IRkernel/repr/issues/new) or a third party repository

So that's hard to reproduce, but I'm getting this a lot in JupyterLab with LSP extension installed. The LSP extension can trigger completions after typing any character, so it may sometimes trigger in odd places and I think this leads to some edge case in completions handling; pretty often the kernel will die and restart with the following message in the console:

```R
Error in suppressWarnings(gregexpr("[^\\.\\w:?$@[\\]]+", linebuffer, perl = TRUE))[[1L]] :
  subscript out of bounds
Calls: <Anonymous> ... handle_shell -> complete -> completions -> <Anonymous>
Execution halted
[I 2021-12-01 15:50:58.092 ServerApp] AsyncIOLoopKernelRestarter: restarting kernel (1/5), keep random ports
kernel 6940fbfd-10d1-4918-ada7-7028d880a2f3 restarted
```

It seems to come from this call:

https://github.com/IRkernel/IRkernel/blob/d872064ff4324e61509af5ebd0038fd16998de89/R/completion.r#L23-L24

To a core function which was not modified in the last 8 years:

https://github.com/wch/r-source/blob/79298c499218846d14500255efd622b5021c10ec/src/library/utils/R/completion.R#L286-L291

I wonder, is this off-by-one error on my side, or potentially something in IRKernel? In either case I thought it would be worth to record an issue here to ask if anyone saw something similar.

I wonder if this could be that sometimes completing on empty `line` triggers this issue?

**Comment by krassowski** [comment]
Would it make sense to wrap this fragment in try catch so it does not break the kernel ever?

**Comment by krassowski** [comment]
Would it make sense to wrap this fragment in try catch so it does not break the kernel ever?

**Comment by Microbion** [comment]
I meet the same problem. My IRkernel version is 1.3, jupyterlab version is 3.4.3, jupyterlab-lsp version is 3.10.1, python-lsp-server version is 1.4.1。In my test, kernel will shut down if I use shift + Enter to run cell with LSP extension. But if I disable Continous hinting in settings, kernel won't die. So just modify advanced settings in jupyterlab solved my problem.

**Comment by li1311139481** [comment]
> I meet the same problem. My IRkernel version is 1.3, jupyterlab version is 3.4.3, jupyterlab-lsp version is 3.10.1, python-lsp-server version is 1.4.1. In my test, kernel will shut down if I use shift + Enter to run cell with LSP extension. But if I disable Continous hinting in settings, kernel won't die. So just modify advanced settings in jupyterlab solved my problem.
It' work, but after disable it , python can't complement code. so it is not perfect.
Do you have other method?

**Comment by krassowski** [comment]
@flying-sheep can I help with the release to get a patch from #703 out?

**Comment by flying-sheep** [comment]
thanks for the reminder. I submitted IRkernel 1.3.1 with the patch, let’s see if it goes through or they changed the checks again.

**Comment by Microbion** [comment]
@li1311139481 Here's my LSP servers config. Anyway, it's a hard work for me, and I would not like to repeat it again🤣.
![image](https://user-images.githubusercontent.com/35793183/200488386-a796f9e2-c8ac-4366-916c-fa00a195bc65.png)
I used python-lsp-server to replace the default one. There were many package conflicts to solve manurally.
