### ISSUE TITLE
Dose R kernel support the jupyter 'introspection' message?

### ISSUE THREAD

**Issue by morning-start** [IRkernel/IRkernel#710]

**Comment by flying-sheep** [comment]
yes:

https://github.com/IRkernel/IRkernel/blob/e7a0fe4ee7c5783912db6c502ad105eacefc2e98/R/kernel.r#L131

https://github.com/IRkernel/IRkernel/blob/e7a0fe4ee7c5783912db6c502ad105eacefc2e98/R/kernel.r#L247-L307

**Comment by morning-start** [comment]
Thinks for your answer
