### ISSUE TITLE
R kernel changes native plot background to transparent

### ISSUE THREAD

**Issue by Fred-Wu** [IRkernel/IRkernel#714]
Running `par()$bg` should be "white" by default, but it is "transparent" in jupyter notebook in VScode-R. So calling R's native `plot()` barely see the graph. 

<img width="538" alt="image" src="https://user-images.githubusercontent.com/4111978/165015213-f43d4474-05e3-4209-aecb-30874657841a.png">

**Comment by flying-sheep** [comment]
Just set `par(fg =, col.axis =, col.lab =, col.main =, col.sub = 'white')` or so when using dark mode.
