### ISSUE TITLE
no reticulate python print() even with stdout flush 

### ISSUE THREAD

**Issue by sushantd195** [IRkernel/IRkernel#715]
<img width="640" alt="image" src="https://user-images.githubusercontent.com/77302408/174422152-d9294447-ef9d-4fee-9891-4f89cafb9fbd.png">

no output for this but it works in r studio, so can't be reticulate issue. I'm running latest IRkernel, IRdisplay and repr.

**Comment by sarathsund** [comment]
Following thread. 
Some base issue with reticulate page too.  As mentioned it works in R console but not in the IRkernel Cells

https://github.com/rstudio/reticulate/issues/1049

**Comment by flying-sheep** [comment]
There’s a pinned issue explaining why this happens #416

RStudio works differently and is therefore able to do this while we aren’t
