### ISSUE TITLE
 installation of package 'IRkernel' had non-zero exit status

### ISSUE THREAD

**Issue by lifan18** [IRkernel/IRkernel#716]
Dear Doctor

I installed IRkernel in R 3.6 and removed the package and all libs. As a software I used required for R 4.1.0, I therefore was trying to install IRkernel again. However, I cannot install it anymore. How can I get ride of this? It seems a common issue, but no cure at this moment.

Hope anyone can help me out :[

Thanks!

Regards,

LF

```
> R

R version 4.1.0 (2021-05-18) -- "Camp Pontanezen"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

>install.packages('IRkernel')

Warning messages:
1: In install.packages("IRkernel") :
  installation of package 'repr' had non-zero exit status
2: In install.packages("IRkernel") :
  installation of package 'IRdisplay' had non-zero exit status
3: In install.packages("IRkernel") :
  installation of package 'IRkernel' had non-zero exit status
```

**Comment by flying-sheep** [comment]
Hi, first: This is a very generic problem. Please ask questions that aren’t specific to IRkernel in a general purpose R help forum

And before you do that: this doesn’t contain enough information for anyone to help you. `installation of package 'repr' had non-zero exit status` just means that it fails, with no hint why. You need to actually provide the command output if you want help. Should look something like this:

```
Installing package into ‘~/R/x86_64-pc-linux-gnu-library/3.6’  (as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/....tar.gz'
Content type 'application/x-gzip' length 28558 bytes (27 KB)
==================================================
downloaded 27 KB

* installing *source* package ‘IRkernel’ ...
[...]
```
