### ISSUE TITLE
Error: unexpected '>' in ">"

### ISSUE THREAD

**Issue by Ametista-stella** [IRkernel/IRkernel#729]
- [x] I followed the [official installation instructions](https://irkernel.github.io/installation/)
  
- [x] I reproduced the error with the newest versions of `IRkernel`, `IRdisplay`, and `repr`
  
- [x] I included a [minimal reproducible example](https://stackoverflow.com/a/5963610/247482)
- [x] This the right repository: I think the issue is with IRkernel, not
      [IRkernel/repr](https://github.com/IRkernel/repr/issues/new) or a third party repository
  
Hello everyone
I have no idea what am I doing, I have just installed python and R 
I am trying to install jupyter notebook on R. 
I pasted the first command in R console ( install.packages('IRkernel') )  and it worked fine but when I paste the next command (IRkernel::installspec() ) nothing happens or I get this error : Error: unexpected '>' in ">"
When I received the error I closed the R and run the first command again that's why it is like this now 
overall, I don't know what to do 
please help! 

![image](https://user-images.githubusercontent.com/123899958/215351984-57f1c552-bd7e-470b-a9ff-eb4e491ec200.png)

**Comment by flying-sheep** [comment]
“Unable to access index for repository https://...” means there’s something wrong with your internet connection or R installation/cache/config.

Please go to a general purpose R community forum to get help with stuff like that.
