### ISSUE TITLE
Remove set_plot_options

### ISSUE THREAD

**Issue by flying-sheep** [IRkernel/IRkernel#73]
…or deprecate and hide it from the docs.

R has a notion of the “default graphics device”, i.e. `getOption('device')`, which is either a string containing a function name or a function.

we could leverage this in two ways:

1. use it with custom options:

	```r
	dev <- getOption('device')
	if (!is.function(dev)) {
		dev <- get(dev)
	}
	do.call(dev, as.list(options('jupyter.plot')))
	```

2. require the user to override the defaults by setting it to a function:

	```r
	#our initialization
	options(device = function(file.name, width = 7, height = 7,...) {
		png(file.name, width = width, height = height, ...)
	})
	
	…
	
	dev <- getOption('device')
	if (!is.function(dev)) {
		dev <- get(dev)
	}
	dev()
	```

---

the only problem: we want to allow different mime types (PNG, JPG, SVG) for plots: if it’s a function, we can’t derive the type from the option.

**Comment by flying-sheep** [comment]
an alternative would be to disregard `getOption('device')` and only use `getOption('jupyter.plot')$format`.

**Comment by JanSchulz** [comment]
Not sure how the R side should be handled, but the python kernel does has a 'what plotting types should be produced` (you can have more than one, similar to the mimetypes for returned objects):

In [knitpy](https://github.com/JanSchulz/knitpy/blob/master/knitpy/engines.py#L40) I currently do this:

```
from IPython.display import set_matplotlib_formats
set_matplotlib_formats(["pdf"]) # or multiple formats...
```

I get the formats from the documents I want to produce, so a html document will request `jpg` and a pdf will requests plots in `pdf` format. 

It would be nice if this would also be possible with R kernels.

I want to do similar things for the plotting dimensions and dpi settings, but I haven't looked that up yet.

**Comment by flying-sheep** [comment]
ok, so what does the requesting here?

my current workflow is

1. edit and execute cells interactively using a notebook server and web frontend
2. `ipython nbconvert saved_notebook.ipynb --to=latex`

i’d think that report generation would work so that i run something like knitpy on a notebook which executes all cells sequentially with some different request parameters?

if so, what are those parameters?

**Comment by flying-sheep** [comment]
a unrelated problem is `par(new = TRUE)`. this allows R users (and package authors) to overpaint onto a existing plot, but it makes out plotting go haywire:

```r
plot(1:2, 1:2)
par(new = TRUE)
plot(1.5, 1.5, col = 'red')
par(new = FALSE)
```

should produce a single plot, but for us, it creates two. the same with

```r
plot(1)
lengend('right', 'hello')
```

**Comment by JanSchulz** [comment]
What I would like to do is:

* be able to influence what plotting format is produced via some well defined API by sending some code
* be able to get more than one image format back, similar to the markdown/html thingy

**Comment by takluyver** [comment]
@flying-sheep the problem with creating new plots when we shouldn't is already tracked as #23

**Comment by flying-sheep** [comment]
@takluyver thanks, i’ll move discussion about that problem to there.

@JanSchulz so the best thing to do would be to

1. fix #23. we need to get an understanding of devices and how to reliably enumerate all plots done during execution of a cell

	e.g. `plot(); plot(); lines(); plot()` has to give us 3 plots, the 2nd of which having the lines painted in

2. in `handle_graphics`, we need to create a device and do `replayPlot` (or whatever we end up using) for every output format we want. i suggest SVG, PNG, PDF as default

and the options for the user would be which format to use for a certain frontend. e.g.

> i want to use SVGs (instead of the default PNGs) in the interactive web frontend

or

> i want to use PNGs (instead of the default PDFs) in the LaTeX output.

---

with ipython+matplotlib that works by telling it what to emit (via `IPython.display.set_matplotlib_formats()`; by default everything AFAIK), and then selecting the used format via `%config InlineBackend.figure_format = 'svg'`.

this only applies to the interactive frontends (web and qt console)

**Comment by JanSchulz** [comment]
sounds good so far as I understand the R side.

**Comment by flying-sheep** [comment]
well, since we kinda agreed to move the displaying to the repr lib, i think we should rename the option `repr.plot` or similar. what do you suggest?

**Comment by takluyver** [comment]
Doing it with `repr_*.plot` seems sensible, but I think there's still a need for something like set_plot_options() to easily change e.g. the size that inline plots appear at. If there's already a good way to do that, great. I might deprecate rather than remove set_plot_options() in case people are already relying on it.

**Comment by flying-sheep** [comment]
that’s what i’m talking about: `repr_png.recordedplot` would work by calling `png(tmp.file, ...); replayPlot(plotobj); dev.off()`

but the options inserted using ... would have to come from somewhere, and that would probably be `getOption('repr.plot')` or similar.

the only remaining problem is that not all devices accept the same options, and some mean something different (e.g. `width` means “inches” for pdf and “pixels” for png). we could of course accept a common set of options that get rerouted to the individual devices, and allow the user to provide device-specific options (e.g. we call `png` with `units = 'in'` which would make `width = 7` mean the same for all devices, and only reroute `useKerning = ...` to the `pdf` device where it is accepted)

PS: of course deprecation (with warning) and eventual removal is the way to go.

**Comment by JanSchulz** [comment]
Seeing this as the author of knitpy, I would very much prefer *one* interface (function/option/... for each dimension/dpi/... option) which sets the defaults for all plotting devices. The interface (or the individual plotting `repr_xxx.recordedplot` functions) should "translate" between inch and pixel, if that is needed.

I wouldn't mind if there is a possibility to specify different options for different devices, which overwrite the default, though.

**Comment by flying-sheep** [comment]
that’s what i suggested, isn’t it?

> e.g. we call png with `units = 'in'` which would make `width = 7` mean the same for all device

in other words, we interpret the `repr.plot$width` option as “width in inches” for all devices.

**Comment by JanSchulz** [comment]
yep, seems that I shouldn't watch soccer and comment on github :-)
