### ISSUE TITLE
Installing extensions with jupyter labextension command is deprecated

### ISSUE THREAD

**Issue by raffaem** [IRkernel/IRkernel#737]
I'm following the official installation instruction, but I can't install the RStudio shortcuts in jupyter as the jupyter command doesn't seem to have a labextension subcommand:

```
❯ jupyter labextension install @techrah/text-shortcuts
usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
               [--paths] [--json] [--debug]
               [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

options:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands: kernel kernelspec migrate run troubleshoot trust

Jupyter command `jupyter-labextension` not found.
```

- [X] I followed the [official installation instructions](https://irkernel.github.io/installation/)
  
- [X] I reproduced the error with the newest versions of `IRkernel`, `IRdisplay`, and `repr`
  
- [X] I included a [minimal reproducible example](https://stackoverflow.com/a/5963610/247482)
- [X] This the right repository: I think the issue is with IRkernel, not
      [IRkernel/repr](https://github.com/IRkernel/repr/issues/new) or a third party repository

**Comment by raffaem** [comment]
After updating jupyterlab:

```
❯ jupyter labextension install @techrah/text-shortcuts
(Deprecated) Installing extensions with the jupyter labextension install command is now deprecated and will be removed in a future major version of JupyterLab.

Users should manage prebuilt extensions with package managers like pip and conda, and extension authors are encouraged to distribute their extensions as prebuilt packages 
An error occurred.
ValueError: Please install Node.js and npm before continuing installation. You may be able to install Node.js from your package manager, from conda, or directly from the Node.js website (https://nodejs.org).
See the log file for details:  /tmp/jupyterlab-debug-48q27wa2.log
```

**Comment by flying-sheep** [comment]
Please raise this issue in https://github.com/techrah/jupyterext-text-shortcuts

There’s nothing we can do here!

**Comment by raffaem** [comment]
> Please raise this issue in https://github.com/techrah/jupyterext-text-shortcuts
> 
> There’s nothing we can do here!

Why you picked that particular repo?

I don't understand

**Comment by flying-sheep** [comment]
Because that repo holds the jupyterlab extension that IRkernel recommends. You referenced it in the third line of this issue:

> ```
> ❯ jupyter labextension install @techrah/text-shortcuts
> ```

IRkernel of course works fine without that extension, but it would be nice to be able to use it going forward.

In order to use it, the issue you describe needs to be fixed in that repo: the extension needs to be packaged as a python package and distributed via PyPI.

**Comment by raffaem** [comment]
oh sorry, I didn't understand that.

Thanks!

**Comment by flying-sheep** [comment]
Also, as a workaround you can of course install npm as told by the error message
