### ISSUE TITLE
Can't register the kernel in the current R installation.

### ISSUE THREAD

**Issue by darkRaspberry** [IRkernel/IRkernel#738]
- [x] I followed the [official installation instructions](https://irkernel.github.io/installation/)
  
- [x] I reproduced the error with the newest versions of `IRkernel`, `IRdisplay`, and `repr`
  
- [x] I included a [minimal reproducible example](https://stackoverflow.com/a/5963610/247482)
- [x] This the right repository: I think the issue is with IRkernel, not
      [IRkernel/repr](https://github.com/IRkernel/repr/issues/new) or a third party repository
  

## What's issue?
I can't register the kernel in step 2.

## What I have done.

1. I started with installing juypter as usual from official docs and run `pip install jupyterlab
` **HERE, I installed jupyter-lab not classic notebook** in my system (Ubuntu 23.04) and after some issue with python 3.11 I installed it anyway.

2. I installed R by compiling it from source. And installed (R version 4.3.0 (2023-04-21) -- "Already Tomorrow")
3. I then launched R and installed the package `install.packages('IRkernel')`
4. I tried registering and it just didn't completed. And through this error.

```R
> IRkernel::installspec()
Error in IRkernel::installspec() : 
  jupyter-client has to be installed but “jupyter kernelspec --version” exited with code 127.
In addition: Warning message:
In system2("jupyter", c("kernelspec", "--version"), FALSE, FALSE) :
  error in running command
```

This seems juypter-lab is not installed but I tried running juypter and it works normally.
I reinstalled juypter-lab but nothing happened.

```bash
➜  ~ pipx install jupyterlab
Installing to existing venv 'jupyterlab'
  installed package jupyterlab 3.6.3, installed using Python 3.11.2
  These apps are now globally available
    - jlpm
    - jupyter-lab
    - jupyter-labextension
    - jupyter-labhub
done! ✨ 🌟 ✨
```

**Comment by darkRaspberry** [comment]
Further running `jupyter --version` shows no results and only `jupyter-lab --version` show anything. Installing classic notebook also doesn't help.

```bash
➜  ~ pipx install notebook
  installed package notebook 6.5.4, installed using Python 3.11.2
  These apps are now globally available
    - jupyter-bundlerextension
    - jupyter-nbextension
    - jupyter-notebook
    - jupyter-serverextension
done! ✨ 🌟 ✨
```

still I see no version `jupyter --version`  and `jupyter-notebook --version` correct version.

**Comment by flying-sheep** [comment]
The error message says:

> ```r
> > IRkernel::installspec()
> Error in IRkernel::installspec() : 
>   jupyter-client has to be installed but “jupyter kernelspec --version” exited with code 127.
> In addition: Warning message:
> In system2("jupyter", c("kernelspec", "--version"), FALSE, FALSE) :
>   error in running command
> ```

Did you read the warning here? https://irkernel.github.io/installation/

> On OS X, be sure to execute this in R started from the Terminal, not the R App!
> (This is because the R app doesn’t honor `$PATH` changes in `~/.bash_profile`) 

You probably executed that command in an environment that doesn’t have `jupyter-kernelspec` in its PATH.
Make sure things work before running `IRkernel::install()`:

```
$ jupter kernelspec -h
Usage: jupyter kernelspec […]
[…]
$ R
> IRkernel::install()
```

**Comment by sje30** [comment]
I wonder if the problem here is that 'jupyter-lab' binary is installed by jupyterlab, whereas the R package assumes the binary is called 'jupyter'. (this at least the problem I'm experiencing).

**Comment by flying-sheep** [comment]
Almost. The package `jupyterlab` provides a shell command called `jupyter-lab`. You shouldn’t use this shell command directly, you should use the `jupyter` shell command provided by the `jupyter-core` package. `jupyter lab` will call `jupyter-lab` internally, and that’s the preferred way to call that.

`jupyter-core` is a dependency of `jupyterlab`, therefore in a properly configured environment, you will have both shell commands installed.

The only exception I can think of is `pipx`, since by default, `pipx` doesn’t export shell commands of dependencies. So if you use it to install `jupyterlab` without specifying `--include-deps` (which will only make `jupyter-lab` but not `jupyter` available in the shell)

**Comment by sje30** [comment]
Thank you for the explanation..  I will need to investigate what I installed.  I am on Mac and so used brew (+ also use pyenv to manage python versions).

**Comment by sje30** [comment]
Just to follow up... I think my problem was that pyenv didn't install Jupyter.  

on my Mac, if I do:

```
brew install jupyter
```
then all is okay.

thanks again for clarifying.
