### ISSUE TITLE
README should mention base64enc

### ISSUE THREAD

**Issue by stefanv** [IRkernel/IRkernel#74]
``install.package('base64enc')`` is necessary to make the installation instructions work

**Comment by flying-sheep** [comment]
yes. that’s a dependency of IRDisplay, so as long as we’re not on CRAN, we need to cover it in the readme.

**Comment by takluyver** [comment]
Wait, why is that necessary? There are a number of other packages we rely on (evaluate, digest, uuid) and we don't have to specify those separately in the README. Maybe we need to add base64enc to the [DESCRIPTION](https://github.com/IRkernel/IRdisplay/blob/master/DESCRIPTION) file for IRdisplay.

**Comment by takluyver** [comment]
I think that's it. IRkernel/IRdisplay#1 updated NAMESPACE, but not DESCRIPTION. I'll push a fix.

**Comment by flying-sheep** [comment]
oh, sorry!
