### ISSUE TITLE
Upcoming evaluate 1.0.0 release

### ISSUE THREAD

**Issue by hadley** [IRkernel/IRkernel#744]
This is just a heads up that we're planning to release evaluate 1.0.0 in the near future. This is almost a ground up re-write of the package, but it shouldn't (🤞) have any changes to the interface. If there's anything more you can do to test the package, I'd greatly appreciate it 😄.

**Comment by flying-sheep** [comment]
I ran the tests with it locally and it looks good!

Thank you for the heads-up, I appreciate it
