### ISSUE TITLE
how to change R pipe from %>% to |> ?

### ISSUE THREAD

**Issue by MOKA1066** [IRkernel/IRkernel#746]
hello
cmd+shift+m: %>%
how to change to:
cmd+shift+m: |>

Thanks!

macOS+jupyter notebook

**Comment by flying-sheep** [comment]
Jupyter notebook still exists?

I’d switch to jupyterlab and use this extension, as described in the readme: https://github.com/techrah/jupyterext-text-shortcuts

If you want to keep using notebook, you have to go to your kernel directory and edit `kernel.js`.

**Comment by MOKA1066** [comment]
> Jupyter notebook still exists?
> 
> I’d switch to jupyterlab and use this extension, as described in the readme: https://github.com/techrah/jupyterext-text-shortcuts
> 
> If you want to keep using notebook, you have to go to your kernel directory and edit `kernel.js`.

thanks!
I use jupyter notebook as nbextension is very easy to use. 
There is no nbextension in jupyterlab!

Thanks again.

**Comment by MOKA1066** [comment]
> Jupyter notebook still exists?
> 
> I’d switch to jupyterlab and use this extension, as described in the readme: https://github.com/techrah/jupyterext-text-shortcuts
> 
> If you want to keep using notebook, you have to go to your kernel directory and edit `kernel.js`.

oops！

cannot find text-shortcut in jupyterlab extension tab.
when I use:
`jupyter labextension install @techrah/text-shortcuts`

> An error occurred.
>   warnings.warn("An error occurred.")
> /opt/anaconda3/lib/python3.12/site-packages/jupyterlab/debuglog.py:55: UserWarning: ValueError: The extension "@techrah/text-shortcuts" does not yet support the current version of JupyterLab.

my jupyterlab version is 4.2.5, text-shortcut only support 2.x, 3.x

**Comment by flying-sheep** [comment]
Ah, seems like jupyterlab has this now built-in: https://github.com/jupyterlab/jupyterlab/issues/10114#issuecomment-821993321

Does the solution described in there work for you?

**Comment by MOKA1066** [comment]
thank you I switched yo jupyter lab. the problem fixed.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by flying-sheep** [comment]
Great!
