### ISSUE TITLE
`installspec()` is sometimes not properly recognizing jupyter kernelspec

### ISSUE THREAD

**Issue by glatterf42** [IRkernel/IRkernel#747]
If this issue does not belong here: apologies, please let me know where else I should raise it. Please also note that I don't actually know how to code in R.

Today, one of our CI runs failed when calling `IRkernel::installspec()`. Specifically, because this might be important, the CI run on the GitHub Actions runner with image `ubuntu-latest` and Python 3.12. Please find an exemplary run [here](https://github.com/iiasa/ixmp/actions/runs/11272964437/job/31348995451?pr=547). The error message we receive is

```bash
 Error in IRkernel::installspec() : 
  jupyter-client has to be installed but “jupyter kernelspec --version” exited with code 1.
Execution halted
```

Essentially, the workflow [(file)](https://github.com/iiasa/ixmp/blob/main/.github/workflows/pytest.yaml) is setting up Python, every version from 3.8 through 3.12, on linux, windows, and macos. We then install all dependencies, including

```bash
jupyter-1.1.1 jupyter-client-8.6.3 jupyter-console-6.6.3 jupyter-core-5.7.2 jupyter-events-0.10.0 jupyter-lsp-2.2.5 jupyter-server-2.14.2 jupyter-server-terminals-0.5.3 jupyterlab-4.2.5 jupyterlab-pygments-0.3.0 jupyterlab-server-2.27.3 jupyterlab-widgets-3.0.13
```

where the versions are identical for 3.12 (failing) and 3.11 (working). We don't use a virtual environment, so as far as I know, there's nothing we could be forgetting to activate or so. Then, we run these commands with `Rscript` (which is likely installed through the [setup-r action](https://github.com/r-lib/actions))

```bash
        install.packages(c("remotes", "Rcpp"))
        remotes::install_cran(
          c("IRkernel", "reticulate"),
          dependencies = TRUE,
          # force = TRUE,
        )

        IRkernel::installspec()
``` 

at which point we run into the error.

I already looked into several possible sources, but can't quite find the culprit:

- GitHub [is currently rolling out](https://github.com/actions/runner-images/issues/10636) the `ubuntu-24.04` image as the `ubuntu-latest` runner image, which doesn't include a pre-installation of R anymore. However, the `ubuntu-latest-py3.11` workflow is using the same image without problems.
- Forcing the reinstall (by enabling `force = TRUE`) does not change anything.

The example run I shared above is coming from a [PR](https://github.com/iiasa/ixmp/pull/547) where I already experimented a lot with troubleshooting this issue, so you can find lots of auxiliary output there.

- Immediately before the `Rscript` step, when I run `jupyter kernelspec --version` in a step using bash, it works well and outputs `8.6.3`. When I `echo $PATH` in the same manner, it starts with `/home/runner/work/_actions/iiasa/actions/main/setup-gams/gams43.4_linux_x64_64_sfx:/opt/hostedtoolcache/Python/3.12.7/x64/bin:/opt/hostedtoolcache/Python/3.12.7/x64`, which includes the paths where jupyter is installed. I have confirmed this through the following:
- Within the `Rscript` step, I have added different lines: `system2('which', 'python', TRUE, TRUE)` outputs `[1] "/opt/hostedtoolcache/Python/3.12.7/x64/bin/python"` and similarly, `system2('which', 'jupyter', TRUE, TRUE)` outputs ` [1] "/opt/hostedtoolcache/Python/3.12.7/x64/bin/jupyter"`. This seems to confirm that the same python and jupyter are used that successfully enable `jupyter kernelspec --version` outside the `Rscript`.
- Also within the `Rscript`, I have tried calling `system(...)` instead of the `system2(...)` that `installspec()` is using. This has allowed me to get the actual error message:
  ```bash 
   Warning message:
  [1] "Traceback (most recent call last):"                                                
  In system2("jupyter", c("kernelspec", "--version"), TRUE, TRUE) :
    running command ''jupyter' kernelspec --version 2>&1' had status 1
  [2] "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/bin/jupyter\", line 5, in <module>"
  [3] "    from jupyter_core.command import main"                                         
  [4] "ModuleNotFoundError: No module named 'jupyter_core'"                               
  attr(,"status")
  ```
- Interestingly, I have also tried directly calling `jupyter-kernelspec`, which changed the error message slightly:
  ```bash
  [1] "Traceback (most recent call last):"                                                           
  In system2("jupyter-kernelspec", "--version", TRUE, TRUE) :
    running command ''jupyter-kernelspec' --version 2>&1' had status 1
  [2] "  File \"/opt/hostedtoolcache/Python/3.12.7/x64/bin/jupyter-kernelspec\", line 5, in <module>"
  [3] "    from jupyter_client.kernelspecapp import KernelSpecApp"                                   
  [4] "ModuleNotFoundError: No module named 'jupyter_client'"                                        
  attr(,"status")
  ```

So it simply seems that jupyter is not properly recognized within the `Rscript`, despite `which` finding it as I would expect. I somehow doubt that `installspec()` is truly at fault here, but I don't know where else to ask.

**Comment by glatterf42** [comment]
Short update: I checked the last day where the CI run on ubuntu-latest-py3.12 still succeeded and the runner image back then used the `ubuntu-22.04` image version 20241006.1.0. So the error appeared with the switch to `ubuntu-24.04`, same version. Among other things, this leads to a different compiler being used: `using C++ compiler: ‘g++ (Ubuntu 13.2.0-23ubuntu4) 13.2.0’` instead of ` using C++ compiler: ‘g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0’`.

**Comment by glatterf42** [comment]
After further debugging, it seems that for some reason, the Python path inside of our `Rscript` step is not correct on `ubuntu-latest-py3.12`: the `/site-packages/` directory is missing, so no packages are found. This is almost certainly not `IRkernel`'s fault, so I'm going to close this issue.
In case anyone wants to follow up on this, though, I have now asked the team of the `setup-r` GitHub Action if they know why now (with R installed via their action as opposed to also being pre-installed) the Python path is incorrect: https://github.com/r-lib/actions/issues/932

**Comment by flying-sheep** [comment]
Hi, I was at a hackathon last week, that’s why I didn’t look at this earlier.

R and Python interop is always hairy, and PATH/PYTHONPATH management between GUI applications and scripts isn’t obvious. Glad that you found the solution for your instance of this problem!

**Comment by glatterf42** [comment]
Hi, thanks for following up and no worries :)
We haven't found a solution, not quite, but for the time being, GitHub reverted `ubuntu-latest` back to Ubuntu 22.04, which is working fine. Here's to hoping they switch again only once their Ubuntu 24.04 image is working just as well :)
