### ISSUE TITLE
Odd help behaviour on Windows

### ISSUE THREAD

**Issue by mikecroucher** [IRkernel/IRkernel#77]
32bit Windows 7, Internet Explorer 11, IPython 3
I'm using the binary of rzmq from @JanSchulz that's referenced in Issue #54 

When trying to get help, for example,

?lm

I see the message 'starting httpd help server ... done' in IPython and a new browser tab opens.  The new tab just spins, doing nothing with the name 'Waiting for 127.0.0.1'.

If I evaluate a cell, the tab name changes to 'R: Fitting Linear models' but the page is still blank.
Evaluating one more cell results in a completed page.

A video demonstration is below.

https://www.youtube.com/watch?v=wwcLxUafBfE

**Comment by takluyver** [comment]
Can you still reproduce this in master? I fixed something with the pager in #114, but this sounds a bit different.

**Comment by mikecroucher** [comment]
The reported behaviour has gone away as of version 0.3. The result is now MUCH nicer, thank you -- the help document is rendered as an output cell and looks rather nice!

I'll close this issue now.

**Comment by takluyver** [comment]
Excellent, thanks!

**Comment by flying-sheep** [comment]
for the record, that’s because i implemented [`repr_html.help_files_with_topic`](https://github.com/IRkernel/repr/blob/master/R/help_files_with_topic.r).

the pager bug is #112
