### ISSUE TITLE
R help documentation does not show in output or lower part of screen

### ISSUE THREAD

**Issue by breschke** [IRkernel/IRkernel#78]
`help()` causes kernel to hang endlessly. IPython 3.1.0 with Python 2.7.8. Session info included in screenshot.
![screenshot](https://cloud.githubusercontent.com/assets/4975604/7037703/5d6b3cc2-dd5b-11e4-9275-838e04635408.png)

**Comment by takluyver** [comment]
What OS? Similar odd behaviour was just reported on Windows: #77.

**Comment by breschke** [comment]
Ubuntu 12.04.5 LTS

**Comment by takluyver** [comment]
I think this should have just been fixed by #114. Let me know if you can reproduce this with master or the next release (0.4)

**Comment by breschke** [comment]
Updated to the current development version. Help now displays in the output as expected.

**Comment by takluyver** [comment]
Thanks :-)
