### ISSUE TITLE
Use R kernel from an IPython instance that started in virtualenv

### ISSUE THREAD

**Issue by drorata** [IRkernel/IRkernel#79]
I completed the installation steps, and it seems like it was successful. However, when I start IPython (3.1.0) I cannot start a notebook with R as its kernel. This happens both for the systemwide IPython and also the one that I have inside a virtualenv. 

How ca I debug the issue? I don't really know where to start...

**Comment by flying-sheep** [comment]
you mean it doesn’t appear in the list of selectable kernels?

![Kernel selector](http://ipython.org/ipython-doc/3/_images/kernel_selector_screenshot.png)

**Comment by takluyver** [comment]
You definitely did the last step `IRkernel::installspec()` ?

Do you have a `~/.ipython/kernels/ir` directory?

**Comment by drorata** [comment]
@flying-sheep Exactly. I only see one Python

@takluyver I did, but following your question I found out that I don't have `~/.ipython/kernels` directory at all. I tried to re-run `IRkernel::installspec()` and found the following error message:

    [TerminalIPythonApp] CRITICAL | Bad config encountered during initialization:
    [TerminalIPythonApp] CRITICAL | Unrecognized flag: '--replace'

Sounds like a good start :) What's the next step?

**Comment by takluyver** [comment]
That's odd. What IPython version do you have? And what do you get if you run the command `ipython kernelspec install --help`?

**Comment by drorata** [comment]
It can well be that I have some mess. System-wise I have to versions of python: 2.3.1 and 3.1.0

Could it be that R tries to use the wrong version? Unless mistakenly I did otherwise, I meant to use the 3.1.0 version.

Following is the output of what you asked:

```
Install a kernel specification directory.

Options
-------

Arguments that take values are actually convenience aliases to full
Configurables, whose aliases are listed on the help line. For more information
on full configurables, see '--help-all'.

--replace
    Replace any existing kernel spec with this name.
--debug
    set log level to logging.DEBUG (maximize logging output)
--user
    Install to the per-user kernel registry
--name=<Unicode> (InstallKernelSpec.kernel_name)
    Default: ''
    Install the kernel spec with this name
--ipython-dir=<Unicode> (BaseIPythonApplication.ipython_dir)
    Default: ''
    The name of the IPython directory. This directory is used for logging
    configuration (through profiles), history storage, etc. The default is
    usually $HOME/.ipython. This option can also be specified through the
    environment variable IPYTHONDIR.
--log-level=<Enum> (Application.log_level)
    Default: 30
    Choices: (0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL')
    Set the log level by value or name.

To see all available configurables, use `--help-all`
```

**Comment by flying-sheep** [comment]
> 2.3 and 3.1

\*shudder*

i have no idea what’s going on, but your pythons are *really* old…

**Comment by JanSchulz** [comment]
@drorata I'm pretty sure you mean **IPython** 2.3 and 3.1?

**Comment by takluyver** [comment]
Yeah, I think that means IPython. Those versions make plenty of sense for IPython, and almost none for Python.

I bet it's getting the wrong version of IPython somehow. I don't know how, but that seems a plausible cause. Try removing 2.3 and ensuring that the command `ipython` starts IPython 3.

**Comment by drorata** [comment]
@JanSchulz Indeed I meant *IPython*.

It seems like I solved the problem. @takluyver tip was helpful; one has to make sure that the command `ipython` is linked to the right version (3.x and above if I understand correctly). This can be checked using `which ipython`.

**Comment by flying-sheep** [comment]
great!

**Comment by igor-go** [comment]
@drorata Can you please give more details about how did you solve the issue. Just changing the link manually with _'ln -s'_?

And then, do I loose the connection with the python 2.7 kernel, that is the one I have now?

Thank you!

**Comment by drorata** [comment]
I started to use virtualenv, and this help. I don't know about the 2.7 python version. For me, no, I have python 3 and R.
