### ISSUE TITLE
No output visible

### ISSUE THREAD

**Issue by takluyver** [IRkernel/IRkernel#8]
@karthik and @sckott, both using Macs, both had an issue where code appeared to run, but no output was visible. However, @ramnathv, also on a Mac, doesn't see it, and it works for a couple of people on Linux. Similar to an earlier, fixed issue (see discussion on #2).

No idea what could be causing this at the moment, but please comment with any ideas, debugging, or best of all, solutions.

**Comment by lucacerone** [comment]
Hi guys, I am experimenting with the new Jupyter and IRKernel, but I can't seem to make it work.
I have installed everything and Jupyter seems to work fine and I can choose to start a new Jupyter notebook using R from the dropdown menu.

However if in I cell I try to type code like:

```

**Comment by takluyver** [comment]
Are there any error messages in the terminal where you launched the notebook?

**Comment by lucacerone** [comment]
Thanks, I have noticed now it reports an error about a module named "terminado"..
I installed it with pip in my virtualenvironment. Is that the correct way to install it? I was reading that it should come as a submodule from the ipython repository.

Thanks for your help (and for the cool package!)

**Comment by takluyver** [comment]
Installing that separately makes sense, but it is optional, and it shouldn't cause the problem you described with running R code, so that error is probably unrelated.

**Comment by lucacerone** [comment]
after installing terminado now everything works just fine.
Ah I also symlinked my /usr/bin/R to the virtualenv/bin directory (maybe this is what fixed the issue)

**Comment by takluyver** [comment]
Bizarre, I'm not sure how either of those would have affected matters, but I'm glad you got it fixed.

**Comment by jtyberg** [comment]
I ran into this problem too, on Ubuntu 14.04.  In my case, libzmq-dev had been previously installed, and I installed libzmq3-dev as well, perhaps causing a conflict.  I was able to resolve the issue by purging the older libzmq-dev, installing libzmq3-dev, and re-compiling the pyzmq and rzmq packages.

Bottom line: I had to purge the old libzmq-dev, not just install libzmq3-dev.

Essentially:

```
$ pip uninstall pyzmq
$ apt-get purge libzmq-dev libzmq1
$ apt-get install libzmq3-dev
$ pip install pyzmq
$ wget http://cran.r-project.org/src/contrib/rzmq_0.7.7.tar.gz && R CMD INSTALL rzmq_0.7.7.tar.gz
```

FWIW, my environment:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty

# I had to purge this...
$ apt-cache showpkg libzmq-dev
Package: libzmq-dev
Versions: 
2.2.0+dfsg-5 (/var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty_universe_binary-amd64_Packages.gz)
 Description Language: 
                 File: /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty_universe_binary-amd64_Packages.gz
                  MD5: 7b2c1e47f6d305566aebc0e65e04f5ee

Reverse Depends: 
  libzmq3-dev,libzmq-dev
  libxs-compat-libzmq-dev,libzmq-dev
  libxs-compat-libzmq-dev,libzmq-dev
Dependencies: 
2.2.0+dfsg-5 - libzmq1 (5 2.2.0+dfsg-5) 
Provides: 
2.2.0+dfsg-5 - 
Reverse Provides: 
libxs-compat-libzmq-dev 1.2.0-1.1

# ...and installed this
apt-cache showpkg libzmq3-dev
Package: libzmq3-dev
Versions: 
4.0.4+dfsg-2 (/var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty_universe_binary-amd64_Packages.gz) (/var/lib/dpkg/status)
 Description Language: 
                 File: /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty_universe_binary-amd64_Packages.gz
                  MD5: 7b2c1e47f6d305566aebc0e65e04f5ee

Reverse Depends: 
  libtango8-dev,libzmq3-dev
  pypy-zmq,libzmq3-dev
  libzmqpp-dev,libzmq3-dev 3.2
  libtango8-dev,libzmq3-dev
  libghc-zeromq3-haskell-dev,libzmq3-dev 3.2.3-0
Dependencies: 
4.0.4+dfsg-2 - libzmq3 (5 4.0.4+dfsg-2) libzmq-dev (0 (null)) 
Provides: 
4.0.4+dfsg-2 - 
Reverse Provides: 

$ R --version
R version 3.0.2 (2013-09-25) -- "Frisbee Sailing"

$ pip show ipython
---
Name: ipython
Version: 3.0.0rc1
Location: /usr/local/lib/python2.7/dist-packages
```

**Comment by alvinwt** [comment]
Had the same issue as @jtyberg, works now after the purge and reinstallation.

**Comment by janakmayer** [comment]
I have the same issue as @jtyberg on Ubuntu 14.04, but when I uninstall libzmq-dev and install libzmq3-dev, even if I first uninstall pyzmq and subsequently reinstall it, when I try to launch the ipython notebook I get "ImportError: IPython.html requires pyzmq >= 13" (though pyzmq==14.7.0 is installed). Only when I reinstall libzmq-dev will IPython notebook run, but then I have the same problem of no R output.
Any suggestions would be much appreciated!

**Comment by jeffjose** [comment]
Thanks @jtyberg 

I was struggling with this (Essentially, no output in the notebook) and following your steps worked.

**Comment by janakmayer** [comment]
Update to my comment above - while simply pip uninstalling and installing pyzmq (after installing libzmq3-dev) didn't work for me, using pip install --no-use-wheel pyzmq to force pyzmq to be compiled fixed the problem for me.

**Comment by flying-sheep** [comment]
if there are problems left, try with the pbdZMQ-based master please
