### ISSUE TITLE
installation instructions for OS X

### ISSUE THREAD

**Issue by smartinsightsfromdata** [IRkernel/IRkernel#80]
Thanks for this really useful package.

I've followed the instructions in the README but they do not seem quite complete - for OS X at least.

After following the instructions and failing to install rzmq,  I had to install ```czmq``` (apparently needed?), and more importantly curl ```zmq.hpp``` that was giving errors on installing rzmq.

Then I discovered (after various trial-and-error) that ```IRkernel::installspec()``` needs to be launched at the terminal: in hindsight it is sort of mentioned, but as I normally use RStudio or R UI for me and people like me needs to be spelled out more  (it wasn't evident for me).

Please let me know if you would like me to submit a PR with clarification for the above.

**Comment by takluyver** [comment]
Can you chime in on the long running issue #50 for the ZMQ OS X installation thing?

What happens if you run `IRkernel::installspec()` from a GUI? AFAIK it shouldn't matter where you run it from.

**Comment by xiaoweiz** [comment]
I can replicate the issue. Running `IRkernel::installspec()` within RStudio gives `sh: ipython: command not found`; whereas it's OK to run it in terminal.

**Comment by JanSchulz** [comment]
I think the easiest way around the `ipython: command not found` in rstudio is adding a small FAQ in the readme that one has to run the command itself...

**Comment by takluyver** [comment]
I suspect that the issue is really the `$PATH` environment variable - I bet it's being modified by a file like `.profile` or `.bashrc` that is run when bash starts. If you launch Rstudio from a GUI launcher, that file is never read, so IPython isn't on $PATH. If I'm right, it will work inside Rstudio if you start Rstudio from a terminal...

Unfortunately, modifying $PATH for GUI apps on Mac appears to be [non trivial](http://apple.stackexchange.com/questions/153402/in-osx-yosemite-why-can-i-set-many-environment-variables-for-gui-apps-but-cann), from the information I've found (unlike Linux, where you can just modify it in `~/.profile`, which gets run at login).

Gah, computers.

**Comment by takluyver** [comment]
@minrk suggested that with some kind of check for 'is this OS X, and are we outside a virtualenv', we could run the command as `bash -l -c "ipython kernelspec ..."` (see the code [here](https://github.com/IRkernel/IRkernel/blob/master/R/kernel.r#L285)).

Thinking about it some more, though, I don't think this is an OS X specific problem - if you install IPython with Anaconda, I imagine you're going to have a similar issue on other platforms. Perhaps we should recommend Anaconda users use @asmeurer's conda packages - but then I assume that that installs a whole new copy of R inside Anaconda, which probably isn't what people with an existing R installation want.

**Comment by JanSchulz** [comment]
What about, if the command is a failure, print the generated commandline and ask the user to run that in a terminal

**Comment by asmeurer** [comment]
Can't you just manually copy the files? Is `ipython kernelspec` doing any more than that?

**Comment by JanSchulz** [comment]
@asmeurer As far as I understood the code: no, just figuring out where to copy to and then a copy...

**Comment by shapiromatron** [comment]
I have ipython in a virtualenv (OSX), so I think I'm running into the same problem as described above. What path should be substitute for the dots in the command above `ipython kernelspec install --replace --name ir ...`?

**Comment by takluyver** [comment]
Well, you could clone the repo and run it on the `inst/kernelspec` directory. But that's essentially what `IRkernel::installspec()` already does, I think.

**Comment by shapiromatron** [comment]
Figured it out. When using Rstudio, I had to add the path to my virtual environment bin as follows:

    Sys.setenv(PATH=paste(Sys.getenv("PATH"), "/path/to/virtualenv/bin/", sep=":"))
    IRkernel::installspec()

Then it was able to find `ipython` and it worked fine.
