### ISSUE TITLE
Kernel crashes with Address already in use

### ISSUE THREAD

**Issue by alvinwt** [IRkernel/IRkernel#87]
I'm getting the *Address already in use*  error when I am using the IRKernel to run code in parallel. The crashes after and I am not sure how to get around the problem.

**Comment by takluyver** [comment]
What platform are you on? Can you give a code snippet that triggers the problem?

**Comment by alvinwt** [comment]
It fails on Debian when I run a script using the NMR R package. The code that I am running can be rather long and requires many dependencies. I am using an Ubuntu system as well but it doesn't seem to have the same problem.

**Comment by alvinwt** [comment]
Revisited the code and it stops crashing after an update. This issue can be closed. Thanks!

**Comment by takluyver** [comment]
Thanks!
