### ISSUE TITLE
Print preview in Jupyter notebook shows nothing when plotting

### ISSUE THREAD

**Issue by randy3k** [IRkernel/IRkernel#89]
When I run `plot(1:10)`, a svg plot is shown. However, when I do print preview, the plot disappears. 
![screen shot 2015-04-17 at 10 29 42 pm](https://cloud.githubusercontent.com/assets/1690993/7214132/4625c728-e551-11e4-8494-3533a8c0d733.png)

I also note that if I first run 
```
options(jupyter.plot_mimetypes = "image/svg+xml")
```
Then, the plot will appear in the Print preview.

I am on current master branch. Mac OS X 10, R 3.2

**Comment by flying-sheep** [comment]
try updating repr:

```r
library(devtools)
install_github('IRkernel/repr')
```

sorry that things are moving so fast still.

**Comment by randy3k** [comment]
I am also using the latest repr. It doesn't help.

**Comment by flying-sheep** [comment]
weird. what does the JSON look like? can you put it in a gist or something?

**Comment by JanSchulz** [comment]
Is there a way that repr returns null even if it shouldn't? I python ob can usually see the real problem with calling the apprpriate method, but for R I wouldn't know how to get at the recorded plot :-(

**Comment by randy3k** [comment]
Here you are
https://gist.github.com/07d5a3b7db6defae7f87.git

**Comment by JanSchulz** [comment]
@randy3k Hm, there are both png and svg outputs in there. Is that with or without adding `options(jupyter.plot_mimetypes = "image/svg+xml")` (I'm guessing without?)?

**Comment by JanSchulz** [comment]
Funny, if I open that on nbviewer (http://nbviewer.ipython.org/gist/randy3k/07d5a3b7db6defae7f87), no plot is shown, but if I downlaod it and load it in a local jupyther (3.1) server, it works and a png is shown.

![2015-04-19_142112](https://cloud.githubusercontent.com/assets/890156/7219423/5eb392b2-e69f-11e4-9f79-c60aa6403b89.png)

**Comment by JanSchulz** [comment]
@flying-sheep On error is in there: there is no `plain/test`

Here is a pyton version of this:
https://gist.github.com/JanSchulz/816206cbf25e095393eb
http://nbviewer.ipython.org/gist/JanSchulz/816206cbf25e095393eb

Main differences:
* python only produces png + plain/text, no pdf/svg
* the png is in a list and the uudecoded thingies are split over multiple lines ('\n' in the end of each string)

**Comment by JanSchulz** [comment]
@randy3k which frontend version (jupyther/Ipython version) do you use?

**Comment by randy3k** [comment]
I have tried both 3.1 and 4-dev. Same result.

**Comment by randy3k** [comment]
@JanSchulz did you do "Print Preview"?

**Comment by JanSchulz** [comment]
@randy3k No, only putting the notebook in a notebook server dir (version 3.0, not 3.1 I assumed above, sorry...) and opening the notebook in chrome.

**Comment by JanSchulz** [comment]
@randy3k @flying-sheep I opened a issue at the jupyter side as I could see the plot it in 3.0 but not in nbviewer:  jupyter/jupyter_notebook#31

**Comment by JanSchulz** [comment]
Ok, finally understood what you meant with print preview (I thought browser print preview, not the one in the jupyter menu) -> I think the print preview does a nbconvert in the background (`http://localhost:8888/nbconvert/html/test.ipynb?download=false`) and the nbconvert issue is that the html export prio was wrong: it prefered pdf but didn't include a block which displayed the pdf (which also makes not much sense in html) -> This is getting fixed in jupyter/jupyter_nbconvert#5

For the r kernel side, I think it makes sense to use the same defaults as ipython, which is only send image/png and text/plain as a default for new plots and remove svg and pdf again :-(

**Comment by randy3k** [comment]
@JanSchulz 
Thanks for figuring it. Yup, it is the print preview that I meant. Sorry for not making it clear enough. Meanwhile, I am checkout out an older commit
```
library(devotools)
install_github("IRkernel/IRkernel", ref="64085b364")
```

**Comment by JanSchulz** [comment]
@randy3k I think it is enough to set `options(jupyter.plot_mimetypes = "image/png")`, which is what ipython does (+ sending text/plain) -> as long as `jupyter.plot_mimetypes` does not include pdf it should work fine.

**Comment by flying-sheep** [comment]
thanks all for figuring this out!

> For the r kernel side, I think it makes sense to use the same defaults as ipython, which is only send image/png and text/plain as a default for new plots and remove svg and pdf again :-(

why? more formats → nbconvert immediately does a sensible thing

**Comment by JanSchulz** [comment]
There is still the missing text/plain representation.
