### ISSUE TITLE
Please add a repo with all packages (including binaries) as a gh-page

### ISSUE THREAD

**Issue by JanSchulz** [IRkernel/IRkernel#90]
I've added such a repository at http://janschulz.github.io/IRkernel/ but only for windows (R 3.1 and 3.2) and source packages. This is pullabale via the 'gh-pages' branch in https://github.com/JanSchulz/IRkernel.git (I can't create a PR against a nonexisting branch in this Repo :-( ).

For a user, this is useable as `install.packages(c("rzmq","repr","IRkernel","IRdisplay"), repos="http://janschulz.github.io/IRkernel")`

My script to generate the windows version looks like this (it has two dirs for the IRkernel: IRkernel with master checked out and IRkernel-ghpage with the 'gh-pages' branch checked out; rzmq is checked out with my PR in https://github.com/armstrtw/rzmq/pull/16; I use drat as in https://github.com/eddelbuettel/drat/pull/16, which has binary support for windows and macosx, but the latter untested):

```
set OLDPATH=%path%
set path=c:\Rtools\bin;c:\Rtools\gcc-4.6.3\bin;C:\Program Files\R\R-3.1.2\bin\x64;%OLDPATH% 
echo "building for R3.1"

rem @echo off
::setlocal EnableDelayedExpansion
set old=%CD%
cd %~dp0

R -e "R.Version()"
pause

for %%G IN (rzmq,repr,IRKernel,IRDisplay) do (
   echo %%G
   R CMD build %%G
   rem R CMD check %%g_*.tar.gz
   R CMD INSTALL --build --compile-both %%G
   )

pause

::goto :EOF

for /f "tokens=*" %%G in ('dir /b "*.zip"') do (
   echo %%G
   R --slave -e "drat:::insert('%%~nG%%~xG', repodir='IRkernel-ghpages')"
   move /y %%G packages\3.1
   )

for /f "tokens=*" %%G in ('dir /b "*.tar.gz"') do (
   echo %%G
   R --slave -e "drat:::insert('%%~nG%%~xG', repodir='IRkernel-ghpages')"
   move /y %%G packages\3.1
   )

pause

set path=c:\Rtools\bin;c:\Rtools\gcc-4.6.3\bin;C:\Program Files\R\R-3.2\bin\x64;%OLDPATH% 
echo "building for R3.2"

R -e "R.Version()"
pause

rem @echo off
::setlocal EnableDelayedExpansion
set old=%CD%
cd %~dp0

for %%G IN (rzmq,repr,IRKernel,IRDisplay) do (
   echo %%G
   R CMD build %%G
   rem R CMD check %%g_*.tar.gz
   R CMD INSTALL --build --compile-both %%G
   )

pause

::goto :EOF

for /f "tokens=*" %%G in ('dir /b "*.zip"') do (
   echo %%G
   R --slave -e "drat:::insert('%%~nG%%~xG', repodir='IRkernel-ghpages')"
   move /y %%G packages\3.2
   )

for /f "tokens=*" %%G in ('dir /b "*.tar.gz"') do (
   echo %%G
   R --slave -e "drat:::insert('%%~nG%%~xG', repodir='IRkernel-ghpages')"
   move /y %%G packages\3.2
   )
```

**Comment by flying-sheep** [comment]
we should add this as a new `irkernel.github.io` repo, and also host documentation there

**Comment by JanSchulz** [comment]
If you pull that into a 'gh_branch' (probably `git remote add jasc <my clone>; git pull jasc; git checkout jasc/gh-pages; git checkout -b 'gh-pages'; git push origin`), you have the repo at `irkernel.github.io` :-)

**Comment by flying-sheep** [comment]
no, i i mean http://irkernel.github.io/docs/... and so on. without the extra “/IRkernel”

then we have the repos

* IRkernel
* irkernel.github.io
* IRdisplay
* repr

**Comment by JanSchulz** [comment]
oups, I meant R repo, from which you can install the packages.

**Comment by flying-sheep** [comment]
sure, and i want one for all packages here on http://irkernel.github.io/repo and not on [http://irkernel.github.io**/IRkernel**/repo](http://irkernel.github.io/IRkernel/repo)

**Comment by JanSchulz** [comment]
https://help.github.com/articles/user-organization-and-project-pages/#user--organization-pages -> about 5 min work :-)

**Comment by takluyver** [comment]
@JanSchulz Thanks for working this stuff out!

@flying-sheep , I've [created the repo](https://github.com/IRkernel/irkernel.github.io) and given you access to set it up. I like the idea of having docs and the package repo both in there. I'm happy to add @JanSchulz as a collaborator as well.

**Comment by JanSchulz** [comment]
@takluyver I'm happy with PRs :-)

Can someone of you add a file to the repo, so that I can clone it? Currently there is no button on the github UI :-( I will resend the r repo as a PR against that git repo and add a small html file which displays only the commands to use to install the packages from that repo.

**Comment by takluyver** [comment]
I've copied the packages in from your repo, so it should now be forkable.

This should also push us to make more regular releases, which will make @asmeurer happy.

**Comment by asmeurer** [comment]
:)

**Comment by asmeurer** [comment]
FYI: https://binstar.org/r/r-irkernel/files

**Comment by takluyver** [comment]
Neat, thanks!
