### ISSUE TITLE
plots should send a text/plain representation

### ISSUE THREAD

**Issue by JanSchulz** [IRkernel/IRkernel#92]
In addition to the image mime types (png, svg, maybe :-) pdf)
See here: https://github.com/IRkernel/IRkernel/issues/89#issuecomment-94271916

**Comment by flying-sheep** [comment]
hmm, why not. but i don’t really see why. output formats that can’t handle graphics?

**Comment by JanSchulz** [comment]
It's in the messaging spec: "Results can have multiple simultaneous formats depending on its configuration. A plain text representation should always be provided in the text/plain mime-type. " https://ipython.org/ipython-doc/dev/development/messaging.html#id4

Ok, it's not "display_data" but "execution_result", but the ipython kernel does treat both the same. i.e. sends "text/plain".

**Comment by flying-sheep** [comment]
OK :+1:
