### ISSUE TITLE
"Got unhandled msg_type:" "is_complete_request"

### ISSUE THREAD

**Issue by JanSchulz** [IRkernel/IRkernel#94]
In knitpy I use the kernel to check if code lines are "complete" (e.g. in python the line which starts a loop is "incomplete"):

```
            msg = engine.kernel.is_complete(lines+"\n\n")
            reply = engine.kernel.get_shell_msg(timeout=self.timeout)
            assert reply['msg_type'] == 'is_complete_reply', str(reply)
            if self.kernel_debug:
                self.log.debug("completion_request: %s", msg)
            if reply['content']['status'] == 'complete':
                [...]
                # run the lines
                self._run_lines(lines+"\n", context)
                lines = ""
            elif reply['content']['status'] == 'invalid':
                # TODO: not sure how this should be handled
                # Either abort execution of the whole file or just retry with the next line?
                # However this should be handled via a user message
                self.log.info("Code invalid:\n%s",  lines)
                lines = ""
            else:
                # the "incomplete" case: don't run anything wait for the next line
                lines += "\n"
```

This doesn't work with the r kernel, as it seems that message is unhandled and the `get_shell_msg` times out with an Exception :-(

Please implement the message :-)

**Comment by takluyver** [comment]
Since R is a curly braces language, if we can tokenize the code, counting `{` and `}` should be good for a first pass.

**Comment by JanSchulz** [comment]
`if (....)\n{...}` might be a problem if a users submits after the closing `)`. The R repl should be able to handle it, as rstudio tells me when my line isn't finished. No idea if that info is available at all in the repl/evaluate :-(

**Comment by JanSchulz** [comment]
```
> evaluate:::parse_all("if (True)")
Error in parse(text = x, srcfile = src) : 
  <text>:2:0: unexpected end of input
1: if (True)
   ^
> evaluate:::parse_all("if (True) {")
Error in parse(text = x, srcfile = src) : 
  <text>:2:0: unexpected end of input
1: if (True) {
   ^
> evaluate:::parse_all("if (True) {print('x')}")
                     src         expr
0 if (True) {print('x')} if (True....
```

**Comment by takluyver** [comment]
So hopefully we can try `parse_all`, catching exceptions. If it raises an exception with the text 'unexpected end of input', it's not complete. If it's another exception, or it completes successfully, it is complete.

**Comment by JanSchulz** [comment]
Another exception should probably be a message with `reply['content']['status'] == 'invalid'`:

```
> evaluate:::parse_all("if (True) {print('x)}")
Error in parse(text = x, srcfile = src) : 
  <text>:1:18: unexpected INCOMPLETE_STRING
1: if (True) {print('x)}
                     ^
> evaluate:::parse_all("of (True) {print('x')}")
Error in parse(text = x, srcfile = src) : <text>:1:11: unexpected '{'
1: of (True) {
              ^
> evaluate:::parse_all("if (TRUEST) {print('x')}")
                       src         expr
0 if (TRUEST) {print('x')} if (TRUE....
```

R's evaluation rules (last example) will make this interesting :-)

**Comment by takluyver** [comment]
Oh yes, I forgot that I added an 'invalid' status.

'INCOMPLETE_STRING' should probably also be considered incomplete - it seems strings can be split over multiple lines OK.

I'm not quite sure what you mean about the last example. It's syntactically valid, isn't it? So we'll try to run it, and get the R equivalent of NameError at runtime. That seems fine.

**Comment by JanSchulz** [comment]
yes, I think INCOMPLETE_STRING should return "incomplete": if it is a valid case (string goes over multiple lines), this does the right thing and if it is just a missing quote the chunk is anyway invalid and will in the end produce an error. Returning invalid will mask the first case, which is bad...

**Comment by JanSchulz** [comment]
Close as #102 is merged
