### ISSUE TITLE
Kernel dying with every plotting command

### ISSUE THREAD

**Issue by noamross** [IRkernel/IRkernel#96]
I am having a problem where the kernel dies every time I attempt to plot something.  In the terminal where I am running the server, I get the following:

```
dev.new(): using pdf(file="Rplots2.pdf")
Error in file(con, "rb") : cannot open the connection
Calls: <Anonymous> ... <Anonymous> -> repr_pdf.recordedplot -> readBin -> file
In addition: Warning messages:
1: In parts[[i]] != charToRaw("<IDS|MSG>") :
  longer object length is not a multiple of shorter object length
2: In parts[[i]] != charToRaw("<IDS|MSG>") :
  longer object length is not a multiple of shorter object length
3: In parts[[i]] != charToRaw("<IDS|MSG>") :
  longer object length is not a multiple of shorter object length
4: In cairo_pdf(tf, width, height, pointsize, FALSE, family, bg, antialias) :
  unable to load shared object '/Library/Frameworks/R.framework/Resources/library/grDevices/libs//cairo.so':
  dlopen(/Library/Frameworks/R.framework/Resources/library/grDevices/libs//cairo.so, 6): image not found
5: In cairo_pdf(tf, width, height, pointsize, FALSE, family, bg, antialias) :
  failed to load cairo DLL
6: In file(con, "rb") :
  cannot open file '/var/folders/69/7ztsqtsx4js1m7y_mhcrgmdw0000gn/T//RtmpC782Zq/file12fb6cb031c.pdf': No such file or directory
Execution halted
```

Generally a file called `Rplot.pdf` is created in the working directory when this happens.  The file usually contains the plot, though sometimes it doesn't and the file isn't readable.  I haven't identified in what cases this happens.

I note if I use `png()` or `pdf()` to write to a file it works fine.

I installed IRKernel as instructed in the README, except to install the `rzmq` package I did `git clone --recursive` and `devtools::install()`.

Versions:
R 3.2.0
OSX darwin13.4.0
Python 2.7.9 :: Anaconda 1.8.0 (x86_64)
XQuartz 2.7.7
zeromq 4.0.5_2

**Comment by flying-sheep** [comment]
do you have R compiled with cairo support?

```
4: In cairo_pdf(tf, width, height, pointsize, FALSE, family, bg, antialias) :
  unable to load shared object '/Library/Frameworks/R.framework/Resources/library/grDevices/libs//cairo.so':
  dlopen(/Library/Frameworks/R.framework/Resources/library/grDevices/libs//cairo.so, 6): image not found
```

this could mean the cairo shared library doesn’t exist

**Comment by noamross** [comment]
Seems right:

```
> capabilities("cairo")
cairo 
FALSE 
```

@karthik and @sckott, you're on OSX, right? Is there any solution to this besides compiling R from source?

**Comment by sckott** [comment]
I get the same `cairo = FALSE`

**Comment by noamross** [comment]
This seems to be new in R 3.2.0.  When I downgrade to R 3.1.3, I get:

```
> capabilities("cairo")
cairo 
TRUE 
```

and the `svg()`, `cairo_pdf()`, and `cairo_svg()` devices work.  AND IRKernel plotting works!

What gives?

**Comment by JanSchulz** [comment]
I think the easiest way around this is adding a guard to the `repr_pdf.recordedplot` ([source](https://github.com/IRkernel/repr/blob/master/R/recordedplot.r#L83)): `if (capabilities("cairo") == FALSE) {return NULL}`

**Comment by flying-sheep** [comment]
or try something with the plain `pdf` device.

also note: no cairo, no SVG device!

**Comment by takluyver** [comment]
IRkernel/repr#3 should fix this, I think - I just implemented what @JanSchulz suggested.

**Comment by flying-sheep** [comment]
that’s a syntax error though. try `if (!capabilities('cairo')) return(NULL)`

**Comment by andrewzhang1** [comment]
I create a new ubuntu linux instance on aws, then installed Anaconda 2.4.1; I also installed IR kernek by "conda install -c r r-essentia". However, when I tried to plot on the ipython notebook, I got error message: "Error in file(con, "rb") : cannot open the connection". The problem was solved after I installed R on linux by "sudo apt-get install r-base". This meant we do need to have current R installed for ipython use R effectively?!

**Comment by flying-sheep** [comment]
sure, why do you think something else would make sense?

**Comment by andrewzhang1** [comment]
I thought I might  IR kernel was suffient to run R in python. 

Recently, I found the %load_ext rmagic won't work anymore; I have to create a seperated R notebook, which can only run R code. Is there a way that I can combine R and python code (as well as other language, such as bash)?

**Comment by flying-sheep** [comment]
jupyter is only designed to run one language kernel at a time. the rmagic kind of creates a second kernel that lives under python and isn’t managed by jupyter.

you should probably investigate why rmagic doesn’t work anymore when you want both

**Comment by takluyver** [comment]
The R magic was moved out of IPython to rpy2, the package that provides the R interface for Python. You can load it now with `%load_ext rpy2.ipython`.
